---
- name: Install Link Library
  hosts: all
  become: yes
  tasks:
    - name: install tools
      apt:
        pkg:
          - net-tools
          - nginx
          - tmux
          - python3
          - build-essential
          - sqlite3
        update_cache: yes
        state: present
    - name: Install Linklib
      tasks:
        - name: pull linklib from github
        - name: install requirements
    - name: configure and run nginx proxy
      # from https://www.scaleway.com/en/docs/how-to-configure-nginx-reverse-proxy/
      # and https://graspingtech.com/ansible-nginx-static-site/
      tasks:
        - name: copy nginx configuration
          copy:
            dest: /etc/nginx/sites-available
            src: ./server_config/nginx_reverseproxy.conf
            
    - name: install Zscrape
    - name: scrape zulip api
    
