{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"100916\" href=\"/#narrow/stream/arch\">#arch</a>.</p>\n<p><strong>Description</strong>: to help each other up arch-installation mountain</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111252824,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 100916,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1495652192,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c1c5789a9ec48818bbc90f3fdc324560d9a2021?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"dominic@spadacene.com\" data-user-id=\"100778\">@Dominic Michael Spadacene (SP2'17)</span> here's the bash script I use to adjust screen brightness:</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"ch\">#!/bin/bash</span>\n\n<span class=\"nv\">BRIGHTNESS</span><span class=\"o\">=</span><span class=\"nv\">$1</span>\n<span class=\"nb\">echo</span> <span class=\"nv\">$BRIGHTNESS</span> &gt; /sys/class/backlight/intel_backlight/brightness\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111298673,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "logan.buckley@gmail.com",
            "sender_full_name": "Logan Buckley (S1'17)",
            "sender_id": 101096,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "brightness",
            "submessages": [],
            "timestamp": 1495744279,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/462d5cb1668a697d179a6db0ba9a316640789ea1?x=x&version=2",
            "client": "website",
            "content": "<p>I'm giving up on this trackpad, I keep clicking stuff accidentally with my fat thumbs.... If anyone is curious the command:</p>\n<div class=\"codehilite\"><pre><span></span>[domspad@sprinklecookie ~]$ xinput\n\u23a1 Virtual core pointer                      id=2    [master pointer  (3)]\n\u239c   \u21b3 Virtual core XTEST pointer                id=4    [slave  pointer  (2)]\n\u239c   \u21b3 TPPS/2 IBM TrackPoint                     id=12   [slave  pointer  (2)]\n\u239c   \u21b3 SynPS/2 Synaptics TouchPad                id=11   [slave  pointer  (2)]\n\u23a3 Virtual core keyboard                     id=3    [master keyboard (2)]\n    \u21b3 Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]\n    \u21b3 Power Button                              id=6    [slave  keyboard (3)]\n    \u21b3 Video Bus                                 id=7    [slave  keyboard (3)]\n    \u21b3 Sleep Button                              id=8    [slave  keyboard (3)]\n    \u21b3 Integrated Camera                         id=9    [slave  keyboard (3)]\n    \u21b3 AT Translated Set 2 keyboard              id=10   [slave  keyboard (3)]\n    \u21b3 ThinkPad Extra Buttons                    id=13   [slave  keyboard (3)]\n[domspad@sprinklecookie ~]$ xinput --disable 11\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111609638,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "dominic@spadacene.com",
            "sender_full_name": "Dominic Michael Spadacene (SP2'17)",
            "sender_id": 100778,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "no mo trackpad",
            "submessages": [],
            "timestamp": 1496429244,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Mine didn't give me much trouble. I had to do some modprobe business to make tap to click work though</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111609703,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "no mo trackpad",
            "submessages": [],
            "timestamp": 1496429370,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p>so, I haven't updated in quite a white. I'm about to install 4GB of updates... wish me luck... <img alt=\":pray:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/unicode/1f64f.png\" title=\":pray:\"></p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113147340,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f631",
                    "emoji_name": "scream",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "me@wesleyac.com",
                        "full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
                        "id": 101330
                    },
                    "user_id": 101330
                },
                {
                    "emoji_code": "1f631",
                    "emoji_name": "scream",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "dominic@spadacene.com",
                        "full_name": "Dominic Michael Spadacene (SP2'17)",
                        "id": 100778
                    },
                    "user_id": 100778
                }
            ],
            "recipient_id": 103903,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "updating",
            "submessages": [],
            "timestamp": 1499639577,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/462d5cb1668a697d179a6db0ba9a316640789ea1?x=x&version=2",
            "client": "website",
            "content": "<p>One blunder I hope nobody else has to make is when partitioning your hard drive, giving root only 15GiB of space... I ended up filling it up once by accidently placing a movie file in root and couldn't install anything for a week until I realized it. Apparently its difficult to allocate more space between partitions as wel...</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113147698,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "dominic@spadacene.com",
            "sender_full_name": "Dominic Michael Spadacene (SP2'17)",
            "sender_id": 100778,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "updating",
            "submessages": [],
            "timestamp": 1499640429,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Knowing arch linux, that is guaranteed to break something.</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113149274,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "updating",
            "submessages": [],
            "timestamp": 1499643976,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p>Yep... Things were already broken before though, so I'm hoping that the total amount of breakage on my system will go down after the update.</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113149459,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "updating",
            "submessages": [],
            "timestamp": 1499644422,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p>So somehow it only broke my icons, which was fairly easily fixed! <img alt=\":tada:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/unicode/1f389.png\" title=\":tada:\"></p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113166394,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "updating",
            "submessages": [],
            "timestamp": 1499685931,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/462d5cb1668a697d179a6db0ba9a316640789ea1?x=x&version=2",
            "client": "website",
            "content": "<p>has anyone successfully mounted an iphone to their arch?</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 114085843,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "dominic@spadacene.com",
            "sender_full_name": "Dominic Michael Spadacene (SP2'17)",
            "sender_id": 100778,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "updating",
            "submessages": [],
            "timestamp": 1501621366,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>I'm climbing the mountain of Arch installation on my desktop and laptop (starting with the desktop). My first stumbling block is network connection.</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171002879,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563294373,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p><code>ping</code> keeps returning <code>temporary failure in name resolution</code> although output from <code>iwconfig wlp5s0</code> looks to me like it made a successful connection</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171003018,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563294474,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p><a href=\"/user_uploads/13/MhnHWPPGq4FYLcFaUclQ5STr/IMG_20190716_103012.jpg\" target=\"_blank\" title=\"IMG_20190716_103012.jpg\">IMG_20190716_103012.jpg</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/MhnHWPPGq4FYLcFaUclQ5STr/IMG_20190716_103012.jpg\" target=\"_blank\" title=\"IMG_20190716_103012.jpg\"><img src=\"/user_uploads/13/MhnHWPPGq4FYLcFaUclQ5STr/IMG_20190716_103012.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171003309,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563294648,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Actually, when I successively call <code>iwconfig</code> the info for my network disappears (I guess after the connection fails)</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171003354,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563294697,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p><a href=\"/user_uploads/13/zLKQZMbAGRcnuDRwt9dFLcfk/IMG_20190716_103202.jpg\" target=\"_blank\" title=\"IMG_20190716_103202.jpg\">IMG_20190716_103202.jpg</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/zLKQZMbAGRcnuDRwt9dFLcfk/IMG_20190716_103202.jpg\" target=\"_blank\" title=\"IMG_20190716_103202.jpg\"><img src=\"/user_uploads/13/zLKQZMbAGRcnuDRwt9dFLcfk/IMG_20190716_103202.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171003456,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563294737,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>My debug instincts are telling me I need to produce a more verbose log of what's happening when I make the connect call</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171003501,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563294765,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Ok, following this article and using <code>wifi-menu</code> I think I have a proper connection. Also it seems the official arch tutorial was giving the wrong <code>ping</code> command for testing -- which may have been the problem all along</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171006383,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563296808,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p><code>ping -c 3 www.google.com</code> works as opposed to just <code>ping archlinux.org</code> as officially suggested</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171006415,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "I'm climbing the mountain",
            "submessages": [],
            "timestamp": 1563296847,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "website",
            "content": "<p>Just installed docker on my arch machine and started/enabled the daemon via <code>systemctl enable docker</code> and <code>systemctl start docker</code></p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 172339731,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "docker run crashes xorg/exwm",
            "submessages": [],
            "timestamp": 1564777466,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "website",
            "content": "<p>now, weirdly enough, whenever I call <code>docker run,</code> my X window server crashes.</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 172339749,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "docker run crashes xorg/exwm",
            "submessages": [],
            "timestamp": 1564777493,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm imagining this might be a problem with Docker, Arch, Xorg, or my window manager, EXWM (emacs window manager)</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 172339775,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "docker run crashes xorg/exwm",
            "submessages": [],
            "timestamp": 1564777522,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "website",
            "content": "<p>if anyone's encountered anything like that before or has suggestions for debugging, i'd appreciate it</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 172339788,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "docker run crashes xorg/exwm",
            "submessages": [],
            "timestamp": 1564777544,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7e63aa0aba54ff44228b8d3081c0f560050b9f31?x=x&version=2",
            "client": "website",
            "content": "<p>Hi, I have a ThinkPad t490 running manjaro with xfce and when I connect my 4k 60Hz external display it get very high cpu usage like 10x normal. Any ideas what might be wrong?</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 190218264,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "dennismartensson@gmail.com",
            "sender_full_name": "Dennis Martensson (S'12)",
            "sender_id": 958,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "thinkpad t490 slow with external monitor",
            "submessages": [],
            "timestamp": 1583870696,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Hard to debug something like this offline, but do you see any obvious differences in the top/htop output? I assume this is some kind of display driver bug, searching for your specific laptop model number and graphics setup might lead to some useful pointers.</p>",
            "content_type": "text/html",
            "display_recipient": "arch linux",
            "flags": [
                "read",
                "historical"
            ],
            "id": 190238453,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 103903,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 100916,
            "subject": "thinkpad t490 slow with external monitor",
            "submessages": [],
            "timestamp": 1583884646,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
