{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://arduino.cc/en/Main/Software\" target=\"_blank\" title=\"http://arduino.cc/en/Main/Software\">http://arduino.cc/en/Main/Software</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12690806,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "software",
            "submessages": [],
            "timestamp": 1384285810,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>hello world <a href=\"http://arduino.cc/en/Tutorial/Blink\" target=\"_blank\" title=\"http://arduino.cc/en/Tutorial/Blink\">http://arduino.cc/en/Tutorial/Blink</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12690858,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "software",
            "submessages": [],
            "timestamp": 1384285882,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>Brought some arduinos !</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12727077,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Meeting today",
            "submessages": [],
            "timestamp": 1384357870,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hi everyone,<br>\nI was on the lighting team at OHM (a 3000 person hacker event) this summer. We controlled about 300k lights, mainly on individually-addressable led strips (150 leds long, wrapped around a pole). Everything worked via custom firmware and dmx ( <a href=\"http://en.wikipedia.org/wiki/DMX512\" target=\"_blank\" title=\"http://en.wikipedia.org/wiki/DMX512\">http://en.wikipedia.org/wiki/DMX512</a> ) over ethernet.<br>\nSome source code: <a href=\"https://github.com/bobo1on1/bobtricks\" target=\"_blank\" title=\"https://github.com/bobo1on1/bobtricks\">https://github.com/bobo1on1/bobtricks</a> (an artnet proxy, among other things - a layer on top of dmx)<br>\n<a href=\"https://github.com/bobo1on1/loc_controller\" target=\"_blank\" title=\"https://github.com/bobo1on1/loc_controller\">https://github.com/bobo1on1/loc_controller</a> (the firmware)<br>\n<a href=\"https://github.com/ohm2013loc/art\" target=\"_blank\" title=\"https://github.com/ohm2013loc/art\">https://github.com/ohm2013loc/art</a> (some lighting effects - by sending them to the proxy, we could run them over *all* the lights at the same time, or custom subsets of them as set up on the proxy).</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12727667,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "ohm lighting",
            "submessages": [],
            "timestamp": 1384358596,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://www.adafruit.com/\" target=\"_blank\" title=\"http://www.adafruit.com/\">http://www.adafruit.com/</a> </p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12727786,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "adafruit",
            "submessages": [],
            "timestamp": 1384358751,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://learn.adafruit.com/category/learn-arduino\" target=\"_blank\" title=\"http://learn.adafruit.com/category/learn-arduino\">http://learn.adafruit.com/category/learn-arduino</a> (they don't assume any background knowledge, and go into tons of useful details that aren't obvious as a beginner)</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12727878,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "good tutorials",
            "submessages": [],
            "timestamp": 1384358847,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>... and if anyone -really- likes this stuff, the edx 'circuits and electronics' course is good.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12728163,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "good tutorials",
            "submessages": [],
            "timestamp": 1384359186,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://en.wikipedia.org/wiki/Atmel_AVR\" target=\"_blank\" title=\"http://en.wikipedia.org/wiki/Atmel_AVR\">http://en.wikipedia.org/wiki/Atmel_AVR</a> - it's a family of microcontrollers. Notably, arduinos are built around them.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12728907,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "avr",
            "submessages": [],
            "timestamp": 1384360165,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://en.wikipedia.org/wiki/Pulse-width_modulation\" target=\"_blank\" title=\"http://en.wikipedia.org/wiki/Pulse-width_modulation\">http://en.wikipedia.org/wiki/Pulse-width_modulation</a> - in quite a lot of detail</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12728993,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "pwm",
            "submessages": [],
            "timestamp": 1384360247,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.google.com/search?q=rgb+led&amp;safe=active&amp;espv=210&amp;es_sm=91&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ei=9K-DUsfnJ9DPkQfNzIGgAQ&amp;ved=0CAkQ_AUoAQ&amp;biw=1678&amp;bih=908#facrc=_&amp;imgdii=_&amp;imgrc=H-fVcUjlLEivOM%3A%3BUbRiJ51HkHg_rM%3Bhttps%253A%252F%252Fcontent.solarbotics.com%252Fproducts%252Fphotos%252F84728eb26b0947ef6547884cea645502%252Flrg%252FLED-RGB-8CD5kCA.jpg%3Bhttps%253A%252F%252Fsolarbotics.com%252Fproduct%252FLED-RGB-8CD5kCA%252F%3B800%3B600\" target=\"_blank\" title=\"https://www.google.com/search?q=rgb+led&amp;safe=active&amp;espv=210&amp;es_sm=91&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ei=9K-DUsfnJ9DPkQfNzIGgAQ&amp;ved=0CAkQ_AUoAQ&amp;biw=1678&amp;bih=908#facrc=_&amp;imgdii=_&amp;imgrc=H-fVcUjlLEivOM%3A%3BUbRiJ51HkHg_rM%3Bhttps%253A%252F%252Fcontent.solarbotics.com%252Fproducts%252Fphotos%252F84728eb26b0947ef6547884cea645502%252Flrg%252FLED-RGB-8CD5kCA.jpg%3Bhttps%253A%252F%252Fsolarbotics.com%252Fproduct%252FLED-RGB-8CD5kCA%252F%3B800%3B600\">https://www.google.com/search?q=rgb+led&amp;safe=active&amp;espv=210&amp;es_sm=91&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ei=9K-DUsfnJ9DPkQfNzIGgAQ&amp;ved=0CAkQ_AUoAQ&amp;biw=1678&amp;bih=908#facrc=_&amp;imgdii=_&amp;imgrc=H-fVcUjlLEivOM%3A%3BUbRiJ51HkHg_rM%3Bhttps%253A%252F%252Fcontent.solarbotics.com%252Fproducts%252Fphotos%252F84728eb26b0947ef6547884cea645502%252Flrg%252FLED-RGB-8CD5kCA.jpg%3Bhttps%253A%252F%252Fsolarbotics.com%252Fproduct%252FLED-RGB-8CD5kCA%252F%3B800%3B600</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12730509,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "RGB LED",
            "submessages": [],
            "timestamp": 1384362037,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://learn.adafruit.com/digital-led-strip\" target=\"_blank\" title=\"http://learn.adafruit.com/digital-led-strip\">http://learn.adafruit.com/digital-led-strip</a> is the documentation for the ones we have at the space.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12730649,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "RGB LED",
            "submessages": [],
            "timestamp": 1384362218,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/948d9d7e524888d7759824164e5be92cfa6b8c3b?x=x&version=2",
            "client": "website",
            "content": "<p>did we set a time? I don't have definite constraints, but after 2 would be nice.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12777868,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "astrosilverio@gmail.com",
            "sender_full_name": "Katie Silverio (she/they) (F2'18)",
            "sender_id": 2869,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "today",
            "submessages": [],
            "timestamp": 1384444163,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>Whats a good time to meet today?</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13054155,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "meeting",
            "submessages": [],
            "timestamp": 1384961044,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ok me and Stacy  have decided to have the meeting up at 4:30 today <span class=\"user-mention\" data-user-email=\"staceysern@gmail.com\">@Stacey Sern (F'13)</span> <span class=\"user-mention\" data-user-email=\"anton@podviaznikov.com\">@Anton Podviaznikov (F'13)</span> <span class=\"user-mention\" data-user-email=\"astrosilverio@gmail.com\">@Katie Silverio (F'13)</span> <span class=\"user-mention\" data-user-email=\"katerinab@gmail.com\">@Katerina Barone-Adesi (F'13)</span> </p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13059609,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "meeting",
            "submessages": [],
            "timestamp": 1384967968,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0d3a1755b1e2bb0552c4fbb42bd02ef0?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"daphne.larose@gmail.com\">@Daphne Larose (F'13)</span> <span class=\"user-mention\" data-user-email=\"julia@jvns.ca\">@Julia Evans (F'13)</span> ^</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13059713,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "staceysern@gmail.com",
            "sender_full_name": "Stacey Sern (she) (m1'20)",
            "sender_id": 855,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "meeting",
            "submessages": [],
            "timestamp": 1384968111,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>Are we still meeting today guys?</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13071377,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "meeting",
            "submessages": [],
            "timestamp": 1384983411,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>4:30!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13561048,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "meeting today",
            "submessages": [],
            "timestamp": 1386004826,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0d3a1755b1e2bb0552c4fbb42bd02ef0?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"anton@podviaznikov.com\">@Anton Podviaznikov (F'13)</span> <span class=\"user-mention\" data-user-email=\"katerinab@gmail.com\">@Katerina Barone-Adesi (F'13)</span> <span class=\"user-mention\" data-user-email=\"astrosilverio@gmail.com\">@Katie Silverio (F'13)</span> ^</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13561065,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "staceysern@gmail.com",
            "sender_full_name": "Stacey Sern (she) (m1'20)",
            "sender_id": 855,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "meeting today",
            "submessages": [],
            "timestamp": 1386004872,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>Adafruit is a great resource for getting supplies. They are located in manhattan so you'll get stuff quick! <a href=\"http://www.adafruit.com/category/17\" target=\"_blank\" title=\"http://www.adafruit.com/category/17\">http://www.adafruit.com/category/17</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13570100,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "buying arduinos",
            "submessages": [],
            "timestamp": 1386016624,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p>I am about to order a wireless adapter for the arduino <a href=\"http://www.adafruit.com/products/1510#Description\" target=\"_blank\" title=\"http://www.adafruit.com/products/1510#Description\">http://www.adafruit.com/products/1510#Description</a><br>\nThis will allow us to send/receive data from the arduino without the usb cable attached to a computer! </p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13570176,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Wireless",
            "submessages": [],
            "timestamp": 1386016733,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89cf9e72bca08a9aa30fb0ece9b08aab?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://learn.adafruit.com/digital-led-strip\" target=\"_blank\" title=\"http://learn.adafruit.com/digital-led-strip\">http://learn.adafruit.com/digital-led-strip</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13607287,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "zunayed@gmail.com",
            "sender_full_name": "Zunayed Ali Morsalin (F'13)",
            "sender_id": 2868,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "strip",
            "submessages": [],
            "timestamp": 1386087816,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0d3a1755b1e2bb0552c4fbb42bd02ef0?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's the spec for the SPI library for the arduino <a href=\"http://arduino.cc/en/Reference/SPI\" target=\"_blank\" title=\"http://arduino.cc/en/Reference/SPI\">http://arduino.cc/en/Reference/SPI</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13611834,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "staceysern@gmail.com",
            "sender_full_name": "Stacey Sern (she) (m1'20)",
            "sender_id": 855,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "SPI Interface",
            "submessages": [],
            "timestamp": 1386093764,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0d3a1755b1e2bb0552c4fbb42bd02ef0?d=identicon&version=1",
            "client": "website",
            "content": "<p>And a tutorial <a href=\"http://tronixstuff.com/2011/05/13/tutorial-arduino-and-the-spi-bus/\" target=\"_blank\" title=\"http://tronixstuff.com/2011/05/13/tutorial-arduino-and-the-spi-bus/\">http://tronixstuff.com/2011/05/13/tutorial-arduino-and-the-spi-bus/</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13611909,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "staceysern@gmail.com",
            "sender_full_name": "Stacey Sern (she) (m1'20)",
            "sender_id": 855,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "SPI Interface",
            "submessages": [],
            "timestamp": 1386093879,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0d3a1755b1e2bb0552c4fbb42bd02ef0?d=identicon&version=1",
            "client": "website",
            "content": "<p>Also a library for driving leds from the arduino <a href=\"https://code.google.com/p/fastspi/\" target=\"_blank\" title=\"https://code.google.com/p/fastspi/\">https://code.google.com/p/fastspi/</a>.  There are links to a second version on that page.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13612106,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "staceysern@gmail.com",
            "sender_full_name": "Stacey Sern (she) (m1'20)",
            "sender_id": 855,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "SPI Interface",
            "submessages": [],
            "timestamp": 1386094157,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c9b2076f73b4bfd3b3a0c52570555d054204fccc?x=x&version=1",
            "client": "website",
            "content": "<p>I'm not sure if I have time but perhaps other HSers do! Arduino is giving out some new 'beta' boards (based on an ARM core), to people who commit to helping them write examples, test libraries and hardware. <a href=\"http://blog.arduino.cc/2014/08/01/20-arduino-zero-dev-edition-available-for-beta-testing-join-us/\" target=\"_blank\" title=\"http://blog.arduino.cc/2014/08/01/20-arduino-zero-dev-edition-available-for-beta-testing-join-us/\">details</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25659893,
            "is_me_message": false,
            "last_edit_timestamp": 1406941574,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "dsniezko@sonic.net",
            "sender_full_name": "Dana Sniezko (S1'14)",
            "sender_id": 5862,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Arduino Zero",
            "submessages": [],
            "timestamp": 1406941553,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/91110739a69aa1d40ecedfcd998320a3?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://gist.github.com/tks2103/d421b42c907ec63f4277\" target=\"_blank\" title=\"https://gist.github.com/tks2103/d421b42c907ec63f4277\">https://gist.github.com/tks2103/d421b42c907ec63f4277</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27173081,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "tsinha@gmail.com",
            "sender_full_name": "Tanoy Sinha (F1'14)",
            "sender_id": 955,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "nes controller",
            "submessages": [],
            "timestamp": 1409771958,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c9b2076f73b4bfd3b3a0c52570555d054204fccc?x=x&version=1",
            "client": "website",
            "content": "<p>A friend sent me this last night. I'd seen *duino clones for $5 but <a href=\"http://www.ebay.com/itm/New-Pro-Mini-atmega328-5V-16M-Replace-ATmega128-for-Arduino-Compatible-Nano-/131261720809\" target=\"_blank\" title=\"http://www.ebay.com/itm/New-Pro-Mini-atmega328-5V-16M-Replace-ATmega128-for-Arduino-Compatible-Nano-/131261720809\">$2.25</a>, wat?!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27231253,
            "is_me_message": false,
            "last_edit_timestamp": 1409866227,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "dsniezko@sonic.net",
            "sender_full_name": "Dana Sniezko (S1'14)",
            "sender_id": 5862,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "clones",
            "submessages": [],
            "timestamp": 1409866153,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/dd9aceaf17982bc33972b3bb8701cd19?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tsinha@gmail.com\">@Tanoy Sinha (F1'14)</span> Here's the NES-playing robot I was talking about earlier - <a href=\"http://youtu.be/Uep1H_NvZS0\" target=\"_blank\" title=\"http://youtu.be/Uep1H_NvZS0\">http://youtu.be/Uep1H_NvZS0</a> (<a href=\"http://youtu.be/52xBCinOLSs\" target=\"_blank\" title=\"http://youtu.be/52xBCinOLSs\">http://youtu.be/52xBCinOLSs</a> has a video of it actually making it all the way through Gradius without desyncing). Instructions on how it was built are here <a href=\"http://www.instructables.com/id/NESBot-Arduino-Powered-Robot-beating-Super-Mario-/\" target=\"_blank\" title=\"http://www.instructables.com/id/NESBot-Arduino-Powered-Robot-beating-Super-Mario-/\">http://www.instructables.com/id/NESBot-Arduino-Powered-Robot-beating-Super-Mario-/</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27313967,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "doy@tozt.net",
            "sender_full_name": "Jesse Luehrs (he) (F1'14)",
            "sender_id": 6426,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "NESbot",
            "submessages": [],
            "timestamp": 1410021740,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/78359dd9d3cf59abacfa85565edc1eb2?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I just got my first arduino! <img alt=\":clap:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/clap.png\" title=\":clap:\"> <img alt=\":clap:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/clap.png\" title=\":clap:\"> <img alt=\":clap:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/clap.png\" title=\":clap:\"> </p>\n<p>It seems like \"arduino\" as a language is just C with some library functions. Is this accurate? If it is not accurate, what's the easiest way to get started writing directly in C for the board? Does anyone have a preferred compile / upload workflow from the command line for the arduino?</p>\n<p>Yay hardware!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27412345,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "jeffowler@gmail.com",
            "sender_full_name": "Jeff Fowler (W'14)",
            "sender_id": 4998,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Uno",
            "submessages": [],
            "timestamp": 1410222420,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c9b2076f73b4bfd3b3a0c52570555d054204fccc?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"jeffowler@gmail.com\">@Jeff Fowler (W'14)</span> Yes, that's accurate! I have a friend who swears by <a href=\"https://github.com/sudar/Arduino-Makefile\" target=\"_blank\" title=\"https://github.com/sudar/Arduino-Makefile\">Arduino Makefile</a>. You can also use plain <a href=\"http://www.micahcarrick.com/tutorials/avr-microcontroller-tutorial/getting-started.html\" target=\"_blank\" title=\"http://www.micahcarrick.com/tutorials/avr-microcontroller-tutorial/getting-started.html\">avr-gcc + avrdude</a></p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27417137,
            "is_me_message": false,
            "last_edit_timestamp": 1410231652,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "dsniezko@sonic.net",
            "sender_full_name": "Dana Sniezko (S1'14)",
            "sender_id": 5862,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Uno",
            "submessages": [],
            "timestamp": 1410231413,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/78359dd9d3cf59abacfa85565edc1eb2?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>ooooh thats good, and actively maintained, too. thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27417228,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "jeffowler@gmail.com",
            "sender_full_name": "Jeff Fowler (W'14)",
            "sender_id": 4998,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Uno",
            "submessages": [],
            "timestamp": 1410231554,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/91110739a69aa1d40ecedfcd998320a3?d=identicon&version=1",
            "client": "website",
            "content": "<p>are there breadboards lying around 455 b'way by any chance?</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27774201,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "tsinha@gmail.com",
            "sender_full_name": "Tanoy Sinha (F1'14)",
            "sender_id": 955,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "breadboard?",
            "submessages": [],
            "timestamp": 1410879383,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a604f6425b41d724539755eb2c457f29536f16d9?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tsinha@gmail.com\">@Tanoy Sinha (F1'14)</span> Yeah in Babbage in one of the boxes I think.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27775068,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "sonali@recurse.com",
            "sender_full_name": "Sonali Sridhar",
            "sender_id": 812,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "breadboard?",
            "submessages": [],
            "timestamp": 1410880307,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c9b2076f73b4bfd3b3a0c52570555d054204fccc?x=x&version=1",
            "client": "website",
            "content": "<p>Intel is trying to catch-up in the embedded market, has been giving away free stuff. They're hosting a <a href=\"https://iotroadshow.intel.com/en/home/\" target=\"_blank\" title=\"https://iotroadshow.intel.com/en/home/\">NY event</a> with free dev kits for their <a href=\"https://www.sparkfun.com/products/13024\" target=\"_blank\" title=\"https://www.sparkfun.com/products/13024\">Edison</a> platform. Bluetooth, wifi, compatible with Arduino  IDE (plus Python, Node, etc, etc)! I figured a few HS people might be interested <img alt=\":smile:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/smile.png\" title=\":smile:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27784354,
            "is_me_message": false,
            "last_edit_timestamp": 1411101525,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "dsniezko@sonic.net",
            "sender_full_name": "Dana Sniezko (S1'14)",
            "sender_id": 5862,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "intel",
            "submessages": [],
            "timestamp": 1410891091,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>I've been curious about things like zeo sleep monitors for a few years, and just noticed that there's a similar, open, arduino-based project, so I've just pre-ordered one of the dev boards: <a href=\"https://openbci.myshopify.com/collections/frontpage/products/openbci-32-bit-board-kit\" target=\"_blank\" title=\"https://openbci.myshopify.com/collections/frontpage/products/openbci-32-bit-board-kit\">https://openbci.myshopify.com/collections/frontpage/products/openbci-32-bit-board-kit</a> , which I'll hopefully get to play with in October. In the meanwhile, it looks like they'll be at NYC maker faire September 20th/21st - I wish I could be there. :-D</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 27909290,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "OpenBCI",
            "submessages": [],
            "timestamp": 1411085342,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c9b2076f73b4bfd3b3a0c52570555d054204fccc?x=x&version=1",
            "client": "website",
            "content": "<p>Anyone at HS interested in bulk <a href=\"http://www.atmel.com/devices/attiny85.aspx\" target=\"_blank\" title=\"http://www.atmel.com/devices/attiny85.aspx\">ATTiny85</a> microcontrollers? I need to buy in quantity and will have extra. They work with a lot of Arduino code and are great for wearables, gifts, paper circuits, small NeoPixel things.  I'm hoping cost \u2264 $1/ each, can mail them.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 30206927,
            "is_me_message": false,
            "last_edit_timestamp": 1415145468,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "dsniezko@sonic.net",
            "sender_full_name": "Dana Sniezko (S1'14)",
            "sender_id": 5862,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "attiny",
            "submessages": [],
            "timestamp": 1415145453,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c34e314b2c38cb8147d66a6a7dbb793627ea3f6?x=x&version=1",
            "client": "website",
            "content": "<p>Totally sharing a moment of triumphant joy here. Before arriving in NYC I was working on little controller boards to go into circus performer outfits. I've been pushing firmware updates back to Melbourne for the designer and creative lead to try out, and just got out of a video conference where I got to see my new accelerometer effects working. Updating firmware from the other side of the world feels *amazing*.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 61626468,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "paul.j.fenwick@gmail.com",
            "sender_full_name": "Paul Fenwick",
            "sender_id": 9520,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "melb/clothing",
            "submessages": [],
            "timestamp": 1468116775,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9285e36f75f9742ae56a71f3af3bf460badd8c11?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"215432\">@Tim Vieregge (SP2'19)</span> <span class=\"user-mention\" data-user-id=\"203422\">@Tim Mickel (SP1'19)</span> and I are working on a robot, and we could use an arduino</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 163748154,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "ngozi.n.nwogwugwu@gmail.com",
            "sender_full_name": "Ngozi Nwogwugwu (she) (SP2'19)",
            "sender_id": 215979,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Does anyone have an arduino that they're not using?",
            "submessages": [],
            "timestamp": 1555693478,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28f189507e2e8b8e810d64114d86cbc64900833c?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Hey there! I have a Leonardo and a Nano for you to use!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 163788548,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "agusanzorena@gmail.com",
            "sender_full_name": "Agustin Ramos Anzorena (he) (SP1'19)",
            "sender_id": 203423,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Does anyone have an arduino that they're not using?",
            "submessages": [],
            "timestamp": 1555739797,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9285e36f75f9742ae56a71f3af3bf460badd8c11?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Wow Thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 163805046,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "ngozi.n.nwogwugwu@gmail.com",
            "sender_full_name": "Ngozi Nwogwugwu (she) (SP2'19)",
            "sender_id": 215979,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "Does anyone have an arduino that they're not using?",
            "submessages": [],
            "timestamp": 1555769546,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2cbb0322e7e334316b2b4ebe6df066631078a63a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Ok this stream seems to be not very active ... <br>\nbut in case anyone here is still reading it: I'm struggeling to connect my flora ... i get boardinformation the port is labeled with flora so clearly there is some communication but when i try to push code i ge the notificatio that it is not connected</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182973204,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "leli@heartofcode.org",
            "sender_full_name": "Leli Schiestl (she) (W1'19)",
            "sender_id": 247168,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575909048,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2cbb0322e7e334316b2b4ebe6df066631078a63a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p><a href=\"/user_uploads/13/o1c8G_JGtRNbYMPPivR3l_z2/Bildschirmfoto-2019-12-08-um-19.11.25.png\" target=\"_blank\" title=\"Bildschirmfoto-2019-12-08-um-19.11.25.png\">Bildschirmfoto-2019-12-08-um-19.11.25.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/o1c8G_JGtRNbYMPPivR3l_z2/Bildschirmfoto-2019-12-08-um-19.11.25.png\" target=\"_blank\" title=\"Bildschirmfoto-2019-12-08-um-19.11.25.png\"><img src=\"/user_uploads/13/o1c8G_JGtRNbYMPPivR3l_z2/Bildschirmfoto-2019-12-08-um-19.11.25.png\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182973240,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "leli@heartofcode.org",
            "sender_full_name": "Leli Schiestl (she) (W1'19)",
            "sender_id": 247168,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575909065,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a4e1f602882ac013a0e19b85c17366e4256f3fe3?x=x&version=2",
            "client": "website",
            "content": "<p>I don't have specific Flora experience, but in general my troubleshooting steps here would be:</p>\n<p>- update your arduino IDE<br>\n- update your drivers (esp. for the Flora, if it has special ones)<br>\n- check to see that the flora is fully powered (is powering it off of USB sufficient?)</p>\n<p>Adafruit support forums are reasonably helpful, also; they usually respond to issues like these within 1 business day.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182981418,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "12795",
                    "emoji_name": "plus1",
                    "reaction_type": "realm_emoji",
                    "user": {
                        "email": "quinnbatten@gmail.com",
                        "full_name": "Quinn Batten (he) (F1'18)",
                        "id": 125112
                    },
                    "user_id": 125112
                }
            ],
            "recipient_id": 27662,
            "sender_email": "bonnie.eisenman@gmail.com",
            "sender_full_name": "Bonnie Eisenman (she) (m5'20)",
            "sender_id": 105050,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575914172,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2cbb0322e7e334316b2b4ebe6df066631078a63a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>thank you ... every should be up to date as i installed it only yesterday :)<br>\nthe only thing i fonud at the forum was that they offered to exchange all the boards that had that issue ... but i kind of want to use it tomorrow so i'm hoping to get it running without that<br>\nbut thank you so much!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182983441,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "leli@heartofcode.org",
            "sender_full_name": "Leli Schiestl (she) (W1'19)",
            "sender_id": 247168,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575915446,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a4e1f602882ac013a0e19b85c17366e4256f3fe3?x=x&version=2",
            "client": "website",
            "content": "<p>Ah gotcha. That's...interesting that it's a known issue.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182983666,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "bonnie.eisenman@gmail.com",
            "sender_full_name": "Bonnie Eisenman (she) (m5'20)",
            "sender_id": 105050,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575915595,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a4e1f602882ac013a0e19b85c17366e4256f3fe3?x=x&version=2",
            "client": "website",
            "content": "<p>Other silly thing that's worked for me before with similar errors with the Gemma board: experiment with restarting the board while the IDE is open but the serial console is closed.</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182983808,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "bonnie.eisenman@gmail.com",
            "sender_full_name": "Bonnie Eisenman (she) (m5'20)",
            "sender_id": 105050,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575915662,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a4e1f602882ac013a0e19b85c17366e4256f3fe3?x=x&version=2",
            "client": "website",
            "content": "<p>We have some spare Floras at NYCR if you want a new one. (Toma and I will be at craft night tonight.)</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182983829,
            "is_me_message": false,
            "last_edit_timestamp": 1575915692,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "bonnie.eisenman@gmail.com",
            "sender_full_name": "Bonnie Eisenman (she) (m5'20)",
            "sender_id": 105050,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575915683,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2cbb0322e7e334316b2b4ebe6df066631078a63a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Will see if I'm able to come by after the PyLadies meetup today ... thx</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182985457,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "leli@heartofcode.org",
            "sender_full_name": "Leli Schiestl (she) (W1'19)",
            "sender_id": 247168,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575916683,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/da7d9ca3583d1a4ac2ee9e157568a451?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"247168\">@Leli Schiestl (she) (W1'19)</span> Could it possibly be related to this issue? <a href=\"https://github.com/arduino/Arduino/issues/9290\" target=\"_blank\" title=\"https://github.com/arduino/Arduino/issues/9290\">https://github.com/arduino/Arduino/issues/9290</a><br>\nThe error readout looks super similar!</p>\n<p>It's a huge thread but looks like there are a few fixes available depending on your board/computer etc</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182990785,
            "is_me_message": false,
            "last_edit_timestamp": 1575919931,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "quinnbatten@gmail.com",
            "sender_full_name": "Quinn Batten (he) (F1'18)",
            "sender_id": 125112,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575919857,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2cbb0322e7e334316b2b4ebe6df066631078a63a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>thank you so much <span class=\"user-mention\" data-user-id=\"125112\">@Quinn Batten (he) (F1'18)</span> <br>\nthis look really similar ... i will try to find someone with an older iOS or windows to try this :)</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 182991176,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f6e0",
                    "emoji_name": "working_on_it",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "quinnbatten@gmail.com",
                        "full_name": "Quinn Batten (he) (F1'18)",
                        "id": 125112
                    },
                    "user_id": 125112
                }
            ],
            "recipient_id": 27662,
            "sender_email": "leli@heartofcode.org",
            "sender_full_name": "Leli Schiestl (she) (W1'19)",
            "sender_id": 247168,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575920097,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2cbb0322e7e334316b2b4ebe6df066631078a63a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>omg yes that was the answer ... thx so much</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 183004526,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "leli@heartofcode.org",
            "sender_full_name": "Leli Schiestl (she) (W1'19)",
            "sender_id": 247168,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575928586,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/da7d9ca3583d1a4ac2ee9e157568a451?d=identicon&version=1",
            "client": "website",
            "content": "<p>oh awesome!! Glad you got it working, that's dope!</p>",
            "content_type": "text/html",
            "display_recipient": "arduino",
            "flags": [
                "read",
                "historical"
            ],
            "id": 183027041,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 27662,
            "sender_email": "quinnbatten@gmail.com",
            "sender_full_name": "Quinn Batten (he) (F1'18)",
            "sender_id": 125112,
            "sender_realm_str": "recurse",
            "stream_id": 23137,
            "subject": "all the error messages",
            "submessages": [],
            "timestamp": 1575951764,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
