{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>Is this a breakdancing stream?</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28776878,
            "is_me_message": false,
            "last_edit_timestamp": 1412707757,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412707749,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a4b3598d81f87cf19c089df9707ede15?d=identicon&version=1",
            "client": "website",
            "content": "<p>shake it down shake it down nowwww</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28776969,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "stan@schwertly.com",
            "sender_full_name": "Stan Schwertly (F2'14)",
            "sender_id": 6674,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412707832,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>no, sorry to disappoint</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28777411,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412708417,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>just made posted an explanation in announce</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28777420,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412708425,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>This is a really cool idea!  I'm even more excited now.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28777704,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412708719,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>awesome, I'm glad :)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28777880,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412708922,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0a35beaf5a354dafdf10494c0313e10fffc154fd?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>(can there also be breakdancing, though?)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28778007,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "maia.mcc@gmail.com",
            "sender_full_name": "Maia McCormick (she) (S2'14)",
            "sender_id": 6175,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412709084,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>This was all a ploy to get y'all to help me :D.  Elixir looks super cool but I don't have time for a complicated networking project.  Idea go!</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28778090,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412709182,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>(but I do want something that makes sense to do *in elixir*, if you know what I mean - no fizzbuzz)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28778153,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412709276,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"maia.mcc@gmail.com\">@Maia McCormick (S'14)</span> CAN AND SHALL</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28778172,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412709316,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>...I think I'm gonna spend A LOT of time in this thread</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28778463,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412709629,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>stream*</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28778465,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "building it up",
            "submessages": [],
            "timestamp": 1412709633,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Getting help:</p>\n<ul>\n<li>post a sentence or two about a project/language/concept/tool/whatever you want to work on, and your current skill level</li>\n<li>the idea is to avoid wasting energy searching for the perfect project, so try to take the first suggestion you get and run with it!  Modifying it slightly is fine.</li>\n<li>if a suggestion is not at all what you want, clarify your requirements before asking for another</li>\n<li>you must do a project within 24 hours, and post a link to the repo</li>\n</ul>\n<p>Helping:</p>\n<ul>\n<li>make suggestions for other people - aim for small, well-defined, 1-3 hour projects</li>\n<li>if someone already has a suggestion, wait until they respond to it before giving another one</li>\n<li>give high fives when people do their project, and nag them if they're late.  Accountability is fun!</li>\n</ul>\n<p>I will check this stream every morning for the next week, and ensure that everyone has a suggestion by 10:00, so current-batchers can work on their project first thing in the morning :)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28778869,
            "is_me_message": false,
            "last_edit_timestamp": 1412773312,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412710095,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5f1c30b34843592830dd7a04fc742e43?d=identicon&version=1",
            "client": "desktop app Linux 0.4.4",
            "content": "<p>hmm, maybe be a little more specific? I'm afraid I don't know anything about elixir I just looked up a few minutes ago</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28780872,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tjarjour@iupui.edu",
            "sender_full_name": "Tyler Jarjoura (F2'14)",
            "sender_id": 6699,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412712398,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tjarjour@iupui.edu\">@Tyler Jarjoura (F2'14)</span> it's built on top of the erlang vm.  So, small actors that send messages to each other, possibly over a network, with a simple system for specifying failure logic.  Neat stuff but I'm not sure how to play with it without designing a massive complicated Thing.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28784064,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412716118,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c18f60acffcf8b205f8c940d50e4859d?d=identicon&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"rose@happyspork.com\">@Rose Ames (W'14)</span></p>\n<blockquote>\n<p>you must do the first project suggested to you within 24 hours, and post a link to the repo</p>\n</blockquote>\n<p>Does it mean we want to have one suggestion for the project and call it a day?</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28788983,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "lohmataja@gmail.com",
            "sender_full_name": "Liuda Nikolaeva (SP1'18)",
            "sender_id": 6168,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412722166,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Yeah.  The idea is to avoid quests for the perfect project and just commit to doing something.  Of course if the first suggestion is not at all what you wanted, you can clarify and ask for another.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28789170,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412722512,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c18f60acffcf8b205f8c940d50e4859d?d=identicon&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>Mm.. maybe do one of the first 5 suggestions? It poses a limit, yet allows *some* degree of choice.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28789214,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "lohmataja@gmail.com",
            "sender_full_name": "Liuda Nikolaeva (SP1'18)",
            "sender_id": 6168,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412722584,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Choice is sometimes the enemy, it's why I made this stream :).  If you want to ask for more suggestions that's fine though.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28789294,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412722800,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7207debf9f46350a4ce327f5b51c305e?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"rose@happyspork.com\">@Rose Ames (W'14)</span> Thanks for thinking of this. I look forward to taking part.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28789395,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rob.moore@gmail.com",
            "sender_full_name": "Rob Moore (F2'14)",
            "sender_id": 6669,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412722966,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>cool cool.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28789461,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412723114,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0a35beaf5a354dafdf10494c0313e10fffc154fd?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>But more suggestions means more ideas for later, if you want to work on a similar thing in the future! And you could also take the first 5 ideas and resort to a random number generator... thus still not having a choice in the matter, but having more variety of non-choice!</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28793095,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "maia.mcc@gmail.com",
            "sender_full_name": "Maia McCormick (she) (S2'14)",
            "sender_id": 6175,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412728780,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c18f60acffcf8b205f8c940d50e4859d?d=identicon&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>Yeah, I thought of asking help with coming up with a project, but I'm not sure I can commit to taking the first suggestion that comes my way. What if I SERIOUSLY dislike it? </p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28793241,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "lohmataja@gmail.com",
            "sender_full_name": "Liuda Nikolaeva (SP1'18)",
            "sender_id": 6168,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412729003,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>HELLO</p>\n<p>I WOULD LIKE TO LEARN ABOUT VIRTUALIZATION.</p>\n<p>I'M A COMPLETE NOOB.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28795393,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412733130,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>(does that follow all the rules? Can <span class=\"user-mention\" data-user-email=\"mindy.preston@yomimono.org\">@Mindy Preston (W'14)</span> help? We shall see!)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28795402,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412733157,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"rose@happyspork.com\">@Rose Ames (W'14)</span> It seems to me that datastructures, more than even algorithms, characterize what it's like to program something, because you always have to use them, and if you pick the wrong one, it can be really hard to get anything done! Hence, I propose that you benchmark a bunch of operations on elixir's map and dict!</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28795802,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412733929,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>That seems possible doable in 1-3 hours. Maybe. I know nothing about elixir.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28795805,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412733946,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Erm.  I hate to set a bad example by rejecting my first suggestion, but this doesn't really get at why elixir is different from python or C++.  I know the difference between an association list and a hash table; I want something that involves the actor model at least a little.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28796171,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412734714,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>Multiplayer Go?</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797048,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412736657,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>If it's all \"a human does a move\" (or if you can plug in pre-existing AI) it might be possible to crunch into 3 hours, or at least some meaningful subset of it.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797060,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412736719,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>Also, I thought of suggestions but I kept them under my hat because I think it's a terrible idea to do what I say under basically any circumstances.  I want people to be able to reject my ideas.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797102,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412736775,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>HELLO ALEX</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797108,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736831,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>I AM NOT SURE I CAN HELP BUT I CAN FOLLOW THE FORMAT YOU HAVE SET</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797155,
            "is_me_message": false,
            "last_edit_timestamp": 1412736900,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736875,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>SURE</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797161,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736910,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>But just to be clear, I mean: CAN MINDY PRESTON SUGGEST A PROJECT?</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797165,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736929,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>HAVE YOU EVER ACTUALLY SET A SYSTEM UP TO BE A VIRTUALIZATION HOST BEFORE</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797171,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736958,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>(e.g. set up vmware or made a machine a xen host or whatever the equiv is in KVM)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797208,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736973,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I HAVE NOT</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797209,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736979,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>MAYBE YOU SHOULD DO THAT</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797211,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736984,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>BUT THAT QUESTION IS MAKING ME EXCITED FOR YOUR SUGGESTION</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797212,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736987,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>AND INSTALL A GUEST VM</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797213,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736987,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>AND SEE HOW MANY FIDDLY THINGS IT WANTS</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797217,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412736992,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>(IT WILL BE A LOT PROBABLY)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797221,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412737016,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>(Actually, that's a pretty damn good suggestion)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797224,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412737026,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>(I hope you get a few more so you have some choices!)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797268,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412737092,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>(Nah, it's obviously right that I should start there)</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28797292,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412737203,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ok, you guys are right.  'Must' is a little harsh.  </p>\n<p>I do want to avoid people getting a huge pile of good suggestions and wasting energy agonizing over which one to do, so I'd like one-suggestion-and-go to be the norm.  I tried to reword the rules to be less draconian while keeping that aspect of it.</p>\n<p><span class=\"user-mention\" data-user-email=\"lohmataja@gmail.com\">@Liuda Nikolaeva (S'14)</span> <span class=\"user-mention\" data-user-email=\"maia.mcc@gmail.com\">@Maia McCormick (S'14)</span> <span class=\"user-mention\" data-user-email=\"mindy.preston@yomimono.org\">@Mindy Preston (W'14)</span> what do you think of the new version?</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28813107,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412773734,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>I like that much better!  I feel less hesitant about contributing, anyway.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28813655,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412774807,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c18f60acffcf8b205f8c940d50e4859d?d=identicon&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>Sounds good: enough leeway to reject smth or get more suggestions if need be, but encouragement to focus on actually doing, rather than agonizing over choice. <img alt=\":thumbsup:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/thumbsup.png\" title=\":thumbsup:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28815708,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "lohmataja@gmail.com",
            "sender_full_name": "Liuda Nikolaeva (SP1'18)",
            "sender_id": 6168,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412778237,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0a35beaf5a354dafdf10494c0313e10fffc154fd?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Good good good!</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28816988,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "maia.mcc@gmail.com",
            "sender_full_name": "Maia McCormick (she) (S2'14)",
            "sender_id": 6175,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "rules",
            "submessages": [],
            "timestamp": 1412780151,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>OH SHIT THERE'S SO MUCH COOL STUFF TO LEARN DOING THIS</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28850566,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412831245,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>DID YOU KNOW THAT A VITRUAL MACHINE MONITOR IS THE *SAME THING* AS A HYPERVISOR????</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28850570,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412831267,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Whaaat</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28850608,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412831312,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>source: <a href=\"http://wiki.xenproject.org/wiki/Xen_Project_Beginners_Guide\" target=\"_blank\" title=\"http://wiki.xenproject.org/wiki/Xen_Project_Beginners_Guide\">http://wiki.xenproject.org/wiki/Xen_Project_Beginners_Guide</a></p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28850609,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412831314,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Anyway. I don't have it quite working yet.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28856326,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412844692,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Welp no working project to show but I'll post what I did:</p>\n<ul>\n<li>looked for elixir/erlang gui things.  Did not find any tempting options</li>\n<li>read reviews of elixir web frameworks.  Decided on Phoenix</li>\n<li>spent some time on <a href=\"http://benjamintanweihao.github.io/blog/2014/02/12/phoenix-elixir-web-framework-and-websockets/\" target=\"_blank\" title=\"http://benjamintanweihao.github.io/blog/2014/02/12/phoenix-elixir-web-framework-and-websockets/\">this</a> tutorial.  </li>\n<li>when various instructions did not work as described I googled a bit and found that the post is obsoleted by phoenix's support for websockets</li>\n<li>started doing that, then realized that phoenix is really a lot like rails - it might use actors under the hood but I wasn't learning how to use them myself</li>\n<li>decided a cli interface would be ok, started writing it from scratch</li>\n<li>ran out of time w/ 30 lines of code that currently don't do anything</li>\n</ul>\n<p>This is a common fail mode for me.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28863380,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412860240,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/61226ce011ec53a878f3accd5726c0b8?d=identicon&version=1",
            "client": "website",
            "content": "<blockquote>\n<p>started doing that, then realized that phoenix is really a lot like rails - it might use actors under the hood but I wasn't learning how to use them myself</p>\n</blockquote>\n<p>Erlang seems to be a bit like this too -- nothing stops you from playing with actors yourself, but for the most part it's recommended that you use one of the patterns in the library and leave the low-level details of actor creation and communication to library code.<br>\nThere's no need to stop just because it's been 24 hours, though! You were delayed by surprising difficulty, but now it seems like you have something that you want to do. If you still think it's interesting, take another day!</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28863519,
            "is_me_message": false,
            "last_edit_timestamp": 1412860517,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "trillionalyssa@gmail.com",
            "sender_full_name": "Alyssa Carter (F1'14)",
            "sender_id": 6414,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412860507,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"clemmer.alexander@gmail.com\">@Alex Clemmer (S'13)</span> that looks like a lot of fun</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28863524,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412860529,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>I intend to, but probably not this week - I've got a flu and stuff that I meant to get finished last week :P</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28863584,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412860656,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"rose@happyspork.com\">@Rose Ames (W'14)</span> how's that a fail? reads like progress to me :) I get the impression that you are disappointed that you wrote \"only\" 30 lines of code that kinda don't work, is that correct? when I am just starting to learn something it's more about absorbing info than producing a lot of output. I think it's normal to take a few wrong turns here and there when you are just starting out with something, specially if you are learning by yourself. so having decided on a project, looked into the available tools and even having started with it would make me consider it a very productive first day, if it were me.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28866218,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412865117,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>It's quite fun!</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28870458,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "let\u2019s do this",
            "submessages": [],
            "timestamp": 1412870147,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tn.pablo@gmail.com\">@Pablo Torres (W'14)</span> it's where a lot of my projects stall out - I gather just enough knowledge to know that I can't do the thing properly, so I end up not doing it at all.  Leaving me with a freakishly high knowledge/accomplishment ratio.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28871861,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412871919,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5f1c30b34843592830dd7a04fc742e43?d=identicon&version=1",
            "client": "desktop app Linux 0.4.4",
            "content": "<p>I want to develop skill using the ncurses library. Someone give me a very basic project to implement?</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28876589,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tjarjour@iupui.edu",
            "sender_full_name": "Tyler Jarjoura (F2'14)",
            "sender_id": 6699,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "Ncurses",
            "submessages": [],
            "timestamp": 1412877488,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>this used to happen to me, until I realised that I don't need to do it properly</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28876606,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412877513,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5f1c30b34843592830dd7a04fc742e43?d=identicon&version=1",
            "client": "desktop app Linux 0.4.4",
            "content": "<p>maybe just try to write a program with two actors that each take input from their users and chat with each other? still not sure I understand what elixir is good for though</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28876677,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tjarjour@iupui.edu",
            "sender_full_name": "Tyler Jarjoura (F2'14)",
            "sender_id": 6699,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412877610,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>once I stopped having expectations of the things I write I actually started doing things. I mean later you can focus on doing them properly, but if that's stopping you from even starting...</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28876701,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412877663,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>this was exactly my situation during hacker school</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28876715,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412877687,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>render markdown in the terminal</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28876885,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "Ncurses",
            "submessages": [],
            "timestamp": 1412877918,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>maybe? I'm not sure if ncurses can do bold and italic...</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28876896,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "Ncurses",
            "submessages": [],
            "timestamp": 1412877930,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Have you talked to Tom? He has spent a lot of time with this.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28879872,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "Ncurses",
            "submessages": [],
            "timestamp": 1412881930,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I don't know when it's appropriate to add someone to a stream. </p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28879886,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "Ncurses",
            "submessages": [],
            "timestamp": 1412881947,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Or I'd add tom here.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28879894,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "Ncurses",
            "submessages": [],
            "timestamp": 1412881957,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Add a curses interface to the client you were making yesterday.  You should have a create account button and a login button which take you to appropriate screens.  When you're logged in, you should see the a list of all user accounts, with logged-in users in green.  Update this info in realtime.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28880995,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "Ncurses",
            "submessages": [],
            "timestamp": 1412883474,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"rose@happyspork.com\">@Rose Ames (W'14)</span> sup</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28917802,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412951276,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>maybe <span class=\"user-mention\" data-user-email=\"jose.valim@gmail.com\">@Jos\u00e9 Valim</span> can help! <span class=\"user-mention\" data-user-email=\"rose@happyspork.com\">@Rose Ames (W'14)</span> is looking for resources and a project to get started with Elixir. looks like she doesn't have time for a complicated networking project, but still wants something that makes sense to write in elixir. I think she got started with multiplayer go?</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28921807,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412956941,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Heh.  I love that pinging the language's creator is an option.  Though Jose might come to disagree.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28921985,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412957200,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>yeah. as is pinging the director of research at google.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28922056,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412957306,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>theoretically.  I don't think I've ever seen him here.</p>",
            "content_type": "text/html",
            "display_recipient": "breaking it down",
            "flags": [
                "read",
                "historical"
            ],
            "id": 28922140,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36714,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 26196,
            "subject": "First halp please",
            "submessages": [],
            "timestamp": 1412957441,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
