{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1fdd84a57c15f7ecfdded3d0c32019ad32f8af5d?x=x&version=5",
            "client": "website",
            "content": "<p>Hi friends :) I'm trying to figure out how to add css styling to my browser. I have a dom tree, and will soon have a tree from the css rules. I'd like to combine these trees in some way, presumably adding styling information to the dom nodes. Any thoughts, advice, links, etc are super welcome.</p>\n<p>The links I'm looking at right now are <br>\n<a href=\"http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/#The_render_tree_relation_to_the_DOM_tree\" target=\"_blank\" title=\"http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/#The_render_tree_relation_to_the_DOM_tree\">http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/#The_render_tree_relation_to_the_DOM_tree</a><br>\n<a href=\"https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-tree-construction?hl=en\" target=\"_blank\" title=\"https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-tree-construction?hl=en\">https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-tree-construction?hl=en</a></p>\n<p>Hi <span class=\"user-mention\" data-user-email=\"sit@emilsit.net\">@Emil Sit</span> <span class=\"user-mention\" data-user-email=\"rose@happyspork.com\">@Rose Ames (W2'16)</span>  :)</p>",
            "content_type": "text/html",
            "display_recipient": "browsers",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100247860,
            "is_me_message": false,
            "last_edit_timestamp": 1471878673,
            "reactions": [],
            "recipient_id": 100198,
            "sender_email": "arpith@feedreader.co",
            "sender_full_name": "Arpith Siromoney (he) (m6'20)",
            "sender_id": 9503,
            "sender_realm_str": "recurse",
            "stream_id": 100050,
            "subject": "rendering",
            "submessages": [],
            "timestamp": 1471878323,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1fdd84a57c15f7ecfdded3d0c32019ad32f8af5d?x=x&version=5",
            "client": "website",
            "content": "<p>Hi <span class=\"user-mention\" data-user-email=\"mdenchev@gmail.com\">@Michail Denchev (S1'16)</span>  :)</p>",
            "content_type": "text/html",
            "display_recipient": "browsers",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100248101,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 100198,
            "sender_email": "arpith@feedreader.co",
            "sender_full_name": "Arpith Siromoney (he) (m6'20)",
            "sender_id": 9503,
            "sender_realm_str": "recurse",
            "stream_id": 100050,
            "subject": "rendering",
            "submessages": [],
            "timestamp": 1471878696,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5b9b07a1e96b1b5acee26709f699c0d1?d=identicon&version=1",
            "client": "website",
            "content": "<p>Haven't really looked into css rendering, but I do know that it doesn't just do styling :). All of the positional attributes (position, float, etc.) and animations (though I guess you can skip those for now) are probably pretty tricky to get right. The tree itself seems to start with some default set of attributes which are later overriden. I would suggest getting some of the positional elements implemented first such as box-sizing and floats.</p>",
            "content_type": "text/html",
            "display_recipient": "browsers",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100300134,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 100198,
            "sender_email": "mdenchev@gmail.com",
            "sender_full_name": "Michail Denchev (S1'16)",
            "sender_id": 9330,
            "sender_realm_str": "recurse",
            "stream_id": 100050,
            "subject": "rendering",
            "submessages": [],
            "timestamp": 1471984225,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5b9b07a1e96b1b5acee26709f699c0d1?d=identicon&version=1",
            "client": "website",
            "content": "<p>It's seems like getting css to work would be quite the journey but on the positive side you can take it one small step at a time and seeing the progression would be quite cool.</p>",
            "content_type": "text/html",
            "display_recipient": "browsers",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100300232,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 100198,
            "sender_email": "mdenchev@gmail.com",
            "sender_full_name": "Michail Denchev (S1'16)",
            "sender_id": 9330,
            "sender_realm_str": "recurse",
            "stream_id": 100050,
            "subject": "rendering",
            "submessages": [],
            "timestamp": 1471984396,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1fdd84a57c15f7ecfdded3d0c32019ad32f8af5d?x=x&version=5",
            "client": "website",
            "content": "<p>that's a good idea</p>",
            "content_type": "text/html",
            "display_recipient": "browsers",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100300292,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 100198,
            "sender_email": "arpith@feedreader.co",
            "sender_full_name": "Arpith Siromoney (he) (m6'20)",
            "sender_id": 9503,
            "sender_realm_str": "recurse",
            "stream_id": 100050,
            "subject": "rendering",
            "submessages": [],
            "timestamp": 1471984449,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
