{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/9fd9de59f964f6e3af477006ddd0116211347010?x=x&version=2",
            "client": "Internal",
            "content": "<p>Stream created by <span class=\"user-mention silent\" data-user-id=\"240968\">Leo Robinovitch (he) (F2'19)</span>.</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176897035,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "notification-bot@zulip.com",
            "sender_full_name": "Notification Bot",
            "sender_id": 100006,
            "sender_realm_str": "zulipcore",
            "stream_id": 210291,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1569808180,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0e46fa6943a5cbf1def6eff88b5e8ca2514b35e2?x=x&version=4",
            "client": "website",
            "content": "<p>In the spirit of Reducing and Reusing, Zero Waste, frugality, and convenience, let's ask for and offer things for free to one another! You're moving and getting rid of stuff - post here first, maybe someone can use it! You're about to buy small common items on amazon or from walmart - post here first, maybe someone has it sitting around!</p>\n<p>Inspired by the various facebook groups started by the Buy Nothing Project: <a href=\"https://buynothingproject.org/about/\" target=\"_blank\" title=\"https://buynothingproject.org/about/\">https://buynothingproject.org/about/</a></p>\n<p>Topics should be in the format (WANT / GIVING) - $LOCATION - $ITEM</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176897312,
            "is_me_message": false,
            "last_edit_timestamp": 1569809106,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "aidanhb17@gmail.com",
                        "full_name": "Aidan Eric Holloway-Bidwell (he) (F2'19)",
                        "id": 240599
                    },
                    "user_id": 240599
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "franco.mendoza.silva@gmail.com",
                        "full_name": "Franco Mendoza (he/they) (F2'19)",
                        "id": 240594
                    },
                    "user_id": 240594
                },
                {
                    "emoji_code": "1f44f",
                    "emoji_name": "clap",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "franco.mendoza.silva@gmail.com",
                        "full_name": "Franco Mendoza (he/they) (F2'19)",
                        "id": 240594
                    },
                    "user_id": 240594
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "lainedkendall@gmail.com",
                        "full_name": "Laine Kendall (she/they) (F2'19)",
                        "id": 240732
                    },
                    "user_id": 240732
                }
            ],
            "recipient_id": 371716,
            "sender_email": "leorobinovitch@gmail.com",
            "sender_full_name": "Leo Robinovitch (he) (F2'19)",
            "sender_id": 240968,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "what is this?",
            "submessages": [],
            "timestamp": 1569808549,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0e46fa6943a5cbf1def6eff88b5e8ca2514b35e2?x=x&version=4",
            "client": "website",
            "content": "<p>Got this for free and am probably never going to use it! Can pick up at RC anytime</p>\n<p><a href=\"/user_uploads/13/86bgr8SWjXPUB58CB_yT008x/IMG_5832.JPG\" target=\"_blank\" title=\"IMG_5832.JPG\">IMG_5832.JPG</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/86bgr8SWjXPUB58CB_yT008x/IMG_5832.JPG\" target=\"_blank\" title=\"IMG_5832.JPG\"><img src=\"/user_uploads/13/86bgr8SWjXPUB58CB_yT008x/IMG_5832.JPG\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176898329,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "leorobinovitch@gmail.com",
            "sender_full_name": "Leo Robinovitch (he) (F2'19)",
            "sender_id": 240968,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Incense + Holder",
            "submessages": [],
            "timestamp": 1569810441,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/973e5363d617a705d4ec13541831691e8d846390?x=x&version=4",
            "client": "website",
            "content": "<p>I would like!</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176898785,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "kathleen.macg@gmail.com",
            "sender_full_name": "Kathleen McGuire (she/they) (F2'19)",
            "sender_id": 228113,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Incense + Holder",
            "submessages": [],
            "timestamp": 1569811283,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0e46fa6943a5cbf1def6eff88b5e8ca2514b35e2?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>Woo! I'll bring it in tomorrow :) ping me anytime on zulip</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176899243,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "leorobinovitch@gmail.com",
            "sender_full_name": "Leo Robinovitch (he) (F2'19)",
            "sender_id": 240968,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Incense + Holder",
            "submessages": [],
            "timestamp": 1569812106,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0e46fa6943a5cbf1def6eff88b5e8ca2514b35e2?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>Hey Kathleen, if you're still here I'm upstairs on floor 5!</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176986733,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "leorobinovitch@gmail.com",
            "sender_full_name": "Leo Robinovitch (he) (F2'19)",
            "sender_id": 240968,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Incense + Holder",
            "submessages": [],
            "timestamp": 1569889180,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/973e5363d617a705d4ec13541831691e8d846390?x=x&version=4",
            "client": "website",
            "content": "<p>Womp I done did goof</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177110545,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "kathleen.macg@gmail.com",
            "sender_full_name": "Kathleen McGuire (she/they) (F2'19)",
            "sender_id": 228113,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Incense + Holder",
            "submessages": [],
            "timestamp": 1569975126,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/973e5363d617a705d4ec13541831691e8d846390?x=x&version=4",
            "client": "website",
            "content": "<p>Idk if we've actually been introduced. I'm the one with the green pixie cut. Give me them whenever</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177110554,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "kathleen.macg@gmail.com",
            "sender_full_name": "Kathleen McGuire (she/they) (F2'19)",
            "sender_id": 228113,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Incense + Holder",
            "submessages": [],
            "timestamp": 1569975152,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0e46fa6943a5cbf1def6eff88b5e8ca2514b35e2?x=x&version=4",
            "client": "ZulipMobile",
            "content": "<p>Free curtain! Bought the wrong one and can\u2019t return it. 42\u201d x 63\u201d</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177875631,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "leorobinovitch@gmail.com",
            "sender_full_name": "Leo Robinovitch (he) (F2'19)",
            "sender_id": 240968,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Curtain (blackout)",
            "submessages": [],
            "timestamp": 1570766125,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0e46fa6943a5cbf1def6eff88b5e8ca2514b35e2?x=x&version=4",
            "client": "ZulipMobile",
            "content": "<p>Pick up at RC anytime</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177875636,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "leorobinovitch@gmail.com",
            "sender_full_name": "Leo Robinovitch (he) (F2'19)",
            "sender_id": 240968,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "GIVING - BK - Curtain (blackout)",
            "submessages": [],
            "timestamp": 1570766151,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c6b498637f2c21e0e1c65b724f63465d?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>Hi RCers! I'm having a karaoke party this Friday. Does anyone have speakers, a mic, or a projector? I would be happy to pick up from you anywhere and you would ofc be welcome at the party!</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 184874253,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "mpinkham3@gmail.com",
            "sender_full_name": "Michael Pinkham (he) (W1'19)",
            "sender_id": 248084,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "WANT - BK - Karaoke Hardware",
            "submessages": [],
            "timestamp": 1578275095,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d344d8a25e4b8be7e88c472049dd7f413c4b40fb?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Hey anyone got any tips on dumpster diving food in NYC? <span class=\"user-mention\" data-user-id=\"240732\">@Laine Kendall (she/they) (F2'19)</span> and I wanna go soon and are looking for collaborators and co conspirators</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 188154297,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "aidanhb17@gmail.com",
            "sender_full_name": "Aidan Eric Holloway-Bidwell (he) (F2'19)",
            "sender_id": 240599,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "Dumpster diving in NYC",
            "submessages": [],
            "timestamp": 1581629535,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9c42d0ccee4e9835cde7dcf4ddf7f6a399d852f5?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>no takers...?</p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 190020143,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "lainedkendall@gmail.com",
            "sender_full_name": "Laine Kendall (she/they) (F2'19)",
            "sender_id": 240732,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "Dumpster diving in NYC",
            "submessages": [],
            "timestamp": 1583686599,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9e7e344d63b503011913719ec6f54eaaad225c24?x=x&version=4",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"240732\">@Laine Kendall (she/they) (F2'19)</span>  <span class=\"user-mention\" data-user-id=\"240599\">@Aidan Eric Holloway-Bidwell (he) (F2'19)</span> <br>\n<strong>waves hand</strong> i'm down and i like to conspire <span aria-label=\"slight smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"slight smile\">:slight_smile:</span></p>",
            "content_type": "text/html",
            "display_recipient": "buy nothing rc",
            "flags": [
                "read",
                "historical"
            ],
            "id": 190039731,
            "is_me_message": false,
            "last_edit_timestamp": 1583725640,
            "reactions": [],
            "recipient_id": 371716,
            "sender_email": "ashlaeblume@gmail.com",
            "sender_full_name": "ashlae blume (they) (W2'20)",
            "sender_id": 257126,
            "sender_realm_str": "recurse",
            "stream_id": 210291,
            "subject": "Dumpster diving in NYC",
            "submessages": [],
            "timestamp": 1583725568,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
