{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3f4785d95e43ecfb2f20d49e6ec824dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Feel free to suggest talks you'd enjoy watching this Monday here.</p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23585084,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "nick@recurse.com",
            "sender_full_name": "Nick Bergson-Shilcock (he)",
            "sender_id": 811,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403308953,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3f4785d95e43ecfb2f20d49e6ec824dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's the thread from when we did this before. It includes the videos we watched: <a href=\"https://groups.google.com/d/topic/hackerschool-nyc/il6h9hfaI-8/discussion\" target=\"_blank\" title=\"https://groups.google.com/d/topic/hackerschool-nyc/il6h9hfaI-8/discussion\">https://groups.google.com/d/topic/hackerschool-nyc/il6h9hfaI-8/discussion</a></p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23585425,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "nick@recurse.com",
            "sender_full_name": "Nick Bergson-Shilcock (he)",
            "sender_id": 811,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403309545,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3f4785d95e43ecfb2f20d49e6ec824dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>I really like this talk by Rich Hickey: <a href=\"http://www.infoq.com/presentations/Simple-Made-Easy\" target=\"_blank\" title=\"http://www.infoq.com/presentations/Simple-Made-Easy\">http://www.infoq.com/presentations/Simple-Made-Easy</a></p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23585439,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "nick@recurse.com",
            "sender_full_name": "Nick Bergson-Shilcock (he)",
            "sender_id": 811,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403309595,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b850936c0011b8c05e23dc6289b55c7e5c2dfd7e?x=x&version=1",
            "client": "website",
            "content": "<p>I really love this talk by the XKCD guy, Randall Munroe.<br>\nIt doesn't have explicit programming content but it is so much fun.</p>\n<p><a href=\"http://www.ted.com/talks/randall_munroe_comics_that_ask_what_if\" target=\"_blank\" title=\"http://www.ted.com/talks/randall_munroe_comics_that_ask_what_if\">http://www.ted.com/talks/randall_munroe_comics_that_ask_what_if</a></p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23585562,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "jorge@izqui.me",
            "sender_full_name": "Jorge Izquierdo (S1'14)",
            "sender_id": 5873,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403309774,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3670aa0d1ce05f885788e64d3ad6404f7cf73962?x=x&version=1",
            "client": "website",
            "content": "<p>I'm gonna propose a different Rich Hickey talk, <a href=\"http://www.infoq.com/presentations/Value-Values\" target=\"_blank\" title=\"http://www.infoq.com/presentations/Value-Values\">The Value of Values</a>. More than Simple Made Easy, it really changed how I think about computing, information, and programming.</p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23586011,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "scott@scott.mn",
            "sender_full_name": "Scott Feeney (W'13)",
            "sender_id": 825,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403310548,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ee5ef8c4705125cfdc43e7d1569c684c58cb518b?x=x&version=2",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>This is my fave security talk <a href=\"https://www.youtube.com/watch?v=3kEfedtQVOY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=3kEfedtQVOY\">https://www.youtube.com/watch?v=3kEfedtQVOY</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=3kEfedtQVOY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=3kEfedtQVOY\"><img src=\"https://i.ytimg.com/vi/3kEfedtQVOY/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23586369,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "maxim@ontoillogical.com",
            "sender_full_name": "Max Veytsman (he) (S1'20)",
            "sender_id": 5875,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403311091,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ad220596b601687b8785b5fbfa8ecbe?d=identicon&version=1",
            "client": "website",
            "content": "<p>What about something by Bret Victor? Maybe \u201cMedia for Thinking the Unthinkable\u201d or \u201cStop Drawing Dead Fish\u201d? Or actually \u201cInventing on Principle\u201d if not a lot of people know about Bret Victor? +1 for Rich Hickey too</p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23586379,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "bgmuthalaly@gmail.com",
            "sender_full_name": "Bert Muthalaly (S1'14)",
            "sender_id": 5871,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403311136,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3670aa0d1ce05f885788e64d3ad6404f7cf73962?x=x&version=1",
            "client": "website",
            "content": "<p>I was just about to suggest \"Inventing on Principle\", would love to watch that. Heard good things.</p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23586389,
            "is_me_message": false,
            "last_edit_timestamp": 1403311172,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "scott@scott.mn",
            "sender_full_name": "Scott Feeney (W'13)",
            "sender_id": 825,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403311158,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3670aa0d1ce05f885788e64d3ad6404f7cf73962?x=x&version=1",
            "client": "website",
            "content": "<p>From my to-watch queue:</p>\n<ul>\n<li><a href=\"http://vimeo.com/36579366\" target=\"_blank\" title=\"http://vimeo.com/36579366\">Bret Victor, Inventing on principle</a>: already suggested but so there's a link to it here :)</li>\n<li><a href=\"http://www.infoq.com/presentations/Live-Programming\" target=\"_blank\" title=\"http://www.infoq.com/presentations/Live-Programming\">Sam Aaron, Zen and the art of live programming</a>: on interactive editors, REPLs, on-the-fly compilation, real-time visuals and sound.</li>\n<li><a href=\"https://www.youtube.com/watch?v=h3KksH8gfcQ&amp;index=31&amp;list=WLsWP8epAaUITdEi3pG0NajQ\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=h3KksH8gfcQ&amp;index=31&amp;list=WLsWP8epAaUITdEi3pG0NajQ\">Pete Hunt, Be predictable, not correct</a>: from a React.js core team member, on how functional programming can simplify building UIs.</li>\n<li><a href=\"https://www.youtube.com/watch?v=uYcAjr2J_rU\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=uYcAjr2J_rU\">Reginald Braithwaite, Invent the future, don't recreate the past</a> proposing that JavaScript should invent ideas people will want to copy in 2044, not copy 1984's ideas.</li>\n<li><a href=\"https://air.mozilla.org/guaranteeing-memory-safety-in-rust/\" target=\"_blank\" title=\"https://air.mozilla.org/guaranteeing-memory-safety-in-rust/\">Niko Matsakis, Guaranteeing memory safety in Rust</a>: \"We show how Rust employs ownership and regions in order to guarantee memory safety, and how these same techniques can be generalized to provide data-race freedom.\"</li>\n<li><a href=\"https://www.youtube.com/watch?v=gTAghAJcO1o\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=gTAghAJcO1o\">Alan Kay, The future doesn't have to be incremental</a></li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23586450,
            "is_me_message": false,
            "last_edit_timestamp": 1403311442,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "scott@scott.mn",
            "sender_full_name": "Scott Feeney (W'13)",
            "sender_id": 825,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403311245,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3670aa0d1ce05f885788e64d3ad6404f7cf73962?x=x&version=1",
            "client": "website",
            "content": "<p>Oh oops, y'all watched Inventing on Principle last time. So for those who were at the first conf you probably don't want to do that again. There is also some very interesting stuff from <a href=\"http://www.infoq.com/conferences/strangeloop2013/\" target=\"_blank\" title=\"http://www.infoq.com/conferences/strangeloop2013/\">Strange Loop 2013</a> we could watch.</p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23587650,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "scott@scott.mn",
            "sender_full_name": "Scott Feeney (W'13)",
            "sender_id": 825,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403313284,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7d378db2f99b9c09f241125fb4829ecf?d=identicon&version=1",
            "client": "website",
            "content": "<p>ha, my work is also showing talks every Friday! we recently watched this that i think many people would enjoy:</p>\n<p><a href=\"https://www.youtube.com/watch?v=FITJMJjASUs\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FITJMJjASUs\">Y Not: Adventures in Functional Programming</a> by Jim Weirich. great talk. as the name might imply, it eventually builds up to the Y combinator.</p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=FITJMJjASUs\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FITJMJjASUs\"><img src=\"https://i.ytimg.com/vi/FITJMJjASUs/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23605399,
            "is_me_message": false,
            "last_edit_timestamp": 1403357007,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "david.a.peter@gmail.com",
            "sender_full_name": "David Peter (he) (S'12)",
            "sender_id": 869,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403356960,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3f4785d95e43ecfb2f20d49e6ec824dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Some more suggestions from <span class=\"user-mention\" data-user-email=\"jabronson@gmail.com\">@Josh Bronson (W'12)</span>:</p>\n<p><a href=\"https://www.youtube.com/watch?v=tXoSK4tLxK8\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=tXoSK4tLxK8\">https://www.youtube.com/watch?v=tXoSK4tLxK8</a><br>\n<a href=\"https://www.youtube.com/watch?v=FvmTSpJU-Xc\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FvmTSpJU-Xc\">https://www.youtube.com/watch?v=FvmTSpJU-Xc</a><br>\n<a href=\"https://www.youtube.com/watch?v=oKg1hTOQXoY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=oKg1hTOQXoY\">https://www.youtube.com/watch?v=oKg1hTOQXoY</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=tXoSK4tLxK8\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=tXoSK4tLxK8\"><img src=\"https://i.ytimg.com/vi/tXoSK4tLxK8/default.jpg\"></a></div><div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=FvmTSpJU-Xc\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FvmTSpJU-Xc\"><img src=\"https://i.ytimg.com/vi/FvmTSpJU-Xc/default.jpg\"></a></div><div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=oKg1hTOQXoY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=oKg1hTOQXoY\"><img src=\"https://i.ytimg.com/vi/oKg1hTOQXoY/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23681610,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "nick@recurse.com",
            "sender_full_name": "Nick Bergson-Shilcock (he)",
            "sender_id": 811,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403533869,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ad220596b601687b8785b5fbfa8ecbe?d=identicon&version=1",
            "client": "website",
            "content": "<p>One more suggestion: This is a fantastic security talk, walking through the thought process of a security person finding vulnerabilities in browsers. Great pacing and buildup, so it\u2019s pretty entertaining, and I learned a lot about what kinds of questions to ask when thinking through the security characteristics of my code by looking at it from an adversary\u2019s perspective. </p>\n<p><a href=\"https://www.youtube.com/watch?v=ibF36Yyeehw\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=ibF36Yyeehw\">https://www.youtube.com/watch?v=ibF36Yyeehw</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=ibF36Yyeehw\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=ibF36Yyeehw\"><img src=\"https://i.ytimg.com/vi/ibF36Yyeehw/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23693641,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "bgmuthalaly@gmail.com",
            "sender_full_name": "Bert Muthalaly (S1'14)",
            "sender_id": 5871,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403549113,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ad220596b601687b8785b5fbfa8ecbe?d=identicon&version=1",
            "client": "website",
            "content": "<p>Also +1 for \u201cThe computing revolution hasn\u2019t happened yet\u201d </p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23693656,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "bgmuthalaly@gmail.com",
            "sender_full_name": "Bert Muthalaly (S1'14)",
            "sender_id": 5871,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "talk suggestions",
            "submessages": [],
            "timestamp": 1403549143,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3f4785d95e43ecfb2f20d49e6ec824dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ok, I chose two of the more popular recommendations I got (and added in WAT just for fun):</p>\n<p>7:15pm: Bret Victor, <a href=\"http://vimeo.com/36579366\" target=\"_blank\" title=\"http://vimeo.com/36579366\">Inventing on Principle</a> (54 min) -- probably the most popular suggestion<br>\n8:15pm: Gary Bernhardt, <a href=\"https://www.destroyallsoftware.com/talks/wat\" target=\"_blank\" title=\"https://www.destroyallsoftware.com/talks/wat\">WAT</a> (4 min) -- because it's fun :)<br>\n8:20pm: Guy Steele, <a href=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\">Growing a Language</a> (53 min) -- multiple folks suggested this, and I found it profound the first time I saw it (though his male-centric pronoun use is annoying).</p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\"><img src=\"https://i.ytimg.com/vi/_ahvzDzKdB0/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23696220,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "nick@recurse.com",
            "sender_full_name": "Nick Bergson-Shilcock (he)",
            "sender_id": 811,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1403552223,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>For those of you following at home, we just started <a href=\"http://vimeo.com/36579366\" target=\"_blank\" title=\"http://vimeo.com/36579366\">Inventing on Principle</a></p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23707754,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1403565695,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>On to <a href=\"https://www.destroyallsoftware.com/talks/wat\" target=\"_blank\" title=\"https://www.destroyallsoftware.com/talks/wat\">Wat</a></p>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23709853,
            "is_me_message": false,
            "last_edit_timestamp": 1403569027,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1403568995,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Now starting <a href=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\">Growing a Language</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_ahvzDzKdB0\"><img src=\"https://i.ytimg.com/vi/_ahvzDzKdB0/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "cached conf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23710199,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34442,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 25724,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1403569577,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
