{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://www.news1130.com/2015/10/17/vancouver-womans-letter-to-stephen-harper-goes-viral/\" target=\"_blank\" title=\"http://www.news1130.com/2015/10/17/vancouver-womans-letter-to-stephen-harper-goes-viral/\">http://www.news1130.com/2015/10/17/vancouver-womans-letter-to-stephen-harper-goes-viral/</a></p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48509857,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "A letter to Harper from a woman in BC (not me. this time)",
            "submessages": [],
            "timestamp": 1445135802,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>I may have tickets to John Oliver on Nov 1, but I wish I could have gone to this: <a href=\"http://www.thedailybeast.com/articles/2015/10/19/john-oliver-and-mike-myers-blast-canada-s-pm-stephen-harper-do-not-vote-for-stephen-harper.html\" target=\"_blank\" title=\"http://www.thedailybeast.com/articles/2015/10/19/john-oliver-and-mike-myers-blast-canada-s-pm-stephen-harper-do-not-vote-for-stephen-harper.html\">http://www.thedailybeast.com/articles/2015/10/19/john-oliver-and-mike-myers-blast-canada-s-pm-stephen-harper-do-not-vote-for-stephen-harper.html</a> </p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48561911,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "A letter to Harper from a woman in BC (not me. this time)",
            "submessages": [],
            "timestamp": 1445273368,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>testing send without topic</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48564420,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1445277268,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.reddit.com/r/canada/comments/3pdudu/reports_coming_in_from_all_over_canada_premarked/\" target=\"_blank\" title=\"https://www.reddit.com/r/canada/comments/3pdudu/reports_coming_in_from_all_over_canada_premarked/\">https://www.reddit.com/r/canada/comments/3pdudu/reports_coming_in_from_all_over_canada_premarked/</a></p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48578463,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Reports coming in from all over Canada: Pre-marked ballots f",
            "submessages": [],
            "timestamp": 1445301591,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://aptn.ca/news/2015/10/19/ballots-run-out-in-2-first-nation-polling-stations/\" target=\"_blank\" title=\"http://aptn.ca/news/2015/10/19/ballots-run-out-in-2-first-nation-polling-stations/\">http://aptn.ca/news/2015/10/19/ballots-run-out-in-2-first-nation-polling-stations/</a></p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48578832,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "More HIGH turnout - Ballots run out in 2 First Nation pollin",
            "submessages": [],
            "timestamp": 1445302401,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>\"Kinew said the ballots were replenished by Elections Canada in the early evening.\"</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48578834,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "More HIGH turnout - Ballots run out in 2 First Nation pollin",
            "submessages": [],
            "timestamp": 1445302405,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>(hopefully not pre-marked ones)</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48578836,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "More HIGH turnout - Ballots run out in 2 First Nation pollin",
            "submessages": [],
            "timestamp": 1445302411,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hey all - I ran afoul with a post of mine on another stream that I thought was opted-in and now I'm feeling a bit nervous. I'm pretty strongly against our current government in Canada (something I apparently share with John Oliver &amp; Mike Myers:  <a href=\"http://www.thedailybeast.com/articles/2015/10/19/john-oliver-and-mike-myers-blast-canada-s-pm-stephen-harper-do-not-vote-for-stephen-harper.html\" target=\"_blank\" title=\"http://www.thedailybeast.com/articles/2015/10/19/john-oliver-and-mike-myers-blast-canada-s-pm-stephen-harper-do-not-vote-for-stephen-harper.html\">http://www.thedailybeast.com/articles/2015/10/19/john-oliver-and-mike-myers-blast-canada-s-pm-stephen-harper-do-not-vote-for-stephen-harper.html</a>) so that's the nature of the posts I'll likely be making. If this is not ok, someone please speak up soon before I make an ass of myself.</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48578906,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Opt-in, probably opinionated stream",
            "submessages": [],
            "timestamp": 1445302562,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/dd016afc5e2d346a0eee00bb0268c2b33da824d5?x=x&version=1",
            "client": "website",
            "content": "<p>fine by me (not canadian, just interested)</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48578979,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "amindfv@gmail.com",
            "sender_full_name": "Tom Murphy (F2'15)",
            "sender_id": 8693,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Opt-in, probably opinionated stream",
            "submessages": [],
            "timestamp": 1445302693,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>:) Well, currently it's a three-way tie for last, including the party whose only seat is its leader (Green) <a href=\"/user_uploads/13/bI7EH4dpuNnW4VwvSa98PhFE/results.png\" target=\"_blank\" title=\"results.png\">results.png</a> </p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/bI7EH4dpuNnW4VwvSa98PhFE/results.png\" target=\"_blank\" title=\"results.png\"><img src=\"/user_uploads/13/bI7EH4dpuNnW4VwvSa98PhFE/results.png\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48578987,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Opt-in, probably opinionated stream",
            "submessages": [],
            "timestamp": 1445302771,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>I did not realize that there are no blackouts this time around! For those who don't know, historically, because so much of Canada's population is in Quebec &amp; Ontario (we have no California equivalent), there was a legally imposed media blackout in every province until their polls closed so that the results coming in from back east couldn't affect voting out west. As you might imagine, cross-border cable, Slingboxes, and the internet made for some interesting challenges in implementing that blackout &amp; apparently they've finally given up</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48579164,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Opt-in, probably opinionated stream",
            "submessages": [],
            "timestamp": 1445303115,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>Which, as a west-coaster, I'm glad to hear - sure, if the result was fully decided in advance, I might not bother to vote if I knew I couldn't change the result, but I might be MORE likely to vote to make sure a protest vote was registered if I knew. </p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48579173,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Opt-in, probably opinionated stream",
            "submessages": [],
            "timestamp": 1445303160,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>Although...whoa: \"Does it all come down to B.C?<br>\nIt's become almost a Canadian election cliche, but with a three-way race in B.C., the winner could be decided in this province.\" <a href=\"http://www.cbc.ca/news/politics/canada-election-2015-election-night-watch-1.3275459\" target=\"_blank\" title=\"http://www.cbc.ca/news/politics/canada-election-2015-election-night-watch-1.3275459\">http://www.cbc.ca/news/politics/canada-election-2015-election-night-watch-1.3275459</a> </p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48579266,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Opt-in, probably opinionated stream",
            "submessages": [],
            "timestamp": 1445303385,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>I wasn't planning to stay up that late!</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48579267,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Opt-in, probably opinionated stream",
            "submessages": [],
            "timestamp": 1445303391,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://news.nationalpost.com/news/canada/canadian-politics/pumpkin-voter\" target=\"_blank\" title=\"http://news.nationalpost.com/news/canada/canadian-politics/pumpkin-voter\">http://news.nationalpost.com/news/canada/canadian-politics/pumpkin-voter</a></p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48580159,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Silly me, I voted without my pumpkin!",
            "submessages": [],
            "timestamp": 1445305252,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>For the Liberals. Which, given that the polls haven't closed in BC yet, is kind of a jerk move. I'd prefer they weren't allowed to do that until that happens at least (I seem to recall an election in the US where the outcome may have been influenced by the fact that the media called the result early &amp; therefore attempts to make sure all votes were counted ended up being a contentious act?)</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48580310,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "CTV has already called the result",
            "submessages": [],
            "timestamp": 1445305640,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>That's much more orange than I expected in Ontario. </p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48580851,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Pretty mosaic colours",
            "submessages": [],
            "timestamp": 1445306796,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/vTB_gRguDevXXXW2DoIzRdWx/multi.png\" target=\"_blank\" title=\"multi.png\">multi.png</a> </p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/vTB_gRguDevXXXW2DoIzRdWx/multi.png\" target=\"_blank\" title=\"multi.png\"><img src=\"/user_uploads/13/vTB_gRguDevXXXW2DoIzRdWx/multi.png\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48580854,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Pretty mosaic colours",
            "submessages": [],
            "timestamp": 1445306808,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>Now that I feel relatively secure about the future of my country, what was that about a new Star Wars trailer?</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48581655,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Pretty mosaic colours",
            "submessages": [],
            "timestamp": 1445308274,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/cae7c4e123601211ea241903314b704e?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'll nuke the stream after this but I'm pretty happy with this article <a href=\"http://www.nationalobserver.com/2015/10/19/opinion/harper-lost-election-because-canadians-are-awesome\" target=\"_blank\" title=\"http://www.nationalobserver.com/2015/10/19/opinion/harper-lost-election-because-canadians-are-awesome\">http://www.nationalobserver.com/2015/10/19/opinion/harper-lost-election-because-canadians-are-awesome</a> and this quote (regarding the late shift to the 'niqab issue' that the CPC took and how Canada reacted to that approach) \"Specifically, Harper tried to run on the fear of otherness, a human psychological mechanism that history has shown can be used in very powerful ways with devastating and tragic consequences. And it is on that happy thought where Canadians being awesome comes in! By un-electing Harper, Canadians sent a clear message that we will not be easily herded into an us-versus-them argument.\"</p>",
            "content_type": "text/html",
            "display_recipient": "canuck-elxn-2015",
            "flags": [
                "read",
                "historical"
            ],
            "id": 48599821,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43672,
            "sender_email": "kara.mcnair@gmail.com",
            "sender_full_name": "Kara McNair (F2'15)",
            "sender_id": 8681,
            "sender_realm_str": "recurse",
            "stream_id": 27857,
            "subject": "Final post",
            "submessages": [],
            "timestamp": 1445350574,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
