{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/9fd9de59f964f6e3af477006ddd0116211347010?x=x&version=2",
            "client": "Internal",
            "content": "<p>Stream created by <span class=\"user-mention silent\" data-user-id=\"257188\">Dree Ko (they) (SP2'20)</span>.</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264693,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "notification-bot@zulip.com",
            "sender_full_name": "Notification Bot",
            "sender_id": 100006,
            "sender_realm_str": "zulipcore",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856295,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>Hey friends! This is a stream I created for discussing and coordinating chat roulette events. The chat roulette hosting team is now five members strong: me, <span class=\"user-mention\" data-user-id=\"7642\">@Serena Peruzzo (she) (SP2'20)</span> , <span class=\"user-mention\" data-user-id=\"263528\">@Sam Lazarus (he) (SP1'20)</span> , <span class=\"user-mention\" data-user-id=\"301014\">@Adam Kelly (they/he) (S1'20)</span> and <span class=\"user-mention\" data-user-id=\"301058\">@Uri Shimon (he) (m4'20)</span> !</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264770,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856368,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>Uri had a couple of great ideas that I think could help with running a chat roulette event:</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264782,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856408,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>1) when deciding whether to increase the size of groups/amount of time per breakout, just ask for a quick show of hands (exp: \"hands up who wants to go from one-on-one conversations to 3 people hangouts?\")</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264852,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856476,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>2) Themed rounds! Just like at MCG</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264863,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856505,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>We could identify a theme for people to discuss, and perhaps people could submit ideas prior to the chat roulette event, of even during the event</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264884,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856550,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>I like this idea, though I'm also wary of trying to force a conversation in a certain direction. I think conversation often works best when it just flows naturally.</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264972,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856621,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>But I'm really excited to give it a try! I also think it might work better with a group conversation?</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199264986,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1590856657,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f3e838bb3578a1bfb7d808f17602e4456f954f4f?x=x&version=3",
            "client": "website",
            "content": "<p>Hi! I was thinking about organising an early chat roulette for Europe + Asia interaction. Maybe 9 UTC on Wednesday. Any clues from the survey if there'd be interest?</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199362188,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "adam@cthulahoops.org",
            "sender_full_name": "Adam Kelly (they/he) (S1'20)",
            "sender_id": 301014,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1591014218,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a48902c9379b61bebcc7d4ddf51078ad881b09c?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>here's <a href=\"/user_uploads/13/wfjEAuflyX7j0dWkdjGVgiCV/heatmap.png\">heatmap</a> of the results. I would keep in mind that only 17 people answered and we don't know in which time zones they are. Also keep in mind some selection bias as only people that saw the survey and were interested in doing took th etime</p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/wfjEAuflyX7j0dWkdjGVgiCV/heatmap.png\" title=\"heatmap\"><img src=\"/user_uploads/13/wfjEAuflyX7j0dWkdjGVgiCV/heatmap.png\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199387962,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "serena.peruzzo@gmail.com",
            "sender_full_name": "Serena Peruzzo (she) (SP2'20)",
            "sender_id": 7642,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1591027707,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c3792b9056fe1d062b306e7499a4188685289890?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>hey! I thought about using zoom API to create a tool for breakout rooms creation</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202674921,
            "is_me_message": false,
            "last_edit_timestamp": 1593688597,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "uri.shimon5@gmail.com",
            "sender_full_name": "Uri Shimon (he) (S2'20)",
            "sender_id": 301058,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593688554,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c3792b9056fe1d062b306e7499a4188685289890?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>one that will have a state</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202674927,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "uri.shimon5@gmail.com",
            "sender_full_name": "Uri Shimon (he) (S2'20)",
            "sender_id": 301058,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593688560,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c3792b9056fe1d062b306e7499a4188685289890?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>and so it will know not to assign the same people to the same rooms over and over</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202674988,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "uri.shimon5@gmail.com",
            "sender_full_name": "Uri Shimon (he) (S2'20)",
            "sender_id": 301058,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593688573,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c3792b9056fe1d062b306e7499a4188685289890?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>what do you think about the idea?</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202675016,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "uri.shimon5@gmail.com",
            "sender_full_name": "Uri Shimon (he) (S2'20)",
            "sender_id": 301058,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593688612,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f3e838bb3578a1bfb7d808f17602e4456f954f4f?x=x&version=3",
            "client": "website",
            "content": "<p>It would be amazing! The breakout room interface is so badly broken, sometimes random, sometimes not, sometimes gets stuck on one layout and refuses to change, gives countdowns or not...</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202677634,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "adam@cthulahoops.org",
            "sender_full_name": "Adam Kelly (they/he) (S1'20)",
            "sender_id": 301014,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593690915,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"301058\">@Uri Shimon (he) (S2'20)</span> , does clicking the \"recreate rooms\" button not randomize things? It works for me pretty consistently</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202713464,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593708241,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f3e838bb3578a1bfb7d808f17602e4456f954f4f?x=x&version=3",
            "client": "website",
            "content": "<p>It doesn't for me at all. It seems to work sometimes, but not mostly. The room is just split in room arrival order.<br>\nIt might be a linux client bug, but I'm suspicious of the randomness in most chat roulette sessions.</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202721944,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "adam@cthulahoops.org",
            "sender_full_name": "Adam Kelly (they/he) (S1'20)",
            "sender_id": 301014,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593712116,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/02a5b2b6f7220adaf39b9eeea3870a2a8b853948?x=x&version=2",
            "client": "website",
            "content": "<p>Hmm, will keep an eye out for that</p>",
            "content_type": "text/html",
            "display_recipient": "chat-roulette-hosting",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202722318,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 487113,
            "sender_email": "driijko@gmail.com",
            "sender_full_name": "Dree Ko (they) (SP2'20)",
            "sender_id": 257188,
            "sender_realm_str": "recurse",
            "stream_id": 241349,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1593712288,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
