{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<div class=\"codehilite\"><pre>    function HammingDistance() {}\n    HammingDistance.numberOfSetBits = function(i) {\n      i = i - ((i &gt;&gt; 1) &amp; 0x55555555);\n      i = (i &amp; 0x33333333) + ((i &gt;&gt; 2) &amp; 0x33333333);\n      i = (i + (i &gt;&gt; 4)) &amp; 0x0f0f0f0f;\n      i = i + (i &gt;&gt; 8);\n      i = i + (i &gt;&gt; 16);\n      return (i &amp; 0x3f);\n    };\n\n    HammingDistance.xor4 = function(a, b, c) {\n      c[0] = a[0] ^ b[0];\n      c[1] = a[1] ^ b[1];\n      c[2] = a[2] ^ b[2];\n      c[3] = a[3] ^ b[3];\n    };\n\n    HammingDistance.popcnt4 = function(i) {\n      var nobs = HammingDistance.numberOfSetBits;\n      return nobs(i[0]) + nobs(i[1]) + nobs(i[2]) + nobs(i[3]);\n    };\n\n    HammingDistance.compute4 = function(a, b, c) {\n      HammingDistance.xor4(a, b, c);\n      return HammingDistance.popcnt4(c);\n    };\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17607851,
            "is_me_message": false,
            "last_edit_timestamp": 1393473484,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "hamming  distance",
            "submessages": [],
            "timestamp": 1393473388,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>although it's generally good practice to know what you look like to the outside network, in this case, it suffices to know who sent you a request - and never forward a request to the same IP address who sent it to you</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17835095,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "bouncing around",
            "submessages": [],
            "timestamp": 1393880023,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e86b91e08ebe97a19f7f998564157c3599c87e74?x=x&version=1",
            "client": "website",
            "content": "<p>We've made a dht!</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17840892,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "andreecmonette@gmail.com",
            "sender_full_name": "Andr\u00e9e Monette (W'14)",
            "sender_id": 5026,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "DHT",
            "submessages": [],
            "timestamp": 1393886589,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"http://en.wikipedia.org/wiki/Marionnet\" target=\"_blank\" title=\"http://en.wikipedia.org/wiki/Marionnet\">http://en.wikipedia.org/wiki/Marionnet</a></p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17939845,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "virtual networking",
            "submessages": [],
            "timestamp": 1394040468,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>this looks really neat, thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17943133,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "virtual networking",
            "submessages": [],
            "timestamp": 1394044541,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>did I send you the mirage link</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17943136,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "virtual networking",
            "submessages": [],
            "timestamp": 1394044546,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://www.openmirage.org/\" target=\"_blank\" title=\"http://www.openmirage.org/\">http://www.openmirage.org/</a></p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17943184,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "virtual networking",
            "submessages": [],
            "timestamp": 1394044575,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>No, cool, thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17944693,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "virtual networking",
            "submessages": [],
            "timestamp": 1394046232,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"http://en.wikipedia.org/wiki/Project_Xanadu#Original_17_rules\" target=\"_blank\" title=\"http://en.wikipedia.org/wiki/Project_Xanadu#Original_17_rules\">The 17 Rules of Project Xanadu</a></p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18329685,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "xanadu",
            "submessages": [],
            "timestamp": 1394673890,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f727856d13b61ec63a08b140a5aad13a?d=identicon&version=1",
            "client": "website",
            "content": "<p>oh, interesting!</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18360251,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "rose@superluser.com",
            "sender_full_name": "Rose Ames (W2'16)",
            "sender_id": 5011,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "xanadu",
            "submessages": [],
            "timestamp": 1394729039,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"http://jbenet.static.s3.amazonaws.com/2037673/gfs.pdf\" target=\"_blank\" title=\"http://jbenet.static.s3.amazonaws.com/2037673/gfs.pdf\">GFS.pdf</a> (draft)</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18477918,
            "is_me_message": false,
            "last_edit_timestamp": 1394927773,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "Galactic File System",
            "submessages": [],
            "timestamp": 1394927763,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>Juan is a good friend of mine - let me know if you want an intro</p>",
            "content_type": "text/html",
            "display_recipient": "distroweb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18477949,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32098,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25240,
            "subject": "Galactic File System",
            "submessages": [],
            "timestamp": 1394927783,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
