{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"128221\" href=\"/#narrow/stream/128221-entertainment\">#entertainment</a>.</p>\n<p><strong>Description</strong>: Discussion of books/television/movies and and any type of entertainment really. Warning: Spoilers ahead!</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128663609,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 128221,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1530028341,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I couldn't watch it live because I was at wedding, but ended up reading spoilers. Honestly, when reading the spoilers I was pretty disappointed / dissatisfied / and confused. I ended up really enjoying it when I watched it on Monday and wanted to write down some of my thoughts:</p>\n<p><a href=\"https://medium.com/@glasdagger/plot-devices-in-westworlds-s2-finale-aa393d886849\" target=\"_blank\" title=\"https://medium.com/@glasdagger/plot-devices-in-westworlds-s2-finale-aa393d886849\">https://medium.com/@glasdagger/plot-devices-in-westworlds-s2-finale-aa393d886849</a> (writing under a pseudonym because I still want my online presence to be mostly technical) FYI: Spoilers!</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128663860,
            "is_me_message": false,
            "last_edit_timestamp": 1530028664,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028653,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>I DID NOT LIKE THIS EPISODE AT ALL</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128663916,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028697,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>LOL</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128663919,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028701,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>My biggest problem with it was the dialogue, because, oy vey clich\u00e9s</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128663952,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028751,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Who do you think has better dialogue, the robots or humans? Or both worst?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664050,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028815,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>\"This isn't a dream, Dolores... this is a f-ing nightmare!\" and \"You live as long as the last person who remembers you!\" were just.... so bad they distracted me. And there were lots more</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664061,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028836,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>That's a good question</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664064,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028844,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Everyone feels like a cardboard cutout at the moment, to be honest</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664070,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028856,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Question: did you realize that Stubbs was a host?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664084,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f62e",
                    "emoji_name": "open_mouth",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "quelledanielle@gmail.com",
                        "full_name": "D Pham (they) (SP1'18)",
                        "id": 5850
                    },
                    "user_id": 5850
                }
            ],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028866,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Wait</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664085,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028869,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I realized that he was Thor's brother, which was pretty shocking.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664089,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028880,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Not Thor! Is! A Host!</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664094,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028891,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Hemsworth the Lesser</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664095,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028897,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Ford designed him?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664100,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028917,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Is that why he is so bad at his job???</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664142,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f600",
                    "emoji_name": "grinning",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "quelledanielle@gmail.com",
                        "full_name": "D Pham (they) (SP1'18)",
                        "id": 5850
                    },
                    "user_id": 5850
                },
                {
                    "emoji_code": "1f600",
                    "emoji_name": "grinning",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rachel@recurse.com",
                        "full_name": "Rachel Vincent Petacat (she)",
                        "id": 5937
                    },
                    "user_id": 5937
                }
            ],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028931,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Oh.... the \"core drive\" comment... I didn't make that connection! I thought he was making it clear he knew what was really going on with Hale.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664160,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530028978,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>I'm reading Stephen King's <em>On Writing</em>, and something he says about plotting in that book struck me as something that's been bothering me about Westworld this season:</p>\n<blockquote>\n<p>In my view, stories and novels consist of three parts: narration, which moves the story from point A to point B and finally to point Z; description, which creates a sensory reality for the reader; and dialogue, which brings characters to life through their speech.</p>\n<p>You may wonder where plot is in all this. The answer \u2014 my answer, anyway \u2014 is nowhere. I won\u2019t try to convince you that I\u2019ve never plotted any more than I\u2019d try to convince you that I\u2019ve never told a lie, but I do both as infrequently as possible. I distrust plot for two reasons: first, because our lives are largely plotless, even when you add in all our reasonable precautions and careful planning; and second, because I believe plotting and the spontaneity of real creation aren\u2019t compatible. It\u2019s best that I be as clear about this as I can \u2014 I want you to understand that my basic belief about the making of stories is that they pretty much make themselves. The job of the writer is to give them a place to grow (and to transcribe them, of course)... Plot is, I think, the good writer\u2019s last resort and the dullard\u2019s first choice. The story which results from it is apt to feel artificial and labored.</p>\n<p>The situation comes first. The characters\u2014always flat and unfeatured, to begin with\u2014come next. Once these things are fixed in my mind, I begin to narrate. I often have an idea of what the outcome may be, but I have never demanded of a set of characters that they do things my way. On the contrary, I want them to do things their way. In some instances, the outcome is what I visualized. In most, however, it\u2019s something I never expected. For a suspense novelist, this is a great thing. I am, after all, not just the novel\u2019s creator but its first reader. And if I\u2019m not able to guess with any accuracy how the damned thing is going to turn out, even with my inside knowledge of coming events, I can be pretty sure of keeping the reader in a state of page-turning anxiety. And why worry about the ending anyway? Why be such a control freak? Sooner or later every story comes out somewhere.</p>\n</blockquote>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664181,
            "is_me_message": false,
            "last_edit_timestamp": 1530029113,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029030,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Most people didn't get that, so much so that the showrunner had to tell everyone that that was the case. And also, delightful tidbit, he wrote that in the night before that scene filmed: <a href=\"http://ew.com/tv/2018/06/25/westworld-host-stubbs/\" target=\"_blank\" title=\"http://ew.com/tv/2018/06/25/westworld-host-stubbs/\">http://ew.com/tv/2018/06/25/westworld-host-stubbs/</a></p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664243,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029101,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>What did you like about the episode?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664260,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029138,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I think I'd agree that dialogue is not what the show uses to bring characters to life. Probably even more emphasized by how the recaps at the beginning of the episodes were basically all visual this season.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664429,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029332,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I wasn't really sure where the show was going. I was sort of convinced they were going to keep exploring other parts of the park that we didn't know about, or that the entire thing was a simulation lol.</p>\n<p>After this episode, it became clear to me that Season 1 &amp; 2 were basically setup for \"the main plot\" of Westworld. Almost like origin stories for Bernard, Dolores, and Robo-William.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664647,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f446",
                    "emoji_name": "point_up_2",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rachel@recurse.com",
                        "full_name": "Rachel Vincent Petacat (she)",
                        "id": 5937
                    },
                    "user_id": 5937
                }
            ],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029483,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>It felt kinda childish though. Almost like the first movie of the Maze Runner series.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664661,
            "is_me_message": false,
            "last_edit_timestamp": 1530029526,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029514,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I liked how Bernard and William both realized they were basically hallucinating Ford, except Bernard seems pretty sane all of a sudden and William is so far-gone.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664729,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029583,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I started seeing more parallels between the robos and humans, which I guess were sorta there the whole time, but became super explicit in this episode.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664742,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029614,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>I'm also still confused about the maze and how it 'activates' 'free will'</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664781,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029642,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>To the point of an origin story: I <em>loved</em> the episode Kiksuya, and I think I would have liked this season more if that was the first episode in it. It feels like there's been a lot of chaff this season to fill time, and they could have made the whole thing tighter</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664831,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f446",
                    "emoji_name": "point_up_2",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "quelledanielle@gmail.com",
                        "full_name": "D Pham (they) (SP1'18)",
                        "id": 5850
                    },
                    "user_id": 5850
                }
            ],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029723,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>By far the best episode.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664838,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029732,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I also liked the Akane no Mai. I think they're actually pretty close on my list.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664847,
            "is_me_message": false,
            "last_edit_timestamp": 1530029883,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029761,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<blockquote>\n<p>the whole thing tighter</p>\n</blockquote>\n<p>100%....</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664894,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029775,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>It was weirdly positioned as the third-to-last episode.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128664940,
            "is_me_message": false,
            "last_edit_timestamp": 1530030112,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029841,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Am I right in thinking this season they focused a lot more on individual characters in each episode?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665025,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029942,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Yeah! And a lot of what it was revealing the origins of almost seemed besides the point by then? idk</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665033,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029956,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>I didn't notice that before, but yeah, I think so! They had a lot of worldbuilding to do in S1</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665043,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530029977,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I think they enjoyed keeping us in the dark. Sort of a cheap trick, but totally worked for me.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665056,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030001,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Probably what kept me coming back the most. I wanted to what was going on. Was pretty lost at times.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665120,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030032,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Yeah, I felt preeeetty lost most of the time too... reading recaps was helpful and also necessary</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665137,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030063,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Podcasts ++</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665145,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030070,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>It was pretty impressive how Akecheta learned so much from the maze from seeing it once.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665238,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030153,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I also thought he was human that got trapped in the park somehow. Maybe punished by (or rebelling against) Ford.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665257,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030184,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>oh interesting -- why's that?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665266,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030204,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Since we see him in the second episode of this season when Logan is being pitched the whole westworld idea.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665267,
            "is_me_message": false,
            "last_edit_timestamp": 1530030290,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030205,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>This pic: <a href=\"https://www.dailydot.com/wp-content/uploads/2018/06/akecheta.png\" target=\"_blank\" title=\"https://www.dailydot.com/wp-content/uploads/2018/06/akecheta.png\">https://www.dailydot.com/wp-content/uploads/2018/06/akecheta.png</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.dailydot.com/wp-content/uploads/2018/06/akecheta.png\" target=\"_blank\" title=\"https://www.dailydot.com/wp-content/uploads/2018/06/akecheta.png\"><img src=\"https://www.dailydot.com/wp-content/uploads/2018/06/akecheta.png\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665338,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030245,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<blockquote>\n<p>Later in the episode, the show cuts to Logan and William, hanging out in a bar doing some business-minded glad-handing \u2014 which in Logan\u2019s case equates with trying to pick somebody up. William retires for the night, and a mysterious man named Akecheta (Fargo\u2019s Zahn McClarnon) approaches Logan, whom he addresses as \u201cMr. Delos.\u201d The host Angela (Talulah Riley) is with Akecheta, but Logan doesn\u2019t appear to recognize her or realize she\u2019s a host. The mysterious businessman tells Logan he\u2019s from something known as the Argos Initiative, and that he\u2019s there to talk about Delos investing in their project. \u201cDo you have any idea how many startups are begging me for my cash right now?\u201d Logan asks. \u201cAI, VR, AR\u2026\u201d</p>\n</blockquote>\n<p><a href=\"https://www.theverge.com/2018/4/30/17288062/westworld-season-2-episode-2-reunion-recap\" target=\"_blank\" title=\"https://www.theverge.com/2018/4/30/17288062/westworld-season-2-episode-2-reunion-recap\">https://www.theverge.com/2018/4/30/17288062/westworld-season-2-episode-2-reunion-recap</a></p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665400,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030322,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>OOOOH</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665402,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030328,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Right right -- I assumed that they were all robots forever</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665416,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030356,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>I guess based on them having profiles of everyone that's ever visited, Akechata could be a copy of someone Ford knew and something something retribution</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665473,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030400,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I thought the profile cards were pretty hilarious. And the robo-profiles too.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665705,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030707,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I think they show Teddy's robo-profile on screen at some point.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665750,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030727,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Googling for: Teddy Profile didn't give me what I wanted.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665753,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030743,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p><a href=\"https://pbs.twimg.com/media/Df8MmjeUwAA1nUn.jpg\" target=\"_blank\" title=\"https://pbs.twimg.com/media/Df8MmjeUwAA1nUn.jpg\">William Profile</a></p>\n<div class=\"message_inline_image\"><a href=\"https://pbs.twimg.com/media/Df8MmjeUwAA1nUn.jpg\" target=\"_blank\" title=\"William Profile\"><img src=\"https://pbs.twimg.com/media/Df8MmjeUwAA1nUn.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665762,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030784,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p><a href=\"https://i1.wp.com/www.thesnarkingdeadrecaps.com/wp-content/uploads/2018/05/HBOs-Westworld-Season-2-Episode-5-Akane-No-Mai-New-Teddy.jpg?resize=700%2C350\" target=\"_blank\" title=\"https://i1.wp.com/www.thesnarkingdeadrecaps.com/wp-content/uploads/2018/05/HBOs-Westworld-Season-2-Episode-5-Akane-No-Mai-New-Teddy.jpg?resize=700%2C350\">Teddy Profile (before and after)</a></p>\n<div class=\"message_inline_image\"><a href=\"https://i1.wp.com/www.thesnarkingdeadrecaps.com/wp-content/uploads/2018/05/HBOs-Westworld-Season-2-Episode-5-Akane-No-Mai-New-Teddy.jpg?resize=700%2C350\" target=\"_blank\" title=\"Teddy Profile (before and after)\"><img src=\"https://i1.wp.com/www.thesnarkingdeadrecaps.com/wp-content/uploads/2018/05/HBOs-Westworld-Season-2-Episode-5-Akane-No-Mai-New-Teddy.jpg?resize=700%2C350\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665834,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030867,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>THERE'S A TYPO</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665836,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030869,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>They spelled Psychological wrong</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665839,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030876,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Little weird to have the names of the hosts on their profiles, given that they change those, no</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665847,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030902,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>I thought that having the wires to the satellite-beam-horseshoe LIGHT UP as data flowed through them was pretty hilarious, too</p>\n<p>Also: why is it the data beamer thing the same shape as the zap-into-the-Matrix horseshoe the hosts stand in?? Why can two hosts access the mainframe in the very important unsecured room that's sitting over the seawater reservoir without a human??</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665860,
            "is_me_message": false,
            "last_edit_timestamp": 1530030969,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030908,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>The design of that interface, though, good golly</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665883,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530030956,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<blockquote>\n<p>Psychological wrong</p>\n</blockquote>\n<p>Right, should have been \"Psycho Profile\" (might be becoming obvious where I stand on William)</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128665989,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031059,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Should have just read \"NOPE\"</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666062,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f923",
                    "emoji_name": "rolling_on_the_floor_laughing",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "andrew@mrdrozdov.com",
                        "full_name": "Andrew Drozdov (S2'16)",
                        "id": 7630
                    },
                    "user_id": 7630
                }
            ],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031121,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>lol!</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666072,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031140,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>The whole way hosts access the computers was pretty weird, but I guess made for cool visuals.</p>\n<p>The horseshoes were maybe the budget version of the brain grappling hook from the other mainframe?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666154,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031212,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>What do you think happened with William when he went down the elevator?</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666174,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031253,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I have no idea.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666179,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031258,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Also, was hilarious how they had a giant horseshoe for all the hosts to enter Eden. They took that pretty far.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666194,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031299,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Does everyone stand in that together? Is there a giant host somewhere? So many questions!</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666277,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031387,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>Oh, I have NO IDEA</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666281,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031391,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>If there was any respect paid to physics he should have died of blood loss several episodes ago, though</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666300,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031419,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Some podcasters were saying that was evidence for him being a host.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666353,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031445,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>More contrast between Dolores and William. She took 5 shots like it was nothing, he almost dies and goes crazy.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666375,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031490,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I think they were shot the same amount of times.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128666457,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530031572,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9db659ff05e341e3f6051dbe00d536334e384c05?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>+1 to Kiksuya being an amazing episode. Probably my favorite of the series.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128669113,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "stevenli42@gmail.com",
            "sender_full_name": "Steven Li (he) (SP2'18)",
            "sender_id": 112084,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530035001,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9db659ff05e341e3f6051dbe00d536334e384c05?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>It made me really feel for someone who had been very opaque to us, <em>and</em> taught us about the world.</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128669128,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "stevenli42@gmail.com",
            "sender_full_name": "Steven Li (he) (SP2'18)",
            "sender_id": 112084,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530035022,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bfc3f3f03baa5b4d5401d4cbfe7d6a3f82b47790?x=x&version=1",
            "client": "website",
            "content": "<p>(We moved the party <a href=\"#narrow/stream/128222-spoilers/topic/Westworld.20S2.20Finale\" title=\"#narrow/stream/128222-spoilers/topic/Westworld.20S2.20Finale\">over here</a> <span class=\"user-mention\" data-user-id=\"112084\">@Steven Li (SP2'18)</span>!)</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128669393,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "thumbs_up",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "stevenli42@gmail.com",
                        "full_name": "Steven Li (he) (SP2'18)",
                        "id": 112084
                    },
                    "user_id": 112084
                }
            ],
            "recipient_id": 153773,
            "sender_email": "rachel@recurse.com",
            "sender_full_name": "Rachel Vincent Petacat (she)",
            "sender_id": 5937,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld S2 Finale",
            "submessages": [],
            "timestamp": 1530035300,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>Two years later, we're finally back with more mystery, more celebrities, and more AI goodness (well, something-ness). I put together a <a href=\"https://github.com/mrdrozdov/westworld-bingo\" target=\"_blank\" title=\"https://github.com/mrdrozdov/westworld-bingo\">bingo game</a> to keep my labmates and I engaged during our remote watch parties. It's basically a single Python script, and is a bit manual to use, but hopefully simple enough that someone might find it useful. Hope you check it out <span aria-label=\"robot\" class=\"emoji emoji-1f916\" role=\"img\" title=\"robot\">:robot:</span> <span aria-label=\"cowboy\" class=\"emoji emoji-1f920\" role=\"img\" title=\"cowboy\">:cowboy:</span></p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 191357940,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f916",
                    "emoji_name": "robot",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "studio@robertdelanghe.com",
                        "full_name": "Bobby DeLanghe (he) (F2'19)",
                        "id": 240584
                    },
                    "user_id": 240584
                }
            ],
            "recipient_id": 153773,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "Westworld Bingo",
            "submessages": [],
            "timestamp": 1584813079,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/fb56b59547d4bdab81957ad5b62321da2ed54ab6?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Interested in hearing people's thoughts about The Midnight Gospel (available on Netflix), created by Pendleton Ward (of Adventure Time fame) and comedian Duncan Trussell, based on Trussell's conversations with guests on his podcast \"The Duncan Trussell Family Hour\". I've seen it described as a \"philosophical podcast adventure on LSD\".</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199954446,
            "is_me_message": false,
            "last_edit_timestamp": 1591415392,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "jennyxing27@gmail.com",
            "sender_full_name": "Jenny Xing (S1'19)",
            "sender_id": 221839,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "The Midnight Gospel",
            "submessages": [],
            "timestamp": 1591415366,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/fb56b59547d4bdab81957ad5b62321da2ed54ab6?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>I'm planning on watching it soon after I finish Maniac (also a great show on Netflix). Would love to discuss/watch together with someone who's interested!</p>",
            "content_type": "text/html",
            "display_recipient": "entertainment",
            "flags": [
                "read",
                "historical"
            ],
            "id": 199954495,
            "is_me_message": false,
            "last_edit_timestamp": 1591415449,
            "reactions": [],
            "recipient_id": 153773,
            "sender_email": "jennyxing27@gmail.com",
            "sender_full_name": "Jenny Xing (S1'19)",
            "sender_id": 221839,
            "sender_realm_str": "recurse",
            "stream_id": 128221,
            "subject": "The Midnight Gospel",
            "submessages": [],
            "timestamp": 1591415443,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
