{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>how has nobody talked about ethereum yet?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 58729329,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": ".",
            "submessages": [],
            "timestamp": 1464376859,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "website",
            "content": "<p>What is that</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 58729485,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": ".",
            "submessages": [],
            "timestamp": 1464376978,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "website",
            "content": "<p>Oh ok now I see</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 58729512,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": ".",
            "submessages": [],
            "timestamp": 1464377010,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>it's like bitcoin, but less lame</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 58824259,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": ".",
            "submessages": [],
            "timestamp": 1464461099,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c05dd15aa70ac779e922e98df12a6b47b5953c9?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"nabil.hassein@gmail.com\">@Nabil Hassein (SP2'16)</span>  and I are interested in getting into ethereum blockchain development... but are backed up with other projects at the moment</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 60465526,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "zoey.jeong@gmail.com",
            "sender_full_name": "Ye Eun Jeong (she) (S1'16)",
            "sender_id": 9343,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": ".",
            "submessages": [],
            "timestamp": 1465867078,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c05dd15aa70ac779e922e98df12a6b47b5953c9?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"http://hackingdistributed.com/2016/06/17/thoughts-on-the-dao-hack/\" target=\"_blank\" title=\"http://hackingdistributed.com/2016/06/17/thoughts-on-the-dao-hack/\">http://hackingdistributed.com/2016/06/17/thoughts-on-the-dao-hack/</a></p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 60770310,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "zoey.jeong@gmail.com",
            "sender_full_name": "Ye Eun Jeong (she) (S1'16)",
            "sender_id": 9343,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "DAO hacked, ethereum likely to hardfork",
            "submessages": [],
            "timestamp": 1466225971,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p>Does anyone have experience setting up a test net on windows?  Having weird problems with my genesis block</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62004012,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "testnet on windows",
            "submessages": [],
            "timestamp": 1468950827,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p>In case anyone has this problem, genesis is deprecated - use init instead!  Only took a whole day to figure out <img alt=\":face_with_open_mouth_and_cold_sweat:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/face_with_open_mouth_and_cold_sweat.png\" title=\":face_with_open_mouth_and_cold_sweat:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62006474,
            "is_me_message": false,
            "last_edit_timestamp": 1468954901,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "testnet on windows",
            "submessages": [],
            "timestamp": 1468954893,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/76eabfebc63c7549301ce6e9508ac82f?d=identicon&version=1",
            "client": "website",
            "content": "<p><img alt=\":cry:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/cry.png\" title=\":cry:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62006691,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "harold@x.st",
            "sender_full_name": "Harold Cooper (he) (F2'16)",
            "sender_id": 9490,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "testnet on windows",
            "submessages": [],
            "timestamp": 1468955256,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p><img alt=\":loudly_crying_face:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/loudly_crying_face.png\" title=\":loudly_crying_face:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62006741,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "testnet on windows",
            "submessages": [],
            "timestamp": 1468955298,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/76eabfebc63c7549301ce6e9508ac82f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Better than taking a whole day to not figure it out</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62006797,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "harold@x.st",
            "sender_full_name": "Harold Cooper (he) (F2'16)",
            "sender_id": 9490,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "testnet on windows",
            "submessages": [],
            "timestamp": 1468955407,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p>v true </p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62006834,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "testnet on windows",
            "submessages": [],
            "timestamp": 1468955444,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>jeez:</p>\n<blockquote>\n<p>After the Ethereum hard fork on July 20, we now have two chains, Ethereum and Ethereum Classic. Both continue to exist as legitimate blockchains with their own digital assets. </p>\n<p>Some exchanges and service providers have chosen to support both, others have not. Join us Sunday as a panel of industry experts discuss the value of network effects vs diversity, and how future forks might be handled and supported.</p>\n</blockquote>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62566803,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1470157360,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>(from <a href=\"http://www.meetup.com/EthereumSiliconValley/events/233053122/?rv=me1\" target=\"_blank\" title=\"http://www.meetup.com/EthereumSiliconValley/events/233053122/?rv=me1\">http://www.meetup.com/EthereumSiliconValley/events/233053122/?rv=me1</a>)</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62566807,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1470157369,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>The ethereum DAO situation introduced me to a subtitle video meme that I wasn't previously familiar with:</p>\n<p><a href=\"https://www.youtube.com/watch?v=_O5fdMFKEC0\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_O5fdMFKEC0\">https://www.youtube.com/watch?v=_O5fdMFKEC0</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=_O5fdMFKEC0\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_O5fdMFKEC0\"><img src=\"https://i.ytimg.com/vi/_O5fdMFKEC0/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62566887,
            "is_me_message": false,
            "last_edit_timestamp": 1470157561,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1470157546,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p>Eth is the best soap opera</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62567122,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1470158001,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>oh my: <a href=\"https://www.reddit.com/r/EthereumClassic/comments/4t30qf/bitsquare_will_add_ethc_trading_immediately/\" target=\"_blank\" title=\"https://www.reddit.com/r/EthereumClassic/comments/4t30qf/bitsquare_will_add_ethc_trading_immediately/\">https://www.reddit.com/r/EthereumClassic/comments/4t30qf/bitsquare_will_add_ethc_trading_immediately/</a></p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62616045,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1470248940,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>there's now ETH and ETC or ETHC</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62616049,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1470248949,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/76eabfebc63c7549301ce6e9508ac82f?d=identicon&version=1",
            "client": "website",
            "content": "<p>i feel like whatever gets to keep being called \"ETH\" has a significant advantage, makes it seem more official</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 62616134,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "harold@x.st",
            "sender_full_name": "Harold Cooper (he) (F2'16)",
            "sender_id": 9490,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1470249047,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"harold@x.st\">@Harold Cooper (S2'16)</span> good idea. that will lead to great conversations like \"there is only one true ETH.\" \"yes, but which one do you mean?\"</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100112002,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1471544922,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>:-) (disclaimer: I'm only interested in ETH because I'm heavily invested in popcorn futures)</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100112021,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what a mess",
            "submessages": [],
            "timestamp": 1471544966,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c52df4d54166ed7db0141bdb21c7935e502d6ddc?x=x&version=1",
            "client": "website",
            "content": "<p>Has anyone else here spent any time trying to judge which Ethereum client is least buggy? My opinion so far:</p>\n<ul>\n<li>Go: too impossibly huge to audit</li>\n<li>Rust: more reasonable</li>\n<li>Python: only 10k lines! I can imagine actually reading it all. But the first file I look through, I see a bug right away (though an unimportant one).</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 100911547,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "darius@wry.me",
            "sender_full_name": "Darius Bacon (W1'16)",
            "sender_id": 902,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "Client code quality",
            "submessages": [],
            "timestamp": 1473398847,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>The most annoying thing I find about Signal is that my account is locked to my phone number, of which I have multiple, and they change. I've just recently been getting interested in ethereum, but I'm getting the impression Signal could pretty easily be run on the Ethereum blockchain, and you could reuse the same Eth account on multiple devices...</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 110792452,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1494719448,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I suppose then someone would have to pay N fractions of a penny for every message you send?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 110792465,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1494719510,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I wonder if it would be possible to add this feature to Signal as it currently is implemented</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 110792504,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1494719530,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/373cedf8b07bbc701ba5f5f8fcae6dfa?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"mcaoxol@gmail.com\" data-user-id=\"6177\">@Max McCrea (W1'15)</span> can the ethereum blockchain handle the transaction volume that would entail? That's a lot of transactions that would have to be included. I'm not on top of ethereum's transaction scaling \u2013 would it need sidechains/lightning networks/whatever the current hot idea is?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111487456,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "andrew.cove@gmail.com",
            "sender_full_name": "Andrew Cove (SP2'17)",
            "sender_id": 100813,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496173341,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>I think it's much more than fractions of a penny.  I think a transaction might be $0.20 at the moment.</p>\n<p>But more to the point, the blockchain itself is around 10GB and growing at about 1GB per month.  By requiring someone to keep the blockchain around to receive new messages, you'd make it impossible to use a cell phone to send/receive messages, and that's the whole point.</p>\n<p>The reason Signal uses phone numbers isn't that it can't think of alternatives -- it uses phone numbers as a proxy for <em>identity</em>.  If you use Ethereum for identity (a Signal contact is an Ethereum address), you've just pushed the identity problem back a layer.  Now you have to map from real people to Ethereum addresses somehow.  Signal thinks that phone numbers are the best way to avoid having to solve that problem.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111487904,
            "is_me_message": false,
            "last_edit_timestamp": 1496174194,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496174148,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ah, looks like transaction fee is actually 60 cents right now: <a href=\"https://bitinfocharts.com/comparison/ethereum-transactionfees.html\" target=\"_blank\" title=\"https://bitinfocharts.com/comparison/ethereum-transactionfees.html\">https://bitinfocharts.com/comparison/ethereum-transactionfees.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111487981,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496174259,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>whoa, I wonder why those fees are skyrocketing like that...</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489083,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176072,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>Because the price of Ethereum to USD went up 30x in the last six months.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489128,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176102,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>(And Ethereum transactions are paid in gas, which is tied to ether.)</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489130,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176131,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I don't understand what you're saying about phone numbers <span class=\"user-mention\" data-user-email=\"chris@printf.net\" data-user-id=\"7857\">@Chris Ball (SP2'15)</span> . A phone number seems like a pretty bad proxy for identity compared to, basically, anything else I can think of</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489131,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176134,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"mcaoxol@gmail.com\" data-user-id=\"6177\">@Max McCrea (W1'15)</span> I would like you to send you a private message.  How should I find your private key?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489136,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176156,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>the standard username/password combination seems much better?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489139,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176158,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I suppose I could publish my name/username along with the key on the blockchain?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489145,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176200,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>And how do I know that you published it? And which username you have on this particular messenger?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489199,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176232,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>because I told you about it, I suppose?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489209,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176259,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>If the answer is \"you use some <em>other</em> communication mechanism to find out which username I've chosen on this particular site\", well, your technique now has one step more than Signal's.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489212,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176264,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm missing something</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489215,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176265,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I don't see how a phone number is any different</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489221,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176280,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>in that respect</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489226,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176297,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>The average person already knows the phone number of their friends.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489227,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176300,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm having a hard time seeing why that makes such a difference</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489289,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176411,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>and I can also think of other things my friends could readily identify me by, which aren't tied to devices or carriers</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489331,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176469,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>e.g. my email address</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489333,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176473,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>The phone number also bootstraps a social network via address book contacts, which can be an important thing for a fledgling social network.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489349,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176547,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>Many average people don't actually use email addresses much, such that their friends don't know them.  It's all Facebook and Snapchat and texts.  So you might be a bit idiosyncratic (or at least out of the average) in that regard.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489409,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176630,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>hmm.. I still think that having a layer beneath the phone number would fix the most annoying things about signal</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489475,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176765,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>e.g. if I had a uname/pword combination that was the seed for my private key or something along those lines, and that private key could be tied to arbitrary phone numbers</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489524,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496176808,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>The value of a key in a (bytes32 =&gt; uint8) mapping in this contract seems to inexplicably change between calls:</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489611,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496176989,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<div class=\"codehilite\"><pre><span></span>pragma solidity ^0.4.10;\n\ncontract Test {\n    mapping (bytes32 =&gt; uint8) public dict;\n\n    function Test() {}\n\n    function Set(bytes32 key, uint8 val) returns (uint8) {\n        dict[key] = val;\n        return dict[key];\n    }\n\n    function Get(bytes32 key) returns (uint8) {\n        return dict[key];\n    }\n\n}\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489612,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496176997,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<div class=\"codehilite\"><pre><span></span>&gt; deployed_contract.Set.call(&quot;akey&quot;, 5)\n{ [String: &#39;5&#39;] s: 1, e: 0, c: [ 5 ] }\n&gt; deployed_contract.Get.call(&quot;akey&quot;)\n{ [String: &#39;0&#39;] s: 1, e: 0, c: [ 0 ] }\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489622,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496177022,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm at a loss how to debug this</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489626,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496177036,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>(running on testrpc, solidity 4.11)</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489669,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496177059,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>Are you running a miner?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489674,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496177072,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>nope, just a web3 connection to testrpc</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489695,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496177117,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"chris@printf.net\" data-user-id=\"7857\">@Chris Ball (SP2'15)</span> concerning tx price going up, I thought the price of gas was supposed to be market-adjusted dynamically or something?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489745,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496177167,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>although I've had a really hard time finding any documentation on how that works concretely</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489761,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496177216,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ah, perhaps the reason it's high is about miner fees rather than gas directly, then.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489779,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496177254,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>I haven't used testrpc but the obvious thing that might be happening is that you created a transaction but its effects aren't visible yet because it hasn't been included in a mined block that your local client has access to.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111489827,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496177301,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>thanks <span class=\"user-mention\" data-user-email=\"chris@printf.net\" data-user-id=\"7857\">@Chris Ball (SP2'15)</span> that led me on the right track: if I do <code>deployed_contract.Set.sendTransaction(\"akey\", 5, {from: acc})</code> instead it works</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111490469,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496178413,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>maybe call() doesn't provide any gas to change commit the state change or something?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111490478,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "strange Solidity contract behaviour",
            "submessages": [],
            "timestamp": 1496178450,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>so I believe that the main reason the fees were so high was that the default gas price in popular mining software and clients were both ~20k</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111813240,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496876002,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>and people didn't really bother to change these settings for a long time</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111813301,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496876088,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>apparently Vitalik Buterin recently said something about it and avg fees dropped dramatically afterwards</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111813312,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496876119,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I've had transactions go through at 3k instead of 20 today</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111813318,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496876143,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>came out to ~$0.01 USD</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111813323,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496876162,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>also, avg transaction costs are inflated because they include complicated contract transactions that burn a ton of gas</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111813366,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496876188,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>inflated w.r.t. what typical use costs</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111813367,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1496876203,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/373cedf8b07bbc701ba5f5f8fcae6dfa?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm reading through the Ethereum tutorial on how to create a crypto token (<a href=\"https://www.ethereum.org/token\" target=\"_blank\" title=\"https://www.ethereum.org/token\">https://www.ethereum.org/token</a>), and there's a line that encapsulates something that's had me confused for a while:</p>\n<div class=\"codehilite\"><pre><span></span>You can add any of those features, but the catch is that you can only add them at the beginning, so all the token holders will always know exactly the rules of the game before they decide to own one.\n</pre></div>\n\n\n<p>Sooo \"the future of the internet\" is being built on things that can't be changed? That seems sorta fragile. How does that mesh with a lean, test and iterate world?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112621760,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "andrew.cove@gmail.com",
            "sender_full_name": "Andrew Cove (SP2'17)",
            "sender_id": 100813,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what about iterating?",
            "submessages": [],
            "timestamp": 1498510858,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>a typical thing for tokens is to include a governance structure into the contract</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112622703,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what about iterating?",
            "submessages": [],
            "timestamp": 1498512502,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>e.g. if 51% of the token holders vote to do so, all ETH in a contract is moved to some other contract</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112622704,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what about iterating?",
            "submessages": [],
            "timestamp": 1498512525,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>that would be a very simple way to allow for iteration</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112622708,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what about iterating?",
            "submessages": [],
            "timestamp": 1498512544,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/373cedf8b07bbc701ba5f5f8fcae6dfa?d=identicon&version=1",
            "client": "website",
            "content": "<p>i see. hm.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112622844,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "andrew.cove@gmail.com",
            "sender_full_name": "Andrew Cove (SP2'17)",
            "sender_id": 100813,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what about iterating?",
            "submessages": [],
            "timestamp": 1498512752,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p>re: lookup of Ethereum addresses, - it's partially a problem the ENS is trying to solve <a href=\"https://ens.domains/\" target=\"_blank\" title=\"https://ens.domains/\">https://ens.domains/</a></p>\n<p>Not that it will really match the ease of use of phone numbers for the average user anytime soon . . .</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112897131,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1499094317,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p>Also sorry to bump a month old thread, lol. Haven't been on de zulip in awhile</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112897137,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "idea: Signal on ethereum",
            "submessages": [],
            "timestamp": 1499094352,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/71f02ce7299df74799f64522208924fd?d=identicon&version=1",
            "client": "website",
            "content": "<p>anyone going to <a href=\"https://ethereumfoundation.org/devcon3/\" target=\"_blank\" title=\"https://ethereumfoundation.org/devcon3/\">devcon</a>? (besides me)</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112898141,
            "is_me_message": false,
            "last_edit_timestamp": 1499096237,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "cowpig@fastmail.com",
            "sender_full_name": "Max McCrea (W1'15)",
            "sender_id": 6177,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "devcon",
            "submessages": [],
            "timestamp": 1499096218,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/85b7bffdc731ce90a89c323fb362a8be0012652e?x=x&version=2",
            "client": "website",
            "content": "<p>Me!</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112898296,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "sarah.anne.friend@gmail.com",
            "sender_full_name": "Sarah Friend (she) (S2'16)",
            "sender_id": 9500,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "devcon",
            "submessages": [],
            "timestamp": 1499096581,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>I'm looking for non-digital things I can buy with ETH. I'm currently getting paid in ETH for some contract work, not related to cryptocurrency, and would love examples of using it as an actual currency, instead of a commodity or public computation.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 118275352,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what can i buy with ETH?",
            "submessages": [],
            "timestamp": 1510266176,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>1. <a href=\"https://coinjournal.net/new-york-city-preschool-accepts-tuition-payments-bitcoin-ethereum-rejects-credit-card/\" target=\"_blank\" title=\"https://coinjournal.net/new-york-city-preschool-accepts-tuition-payments-bitcoin-ethereum-rejects-credit-card/\">Montessori Preschool</a></p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 118275363,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what can i buy with ETH?",
            "submessages": [],
            "timestamp": 1510266198,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/391eb183c3474a15bf9ad0e87d3ff118?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"6188\">@Jonathan Dahan (S'14)</span> Did you ever find anything? I feel like there is some UX problems that need to get solved before we can start daily transacting with Eth.</p>\n<p>1. We need a highly secure audited mobile wallet (Hardware wallets kind of fill this void, but mobile wallet would == better ease to get started)<br>\n2. A solid invoicing/payments system that could integrate with Point-of-Sale endpoints<br>\n3. Boots on the ground initiative to educate physical retailers about how to accept payments in eth</p>\n<p>For #2 I'm watching the Request Network. For #1 I'm still not using any mobile wallets, just seems so difficult to manually audit code at the moment. We need some automated auditing programs for these mobile applications that can do some serious bytecode/source-code digging to reduce attack space, at least for me to start recommending mobile wallets that would likely be securing the only private keys of the standard user. #3 is going to be fun once #1 &amp; #2 start building some inertia, but is going to require some serious meatspace work.</p>\n<p>As far as online services to buy physical goods, there isn't much yet that I'd trust. The nice thing is that all online purchases of physical goods SHOULD be bought using escrow to protect the buyers, but would require a well trusted third party to resolve disputes. Hopefully some of the larger retailers can enter this space as the the who ecosystem gains more inertia.</p>\n<p>For now I'm just banking my ETH and plan on using it for traveling to the most forward thinking countries that are embracing cryptocurrency tech.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123922726,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "ghthor@gmail.com",
            "sender_full_name": "Will Drengwitz (he) (W1'17)",
            "sender_id": 7099,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "what can i buy with ETH?",
            "submessages": [],
            "timestamp": 1521476006,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/391eb183c3474a15bf9ad0e87d3ff118?d=identicon&version=1",
            "client": "website",
            "content": "<p>Has anyone built out a site using this type of authentication provider? <a href=\"https://hackernoon.com/never-use-passwords-again-with-ethereum-and-metamask-b61c7e409f0d\" target=\"_blank\" title=\"https://hackernoon.com/never-use-passwords-again-with-ethereum-and-metamask-b61c7e409f0d\">https://hackernoon.com/never-use-passwords-again-with-ethereum-and-metamask-b61c7e409f0d</a></p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 128110889,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "ghthor@gmail.com",
            "sender_full_name": "Will Drengwitz (he) (W1'17)",
            "sender_id": 7099,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "Web3 Account Management",
            "submessages": [],
            "timestamp": 1529053948,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/391eb183c3474a15bf9ad0e87d3ff118?d=identicon&version=1",
            "client": "website",
            "content": "<p>The current main headquarters for ethereum design discussion is happening at <a href=\"https://ethereum-magicians.org/\" target=\"_blank\" title=\"https://ethereum-magicians.org/\">https://ethereum-magicians.org/</a></p>\n<p>I'd suggest any discussion start there instead of here.</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 132576425,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "ghthor@gmail.com",
            "sender_full_name": "Will Drengwitz (he) (W1'17)",
            "sender_id": 7099,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "Discussion Zeitgiest",
            "submessages": [],
            "timestamp": 1534942836,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/753274cbd3bb05b5be08f0eb9f095074b75a8b3b?x=x&version=3",
            "client": "website",
            "content": "<p>Hey, I'm manually deploying a transaction to the Ropsten network, and I keep running into this error; \"Error: The contract code couldn't be stored, please check your gas limit.\". I'm calling a function from an already deployed contract, so i'm not sure what's causing this to happen. Has anybody ever ran into this before? Any creative solutions?</p>",
            "content_type": "text/html",
            "display_recipient": "ethereum",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202250674,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 50303,
            "sender_email": "joshkn@protonmail.com",
            "sender_full_name": "Josh Kean (he) (F1'19)",
            "sender_id": 234089,
            "sender_realm_str": "recurse",
            "stream_id": 32809,
            "subject": "Ropsten Gas Limit",
            "submessages": [],
            "timestamp": 1593372278,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
