{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/9fd9de59f964f6e3af477006ddd0116211347010?x=x&version=2",
            "client": "Internal",
            "content": "<p>Stream created by <span class=\"user-mention silent\" data-user-id=\"233941\">Natalie K Olivo (she) (F1'19)</span>.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173684516,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "notification-bot@zulip.com",
            "sender_full_name": "Notification Bot",
            "sender_id": 100006,
            "sender_realm_str": "zulipcore",
            "stream_id": 206924,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1566326940,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p><a href=\"https://davidshariff.com/quiz/\" target=\"_blank\" title=\"https://davidshariff.com/quiz/\">https://davidshariff.com/quiz/</a></p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173684625,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566326973,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"2146\">@Joe Del (he) (S2'19)</span> <span class=\"user-mention\" data-user-id=\"226506\">@Ross Patton (he) (S2'19)</span> <span class=\"user-mention\" data-user-id=\"233913\">@Larry Person (he) (F1'19)</span> <span class=\"user-mention\" data-user-id=\"234882\">@Eli Kim (she) (F1'19)</span> <span class=\"user-mention\" data-user-id=\"234168\">@Maryanne Wachter (she) (F1'19)</span> Here is the quiz I mentioned in our meeting today.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173685563,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566327539,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Also here's a new Full Stack Friends stream :-)</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173685637,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566327586,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/78e97915324799607ad54424e091e3fe937ea1e2?x=x&version=2",
            "client": "website",
            "content": "<p>thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173688297,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "ross_patton@protonmail.com",
            "sender_full_name": "Ross Patton (he) (S2'19)",
            "sender_id": 226506,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566329530,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/78e97915324799607ad54424e091e3fe937ea1e2?x=x&version=2",
            "client": "website",
            "content": "<p>also, this is the article i was following for implementing my hashing/salting/peppering/encrypting process =&gt; <br>\n<a href=\"https://blogs.dropbox.com/tech/2016/09/how-dropbox-securely-stores-your-passwords/\" target=\"_blank\" title=\"https://blogs.dropbox.com/tech/2016/09/how-dropbox-securely-stores-your-passwords/\">https://blogs.dropbox.com/tech/2016/09/how-dropbox-securely-stores-your-passwords/</a></p>\n<p>to be clear - as long as yer hashin with a modern algorithm (bcrypt, scrypt, argon2, dont use md5 or sha1), salting that hash, and storing that then you're mostly fine. that's recommended best practice. im going way beyond what's necessary in my implementation</p>\n<p>initially i was planning to just append the pepper to the password before hashing, as an extra dose of random data, but if the pepper is ever compromised then i'd basically be screwed. i'd have to make a new pepper, and then hash the hash, since hashes are one-way</p>\n<p>so now i'm trying the dropbox thing - keep the pepper, but save it for encrypting the hashed and salted pw. that way we still get an extra level of security, and it's reversible. so if the pepper is ever leaked, it can just be rotated (decrypt entries in the db, recrypt with new pepper, destroy old pepper)</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173688674,
            "is_me_message": false,
            "last_edit_timestamp": 1566329915,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "ross_patton@protonmail.com",
            "sender_full_name": "Ross Patton (he) (S2'19)",
            "sender_id": 226506,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566329864,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/78e97915324799607ad54424e091e3fe937ea1e2?x=x&version=2",
            "client": "website",
            "content": "<p>the css portion of this quiz is exactly why i only write atomic css now</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173689116,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "ross_patton@protonmail.com",
            "sender_full_name": "Ross Patton (he) (S2'19)",
            "sender_id": 226506,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566330190,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/78e97915324799607ad54424e091e3fe937ea1e2?x=x&version=2",
            "client": "website",
            "content": "<p>also some of these questions are very subjective and/or wrong</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173689352,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "ross_patton@protonmail.com",
            "sender_full_name": "Ross Patton (he) (S2'19)",
            "sender_id": 226506,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566330388,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7c81827d2f1fee58170fb9fb326655d65ff716b6?x=x&version=2",
            "client": "website",
            "content": "<p>Wait, was there a link? Don't think I saw a link.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173703829,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "elizabethswkim@gmail.com",
            "sender_full_name": "Eli Kim (she) (W1'19)",
            "sender_id": 234882,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566341967,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7c81827d2f1fee58170fb9fb326655d65ff716b6?x=x&version=2",
            "client": "website",
            "content": "<p>Oops, sorry. Prev msg.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173703936,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "elizabethswkim@gmail.com",
            "sender_full_name": "Eli Kim (she) (W1'19)",
            "sender_id": 234882,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566342013,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p><span class=\"user-mention\" data-user-id=\"226506\">@Ross Patton (he) (S2'19)</span>  yea I noticed that too!</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173800476,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566398698,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Great resource on dissecting static typing vs dynamic typing in JavaScript. I'm through half of part I and it's very insightful so far. While I don't have a lot of experience with static typing in JavaScript, my perception so far is that a static typing system baked in and compatible with your framework can be a big plus for dependability and configurability. Static typing also allows for around runtime. Although for front end apps I'm not sure why compile time linting (es6) would not be enough in many cases real world cases. </p>\n<p><a href=\"https://www.freecodecamp.org/news/why-use-static-types-in-javascript-part-1-8382da1e0adb/\" target=\"_blank\" title=\"https://www.freecodecamp.org/news/why-use-static-types-in-javascript-part-1-8382da1e0adb/\">https://www.freecodecamp.org/news/why-use-static-types-in-javascript-part-1-8382da1e0adb/</a></p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 173899406,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Front End Quiz",
            "submessages": [],
            "timestamp": 1566492542,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>It was just <span class=\"user-mention\" data-user-id=\"234168\">@Maryanne Wachter (she) (F1'19)</span> and I at todays meeting. We talked about Material UI, styles within a React component, things node js is used for and life. Looking forward to next weeks meeting !</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175371868,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1568144804,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "website",
            "content": "<p>Hi everyone! Going to make an attempt here to revive Full Stack Friends meeting today! From 3-4 pm I have reserved Hopper. We can talk about getting started with gatsby, manipulating audio streams,  a tricky problem someone is facing currently or any other topic. Its not a rigid structure. Reply with emojis if you think you'll attend.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176484244,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569344660,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Thank you <span class=\"user-mention\" data-user-id=\"240575\">@Helen Durrant (she) (F2'19)</span> and <span class=\"user-mention\" data-user-id=\"241086\">@Mihir Kedia (m6'19)</span> for chatting today. I just realized this stream may not be public or as visible as I suspected <span aria-label=\"see no evil\" class=\"emoji emoji-1f648\" role=\"img\" title=\"see no evil\">:see_no_evil:</span>. I'll figure out how to make it more visible.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176500345,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f642",
                    "emoji_name": "slight_smile",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "hh.durrant@gmail.com",
                        "full_name": "Helen Durrant (she) (F2'19)",
                        "id": 240575
                    },
                    "user_id": 240575
                }
            ],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569355374,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c2c732b24ee5bd02a9d15fa2bcc59e647934b42?x=x&version=2",
            "client": "website",
            "content": "<p>yea you may have more luck with promo in 397Bridge and @ currently at rc, the same for js mudder since only a few of us are actually in the stream</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176500602,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "joeleedel@gmail.com",
            "sender_full_name": "Joe Del (he) (S2'19)",
            "sender_id": 2146,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569355535,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Ok good call. Thanks Joe! I'll message 397 Bridge next time.</p>\n<p>For next week's meeting, Helen suggested we do one or two code alongs on promises or other topics. We can discuss as we get closer to next tuesday.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176500937,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569355762,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c2c732b24ee5bd02a9d15fa2bcc59e647934b42?x=x&version=2",
            "client": "website",
            "content": "<p>aw that sounds great</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176501417,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "joeleedel@gmail.com",
            "sender_full_name": "Joe Del (he) (S2'19)",
            "sender_id": 2146,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569356107,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>We/I miss you Joe!</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176502907,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569357002,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "website",
            "content": "<p>Greetings Friends! At 3pm today we have Hopper booked for Full Stack Friends meeting. As suggested by <span class=\"user-mention\" data-user-id=\"240575\">@Helen Durrant (she) (F2'19)</span> I'd love to do one or two code alongs / reviews. I can show the native js code I wrote for early progress of my scrabble game (drag and drop native).  I also have rest api I wrote with Express/Mongoose. Or, if anyone else would like to walk us through some other code I'm game for that as well.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177060848,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569940313,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/47e674abdaf1f4135f1bebd286cd85bd641975cb?x=x&version=2",
            "client": "website",
            "content": "<p>I'm happy to walk through some code! I've got a react project I've done recently or can walk through some of the little things I've been working on this / last week</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177064323,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "hh.durrant@gmail.com",
            "sender_full_name": "Helen Durrant (she) (F2'19)",
            "sender_id": 240575,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569942482,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Awesome!</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177070871,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569946354,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Today at Full Stack Friends <span class=\"user-mention\" data-user-id=\"240575\">@Helen Durrant (she) (F2'19)</span> <span class=\"user-mention\" data-user-id=\"240580\">@Yana Chen (she) (F2'19)</span> and I did code walkthroughs. We discovered some security / complexity challenges with reading audio stream data from the browser and Helen white boarded a really cool podcast app she's working on.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177098343,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f60a",
                    "emoji_name": "blush",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "hh.durrant@gmail.com",
                        "full_name": "Helen Durrant (she) (F2'19)",
                        "id": 240575
                    },
                    "user_id": 240575
                }
            ],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1569964144,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "website",
            "content": "<p>Does anyone have any code they'd like to walkthrough at our Full Stack Friends meeting at 3pm today? It could be of any range of complexity, you would just need to be prepared to talk through it.</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177628444,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1570549172,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/47e674abdaf1f4135f1bebd286cd85bd641975cb?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"233941\">@Natalie K Olivo (she) (F1'19)</span> if no one pipes up, how would you feel about going through a list of front end interview questions?</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177628610,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "hh.durrant@gmail.com",
            "sender_full_name": "Helen Durrant (she) (F2'19)",
            "sender_id": 240575,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1570549278,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/47e674abdaf1f4135f1bebd286cd85bd641975cb?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>There's a big list here: <a href=\"https://frontendmasters.com/books/front-end-handbook/2018/practice/interview-q.html\" target=\"_blank\" title=\"https://frontendmasters.com/books/front-end-handbook/2018/practice/interview-q.html\">https://frontendmasters.com/books/front-end-handbook/2018/practice/interview-q.html</a>. Keen for code walk through though if someone has something to share! <span aria-label=\"smiley\" class=\"emoji emoji-1f603\" role=\"img\" title=\"smiley\">:smiley:</span></p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177629163,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "hh.durrant@gmail.com",
            "sender_full_name": "Helen Durrant (she) (F2'19)",
            "sender_id": 240575,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1570549606,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>I'm not opposed to this</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177634548,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1570553095,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"240575\">@Helen Durrant (she) (F2'19)</span> <br>\nshort circuit evaluation:<br>\n<a href=\"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Short-circuit_evaluation\" target=\"_blank\" title=\"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Short-circuit_evaluation\">https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Short-circuit_evaluation</a></p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177653336,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1570564963,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/47e674abdaf1f4135f1bebd286cd85bd641975cb?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>FYI tomorrow we're going to meet at 12pm, not 3pm, and we're going to go through a big bunch of JS questions together (<a href=\"https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md\" target=\"_blank\" title=\"https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md\">https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md</a>)</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 178144590,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "hh.durrant@gmail.com",
            "sender_full_name": "Helen Durrant (she) (F2'19)",
            "sender_id": 240575,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1571092163,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/82feeacd5dd8ed59a4aaa1137553c5e4ac3f5242?x=x&version=2",
            "client": "website",
            "content": "<p>FYI, Since I have to leave early and Helen was the only one who rsvp'd we figured we'd move the meeting time to 12pm. If anyone would like to join us I have some light snacks! Chocolate pocky and dried mangos! If for anything at all come for the snacks!</p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 178201554,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f60d",
                    "emoji_name": "heart_eyes",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "hh.durrant@gmail.com",
                        "full_name": "Helen Durrant (she) (F2'19)",
                        "id": 240575
                    },
                    "user_id": 240575
                }
            ],
            "recipient_id": 359544,
            "sender_email": "nolivo1@gmail.com",
            "sender_full_name": "Natalie K Olivo (she) (F1'19)",
            "sender_id": 233941,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1571151582,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/47e674abdaf1f4135f1bebd286cd85bd641975cb?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"https://javascript.info/async-await\" target=\"_blank\" title=\"https://javascript.info/async-await\">https://javascript.info/async-await</a></p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 178790568,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 359544,
            "sender_email": "hh.durrant@gmail.com",
            "sender_full_name": "Helen Durrant (she) (F2'19)",
            "sender_id": 240575,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1571772633,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f6ffea7772067c115ff6d3e9732194d9204b9277?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p><a href=\"https://www.freecodecamp.org/news/avoiding-the-async-await-hell-c77a0fb71c4c/\" target=\"_blank\" title=\"https://www.freecodecamp.org/news/avoiding-the-async-await-hell-c77a0fb71c4c/\">https://www.freecodecamp.org/news/avoiding-the-async-await-hell-c77a0fb71c4c/</a></p>",
            "content_type": "text/html",
            "display_recipient": "Full Stack Friends",
            "flags": [
                "read",
                "historical"
            ],
            "id": 178792954,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2764",
                    "emoji_name": "heart",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "nolivo1@gmail.com",
                        "full_name": "Natalie K Olivo (she) (F1'19)",
                        "id": 233941
                    },
                    "user_id": 233941
                },
                {
                    "emoji_code": "2764",
                    "emoji_name": "heart",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "hh.durrant@gmail.com",
                        "full_name": "Helen Durrant (she) (F2'19)",
                        "id": 240575
                    },
                    "user_id": 240575
                }
            ],
            "recipient_id": 359544,
            "sender_email": "saduve@gmail.com",
            "sender_full_name": "Sarah Duve (she) (F1'19)",
            "sender_id": 233911,
            "sender_realm_str": "recurse",
            "stream_id": 206924,
            "subject": "Meetings",
            "submessages": [],
            "timestamp": 1571774275,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
