{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e21d9a49cab702093eba359b2dbf1dac?d=identicon&version=1",
            "client": "website",
            "content": "<p>There are a huge number of python resources, e.g.:</p>\n<p><a href=\"https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#python\" target=\"_blank\" title=\"https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#python\">https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#python</a><br>\n<a href=\"http://www.tutorialspoint.com/python/python_useful_resources.htm\" target=\"_blank\" title=\"http://www.tutorialspoint.com/python/python_useful_resources.htm\">http://www.tutorialspoint.com/python/python_useful_resources.htm</a><br>\ngiant list: <a href=\"https://freepythontips.wordpress.com/2013/09/01/best-python-resources/\" target=\"_blank\" title=\"https://freepythontips.wordpress.com/2013/09/01/best-python-resources/\">https://freepythontips.wordpress.com/2013/09/01/best-python-resources/</a><br>\n<a href=\"http://www.quora.com/How-do-I-learn-Python-3\" target=\"_blank\" title=\"http://www.quora.com/How-do-I-learn-Python-3\">http://www.quora.com/How-do-I-learn-Python-3</a><br>\n<a href=\"http://www.quora.com/What-are-the-best-books-courses-for-learning-Python\" target=\"_blank\" title=\"http://www.quora.com/What-are-the-best-books-courses-for-learning-Python\">http://www.quora.com/What-are-the-best-books-courses-for-learning-Python</a><br>\n<a href=\"http://stackoverflow.com/questions/70577/best-online-resource-to-learn-python\" target=\"_blank\" title=\"http://stackoverflow.com/questions/70577/best-online-resource-to-learn-python\">http://stackoverflow.com/questions/70577/best-online-resource-to-learn-python</a><br>\n<a href=\"http://www.fullstackpython.com/best-python-resources.html\" target=\"_blank\" title=\"http://www.fullstackpython.com/best-python-resources.html\">http://www.fullstackpython.com/best-python-resources.html</a><br>\n<a href=\"https://wiki.python.org/moin/BeginnersGuide\" target=\"_blank\" title=\"https://wiki.python.org/moin/BeginnersGuide\">https://wiki.python.org/moin/BeginnersGuide</a></p>\n<p>I plan to sort through these tonight and decide which ones to focus on for the next month or two. </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33338978,
            "is_me_message": false,
            "last_edit_timestamp": 1427917936,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "noahennis@gmail.com",
            "sender_full_name": "Noah Ennis (W2'15)",
            "sender_id": 7102,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1420670974,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e21d9a49cab702093eba359b2dbf1dac?d=identicon&version=1",
            "client": "website",
            "content": "<p>this site visually represents python code executing:<br>\n<a href=\"http://www.pythontutor.com/visualize.html#mode=edit\" target=\"_blank\" title=\"http://www.pythontutor.com/visualize.html#mode=edit\">http://www.pythontutor.com/visualize.html#mode=edit</a><br>\n(scroll down for preset examples)</p>\n<p>I was surprised to find that even when I could predict the program's outputs from the inputs, I was not visualizing the program in my head, as represented here. </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33369642,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "noahennis@gmail.com",
            "sender_full_name": "Noah Ennis (W2'15)",
            "sender_id": 7102,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1420730897,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec4053b80ac64f20e8597d073dd84eff3dc7eda5?x=x&version=1",
            "client": "website",
            "content": "<p>that's really cool - should be especially helpful for more advanced concepts and things like recursion that are hard to visualize.</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33370339,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "jim.j.shields@gmail.com",
            "sender_full_name": "Jim Shields (he) (m8'20)",
            "sender_id": 7093,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1420731718,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b9888e7d73b8ee4743f44b1bd8dac2108ba9d29c?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><a href=\"/user_uploads/13/irFnl-xconsus6ouzmNg7NFk/img_0482.jpg\" target=\"_blank\" title=\"img_0482.jpg\">img_0482.jpg</a> </p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/irFnl-xconsus6ouzmNg7NFk/img_0482.jpg\" target=\"_blank\" title=\"img_0482.jpg\"><img src=\"/user_uploads/13/irFnl-xconsus6ouzmNg7NFk/img_0482.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33390513,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "pickering.amanda@gmail.com",
            "sender_full_name": "Amanda Pickering (W1'14)",
            "sender_id": 6915,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "mind map photo",
            "submessages": [],
            "timestamp": 1420754934,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/11ed5743e4e57d1aa01ba7581e2fdd702ded658c?x=x&version=1",
            "client": "website",
            "content": "<p>half of the post-its are unreadable lol, I hope no one takes them away!</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33392385,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "davoclavo@gmail.com",
            "sender_full_name": "David Gomez-Urquiza (W2'15)",
            "sender_id": 7087,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "mind map photo",
            "submessages": [],
            "timestamp": 1420757203,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a2c54603a7ffb0dbc912f860fc464037ad92d79c?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>As of this morning, they are still up.</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33423304,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "marie.clemessy@gmail.com",
            "sender_full_name": "Marie Charlotte-Amalie Clemessy (she) (W1'14)",
            "sender_id": 6914,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "mind map photo",
            "submessages": [],
            "timestamp": 1420816952,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e21d9a49cab702093eba359b2dbf1dac?d=identicon&version=1",
            "client": "website",
            "content": "<p>What are good sources for annotated python programs? </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33475847,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "noahennis@gmail.com",
            "sender_full_name": "Noah Ennis (W2'15)",
            "sender_id": 7102,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "reading python programs",
            "submessages": [],
            "timestamp": 1420909195,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e21d9a49cab702093eba359b2dbf1dac?d=identicon&version=1",
            "client": "website",
            "content": "<p>in Dive into Python (or elsewhere), does anyone understand \"the and-or trick\"? I don't understand what it's supposed to do, OR why you would want to use it</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33565883,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "noahennis@gmail.com",
            "sender_full_name": "Noah Ennis (W2'15)",
            "sender_id": 7102,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1421094203,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b9888e7d73b8ee4743f44b1bd8dac2108ba9d29c?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>can you show an example/what chapter is this?</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33565943,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "pickering.amanda@gmail.com",
            "sender_full_name": "Amanda Pickering (W1'14)",
            "sender_id": 6915,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1421094275,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e21d9a49cab702093eba359b2dbf1dac?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://www.diveintopython.net/power_of_introspection/and_or.html\" target=\"_blank\" title=\"http://www.diveintopython.net/power_of_introspection/and_or.html\">http://www.diveintopython.net/power_of_introspection/and_or.html</a></p>\n<p>\"If you're a C hacker, you are certainly familiar with the bool ? a : b expression, which evaluates to a if bool is true, and b otherwise. Because of the way and and or work in Python, you can accomplish the same thing.\"</p>\n<p>I haven't used C and am not familiar with this expression. I guess it's a shorthand \"if a == true, X, else Y\".  </p>\n<p>I don't follow how and/or produces the same effect as the C code, but it also doesn't seem useful?</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33566327,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "noahennis@gmail.com",
            "sender_full_name": "Noah Ennis (W2'15)",
            "sender_id": 7102,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1421094735,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/11ed5743e4e57d1aa01ba7581e2fdd702ded658c?x=x&version=1",
            "client": "website",
            "content": "<p>It is a way to do a one-liner <code>if</code>. Another way to do it is <code>X if a else Y</code></p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33566542,
            "is_me_message": false,
            "last_edit_timestamp": 1421095024,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "davoclavo@gmail.com",
            "sender_full_name": "David Gomez-Urquiza (W2'15)",
            "sender_id": 7087,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1421095014,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/d14c2ca7104d9623bd7a7edd821339db?d=identicon&version=1",
            "client": "website",
            "content": "<p>I just found myself asking if Python passes objects by reference or by value. If you can't answer that quesetion immediately, this link does a really good job of explaining it <a href=\"http://robertheaton.com/2014/02/09/pythons-pass-by-object-reference-as-explained-by-philip-k-dick/\" target=\"_blank\" title=\"http://robertheaton.com/2014/02/09/pythons-pass-by-object-reference-as-explained-by-philip-k-dick/\">http://robertheaton.com/2014/02/09/pythons-pass-by-object-reference-as-explained-by-philip-k-dick/</a></p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33954984,
            "is_me_message": false,
            "last_edit_timestamp": 1421795704,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "jdp5087@gmail.com",
            "sender_full_name": "Jon Poler (he) (W2'15)",
            "sender_id": 7078,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Pass object references by value?",
            "submessages": [],
            "timestamp": 1421795683,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b4d94d953db52e1e7cfc3724b95a6dc906fa9d58?x=x&version=2",
            "client": "website",
            "content": "<p>The phrase I like is \"value of the reference\"</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33954997,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "me@ballingt.com",
            "sender_full_name": "Tom Ballinger (he) (W'12)",
            "sender_id": 807,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Pass object references by value?",
            "submessages": [],
            "timestamp": 1421795710,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/d14c2ca7104d9623bd7a7edd821339db?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hey, that works!</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33955053,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "jdp5087@gmail.com",
            "sender_full_name": "Jon Poler (he) (W2'15)",
            "sender_id": 7078,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Pass object references by value?",
            "submessages": [],
            "timestamp": 1421795772,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e21d9a49cab702093eba359b2dbf1dac?d=identicon&version=1",
            "client": "website",
            "content": "<p>This is a useful summary, thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33955618,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "noahennis@gmail.com",
            "sender_full_name": "Noah Ennis (W2'15)",
            "sender_id": 7102,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Pass object references by value?",
            "submessages": [],
            "timestamp": 1421796579,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e21d9a49cab702093eba359b2dbf1dac?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm doing some of the \"Easy\" CodeEval problems in python, if anyone wants to pair on them or do code review.<br>\n<a href=\"https://www.codeeval.com/\" target=\"_blank\" title=\"https://www.codeeval.com/\">https://www.codeeval.com/</a></p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 34184469,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "noahennis@gmail.com",
            "sender_full_name": "Noah Ennis (W2'15)",
            "sender_id": 7102,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "code eval",
            "submessages": [],
            "timestamp": 1422241334,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/59d271635f877633887d5e7b56b961b3?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey , I need a way to do some very simple visualizations / drawing in python, like, draw Cartesian coordinate points and draw lines between them, hopefully switch between different colors etc.. very basic graphics.  what would be a good tool / library to do that in python? </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 35605240,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "cvitanovic.jelena@gmail.com",
            "sender_full_name": "Jelena Cvitanovic (W2'15)",
            "sender_id": 7085,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Visualization in Python",
            "submessages": [],
            "timestamp": 1424810195,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/508dd2e25655046eb1c036c661cb0bac63ec303f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"cvitanovic.jelena@gmail.com\">@Jelena Cvitanovic (W2'15)</span> matplotlib</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 35605561,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "kpishdadian@gmail.com",
            "sender_full_name": "Keyan Pishdadian (he) (W2'15)",
            "sender_id": 7079,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Visualization in Python",
            "submessages": [],
            "timestamp": 1424810518,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/508dd2e25655046eb1c036c661cb0bac63ec303f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><a href=\"http://matplotlib.org/\" target=\"_blank\" title=\"http://matplotlib.org/\">http://matplotlib.org/</a></p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 35605596,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "kpishdadian@gmail.com",
            "sender_full_name": "Keyan Pishdadian (he) (W2'15)",
            "sender_id": 7079,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Visualization in Python",
            "submessages": [],
            "timestamp": 1424810528,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/59d271635f877633887d5e7b56b961b3?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"kpishdadian@gmail.com\">@Keyan Pishdadian (W2'15)</span> this looks like exactly what I need! thank you! </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 35605651,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "cvitanovic.jelena@gmail.com",
            "sender_full_name": "Jelena Cvitanovic (W2'15)",
            "sender_id": 7085,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Visualization in Python",
            "submessages": [],
            "timestamp": 1424810611,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/508dd2e25655046eb1c036c661cb0bac63ec303f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>np, also I would look into <a href=\"http://ipython.org/\" target=\"_blank\" title=\"http://ipython.org/\">http://ipython.org/</a>. It lets you put code into a browser window and see what the graphs look like in realtime.</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 35605710,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "kpishdadian@gmail.com",
            "sender_full_name": "Keyan Pishdadian (he) (W2'15)",
            "sender_id": 7079,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Visualization in Python",
            "submessages": [],
            "timestamp": 1424810692,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/59d271635f877633887d5e7b56b961b3?d=identicon&version=1",
            "client": "website",
            "content": "<p>awesome, I will use it for sure :) thanks! </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 35606089,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "cvitanovic.jelena@gmail.com",
            "sender_full_name": "Jelena Cvitanovic (W2'15)",
            "sender_id": 7085,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Visualization in Python",
            "submessages": [],
            "timestamp": 1424811145,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b8a401c87d51446d7ed50d97dfb81d26?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"noahennis@gmail.com\">@Noah Ennis (W2'15)</span> I'd love to pair on some of these</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37510424,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "lunacodes@gmail.com",
            "sender_full_name": "Luna Lunapiena (she) (SP2'15)",
            "sender_id": 7863,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "code eval",
            "submessages": [],
            "timestamp": 1427917385,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b8a401c87d51446d7ed50d97dfb81d26?d=identicon&version=1",
            "client": "website",
            "content": "<p>Wanna add two more resources:<br>\n<a href=\"https://inventwithpython.com/chapters/\" target=\"_blank\" title=\"https://inventwithpython.com/chapters/\">https://inventwithpython.com/chapters/</a> - Inventing Games with Python - All Command Line Based<br>\n<a href=\"https://inventwithpython.com/pygame/chapters/\" target=\"_blank\" title=\"https://inventwithpython.com/pygame/chapters/\">https://inventwithpython.com/pygame/chapters/</a> - Making Games With Pygame - Uses Pygame Library for GUI purposes</p>\n<p>Both of these books have been wonderful for learning the language in a way that's concrete and fun!!</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37511059,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "lunacodes@gmail.com",
            "sender_full_name": "Luna Lunapiena (she) (SP2'15)",
            "sender_id": 7863,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1427918066,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/df9e8700a8e4136c62edb59ca1bb090893914a8b?x=x&version=3",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>I got started on python with the first book in that collection, so I'm sure that one is just as good :)</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37511216,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "nikkicubed@gmail.com",
            "sender_full_name": "Nikki Bee (she) (SP1'15)",
            "sender_id": 7636,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1427918302,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/df9e8700a8e4136c62edb59ca1bb090893914a8b?x=x&version=3",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>if anybody likes pygame and is interested in pygame, come talk to me because I love using pygcurse, which is by the author of those books!</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37511224,
            "is_me_message": false,
            "last_edit_timestamp": 1427918343,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "nikkicubed@gmail.com",
            "sender_full_name": "Nikki Bee (she) (SP1'15)",
            "sender_id": 7636,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1427918325,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/869e901d9f723754a3c039922095326c0d4031e6?x=x&version=2",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I need help. I'm building an app in Django and I need to implement user accounts. I think I'm *this* close to getting it working but I'm super stuck. I posted on Stack Overflow and got one answer... but it didn't work. If anybody wants some SO points and has an idea of what I'm doing wrong, here's my question: <a href=\"http://stackoverflow.com/questions/30144751/django-user-accounts-creating-view-from-model\" target=\"_blank\" title=\"http://stackoverflow.com/questions/30144751/django-user-accounts-creating-view-from-model\">http://stackoverflow.com/questions/30144751/django-user-accounts-creating-view-from-model</a></p>\n<p>Edit: I might\u2019ve misunderstood the person\u2019s response, so clarification on that would be helpful, too. </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 39321173,
            "is_me_message": false,
            "last_edit_timestamp": 1431221526,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "nancyorgan@gmail.com",
            "sender_full_name": "Nancy Organ (W2'15)",
            "sender_id": 7094,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Django user accounts",
            "submessages": [],
            "timestamp": 1431221420,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea5ab7f7d6e19ffdee32487a6e145475c956689b?x=x&version=3",
            "client": "website",
            "content": "<p>I know that <span class=\"user-mention\" data-user-email=\"heidi.kasemir@gmail.com\">@Heidi Kasemir (SP2'15)</span> was working on Django recently. Maybe she can help?</p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 39322536,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "andrew@mrdrozdov.com",
            "sender_full_name": "Andrew Drozdov (S2'16)",
            "sender_id": 7630,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Django user accounts",
            "submessages": [],
            "timestamp": 1431224896,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/869e901d9f723754a3c039922095326c0d4031e6?x=x&version=2",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Fwiw, I figured it out. Posted my answer on SO, too. Hope it helps someone haha </p>",
            "content_type": "text/html",
            "display_recipient": "intro python group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 39348382,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38081,
            "sender_email": "nancyorgan@gmail.com",
            "sender_full_name": "Nancy Organ (W2'15)",
            "sender_id": 7094,
            "sender_realm_str": "recurse",
            "stream_id": 26423,
            "subject": "Django user accounts",
            "submessages": [],
            "timestamp": 1431288544,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
