{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f1a76a74c82ee6b6f035964c3920908a?d=identicon&version=1",
            "client": "website",
            "content": "<p>kicking this off: jake, james, and I have been spending some time studying and refining our linear algebra skills. to make having a consistent source of material as painless as possible, i assembled together the lecture notes, problem sets and their solutions, exams and their solutions, and the course textbook and put it together into a zip.</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47910710,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "pkurpiewski@gmail.com",
            "sender_full_name": "Marie Jeanne Kurpiewski (she) (S2'15)",
            "sender_id": 8324,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "MIT OCW Materials",
            "submessages": [],
            "timestamp": 1443994644,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f1a76a74c82ee6b6f035964c3920908a?d=identicon&version=1",
            "client": "website",
            "content": "<p>here is a link to the course: <a href=\"http://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/index.htm\" target=\"_blank\" title=\"http://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/index.htm\">http://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/index.htm</a><br>\nhere is a link to said .zip: <a href=\"https://mega.nz/#!QMoSwYJA!EqDP0_vmPqJKjPUX4khcPF5ERTmbBAZHcu54C02RMWQ\" target=\"_blank\" title=\"https://mega.nz/#!QMoSwYJA!EqDP0_vmPqJKjPUX4khcPF5ERTmbBAZHcu54C02RMWQ\">https://mega.nz/#!QMoSwYJA!EqDP0_vmPqJKjPUX4khcPF5ERTmbBAZHcu54C02RMWQ</a><br>\nhere is a sha256 hash for the zip: 6946CDCBF42BECB6744FD35D69E5332E4DADED17CD78FB3B9397E592CEA25447</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47910736,
            "is_me_message": false,
            "last_edit_timestamp": 1443994869,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "pkurpiewski@gmail.com",
            "sender_full_name": "Marie Jeanne Kurpiewski (she) (S2'15)",
            "sender_id": 8324,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "MIT OCW Materials",
            "submessages": [],
            "timestamp": 1443994778,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/43629df76ff51972188919f392a50fccf6233dfb?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>very nice, thanks for giving some organization to this peter</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47912239,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "jamesmlee@gmail.com",
            "sender_full_name": "James M Lee (F1'15)",
            "sender_id": 8477,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "MIT OCW Materials",
            "submessages": [],
            "timestamp": 1444001415,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/9e0096ad9f376eb9f609372bc87542e4?d=identicon&version=1",
            "client": "desktop app Mac 0.5.0",
            "content": "<p>having a hard time finding how to do very simple collisions based off of velocity vectors rather than angle/speed. anyone in here have an idea how I'd reflect a vector with respect to another LA style?</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47968847,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "tehgeekmeister@gmail.com",
            "sender_full_name": "Sophie Ren\u00e9e Smithburg (she) (F2'15)",
            "sender_id": 8690,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444140912,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/9e0096ad9f376eb9f609372bc87542e4?d=identicon&version=1",
            "client": "desktop app Mac 0.5.0",
            "content": "<p>wait is this just multiplication by a vector of unit length?</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47968861,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "tehgeekmeister@gmail.com",
            "sender_full_name": "Sophie Ren\u00e9e Smithburg (she) (F2'15)",
            "sender_id": 8690,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444140925,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/9e0096ad9f376eb9f609372bc87542e4?d=identicon&version=1",
            "client": "desktop app Mac 0.5.0",
            "content": "<p>...</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47968865,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "tehgeekmeister@gmail.com",
            "sender_full_name": "Sophie Ren\u00e9e Smithburg (she) (F2'15)",
            "sender_id": 8690,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444140928,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/9e0096ad9f376eb9f609372bc87542e4?d=identicon&version=1",
            "client": "desktop app Mac 0.5.0",
            "content": "<p>I HAVE NO CLUE</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47968873,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "tehgeekmeister@gmail.com",
            "sender_full_name": "Sophie Ren\u00e9e Smithburg (she) (F2'15)",
            "sender_id": 8690,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444140932,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c52df4d54166ed7db0141bdb21c7935e502d6ddc?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tehgeekmeister@gmail.com\">@Ezekiel Benjamin Smithburg (F2'15)</span> want to work it out together on paper? Maybe I can help.</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47974369,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "darius@wry.me",
            "sender_full_name": "Darius Bacon (W1'16)",
            "sender_id": 902,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444144540,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/9e0096ad9f376eb9f609372bc87542e4?d=identicon&version=1",
            "client": "desktop app Mac 0.5.0",
            "content": "<p>found a stack overflow question with the formula, just going to use that</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47974395,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "tehgeekmeister@gmail.com",
            "sender_full_name": "Sophie Ren\u00e9e Smithburg (she) (F2'15)",
            "sender_id": 8690,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444144562,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/9e0096ad9f376eb9f609372bc87542e4?d=identicon&version=1",
            "client": "desktop app Mac 0.5.0",
            "content": "<p>but thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47974405,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "tehgeekmeister@gmail.com",
            "sender_full_name": "Sophie Ren\u00e9e Smithburg (she) (F2'15)",
            "sender_id": 8690,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444144563,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/9e0096ad9f376eb9f609372bc87542e4?d=identicon&version=1",
            "client": "desktop app Mac 0.5.0",
            "content": "<p><a href=\"http://math.stackexchange.com/questions/13261/how-to-get-a-reflection-vector\" target=\"_blank\" title=\"http://math.stackexchange.com/questions/13261/how-to-get-a-reflection-vector\">http://math.stackexchange.com/questions/13261/how-to-get-a-reflection-vector</a></p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47974443,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "tehgeekmeister@gmail.com",
            "sender_full_name": "Sophie Ren\u00e9e Smithburg (she) (F2'15)",
            "sender_id": 8690,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "collisions!",
            "submessages": [],
            "timestamp": 1444144578,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c6a9338d0899d13e4b427fa30432a1a0?d=identicon&version=6",
            "client": "website",
            "content": "<p>(deleted)</p>",
            "content_type": "text/html",
            "display_recipient": "linear algebra",
            "flags": [
                "read",
                "historical"
            ],
            "id": 114044994,
            "is_me_message": false,
            "last_edit_timestamp": 1501537361,
            "reactions": [],
            "recipient_id": 43398,
            "sender_email": "eunjincho503@gmail.com",
            "sender_full_name": "Jinny Cho (m1'17)",
            "sender_id": 101399,
            "sender_realm_str": "recurse",
            "stream_id": 27734,
            "subject": "kernels and determinants",
            "submessages": [],
            "timestamp": 1501536970,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
