{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"202706\" href=\"/#narrow/stream/202706-livestreaming\">#livestreaming</a>.</p>\n<p><strong>Description</strong>: Discuss video streaming coding, art making, or anything else, to Twitch, YouTube, or anywhere else!</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169181514,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 202706,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1561674407,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Hi all! I went ahead and created the stream, since why not :) I invited everyone who was mentioned/participated in the other thread, so my apologies if there was any collateral damage and I subscribed people who would rather not be!</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169181731,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "lisa.neigut@gmail.com",
                        "full_name": "Lisa Neigut (she) (S'12)",
                        "id": 917
                    },
                    "user_id": 917
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rj@rybar.tech",
                        "full_name": "Rachel Julianne Rybarczyk (she) (SP1'19)",
                        "id": 203863
                    },
                    "user_id": 203863
                },
                {
                    "emoji_code": "1f4aa",
                    "emoji_name": "muscle",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "phoebe@slub.co",
                        "full_name": "phoebe beatrice jenkins (she) (m4'18)",
                        "id": 101991
                    },
                    "user_id": 101991
                }
            ],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1561674529,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Also, I gave it the broadest possible stream description, since I'm not sure what people are most interested in.</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169181758,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1561674568,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>To get things off to a good start, let's go with what will probably be the first of many technical support type questions/discussions <span aria-label=\"fire\" class=\"emoji emoji-1f525\" role=\"img\" title=\"fire\">:fire:</span> <span aria-label=\"computer\" class=\"emoji emoji-1f4bb\" role=\"img\" title=\"computer\">:computer:</span></p>\n<p>Has anyone gotten streaming in 4k working? I got a 4k capture card working, but the output on youtube is blurry, even though youtube is claiming (via the little gear on my stream) to be in 4k. 4k streaming is super bandwidth intensive (50,000 megabits/second) and nobody actually does it, so I'm suspecting that it's not well supported.</p>\n<p>And, relatedly, what resolution do people like to stream in? On Twitch, non-partnered streamers usually stream at 720p, and partnered streamers usually stream at 1080p*. But, I like to code at a higher resolution, and find my workspace is pretty cramped at 1080p. However, since it's important that viewers of a coding livestream actually be able to read the text,  larger text at 1080p might be better for legibility. So yeah, dilemma <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span> Any thoughts?</p>\n<p>*Non-partnered streamers go with 720p because if you're not partnered, Twitch won't downsample and re-encode your stream, so if you stream at a high bandwidth you might be reducing your audience. Partnered streamers stream at 1080p because Twitch provides downsampled and reencoded streams at 720p, 480p, etc, so people with a variety of internet connections can still watch the stream.</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169182277,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1561675150,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>I have a horrible connection, so I'm trying streaming at 720p and hoping for the best.  Realistically though, I think my \"livestreaming\" is always going to be recorded and posted later, unless I manage some better voodoo.</p>\n<p>That said, it seems pretty ridiculous that 720p is the lowest I can choose in <code>obs</code>.  When I'm making embroidery videos I'm composing two cameras  and want a wider canvas that the user can decide how to adapt, and when I'm doing coding I'm recording a terminal and could just as easily record in a smaller resolution directly without loss of fidelity and let the user scale things up (really, it could just be <code>tmux</code> - if <code>asciicast</code> supported an accompanying audio track, that would be perfect).</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169425523,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1562010611,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Yeah, the options are pretty rough. It might be hard to set up, but streaming asciicast + audio to a server with better connectivity, and then rendering there and streaming the video to twitch or youtube, would be awesome.</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169436099,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1562019542,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Audio and asciiicast are very low bandwidth, so almost any connection would probably be fine, with some buffering.</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169436138,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1562019573,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"4994\">@Mindy Preston (she) (m4'18)</span> PS Are you sure you can't stream lower than 720p in OBS? I google searched a little bit, and it looks like there are some tutorials for how to stream at below 480p. Are you using OBS Studio?</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169617305,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1562209425,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>Hm, so I'd assumed from the <code>canvas size</code> being a drop-down with two items that those were the only things supported, but prompted by this message I tried typing stuff in there and indeed you can put whatever you like.  (I am using OBS studio, version 22something.)</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169778846,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1562440302,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>I actually ran into the same problem. I wanted a resolution that wasn't in a drop down menu, and it took me quite a while to figure out that I could just type things in there &gt;_&lt;</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169784589,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1562451185,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Pretty questionable UI! It's like a series of checkboxes where you can actually delete the text after one of the checkboxes and put whatever you want in.</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169784601,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "Streaming resolution",
            "submessages": [],
            "timestamp": 1562451231,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>i've been trying to stream as much of my work on c-lightning as possible, so i haven't really been paying much attention to scheduling since i'm more 'concerned' about output than audience but now i'm wondering if it'd be more accessible in terms of providing a service that others can tune into regularly if i published and stuck to a regular schedule (like 12noon to 1p two or three days a week)</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170411598,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562629547,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>the whole point of streaming is to make c-lightning development more accessible, so it seems like having a set schedule is a pretty good idea</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170411662,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562629599,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>does anyone else have thoughts around this?</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170411668,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562629611,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>i saw <span class=\"user-mention\" data-user-id=\"2911\">@Andrew Kelley (he) (SP1'17)</span> mention that he does Zig programming on a schedule, which is what made me think of it!</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170411687,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562629636,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>ok so this is happening. it turns out you can schedule things on twitch! <a href=\"https://www.twitch.tv/events/mTQSxOGKTF2g6zt38KA8OA\" target=\"_blank\" title=\"https://www.twitch.tv/events/mTQSxOGKTF2g6zt38KA8OA\">https://www.twitch.tv/events/mTQSxOGKTF2g6zt38KA8OA</a></p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170412449,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562630563,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>I get the feeling that consistency wins out over anything in the long run, so hopefully will have something interesting to report back in a few weeks :)</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170412467,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562630602,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>it seems like there's been a few comments on my streams while i've been doing them live, but i can't for the life of me figure out how to see them after the stream has ended. does anyone else know how to do this?</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170412523,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "how t o see comments on twitch?",
            "submessages": [],
            "timestamp": 1562630646,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>i'd be interested in checking out some other people's streams, if you've got a schedule going post it here and i'll add it to my calendar :)</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170412576,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562630728,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Regarding consistency, from posts I've read on reddit about how to grow a stream, consistency and stream length are both commonly mentioned.</p>\n<p>My takeaway has been that having a consistent schedule so that people who find your stream know when to tune in again is important. Probably streaming at the same time every day is best, so that people don't have to think too much about when they can tune in next.</p>\n<p>Twitch heavily promotes streams with a high current viewer count in various places in its UI. Current viewer count is the main (I think only?) factor that determines where a stream shows up in search results. Most frustratingly, current viewer count also determines where a live stream shows up in a user's favorite list. (My rant on the subject: <a href=\"https://twitter.com/rodarmor/status/1142559835277279233\" target=\"_blank\" title=\"https://twitter.com/rodarmor/status/1142559835277279233\">https://twitter.com/rodarmor/status/1142559835277279233</a>)</p>\n<p>So, given the above, I think a long stream length is also important for building viewership. Current viewer count takes some time to build up over the course of a given stream, which helps a stream climb in various lists in Twitch's UI. The recommendation I've seen is that streaming for four hours or more is a good idea to build up current viewer count. Anything less than four hours, it is opined, isn't enough for a given stream to build up viewership momentum.</p>\n<p>It's interesting to think about how this might work for a programming stream. I could maybe imagine doing 4 hours of quality programming in one go, but 6 or more, which is the length of most popular gaming streams, would probably be too fatiguing. For my own streams, I might try to figure out some other activities that I could add in that could get the stream length up that I would enjoy, that would be a good break from programming. Like, 3 hours of programming, then an hour and a half of me playing minecraft while I complain about pet peeves in programming and ride around my favorite hobby horses, and then back to some programming.</p>\n<p>This is second hand and unverified, so take it with a grain of salt!</p>\n<div class=\"inline-preview-twitter\"><div class=\"twitter-tweet\"><a href=\"https://twitter.com/rodarmor/status/1142559835277279233\" target=\"_blank\"><img class=\"twitter-avatar\" src=\"https://pbs.twimg.com/profile_images/925271448209330176/CQK9OiW9_normal.jpg\"></a><p>Yo <a href=\"https://twitter.com/Twitch\" target=\"_blank\" title=\"https://twitter.com/Twitch\">@Twitch</a> your recommendation / ranking / notification / everything algorithm's sole metric seems to be channel popularity.\n\nThis has a few problems:</p><span>- Casey Rodarmor (@rodarmor)</span></div></div>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170413585,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562632004,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>By the way, how has your experience streaming been in terms of stream length/fatigue/your own engagement been? Do you have a feeling about what the optimal stream length would be for you?</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170413805,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562632256,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>oh wow four hours is a lot. recently i've been streaming pomodoro cycles, which is 25 minutes at a chunk. sometimes i'll go over when i get into a thing and don't want to stop. they average out to 30min a pop tho</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170414700,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562633500,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>the pomodoros have been working really well, fwiw!</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170414763,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562633532,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>(but that's from a personal productivity standpoint, not a viewership one!) <span aria-label=\"laughing\" class=\"emoji emoji-1f606\" role=\"img\" title=\"laughing\">:laughing:</span></p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170414785,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562633590,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>It's possible that you could balance out the effect of short streams (.5-2 hours, say), by doing them at the same time every day. I'm still trying to get my ish together to actually stream, right now I'm being stymied by not having good internet, but when I eventually can, I'm going to try to do short streams but do them every day.</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170415344,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "mindy.preston@yomimono.org",
                        "full_name": "Mindy Preston (she) (F2'19)",
                        "id": 4994
                    },
                    "user_id": 4994
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "lisa.neigut@gmail.com",
                        "full_name": "Lisa Neigut (she) (S'12)",
                        "id": 917
                    },
                    "user_id": 917
                }
            ],
            "recipient_id": 344485,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "scheduling",
            "submessages": [],
            "timestamp": 1562634338,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/81c6c8040fc0263607edd05c09dacf6b?d=identicon&version=1",
            "client": "website",
            "content": "<p>The only way I know how to do this is to replay the video, which will also replay the comments.  Maybe there's a better way?</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171863263,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "julian@cipht.net",
            "sender_full_name": "Julian Squires (he) (F2'17)",
            "sender_id": 101992,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "how t o see comments on twitch?",
            "submessages": [],
            "timestamp": 1564267984,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/da27a2081fcf44c802c1806cdb5bb881310dfe7c?x=x&version=5",
            "client": "website",
            "content": "<p>You can also have bots that record history</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 172186782,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "ad@lamarque.fr",
            "sender_full_name": "Adrien Lamarque (they/he) (S1'16)",
            "sender_id": 9335,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "how t o see comments on twitch?",
            "submessages": [],
            "timestamp": 1564629201,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5ca882c23204bfc3a53558da17fdb03caf83ced2?x=x&version=1",
            "client": "website",
            "content": "<p>i figured out that you can scroll to the end and they'll all show up</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 174404067,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "lisa.neigut@gmail.com",
            "sender_full_name": "Lisa Neigut (she) (S'12)",
            "sender_id": 917,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "how t o see comments on twitch?",
            "submessages": [],
            "timestamp": 1567028849,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ebebe577b320b85ac95f2e4d70501e57?d=identicon&version=1",
            "client": "website",
            "content": "<p>I\u2019m live now! <a href=\"https://twitch.tv/bern\" target=\"_blank\" title=\"https://twitch.tv/bern\">https://twitch.tv/bern</a></p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 185146752,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f419",
                    "emoji_name": "octopus",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "lisa.neigut@gmail.com",
                        "full_name": "Lisa Neigut (she) (S'12)",
                        "id": 917
                    },
                    "user_id": 917
                }
            ],
            "recipient_id": 344485,
            "sender_email": "bern422@gmail.com",
            "sender_full_name": "Bernie Marger (he) (m1'20)",
            "sender_id": 255212,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "I\u2019m livestreaming some sessions from my RC Batch",
            "submessages": [],
            "timestamp": 1578510968,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>I'm going to try livestreaming building qubes-mirage-firewall with a new low-level stack over at <a href=\"http://twitch.tv/yomimono\">http://twitch.tv/yomimono</a> at 19:00 CDT (that's UTC-5) tonight!</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 206200553,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "some ocaml stuff",
            "submessages": [],
            "timestamp": 1596750133,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>nm, canceling this! something came up and it's not a good night to try a livestream</p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 206204362,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "some ocaml stuff",
            "submessages": [],
            "timestamp": 1596752866,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/04ca5a14273f759166bbbfc15e3e400910e7a053?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention silent\" data-user-id=\"100476\">Nelson Elhage</span> is live on <span class=\"user-mention silent\" data-user-id=\"6927\">Jean Yang</span> + Hongyi Hu's PLT stream now talking about Sorbet (the Ruby typechecker): <a href=\"https://www.twitch.tv/jeanqasaur\">https://www.twitch.tv/jeanqasaur</a></p>",
            "content_type": "text/html",
            "display_recipient": "livestreaming",
            "flags": [
                "read",
                "historical"
            ],
            "id": 208402380,
            "is_me_message": false,
            "last_edit_timestamp": 1598655514,
            "reactions": [],
            "recipient_id": 344485,
            "sender_email": "jdherg@gmail.com",
            "sender_full_name": "John Hergenroeder (he) (SP2'15)",
            "sender_id": 7851,
            "sender_realm_str": "recurse",
            "stream_id": 202706,
            "subject": "sorbet stream",
            "submessages": [],
            "timestamp": 1598654423,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
