{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b2d41e7def3ee97a7bd5612e7fe2f604?d=identicon&version=1",
            "client": "website",
            "content": "<p>We could talk about it here!</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29216575,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "earthlingzephyr@gmail.com",
            "sender_full_name": "Zephyr Shannon (they) (F2'14)",
            "sender_id": 6687,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413490877,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b2d41e7def3ee97a7bd5612e7fe2f604?d=identicon&version=1",
            "client": "website",
            "content": "<p>Instead of always using PMs</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29216580,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "earthlingzephyr@gmail.com",
            "sender_full_name": "Zephyr Shannon (they) (F2'14)",
            "sender_id": 6687,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413490887,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b2d41e7def3ee97a7bd5612e7fe2f604?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tacla.yamada@gmail.com\">@Pedro Tacla Yamada (F2'14)</span> <span class=\"user-mention\" data-user-email=\"a.alekseyev@inventati.org\">@Alex Alekseyev (F1'14)</span> <span class=\"user-mention\" data-user-email=\"adrien.guillo@gmail.com\">@Adrien Guillo (F2'14)</span> </p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29216635,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "earthlingzephyr@gmail.com",
            "sender_full_name": "Zephyr Shannon (they) (F2'14)",
            "sender_id": 6687,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413490929,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Cool...</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29216727,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413491049,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"geoffpshannon@gmail.com\">@Geoff Shannon (F2'14)</span> <span class=\"user-mention\" data-user-email=\"adrien.guillo@gmail.com\">@Adrien Guillo (F2'14)</span> <span class=\"user-mention\" data-user-email=\"tacla.yamada@gmail.com\">@Pedro Tacla Yamada (F2'14)</span> How is it going? I've got chapter 3 working, but refactoring doesn't come easy.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391312,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836081,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>Currently struggling with the Python bindings</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391344,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836138,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b2d41e7def3ee97a7bd5612e7fe2f604?d=identicon&version=1",
            "client": "website",
            "content": "<p>Still grappling with issues from Xcode llvm vs homebrew llvm vs a version that I built myself...</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391772,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "earthlingzephyr@gmail.com",
            "sender_full_name": "Zephyr Shannon (they) (F2'14)",
            "sender_id": 6687,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836668,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Still making the REPL work :P haha... But I'll catch up with you; no problem</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391800,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836703,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I made a Range wrapper for STDIN</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391805,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836716,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Actually a class which generates a Range (essentially an iterator) out of a file handle and buffers it accordingly</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391814,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836739,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Except it isn't working that well</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391820,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836748,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Worse case scenario I'll just port global variable soup to D and move on</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391856,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836767,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"a.alekseyev@inventati.org\">@Alex Alekseyev (F1'14)</span> How did you model state with classes?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391873,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836788,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>By the way, if we want to get ride of the ugly global variables, we need to pass them around between each loop right ?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391884,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836803,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>The haskell version does it all in a very clean way, but it's reading line by line, rather than character by character as far as I'm aware</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391896,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836824,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"adrien.guillo@gmail.com\">@Adrien Guillo (F2'14)</span> I guess...</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391900,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836835,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I don't know really... For me the Lexer is consuming a stream of characters and the Parser a stream of tokens, but of course D isn't as high-level of a language to model that correctly</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391924,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836873,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>And it doesn't help me that <code>std.stream</code> is deprecated :P</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29391949,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413836884,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>Yeah doing it in Python is quite handy, I managed to have byte-per-byte lexer and a token-per-token parser quite easily, both working concurrently</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29392089,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413837021,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tacla.yamada@gmail.com\">@Pedro Tacla Yamada (F2'14)</span> I haven't modeled it with classes, I'm just trying to. The character-by-character thing is really in my way.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29392090,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413837023,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>But how are you consuming the parser's output?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29392365,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413837289,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p>Isn't parser's output an AST? Do you mean lexer's output? If yes, that's the problem - I end up with either very tightly coupled lexer and parser, or a \"lex everything, then parse everything\" approach.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29392514,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413837489,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p>...or just wrap everything into a singleton, which I'd like to avoid.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29392891,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413837963,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p>Maybe it's not such a bad idea to just walk through the tutorial as is, and then start implementing your own thing from scratch.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29395975,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413842122,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Yes</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29395980,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413842139,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I'm tempted to just read the Haskell or Ocaml tutorial</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29395989,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413842159,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>*als</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29396019,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413842168,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/556318094ee6dbabf9570403d54e02f3?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"adrien.guillo@gmail.com\">@Adrien Guillo (F2'14)</span> Did you give-up on Rust?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29396609,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "tacla.yamada@gmail.com",
            "sender_full_name": "Pedro Tacla Yamada (F2'14)",
            "sender_id": 6682,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413843101,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm getting this working in Python, then I'll see about Rust</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29396653,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413843140,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b2d41e7def3ee97a7bd5612e7fe2f604?d=identicon&version=1",
            "client": "website",
            "content": "<p>Okay, so I just worked my way through the 4th chapter in C++.  And the code that they reference is frankly broken.  I managed to fix it with some excellent input from Alex, but it wasn't entirely trivial to determine what to change and why...  So I'm totally on board with the idea of simply going through the tutorial as-is before even attempting to change the structure of the code.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29397507,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "earthlingzephyr@gmail.com",
            "sender_full_name": "Zephyr Shannon (they) (F2'14)",
            "sender_id": 6687,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413844589,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>Has anyone got a REPL working?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29441622,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919312,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>Mine is except for redefining functions. I'd like to see how your implementations behave.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29441671,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919354,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p>Do you actually execute the code or just produce an IR?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29441699,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919401,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>produce IR</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29441863,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919583,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p>Oh, I have that working.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29441902,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919637,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p>But I pretty much quit following along code-wise and am just reading the tutorial and planning to start something from scratch today or tomorrow.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29441976,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919719,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ok. Can I check something with you ?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29442022,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919803,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6ecc102c3cee58ab6ed566b2eb95ee969bab6fb1?x=x&version=1",
            "client": "website",
            "content": "<p>Sure.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 29442071,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "alex@evectant.com",
            "sender_full_name": "Alex Alekseyev (F1'14)",
            "sender_id": 6430,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Kaleidoscope tutorial",
            "submessages": [],
            "timestamp": 1413919820,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"ethan.o.raymond@vanderbilt.edu\" data-user-id=\"101112\">@Ethan Raymond (S1'17)</span> <span class=\"user-mention\" data-user-email=\"jaseemabid@gmail.com\" data-user-id=\"101128\">@Jaseem Abid (S1'17)</span> Looks like we all have interest in using LLVM now or soon. Let's use this stream for questions/ideas.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111204068,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "code@saul.pw",
                        "full_name": "Saul Pwanson (SP2'17)",
                        "id": 100791
                    },
                    "user_id": 100791
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jaseemabid@gmail.com",
                        "full_name": "Jaseem Abid (he) (S1'17)",
                        "id": 101128
                    },
                    "user_id": 101128
                }
            ],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495555108,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4e0e55d0dc86c5e9d5390f80a23a6f8f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Sounds good <img alt=\":+1:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/unicode/1f44d.png\" title=\":+1:\"></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111204099,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "ethan.o.raymond@vanderbilt.edu",
            "sender_full_name": "Ethan Raymond (S1'17)",
            "sender_id": 101112,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495555191,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>How are you all planning to get started? I'm read through the intro posts on <a href=\"http://llvm.org/docs\" target=\"_blank\" title=\"http://llvm.org/docs\">llvm.org/docs</a> and is now going through this (very) long document describing the IR. <a href=\"http://llvm.org/docs/LangRef.html\" target=\"_blank\" title=\"http://llvm.org/docs/LangRef.html\">http://llvm.org/docs/LangRef.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111204313,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495555493,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p>Def do the Kaleidoscope tutorial if you haven't:</p>\n<p><a href=\"http://llvm.org/docs/tutorial/LangImpl01.html\" target=\"_blank\" title=\"http://llvm.org/docs/tutorial/LangImpl01.html\">http://llvm.org/docs/tutorial/LangImpl01.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111204453,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495555702,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4e0e55d0dc86c5e9d5390f80a23a6f8f?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm just starting off with a lexer, using the kaleidoscope for reference</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111204545,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "ethan.o.raymond@vanderbilt.edu",
            "sender_full_name": "Ethan Raymond (S1'17)",
            "sender_id": 101112,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495555879,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Inviting <span class=\"user-mention\" data-user-email=\"veit@veitheller.de\" data-user-id=\"101103\">@Veit Heller (S1'17)</span> as well.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111215115,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495572623,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>Thanks for the invite. I've used LLVM in the past, both compiling to IR without having to use the programmatic bindings and using the C++ and Python bindings. It's been a while since I last used it, though, and I'm not sure I'm still up to date with 4.0. If you have any questions, let me know, maybe I can answer them.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111215263,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495572890,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>Also, the Rust bindings <span class=\"user-mention\" data-user-email=\"joshua.hudelson@gmail.com\" data-user-id=\"101108\">@Joshua Hudelson (S1'17)</span> and I used were stellar. Really cool stuff.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111215277,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495572918,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"veit@veitheller.de\" data-user-id=\"101103\">@Veit Heller (S1'17)</span> Can you do an intro talk or something?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111215338,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495572987,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>sure can. maybe ill have time to cook something up until tomorrow. what would y'all like to hear about? because the bindings vary considerably and make working with llvm quite different depending on which you use, from my experience</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111215775,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495573696,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>have y'all settled on a language</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111215779,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "congragating here...",
            "submessages": [],
            "timestamp": 1495573717,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<blockquote>\n<p>Def do the Kaleidoscope tutorial if you haven't:</p>\n<p><a href=\"http://llvm.org/docs/tutorial/LangImpl01.html\" target=\"_blank\" title=\"http://llvm.org/docs/tutorial/LangImpl01.html\">http://llvm.org/docs/tutorial/LangImpl01.html</a></p>\n</blockquote>\n<p><span class=\"user-mention\" data-user-email=\"trbabb@gmail.com\" data-user-id=\"101091\">@Tim Babb (S1'17)</span> , I found this python version a bit more accessible. <a href=\"https://github.com/eliben/pykaleidoscope\" target=\"_blank\" title=\"https://github.com/eliben/pykaleidoscope\">https://github.com/eliben/pykaleidoscope</a></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218278,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "trbabb@gmail.com",
                        "full_name": "Tim Babb (S1'17)",
                        "id": 101091
                    },
                    "user_id": 101091
                }
            ],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578033,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>the python version is definitely easier on the eyes, but the llvmlite wrapper is a bit weird in that it is not really a wrapper, but an ir builder that looks similar. its also not complete, because it is maintained by numba (had to look that one up) and they dont need a complete implementation.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218514,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578458,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>just something to keep in mind</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218516,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578465,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>yeah, I also worked on the Python version (<a href=\"https://github.com/guilload/kaleidoscope\" target=\"_blank\" title=\"https://github.com/guilload/kaleidoscope\">https://github.com/guilload/kaleidoscope</a>) in the past and the wrapper has some quirks.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218579,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578592,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>i see that you used the old wrapper, llvmpy, though, right?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218691,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578738,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>it has been kind of deprecated in favor of llvmlite by most (?)</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218694,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578755,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/05737f7353d71ece81912e75bd95cf17?d=identicon&version=1",
            "client": "website",
            "content": "<p>yeah, it was 2+ years ago</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218696,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "adrien.guillo@gmail.com",
            "sender_full_name": "Adrien Guillo (S1'17)",
            "sender_id": 6676,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578772,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>in that case im happy to report that its gotten better since then :)</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111218704,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Getting started",
            "submessages": [],
            "timestamp": 1495578812,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Anyone tried this book? <a href=\"https://www.amazon.com/dp/B00N2RWMSQ\" target=\"_blank\" title=\"https://www.amazon.com/dp/B00N2RWMSQ\">https://www.amazon.com/dp/B00N2RWMSQ</a></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111219041,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Book review",
            "submessages": [],
            "timestamp": 1495579537,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>How are y'all feeling for an intro meeting today? Let's see which time works for most of you and what you want to see covered. I didn't prepare it much yet, but I think I'm pretty okay with giving an ad-hoc demo of the most important things to keep in mind.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111253729,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495653801,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p>Interested. Just let me know when.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111253787,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495653899,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/faad5e420e35c613eac0b16a547c66e229d055de?x=x&version=2",
            "client": "website",
            "content": "<p>I am at the don't know what I'd like to know stage. Am free untill 5pm today as am moving.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111253981,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "sam.x.patterson@gmail.com",
            "sender_full_name": "Sam Patterson (S1'17)",
            "sender_id": 101080,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654210,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>There is a papers we love meetup from 7 to 10, so let's have this before 5. Will 4:30 work for everyone?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254049,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654331,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Or maybe even 4pm?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254053,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654348,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>Any time works for me right now :)</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254074,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654396,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>There is a visidata session by Saul at 5</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254132,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654508,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>then 4 sounds like a good idea. lets meet in hopper?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254193,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654602,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/faad5e420e35c613eac0b16a547c66e229d055de?x=x&version=2",
            "client": "website",
            "content": "<p>sounds good</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254207,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "sam.x.patterson@gmail.com",
            "sender_full_name": "Sam Patterson (S1'17)",
            "sender_id": 101080,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654635,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Yes. I'm good with 4pm at hopper. I heard yesterday that you need to do some RSVP thing and reserve rooms. I'm not sure.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254212,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654648,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>Pinging <span class=\"user-mention\" data-user-email=\"trbabb@gmail.com\" data-user-id=\"101091\">@Tim Babb (S1'17)</span> &amp; <span class=\"user-mention\" data-user-email=\"adrien.guillo@gmail.com\" data-user-id=\"6676\">@Adrien Guillo (S1'17)</span></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254263,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "trbabb@gmail.com",
                        "full_name": "Tim Babb (S1'17)",
                        "id": 101091
                    },
                    "user_id": 101091
                }
            ],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654692,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4e0e55d0dc86c5e9d5390f80a23a6f8f?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'd like to go but I may be a little late</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254333,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "ethan.o.raymond@vanderbilt.edu",
            "sender_full_name": "Ethan Raymond (S1'17)",
            "sender_id": 101112,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654816,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>No problem at all!</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111254340,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495654834,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>im game for any llvm-related pairings during our batch, by the way, if you ever want to pair with me :)</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111257400,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495659984,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/661412d42ecbf0c0bd354116859a5af3562f8e5f?x=x&version=4",
            "client": "website",
            "content": "<p>or need help with a more in-depth or more specific topic</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111257481,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "veit@veitheller.de",
            "sender_full_name": "Veit Heller (he) (S1'17)",
            "sender_id": 101103,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "intro meeting",
            "submessages": [],
            "timestamp": 1495660124,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p>Just starting out the compiler portion of my language. Come on by if you wanna pair.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111567667,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Doing some LLVM work now",
            "submessages": [],
            "timestamp": 1496342425,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/d5518741e12b2070f0063a21cd60c939?d=identicon&version=4",
            "client": "website",
            "content": "<p>Can anyone help me with the expected representationof floats in LLVM IR?</p>\n<div class=\"codehilite\"><pre><span></span>/usr/local/Cellar/llvm/4.0.0_1/bin/llc: test-2.ll:2:12: error: floating point constant invalid for type\nfadd float 1.32, 1.64\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111615512,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "carl.douglas@gmail.com",
            "sender_full_name": "Carl Douglas (S1'17)",
            "sender_id": 101092,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "float constants?",
            "submessages": [],
            "timestamp": 1496439713,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>I think it wants a value with unambiguous floating point representation.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111615572,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "float constants?",
            "submessages": [],
            "timestamp": 1496439820,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>My notes on LLVM types. These are the only ones I needed so far to compile a tiny language into LLVM IR. Should be useful for anyone who is just getting started. <a href=\"https://github.com/jaseemabid/Olifant/blob/master/LLVM.org\" target=\"_blank\" title=\"https://github.com/jaseemabid/Olifant/blob/master/LLVM.org\">https://github.com/jaseemabid/Olifant/blob/master/LLVM.org</a></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111721756,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Minimal types",
            "submessages": [],
            "timestamp": 1496690933,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p>Anyone have insight on the correct way to allocate memory from the heap?</p>\n<p>I see a <code>malloc</code> \"instruction\" in the docs for early versions of LLVM, but not (that I can see) in current ones.</p>\n<p>What's the right platform-generic way to allocate heap memory?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111721990,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "malloc() in LLVM",
            "submessages": [],
            "timestamp": 1496691307,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a6a0ff0a4a9a86ae7bc4524453d439bd?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm not sure if this is exactly what you're after, but there's an <code>alloca</code> instruction, <a href=\"http://llvm.org/docs/LangRef.html#alloca-instruction\" target=\"_blank\" title=\"http://llvm.org/docs/LangRef.html#alloca-instruction\">here's</a> the documentation, and there's an example of how to get this from the API in the <a href=\"http://llvm.org/docs/tutorial/LangImpl07.html\" target=\"_blank\" title=\"http://llvm.org/docs/tutorial/LangImpl07.html\">Kaleidoscope tutorial</a></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111727876,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "annie.cherk@gmail.com",
            "sender_full_name": "Annie Cherkaev (she/they) (m4'18)",
            "sender_id": 9502,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "malloc() in LLVM",
            "submessages": [],
            "timestamp": 1496702177,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a6a0ff0a4a9a86ae7bc4524453d439bd?d=identicon&version=1",
            "client": "website",
            "content": "<p>oh wait that allocates on the <em>stack</em> and you said you wanted to allocate on the <em>heap</em></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111727880,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "annie.cherk@gmail.com",
            "sender_full_name": "Annie Cherkaev (she/they) (m4'18)",
            "sender_id": 9502,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "malloc() in LLVM",
            "submessages": [],
            "timestamp": 1496702213,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a6a0ff0a4a9a86ae7bc4524453d439bd?d=identicon&version=1",
            "client": "website",
            "content": "<p>It looks like, <a href=\"https://groups.google.com/forum/#!topic/llvm-dev/QElg-R1CqNg\" target=\"_blank\" title=\"https://groups.google.com/forum/#!topic/llvm-dev/QElg-R1CqNg\">as per this discussion</a> the thing to do is maybe call the libc function malloc...</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111727943,
            "is_me_message": false,
            "last_edit_timestamp": 1496702381,
            "reactions": [
                {
                    "emoji_code": "2b50",
                    "emoji_name": "star",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "trbabb@gmail.com",
                        "full_name": "Tim Babb (S1'17)",
                        "id": 101091
                    },
                    "user_id": 101091
                }
            ],
            "recipient_id": 36902,
            "sender_email": "annie.cherk@gmail.com",
            "sender_full_name": "Annie Cherkaev (she/they) (m4'18)",
            "sender_id": 9502,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "malloc() in LLVM",
            "submessages": [],
            "timestamp": 1496702364,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p>Anyone know how, in LLVM, to add global variables which are initialized at runtime? Where does that initialization code go?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111764437,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Initializing globals",
            "submessages": [],
            "timestamp": 1496778134,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"trbabb@gmail.com\" data-user-id=\"101091\">@Tim Babb (S1'17)</span>  Did you find the answer?</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111798463,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Initializing globals",
            "submessages": [],
            "timestamp": 1496849704,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p>Not for this question, no.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111798477,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Initializing globals",
            "submessages": [],
            "timestamp": 1496849739,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ec744a06627e6ec9061a398bc83ec7d196ec4d8e?x=x&version=2",
            "client": "website",
            "content": "<p>Though I think the answer to \"when do you have to <code>alloca</code>is \"when you have variables that are mutable\". Which probably won't apply to me for a little while...</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111798527,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "trbabb@gmail.com",
            "sender_full_name": "Tim Babb (S1'17)",
            "sender_id": 101091,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Initializing globals",
            "submessages": [],
            "timestamp": 1496849774,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5693e93e0e540757b3d92c6350f39af0?d=identicon&version=1",
            "client": "website",
            "content": "<p>I missed the intro meeting on May 24th because at that time I was vaguely aware of what LLVM is. But in my interest in using Web Assembly and perhaps attempting a tiny toy language I'm interested in LLVM -- more so language design.</p>\n<p>What's a good starter pack to get myself up to date on Lexical Analysis, Abstract Syntax Tree? <br>\nI'm aware of Flex &amp; Bison and glanced at <a href=\"http://llvm.org/docs/tutorial/\" target=\"_blank\" title=\"http://llvm.org/docs/tutorial/\">http://llvm.org/docs/tutorial/</a> but I don't think I quite understand or appreciate the concepts behind AST and such. and can I just write my own AST and void external tools? Why would I want to use external tools even (Flex, Bison)?</p>\n<p>How do i go from AST -&gt; to a simple language?</p>\n<p>I'd appreciate a tutorial on this topic, or to spend one afternoon watching someone currently working with LLVM and perusing their code and asking questions.</p>\n<p>Thnx!</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111873179,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "sabelo@sabelo.io",
            "sender_full_name": "Sabelo Mhlambi (F1'17)",
            "sender_id": 101085,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Starter Pack",
            "submessages": [],
            "timestamp": 1496990040,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>We can pair on this anytime. I'm doing this all day.</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 111887446,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "sabelo@sabelo.io",
                        "full_name": "Sabelo Mhlambi (F1'17)",
                        "id": 101085
                    },
                    "user_id": 101085
                }
            ],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Starter Pack",
            "submessages": [],
            "timestamp": 1497021486,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/40e1eb4186c76edfecca264f74e088ed0e62af25?x=x&version=2",
            "client": "website",
            "content": "<p>So LLVM booleans are <code>Int 8</code>mapped to 1 and 0? :) Finally my language is starting to look like C :P</p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 112132977,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f642",
                    "emoji_name": "simple_smile",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "annie.cherk@gmail.com",
                        "full_name": "Annie Cherkaev (she/they) (m4'18)",
                        "id": 9502
                    },
                    "user_id": 9502
                }
            ],
            "recipient_id": 36902,
            "sender_email": "jaseemabid@gmail.com",
            "sender_full_name": "Jaseem Abid (he) (S1'17)",
            "sender_id": 101128,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Booleans are just 1 and 0!",
            "submessages": [],
            "timestamp": 1497544347,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5693e93e0e540757b3d92c6350f39af0?d=identicon&version=1",
            "client": "website",
            "content": "<blockquote>\n<p>We can pair on this anytime. I'm doing this all day.</p>\n</blockquote>\n<p>literally just seeing this..  Zulip needs to improve!  cc <span class=\"user-mention\" data-user-email=\"jaseemabid@gmail.com\" data-user-id=\"101128\">@Jaseem Abid (S1'17)</span></p>",
            "content_type": "text/html",
            "display_recipient": "llvm",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113403524,
            "is_me_message": false,
            "last_edit_timestamp": 1500185398,
            "reactions": [],
            "recipient_id": 36902,
            "sender_email": "sabelo@sabelo.io",
            "sender_full_name": "Sabelo Mhlambi (F1'17)",
            "sender_id": 101085,
            "sender_realm_str": "recurse",
            "stream_id": 26219,
            "subject": "Starter Pack",
            "submessages": [],
            "timestamp": 1500185263,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
