{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3670aa0d1ce05f885788e64d3ad6404f7cf73962?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"myf@worldtalks.org\">@Myf Ma (F'12)</span> Any specific plans for this stream? I did a project in Lua in my batch, but couldn't get anyone interested in collaborating. It's a cool language, though I think it suffers from being the opposite of batteries-included (and lacking a good package system to help you add batteries)... I grew weary writing so much basic stuff. But Lua could be awesome!</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 23993340,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "scott@scott.mn",
            "sender_full_name": "Scott Feeney (W'13)",
            "sender_id": 825,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "yay lua",
            "submessages": [],
            "timestamp": 1404068727,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c26df9d99d13610d1a1e11f86efce88d?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"scott@scott.mn\">@Scott Feeney (W'13)</span> I didn't see lua show up on the stream list so I created it, giving a place for people to nerd out about it. For me, I have been learning a tiny bit of lua very slowly. I started from using awesome window manager and luakit as my browser. I really want to get into it a bit more, especially with some hype about machine learning in lua lately. What project have you (or any lurkers) done? care to share?</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 24057660,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "myf@worldtalks.org",
            "sender_full_name": "Myf Ma (F'12)",
            "sender_id": 885,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "yay lua",
            "submessages": [],
            "timestamp": 1404181661,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3670aa0d1ce05f885788e64d3ad6404f7cf73962?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"myf@worldtalks.org\">@Myf Ma (F'12)</span> I made an audio framework called <a href=\"https://github.com/graue/luasynth\" target=\"_blank\" title=\"https://github.com/graue/luasynth\">Luasynth</a> and a <a href=\"https://github.com/graue/moon-noise\" target=\"_blank\" title=\"https://github.com/graue/moon-noise\">noise generator</a></p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 24064805,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "scott@scott.mn",
            "sender_full_name": "Scott Feeney (W'13)",
            "sender_id": 825,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "yay lua",
            "submessages": [],
            "timestamp": 1404194762,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c26df9d99d13610d1a1e11f86efce88d?d=identicon&version=1",
            "client": "Android",
            "content": "<p>I'm a bit confused, where did my packages go?</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 24472430,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "myf@worldtalks.org",
            "sender_full_name": "Myf Ma (F'12)",
            "sender_id": 885,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "how to do luarocks on luajit?",
            "submessages": [],
            "timestamp": 1404865094,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b38a0745ab079cc09b97aa68d03607b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Is there a standard practice for writing docstrings in Lua?  torch packages seem to use a separate markdown file for docs, I'm curious if this is standard or is there a way to write doc-strings for functions, next to them? </p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 46631205,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "punchagan@muse-amuse.in",
            "sender_full_name": "Puneeth Chaganti (he) (S1'14)",
            "sender_id": 5868,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "How to write docstrings in Lua?",
            "submessages": [],
            "timestamp": 1441530046,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Not that I've heard of; if you find one, please tell me, <span class=\"user-mention\" data-user-email=\"punchagan@muse-amuse.in\">@Puneeth Chaganti (S'14)</span> :)</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 46688829,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "How to write docstrings in Lua?",
            "submessages": [],
            "timestamp": 1441650184,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b38a0745ab079cc09b97aa68d03607b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Sure. </p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47112691,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "punchagan@muse-amuse.in",
            "sender_full_name": "Puneeth Chaganti (he) (S1'14)",
            "sender_id": 5868,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "How to write docstrings in Lua?",
            "submessages": [],
            "timestamp": 1442382366,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b38a0745ab079cc09b97aa68d03607b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Does anyone have recommendations for an inline debugger for Lua?  I use IPython's debugger for Python and am happy with it.  <a href=\"http://lua-users.org/wiki/DebuggingLuaCode\" target=\"_blank\" title=\"http://lua-users.org/wiki/DebuggingLuaCode\">This page</a> lists a bunch of debuggers, but wanted to get first hand recommendations, if any, instead of trying out a bunch of these.  </p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47112742,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "punchagan@muse-amuse.in",
            "sender_full_name": "Puneeth Chaganti (he) (S1'14)",
            "sender_id": 5868,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Debugger for Lua",
            "submessages": [],
            "timestamp": 1442382511,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/919b4af386b43c5ca84d8e664790a7d906336c0d?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"genericpb@gmail.com\" data-user-id=\"100446\">@Mel Vaughan (W2'17)</span> <br>\nQuick snippet [not mine] of what I think is the most elegant and Lua-ish way to implement str:split in Lua, as the standard library is barebones and does not have it. metatables FTW</p>\n<div class=\"codehilite\"><pre><span></span>--[[ written for Lua 5.1\nsplit a string by a pattern, take care to create the &quot;inverse&quot; pattern\nyourself. default pattern splits by white space.\n]]\nstring.split = function(str, pattern)\n   pattern = pattern or &quot;[^%s]+&quot;\n   if pattern:len() == 0 then\n      pattern = &quot;[^%s]+&quot;\n   end\n   local parts = {__index = table.insert}\n   setmetatable(parts, parts)\n   str:gsub(pattern, parts)\n   setmetatable(parts, nil)\n   parts.__index = nil\n   return parts\nend\n-- example 1\nstr = &quot;no separators in this string&quot;\nparts = str:split( &quot;[^,]+&quot; )\nprint( # parts )\ntable.foreach(parts, print)\n--[[ output:\n1\n1   no separators in this string\n]]\n\n-- example 2\nstr = &quot;   split, comma, separated  , , string   &quot;\nparts = str:split( &quot;[^,%s]+&quot; )\nprint( # parts )\ntable.foreach(parts, print)\n--[[ output:\n4\n1   split\n2   comma\n3   separated\n4   string\n]]\n</pre></div>\n\n\n<p>From </p>\n<p><a href=\"http://lua-users.org/wiki/SplitJoin\" target=\"_blank\" title=\"http://lua-users.org/wiki/SplitJoin\">http://lua-users.org/wiki/SplitJoin</a></p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 108821457,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "botwhytho@gmail.com",
            "sender_full_name": "Alberto Torres (SP1'17)",
            "sender_id": 100545,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "str:split with metatables",
            "submessages": [],
            "timestamp": 1490560459,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e9bbea7116dbac067c366b35a5e494286fbe2b21?x=x&version=1",
            "client": "website",
            "content": "<p>haha woah nice, thats interesting</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 108836854,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "genericpb@gmail.com",
            "sender_full_name": "Mel Vaughan (W2'17)",
            "sender_id": 100446,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "str:split with metatables",
            "submessages": [],
            "timestamp": 1490597690,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/919b4af386b43c5ca84d8e664790a7d906336c0d?x=x&version=1",
            "client": "website",
            "content": "<p>yeah, didn't know that you could supply a table as the second argument to string.gsub. seems like it looks at the table and replaces each match of the find with the value of the table at a specific key. Another use case without using that meta-table trick is a spell checker or something like that, you can have a function as a value to a key so string.gsub just turned much more powerful in my mind.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 108864824,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "botwhytho@gmail.com",
            "sender_full_name": "Alberto Torres (SP1'17)",
            "sender_id": 100545,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "str:split with metatables",
            "submessages": [],
            "timestamp": 1490653708,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8b0373befcb9fe1ca27ee0ac86fccc63eb8ccabe?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"w.aptekar@gmail.com\" data-user-id=\"101330\">@Wesley Aptekar-Cassels (S2'17)</span>  sorry for force subscribe you here! </p>\n<p>Just ran into <code>:</code> in Lua. Looks like it's comparable to a calling static method?</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"n\">obj</span><span class=\"p\">:</span><span class=\"n\">method</span><span class=\"p\">(</span><span class=\"n\">obj</span><span class=\"p\">,</span> <span class=\"n\">arg</span><span class=\"o\">*</span><span class=\"p\">)</span>\n<span class=\"c1\">-- vs</span>\n<span class=\"n\">obj</span><span class=\"p\">.</span><span class=\"n\">method</span><span class=\"p\">(</span><span class=\"n\">arg</span><span class=\"o\">*</span><span class=\"p\">)</span>\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113346350,
            "is_me_message": false,
            "last_edit_timestamp": 1500052802,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "jo.chasinga@gmail.com",
            "sender_full_name": "Joe Chasinga (S2'17)",
            "sender_id": 101482,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Lua ':' and '.'",
            "submessages": [],
            "timestamp": 1500052729,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p>IIRC what <code>:</code> does is automatically adds the self arg to the function. so <code>obj:test(42)</code> is the same as <code>obj.test(obj, 42)</code>.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113346430,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f31d",
                    "emoji_name": "full_moon_with_face",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "k.allen@live.com",
                        "full_name": "Katie Allen (SP2'17)",
                        "id": 100774
                    },
                    "user_id": 100774
                }
            ],
            "recipient_id": 34657,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Lua ':' and '.'",
            "submessages": [],
            "timestamp": 1500052914,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p>object orientation is really weird in lua though - I've usually avoided it.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113346476,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Lua ':' and '.'",
            "submessages": [],
            "timestamp": 1500052942,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p>I find that for games I can usually get away with just having tables of objects and updating them instead of using metatables. But I've done both.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113346494,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Lua ':' and '.'",
            "submessages": [],
            "timestamp": 1500052999,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8b0373befcb9fe1ca27ee0ac86fccc63eb8ccabe?x=x&version=2",
            "client": "website",
            "content": "<p>I guess in Lua with just table (hashmap) it's OOP is similar to JS prototype in a way</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113346608,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "jo.chasinga@gmail.com",
            "sender_full_name": "Joe Chasinga (S2'17)",
            "sender_id": 101482,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Lua ':' and '.'",
            "submessages": [],
            "timestamp": 1500053225,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5de070e753aa687ed150feb24a19fd20?d=identicon&version=1",
            "client": "website",
            "content": "<p>Lua supports OOP, but is sort of keeping all of the plumbing exposed, and if you want to build in a different kind of object system you can.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113348960,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f4af",
                    "emoji_name": "100",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jo.chasinga@gmail.com",
                        "full_name": "Joe Chasinga (S2'17)",
                        "id": 101482
                    },
                    "user_id": 101482
                }
            ],
            "recipient_id": 34657,
            "sender_email": "vokes.s@gmail.com",
            "sender_full_name": "Scott Vokes",
            "sender_id": 7280,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Lua ':' and '.'",
            "submessages": [],
            "timestamp": 1500057163,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5de070e753aa687ed150feb24a19fd20?d=identicon&version=1",
            "client": "website",
            "content": "<p>There isn't anything magical going on, it's just a couple well-defined hooks.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113348975,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "vokes.s@gmail.com",
            "sender_full_name": "Scott Vokes",
            "sender_id": 7280,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Lua ':' and '.'",
            "submessages": [],
            "timestamp": 1500057197,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8b0373befcb9fe1ca27ee0ac86fccc63eb8ccabe?x=x&version=2",
            "client": "website",
            "content": "<p>In torch REPL, I create an uninitialized matrix like:</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"n\">a</span>  <span class=\"o\">=</span> <span class=\"n\">torch</span><span class=\"p\">.</span><span class=\"n\">Tensor</span><span class=\"p\">(</span><span class=\"mi\">5</span><span class=\"p\">,</span> <span class=\"mi\">3</span><span class=\"p\">)</span>\n<span class=\"n\">b</span> <span class=\"o\">=</span> <span class=\"n\">torch</span><span class=\"p\">.</span><span class=\"n\">Tensor</span><span class=\"p\">(</span><span class=\"mi\">5</span><span class=\"p\">,</span> <span class=\"mi\">3</span><span class=\"p\">)</span>\n<span class=\"nb\">print</span><span class=\"p\">(</span><span class=\"n\">a</span><span class=\"p\">)</span>\n<span class=\"nb\">print</span><span class=\"p\">(</span><span class=\"n\">b</span><span class=\"p\">)</span>\n</pre></div>\n\n\n<p>When printed <code>a</code> turns out like this:</p>\n<div class=\"codehilite\"><pre><span></span>6.9294e-310   6.9294e-310   4.9135e+252\n1.0116e-153   3.3640e+175  1.2890e+248\n1.0626e+248  1.1132e+171  1.9430e-57\n7.6283e+228  6.0112e+175  6.9981e-308\n7.3651e+228  7.0981e+194  9.4372e-96\n[torch.DoubleTensor of size 5x3]\n</pre></div>\n\n\n<p>while <code>b</code> is a 5x3 matrix of zeros. Is this the same thing that's happening to an uninitialized variables in C/C++?</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113960146,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "jo.chasinga@gmail.com",
            "sender_full_name": "Joe Chasinga (S2'17)",
            "sender_id": 101482,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "uninitialized torch matrix with undefined values",
            "submessages": [],
            "timestamp": 1501345275,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1354dfa4e6106dc6ac46ad953083dec9efdfb517?x=x&version=2",
            "client": "website",
            "content": "<p>whaaaat... that is weird, I just checked it in my REPL, but I'm getting the reverse, except the central element of a is 3: </p>\n<p><code>th&gt; a = torch.Tensor(5, 3)</code><br>\n<code>th&gt; b = torch.Tensor(5, 3)</code></p>\n<p><code>th&gt; print(a)\n 0.0000  0.0000  0.0000\n 0.0000  0.0000  0.0000\n 0.0000  3.0000  0.0000\n 0.0000  0.0000  0.0000\n 0.0000  0.0000  0.0000\n[torch.DoubleTensor of size 5x3]</code></p>\n<p><code>th&gt; print(b)\n 6.9508e-310  1.1181e-316  9.9407e-317\n 1.0453e-316  1.1116e-316  1.1116e-316\n 5.2987e+180  8.1969e+247  1.1445e+243\n 2.4209e-322  1.1106e-316  9.8961e-317\n 1.1116e-316   1.0000e+00  6.3240e-322\n[torch.DoubleTensor of size 5x3]</code></p>\n<p>I have no clue, but it's intriguing!</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 114208772,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f47d",
                    "emoji_name": "alien",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jo.chasinga@gmail.com",
                        "full_name": "Joe Chasinga (S2'17)",
                        "id": 101482
                    },
                    "user_id": 101482
                }
            ],
            "recipient_id": 34657,
            "sender_email": "abehmiel@gmail.com",
            "sender_full_name": "Abraham Hmiel (he/they) (S1'17)",
            "sender_id": 101122,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "uninitialized torch matrix with undefined values",
            "submessages": [],
            "timestamp": 1501866127,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8b0373befcb9fe1ca27ee0ac86fccc63eb8ccabe?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"abehmiel@gmail.com\" data-user-id=\"101122\">@Abraham Hmiel (S1'17)</span> the doc just refers to these as garbage values, thus, I am relating this to the underlying C uninitialized variables. Often in C/C++ some time if you print uninitialized values to <code>stdout</code> some really big <code>long</code> appears.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 114409166,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "jo.chasinga@gmail.com",
            "sender_full_name": "Joe Chasinga (S2'17)",
            "sender_id": 101482,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "uninitialized torch matrix with undefined values",
            "submessages": [],
            "timestamp": 1502297785,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a6188a392c3f67335e6fa8f490844901?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hey all, I'm just getting started with Lua and I figured this would be a good place to ask for some advice.</p>\n<p>There have been two independent situations in the same number of weeks in which it would have been extremely helpful for me to know more about the Lua programming langauge than I do. The first is when I took a look at an Nmap NSE script, which was Lua, and the second was when I found myself needing to write a Wireshark protocol dissector, but hoping not to dive too far into Wireshark's C API because all the documentation keeps telling me that using Lua is faster for prototyping.</p>\n<p>A lot of the Lua stuff I'm finding seems to be revolving around game development. That's nice and all but not really what I'm interested in. I have, of course, found the Lua reference manual and its getting started sections, and they're\u2026fine. The book they recommend is also\u2026fine. It has a lot of maths examples, which I don't care for. I'll read them if there's nothing better but I just thought I'd ask for advice in case anyone knows of a diamond in the rough for these sorts of tasks.</p>\n<p>Thanks in advance. :)</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 134690970,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "meitarm@gmail.com",
            "sender_full_name": "May may (F2'16)",
            "sender_id": 100208,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Favorite Lua learning resource?",
            "submessages": [],
            "timestamp": 1537983499,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f47c30352bcf26bb97f17f9ee3db944cf167e09b?x=x&version=2",
            "client": "website",
            "content": "<p>I've not seen a great deal of Lua learning resources. Programming in Lua is The Book as far as I've seen. There is some good code in Snabb <a href=\"https://github.com/snabbco/snabb\" target=\"_blank\" title=\"https://github.com/snabbco/snabb\">https://github.com/snabbco/snabb</a> with some examples of FFI (it sounds like that's what you might be after). The language is surprisingly small which may be why there aren't many resources.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 134692813,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "williamsykesfisher@gmail.com",
            "sender_full_name": "William Sykes Fisher (he) (F2'18)",
            "sender_id": 129933,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Favorite Lua learning resource?",
            "submessages": [],
            "timestamp": 1537985315,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a6188a392c3f67335e6fa8f490844901?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"129933\">@William Sykes Fisher (F2'18)</span> Thanks for the pointer to Snabb. You're right, I spent most of yesterday simply reading the (dry but useful) Lua Reference Manual and was able to put together a working prototype for my project in about 6 hours. I didn't expect it to be as straightforward as it turned out to be. I'm no Lua guru but the language was small enough that it fit in my head while reading the Reference Manual, making it surprisingly easy to learn enough to get going. :)</p>\n<p>As an example, my first ever Lua code is <a href=\"https://github.com/meitar/ntalk-dissector/\" target=\"_blank\" title=\"https://github.com/meitar/ntalk-dissector/\">this toy Wireshark dissector</a>. Any tips for improving my Lua style would be welcome.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 134749752,
            "is_me_message": false,
            "last_edit_timestamp": 1538059795,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "meitarm@gmail.com",
            "sender_full_name": "May may (F2'16)",
            "sender_id": 100208,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "Favorite Lua learning resource?",
            "submessages": [],
            "timestamp": 1538059756,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ac25c0f0dbfaa3e0d68634873943e63bdd41139c?x=x&version=1",
            "client": "website",
            "content": "<p>Anyone have any experience with <a href=\"https://fennel-lang.org/\">Fennel</a>?  I've recently been looking into it.  It's a language with lispy syntax and Lua's semantics, that compiles to Lua.  There's a <a href=\"https://fennel-lang.org/rationale\">rationale</a> doc that highlights why someone might want to use it rather than Lua.</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 208413732,
            "is_me_message": false,
            "last_edit_timestamp": 1598670390,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "paul@paulwmorris.com",
            "sender_full_name": "Paul Morris (he) (SP1'17)",
            "sender_id": 100524,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "fennel-lang",
            "submessages": [],
            "timestamp": 1598670158,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2dd869aa22bdb3491ea3727890869a8f?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm only a casual Lua user and haven't tried Fennel, but would be curious to hear your thoughts on the comparative experience. Bifurcating the table notation makes a lot of sense to me, especially since I think the implementation from Lua 5.0 is a hybrid of hashmap and array. Tables were a major source of confusion when I first started, what with array-like items being explicitly <code>remove()</code>-able, while hashmap-like items needing to be assigned <code>nil</code> (presumably for the GC to then come around).</p>",
            "content_type": "text/html",
            "display_recipient": "lua",
            "flags": [
                "read",
                "historical"
            ],
            "id": 208454785,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 34657,
            "sender_email": "taro.kuriyama@gmail.com",
            "sender_full_name": "Taro Kuriyama (he) (F1'20)",
            "sender_id": 327353,
            "sender_realm_str": "recurse",
            "stream_id": 25757,
            "subject": "fennel-lang",
            "submessages": [],
            "timestamp": 1598736478,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
