{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/9fd9de59f964f6e3af477006ddd0116211347010?x=x&version=2",
            "client": "Internal",
            "content": "<p>Stream created by <span class=\"user-mention silent\" data-user-id=\"234089\">Josh Kean (he) (F1'19)</span>.</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175468327,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "notification-bot@zulip.com",
            "sender_full_name": "Notification Bot",
            "sender_id": 100006,
            "sender_realm_str": "zulipcore",
            "stream_id": 208668,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1568230818,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/189ab48671e3d9cd22b1a02487892411da469a9a?x=x&version=2",
            "client": "website",
            "content": "<p>heard you might want a router for this... i have a TP-link with openwrt flashed onto it that i'd be happy to donate... i screwed something up when i was ssh-ing into it, but probably easy to fix if you've worked with routers before</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175468971,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "doron.rasis@nyu.edu",
            "sender_full_name": "Doron Rasis (he) (F1'19)",
            "sender_id": 234876,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1568231170,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/753274cbd3bb05b5be08f0eb9f095074b75a8b3b?x=x&version=3",
            "client": "website",
            "content": "<p>Hey!, we may need one. Would you want to work on this at all with us?</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175469773,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "joshkn@protonmail.com",
            "sender_full_name": "Josh Kean (he) (F1'19)",
            "sender_id": 234089,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1568231659,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/189ab48671e3d9cd22b1a02487892411da469a9a?x=x&version=2",
            "client": "website",
            "content": "<p>sure!</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175469939,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "doron.rasis@nyu.edu",
            "sender_full_name": "Doron Rasis (he) (F1'19)",
            "sender_id": 234876,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1568231771,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/189ab48671e3d9cd22b1a02487892411da469a9a?x=x&version=2",
            "client": "website",
            "content": "<p>I'll find you to ask about it</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175469951,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "doron.rasis@nyu.edu",
            "sender_full_name": "Doron Rasis (he) (F1'19)",
            "sender_id": 234876,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1568231783,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea84d38d0a9e331c310fd57dd02f2aee7fc97862?x=x&version=2",
            "client": "website",
            "content": "<p>COFFEE DRONE</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175470572,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "jon@jon.network",
            "sender_full_name": "Jon York (he) (F1'19)",
            "sender_id": 233934,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "DRONE",
            "submessages": [],
            "timestamp": 1568232151,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea84d38d0a9e331c310fd57dd02f2aee7fc97862?x=x&version=2",
            "client": "website",
            "content": "<p>It it done yet??? I need a coffeebot that I can take to school</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176800677,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "jon@jon.network",
            "sender_full_name": "Jon York (he) (F1'19)",
            "sender_id": 233934,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "Update?",
            "submessages": [],
            "timestamp": 1569633993,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/973e5363d617a705d4ec13541831691e8d846390?x=x&version=4",
            "client": "ZulipMobile",
            "content": "<p>We successfully broke the coffee machine but then we got tired</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176832703,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "kathleen.macg@gmail.com",
            "sender_full_name": "Kathleen McGuire (she/they) (F2'19)",
            "sender_id": 228113,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "Update?",
            "submessages": [],
            "timestamp": 1569689191,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/973e5363d617a705d4ec13541831691e8d846390?x=x&version=4",
            "client": "ZulipMobile",
            "content": "<p>Soon tho</p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 176832705,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "kathleen.macg@gmail.com",
            "sender_full_name": "Kathleen McGuire (she/they) (F2'19)",
            "sender_id": 228113,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "Update?",
            "submessages": [],
            "timestamp": 1569689198,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"https://github.com/ijl20/cambridge_coffee_pot\" target=\"_blank\" title=\"https://github.com/ijl20/cambridge_coffee_pot\">https://github.com/ijl20/cambridge_coffee_pot</a></p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 179559166,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "further inspiration",
            "submessages": [],
            "timestamp": 1572545236,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ea84d38d0a9e331c310fd57dd02f2aee7fc97862?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"https://imgflip.com/i/3fqgpt\" target=\"_blank\" title=\"https://imgflip.com/i/3fqgpt\">https://imgflip.com/i/3fqgpt</a></p>",
            "content_type": "text/html",
            "display_recipient": "makecoffebot",
            "flags": [
                "read",
                "historical"
            ],
            "id": 180270062,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 366492,
            "sender_email": "jon@jon.network",
            "sender_full_name": "Jon York (he) (F1'19)",
            "sender_id": 233934,
            "sender_realm_str": "recurse",
            "stream_id": 208668,
            "subject": "well...",
            "submessages": [],
            "timestamp": 1573245925,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
