{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ddf79a11b9b2a19ed45394c4fd3167fb?d=identicon&version=1",
            "client": "website",
            "content": "<p>clc<br>\nclear all<br>\nt=-10:0.01:10;<br>\nx=16*(power(sin(t),3));<br>\ny=(13*cos(t))-(5*cos(2*t))-(2*cos(3*t))-(cos(4*t));<br>\nplot(x,y)</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2481925,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ruby.childs1@gmail.com",
            "sender_full_name": "Ruby Childs (she) (F'12)",
            "sender_id": 883,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "Valentines",
            "submessages": [],
            "timestamp": 1360876458,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/21aeae1f260365557523718bc19640f7?d=identicon&version=1",
            "client": "website",
            "content": "<p>I just joined this stream yesterday, so I have no idea what was going on before, but if anyone has any Matlab questions, I know an unreasonable amount of Matlab, so feel free to ask me stuff</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2507167,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "stefan@karpinski.org",
            "sender_full_name": "Stefan Karpinski",
            "sender_id": 892,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "help",
            "submessages": [],
            "timestamp": 1360949570,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ddf79a11b9b2a19ed45394c4fd3167fb?d=identicon&version=1",
            "client": "website",
            "content": "<p>I may ask you lots, taking a course on image processing and scientific computing which uses both</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2709592,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ruby.childs1@gmail.com",
            "sender_full_name": "Ruby Childs (she) (F'12)",
            "sender_id": 883,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "help",
            "submessages": [],
            "timestamp": 1361467720,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/21aeae1f260365557523718bc19640f7?d=identicon&version=1",
            "client": "website",
            "content": "<p>nice. well, shoot me questions whenever you like.</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2709690,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "stefan@karpinski.org",
            "sender_full_name": "Stefan Karpinski",
            "sender_id": 892,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "help",
            "submessages": [],
            "timestamp": 1361467897,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ddf79a11b9b2a19ed45394c4fd3167fb?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hi Stefan,<br>\nI had a few questions, hope you don't mind. I wrote a JPEG compression over the weekend. It still has a few things I need to do such as cropping the image. How ever I wondered what normal conventions are in respect to writing Matlab and if there are any does or don'ts. Anyway my code can be found here: <a href=\"https://github.com/rubychilds/JPEGCompression\" target=\"_blank\" title=\"https://github.com/rubychilds/JPEGCompression\">https://github.com/rubychilds/JPEGCompression</a></p>\n<p>Its part of the coursera image processing course so has the questions and steps written at the top</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2893601,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ruby.childs1@gmail.com",
            "sender_full_name": "Ruby Childs (she) (F'12)",
            "sender_id": 883,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "help",
            "submessages": [],
            "timestamp": 1361915702,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ddf79a11b9b2a19ed45394c4fd3167fb?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Stefan Karpinski</strong> hey not sure if you've seen this given you weren't here yesterday! No rush though :)</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2920943,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ruby.childs1@gmail.com",
            "sender_full_name": "Ruby Childs (she) (F'12)",
            "sender_id": 883,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "help",
            "submessages": [],
            "timestamp": 1361981345,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ddf79a11b9b2a19ed45394c4fd3167fb?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hi all,<br>\nI just wondered with regards to an image, we have mxnx3 dimensions, with the 3 being rgb. So lets say you have an image I, then when you apply a subtraction from it i.e. 1-128 is it right to assume this is impacting all layers of the colour space</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3443208,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ruby.childs1@gmail.com",
            "sender_full_name": "Ruby Childs (she) (F'12)",
            "sender_id": 883,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "colour and images",
            "submessages": [],
            "timestamp": 1363202103,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ddf79a11b9b2a19ed45394c4fd3167fb?d=identicon&version=1",
            "client": "website",
            "content": "<p>sorry just answered my own question, but creating a = zeros(3,3,3), then a-128 and seeing what it does</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3443242,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ruby.childs1@gmail.com",
            "sender_full_name": "Ruby Childs (she) (F'12)",
            "sender_id": 883,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "colour and images",
            "submessages": [],
            "timestamp": 1363202164,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ddf79a11b9b2a19ed45394c4fd3167fb?d=identicon&version=1",
            "client": "website",
            "content": "<p>Its so interesting to me, as when I did image processing in java you had  to break down every pixel into its own components, so is great Matlab is so easy wrt image manipulation etc</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3443298,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ruby.childs1@gmail.com",
            "sender_full_name": "Ruby Childs (she) (F'12)",
            "sender_id": 883,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "colour and images",
            "submessages": [],
            "timestamp": 1363202219,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/21aeae1f260365557523718bc19640f7?d=identicon&version=1",
            "client": "website",
            "content": "<p>Yes, vectorized programming is great for image manipulation. Definitely one of Matlab's strong point.</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3444157,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "stefan@karpinski.org",
            "sender_full_name": "Stefan Karpinski",
            "sender_id": 892,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "colour and images",
            "submessages": [],
            "timestamp": 1363203580,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/35351c8d4dee64d54b92fe38875cb762854d9299?x=x&version=2",
            "client": "website",
            "content": "<p>If anyone here does matlab, I just posted a noob question and would love some help <a href=\"http://stackoverflow.com/questions/25191743/matlab-array-which-stores-numbers-of-any-base\" target=\"_blank\" title=\"http://stackoverflow.com/questions/25191743/matlab-array-which-stores-numbers-of-any-base\">http://stackoverflow.com/questions/25191743/matlab-array-which-stores-numbers-of-any-base</a></p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25938998,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ertysdl@gmail.com",
            "sender_full_name": "Erty Seidohl (he) (S'13)",
            "sender_id": 2154,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "question",
            "submessages": [],
            "timestamp": 1407444511,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/06d4a7e1ffcb35ace2fcfc5c2208d6b83a0dc6ab?x=x&version=2",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I think you're missing an <code>end</code>, not sure if that's the only problem though</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25996052,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "rpsoko@gmail.com",
            "sender_full_name": "Rob Sokolowski (W'14)",
            "sender_id": 4995,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "question",
            "submessages": [],
            "timestamp": 1407537594,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/06d4a7e1ffcb35ace2fcfc5c2208d6b83a0dc6ab?x=x&version=2",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I was able to create the object but not <code>a.get(2)</code> correctly.</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25996093,
            "is_me_message": false,
            "last_edit_timestamp": 1407537640,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "rpsoko@gmail.com",
            "sender_full_name": "Rob Sokolowski (W'14)",
            "sender_id": 4995,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "question",
            "submessages": [],
            "timestamp": 1407537615,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/35351c8d4dee64d54b92fe38875cb762854d9299?x=x&version=2",
            "client": "website",
            "content": "<p>Yeah, I got a great answer from someone on S.O. but I haven't been able to get it to run since I can't figure out how to import the class :\\</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25996106,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ertysdl@gmail.com",
            "sender_full_name": "Erty Seidohl (he) (S'13)",
            "sender_id": 2154,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "question",
            "submessages": [],
            "timestamp": 1407537645,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/35351c8d4dee64d54b92fe38875cb762854d9299?x=x&version=2",
            "client": "website",
            "content": "<p>My friend who actually needed the code says she figured it out though so I assume it works :P</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25996112,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "ertysdl@gmail.com",
            "sender_full_name": "Erty Seidohl (he) (S'13)",
            "sender_id": 2154,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "question",
            "submessages": [],
            "timestamp": 1407537657,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/06d4a7e1ffcb35ace2fcfc5c2208d6b83a0dc6ab?x=x&version=2",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Ah ok</p>",
            "content_type": "text/html",
            "display_recipient": "matlab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25996122,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20378,
            "sender_email": "rpsoko@gmail.com",
            "sender_full_name": "Rob Sokolowski (W'14)",
            "sender_id": 4995,
            "sender_realm_str": "recurse",
            "stream_id": 19068,
            "subject": "question",
            "submessages": [],
            "timestamp": 1407537673,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
