{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/09f2ca686b8694d23ff27d70f519a209?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey ya'll, i added a bunch of people who expressed interest in the class. unsubscribe if you dont' want to do the class :)</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4103866,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "nehalita@gmail.com",
            "sender_full_name": "Neha Batra (she) (W'13)",
            "sender_id": 836,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364832945,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/09f2ca686b8694d23ff27d70f519a209?d=identicon&version=1",
            "client": "website",
            "content": "<p>are people up for lecture time 9:30am tmrw? We'd just set it up on the projector. </p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4103871,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "nehalita@gmail.com",
            "sender_full_name": "Neha Batra (she) (W'13)",
            "sender_id": 836,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364832962,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>ah i'm actually taking the day off on tues since my parents are visiting, but u guys can go on w/o me</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4103909,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364833013,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/675466cb255ba68bf2b4e714d9371d9a0dab1e39?x=x&version=1",
            "client": "website",
            "content": "<p>9:30 is fine. Are you sure we won't have a time collision with check-in, though? I'll be here as early as necessary.</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4103947,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "dpb@brannerchinese.com",
            "sender_full_name": "David P Branner (SP2'17)",
            "sender_id": 850,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364833101,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/09f2ca686b8694d23ff27d70f519a209?d=identicon&version=1",
            "client": "website",
            "content": "<p>hm, since the only people i know that are in the class are the 3 of us, why don't we do wednesday morning. i looked at some of hte videos. it looks like the first 40 minute are an intro to mongodb, databases, and json. the next set of lectures are a complete intro to python so i'm guessing dpb and i can skip these. the hour will probably involve the intro and installing mongodb which will be most of the week 1</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104274,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "nehalita@gmail.com",
            "sender_full_name": "Neha Batra (she) (W'13)",
            "sender_id": 836,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364833846,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/09f2ca686b8694d23ff27d70f519a209?d=identicon&version=1",
            "client": "website",
            "content": "<p>jin, i didn't remember if you have coded in python before</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104279,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "nehalita@gmail.com",
            "sender_full_name": "Neha Batra (she) (W'13)",
            "sender_id": 836,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364833873,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/675466cb255ba68bf2b4e714d9371d9a0dab1e39?x=x&version=1",
            "client": "website",
            "content": "<p>Okay with me. The whole course is supposed to run into late May. I'd rather do as much as I can sooner. </p>\n<p>Are we leaving time for discussion?</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104371,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "dpb@brannerchinese.com",
            "sender_full_name": "David P Branner (SP2'17)",
            "sender_id": 850,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364834088,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/09f2ca686b8694d23ff27d70f519a209?d=identicon&version=1",
            "client": "website",
            "content": "<p>no but we can do that at lunch time or something. the chances of me appearing at hacker school before 9:30am are almost impossible (esp because i'm moving this week). </p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104481,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "nehalita@gmail.com",
            "sender_full_name": "Neha Batra (she) (W'13)",
            "sender_id": 836,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364834352,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b3b0d1423bed3249661b8099f5f6512a5cada1d8?x=x&version=2",
            "client": "website",
            "content": "<p>I think I already watched the videos for week one last week off of youtube.</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104527,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "einas.haddad@gmail.com",
            "sender_full_name": "Einas Haddad (she) (m5'18)",
            "sender_id": 838,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364834435,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/09f2ca686b8694d23ff27d70f519a209?d=identicon&version=1",
            "client": "website",
            "content": "<p>actually same - i watched them last year. i might skip around the lectures tonight. do ya'll want to go over the hw on wednesday morning then? i wonder if the lectures are the same as the ones on yt... it would make sense, right? </p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104680,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "nehalita@gmail.com",
            "sender_full_name": "Neha Batra (she) (W'13)",
            "sender_id": 836,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364834799,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b3b0d1423bed3249661b8099f5f6512a5cada1d8?x=x&version=2",
            "client": "website",
            "content": "<p>it does, I don't see why they would remake them.</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104746,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "einas.haddad@gmail.com",
            "sender_full_name": "Einas Haddad (she) (m5'18)",
            "sender_id": 838,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364834957,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>sounds good - yes i have done some python while here in HS - wed morning sounds good!</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 4104853,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1364835172,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8811fd9098e64f388737ea7b99269a78?d=identicon&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>Anyone doing the latest version of MongoDB for Node devs course by 10gen?</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 11717175,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "mehul.mandania@gmail.com",
            "sender_full_name": "Mehul Mandania (F'13)",
            "sender_id": 2890,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1382383700,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8811fd9098e64f388737ea7b99269a78?d=identicon&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>It starts today. Here's a link to the course: <a href=\"https://education.mongodb.com/courses/10gen/M101JS/2013_October/about\" target=\"_blank\" title=\"https://education.mongodb.com/courses/10gen/M101JS/2013_October/about\">https://education.mongodb.com/courses/10gen/M101JS/2013_October/about</a></p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 11717190,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "mehul.mandania@gmail.com",
            "sender_full_name": "Mehul Mandania (F'13)",
            "sender_id": 2890,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1382383738,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8811fd9098e64f388737ea7b99269a78?d=identicon&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>Anyone implemented a Mongo DB using Heroku?</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 11860320,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "mehul.mandania@gmail.com",
            "sender_full_name": "Mehul Mandania (F'13)",
            "sender_id": 2890,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1382650127,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e6e28e6763c390b7a49f17be932d57ad?d=identicon&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>Given how Heroku works, I think your options there are either to use a MongoDB addon or connect to a Mongo service you have running somewhere else (preferably on EC2). I have experience with the latter and could talk to you after presentations if you wish.</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 11860346,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "travis.thieman@gmail.com",
            "sender_full_name": "Travis Thieman (F'13)",
            "sender_id": 2881,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1382650187,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8811fd9098e64f388737ea7b99269a78?d=identicon&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>Awesome. I'll take you up on that once I move my DB onto an EC2 instance</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 11860552,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "mehul.mandania@gmail.com",
            "sender_full_name": "Mehul Mandania (F'13)",
            "sender_id": 2890,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "week 1!",
            "submessages": [],
            "timestamp": 1382650452,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1380ded36dafac0d6f808b9b7b6c4e85266428a1?x=x&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>For anyone using MongoDB:<br>\nWhy are you using Mongo vs. any other type of datastore (Postgres, sqlite, BerkleyDB, Hive, a text file, etc.)?</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 11997497,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "travis@mcdem.us",
            "sender_full_name": "Travis McDemus (S'13)",
            "sender_id": 2139,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "Why do you use it?",
            "submessages": [],
            "timestamp": 1382964841,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e6e28e6763c390b7a49f17be932d57ad?d=identicon&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>Mongo's web scale, duh. <img alt=\":smiley:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/smiley.png\" title=\":smiley:\"> BSON has most data types you want and allows efficient querying, prototyping is really easy, denormalized schema structures are pretty easy once you get the hang of them. If you take a look at the <code>mongo</code> and <code>sqlite</code> <code>sqlite_models</code> modules here, you'll see how big of a difference there can be in programming effort: <a href=\"https://github.com/tthieman/dagobah/tree/master/dagobah/backend\" target=\"_blank\" title=\"https://github.com/tthieman/dagobah/tree/master/dagobah/backend\">https://github.com/tthieman/dagobah/tree/master/dagobah/backend</a></p>\n<p>The only other solution that might be worth looking into is Postgres, but I'm not familiar enough with its JSON offerings to know how it handles unstructured data. SQLite is just SQL with poor DDL support, you can't alter tables very well, etc. Text files will drown you in serialization costs if you try to store JSON in them, and you can't query them effectively like you can with BSON. Hadoop/Hive in my experience cannot be used for fast, user-facing queries, but that may be a deficiency with me and not with Hadoop. I have no experience with BerkeleyDB.</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 11999420,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "travis.thieman@gmail.com",
            "sender_full_name": "Travis Thieman (F'13)",
            "sender_id": 2881,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "Why do you use it?",
            "submessages": [],
            "timestamp": 1382968751,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1380ded36dafac0d6f808b9b7b6c4e85266428a1?x=x&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>Thanks. What makes it good for \"web scale\"?  <br>\nDoes it have faster reads or something when sharded than any other alternative? <br>\nCan a shard master handle aberrantly more requests before performance slowdown or something?<br>\n(These questions may be the wrong ones - I'm just trying to discover Mongo's strongest use cases and how to identify those scenarios.) </p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12003734,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "travis@mcdem.us",
            "sender_full_name": "Travis McDemus (S'13)",
            "sender_id": 2139,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "Why do you use it?",
            "submessages": [],
            "timestamp": 1382975918,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e6e28e6763c390b7a49f17be932d57ad?d=identicon&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>It's good for read-heavy workloads where you get some benefit from flexibility in your schema design. It's also best when you have a small subset of your data that's \"hot\" at any given time, since performance will die if you are hitting disk a lot.</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12003828,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "travis.thieman@gmail.com",
            "sender_full_name": "Travis Thieman (F'13)",
            "sender_id": 2881,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "Why do you use it?",
            "submessages": [],
            "timestamp": 1382976060,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6b86a98e8030a769db9aa9d76169d1a08ce6b42a?x=x&version=3",
            "client": "desktop app Mac 0.3.8",
            "content": "<p><span class=\"user-mention\" data-user-email=\"travis@mcdem.us\">@Travis McDemus (S'13)</span> we had a MongoDB team lead come in to KrashPad recently (Tyler Brock, he handles the Ruby frontend), and he gave a nice intro, including some of the advantages vis-a-vis other systems (easy scaling, sharding, replication, etc.). He was very open about meeting up, answering emails, etc.</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12008075,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "hackerschool@fabian-lischka.de",
            "sender_full_name": "Fabian Lischka (F'13)",
            "sender_id": 2901,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "Why do you use it?",
            "submessages": [],
            "timestamp": 1382982137,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1380ded36dafac0d6f808b9b7b6c4e85266428a1?x=x&version=1",
            "client": "desktop app Mac 0.3.8",
            "content": "<p>Thanks guys.  Did Tyler have any benchmarks, etc.?</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 12052613,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "travis@mcdem.us",
            "sender_full_name": "Travis McDemus (S'13)",
            "sender_id": 2139,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "Why do you use it?",
            "submessages": [],
            "timestamp": 1383065546,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8811fd9098e64f388737ea7b99269a78?d=identicon&version=1",
            "client": "desktop app Mac 0.3.10",
            "content": "<p>I need to get a random document from a collection. It isn't a feature Mongo currently provides. I've come across a couple of hacks online, can anyone recommend a method?</p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 13270683,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "mehul.mandania@gmail.com",
            "sender_full_name": "Mehul Mandania (F'13)",
            "sender_id": 2890,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "Getting a random document from a collection",
            "submessages": [],
            "timestamp": 1385398058,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/52a0f0902c701d3d6258ac2a5538390ca3efff01?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>hi there! just getting started with MongoDB and have some pretty basic questions.  Would anyone be willing to pair for a bit and chat? </p>",
            "content_type": "text/html",
            "display_recipient": "mongodb",
            "flags": [
                "read",
                "historical"
            ],
            "id": 25150454,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 21375,
            "sender_email": "jacob.schonberg@gmail.com",
            "sender_full_name": "Jacob Schonberg (S2'14)",
            "sender_id": 6169,
            "sender_realm_str": "recurse",
            "stream_id": 19625,
            "subject": "beginner questions",
            "submessages": [],
            "timestamp": 1406062975,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
