{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1380ded36dafac0d6f808b9b7b6c4e85266428a1?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"doronr@sas.upenn.edu\">@Doron Roberts-Kedes</span> , <span class=\"user-mention\" data-user-email=\"samueljpost@gmail.com\">@Sam Post</span> , would either of you know of a decent sample / wave editor for OS X (or linux)?   Audacity just ain't cutting it for sample editing (literally)! </p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 8848284,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "travis@mcdem.us",
            "sender_full_name": "Travis McDemus (S'13)",
            "sender_id": 2139,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "sample editors",
            "submessages": [],
            "timestamp": 1375887627,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8a792e49cb498167a46bea940fcbdaa8?d=identicon&version=1",
            "client": "website",
            "content": "<p>i don't, sadly. what're you trying to do exactly?</p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 8848294,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "samueljpost@gmail.com",
            "sender_full_name": "Sam Post (S'13)",
            "sender_id": 2107,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "sample editors",
            "submessages": [],
            "timestamp": 1375887698,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c2391d31983698715db52fca31968526?d=identicon&version=1",
            "client": "website",
            "content": "<p>haha. unfortunately im always using logic, but if you find any good freeware let me know!</p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 8848903,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "doronr@sas.upenn.edu",
            "sender_full_name": "Doron Roberts-Kedes (S'13)",
            "sender_id": 2120,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "sample editors",
            "submessages": [],
            "timestamp": 1375888954,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1380ded36dafac0d6f808b9b7b6c4e85266428a1?x=x&version=1",
            "client": "website",
            "content": "<p>I'm just trying to manually cut up sample files into perfectly repeating loops. <br>\nReaper is pretty good for the scrubbing / selection, but the exporting / mix down is laborious.<br>\nAudacity is almost good, but it doesn't let you expand (shift+click) the selection without stopping loop playback. </p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 8849356,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "travis@mcdem.us",
            "sender_full_name": "Travis McDemus (S'13)",
            "sender_id": 2139,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "sample editors",
            "submessages": [],
            "timestamp": 1375889857,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1920d37780c9a711b0030870b0c726098e0efb10?x=x&version=2",
            "client": "website",
            "content": "<p>LMMS is an open source digital audio workstation - you can use it to make music on your computer. It just moved from sourceforge to GitHub and apparently is picking up steam as a result. It's a huge project but there are lots of little ways it can be improved if you're interested.</p>\n<p><a href=\"https://github.com/LMMS/lmms\" target=\"_blank\" title=\"https://github.com/LMMS/lmms\">https://github.com/LMMS/lmms</a></p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 15747374,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "superjoe30@gmail.com",
            "sender_full_name": "Andrew Kelley (he) (SP1'17)",
            "sender_id": 2911,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "lmms",
            "submessages": [],
            "timestamp": 1390378087,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/698f6cb788a1bf94da9781c181bf151cad452950?x=x&version=1",
            "client": "website",
            "content": "<p>cool, thanks for posting! Will look into it.<br>\nGood to have some life in this thread :)</p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 19923756,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "wforzo@gmail.com",
            "sender_full_name": "Will Orzo (W'14)",
            "sender_id": 5029,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "lmms",
            "submessages": [],
            "timestamp": 1397488056,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/698f6cb788a1bf94da9781c181bf151cad452950?x=x&version=1",
            "client": "website",
            "content": "<p>er...\"stream,\" rather.</p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 19923798,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "wforzo@gmail.com",
            "sender_full_name": "Will Orzo (W'14)",
            "sender_id": 5029,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "lmms",
            "submessages": [],
            "timestamp": 1397488087,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/df9e8700a8e4136c62edb59ca1bb090893914a8b?x=x&version=3",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>does anybody use this? right now I'm working on a database interface program for randomizing tracker files for OpenMPT :) </p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38494666,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "nikkicubed@gmail.com",
            "sender_full_name": "Nikki Bee (she) (SP1'15)",
            "sender_id": 7636,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "openmpt",
            "submessages": [],
            "timestamp": 1429718210,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/009427e1b56c85d4a70a091905cf7a305c109dc6?x=x&version=5",
            "client": "website",
            "content": "<p>Really interesting blog post discussing several issues with Lilypond, and several thoughts on what future music engraving software should do better:<br>\n<a href=\"http://noteflakes.com/blog/2016/11/21/teaching-a-computer-to-typeset-music-I/\" target=\"_blank\" title=\"http://noteflakes.com/blog/2016/11/21/teaching-a-computer-to-typeset-music-I/\">http://noteflakes.com/blog/2016/11/21/teaching-a-computer-to-typeset-music-I/</a></p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 109019965,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "heneli@kailahi.com",
            "sender_full_name": "Heneli Ta'angafala Kailahi (SP2'17)",
            "sender_id": 100771,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "Issues with Current Music Notation Software",
            "submessages": [],
            "timestamp": 1490961542,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/009427e1b56c85d4a70a091905cf7a305c109dc6?x=x&version=5",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"andrewyoon2@gmail.com\" data-user-id=\"100202\">@Andrew Yoon (F2'16)</span>  - link is back up</p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 110358454,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "heneli@kailahi.com",
            "sender_full_name": "Heneli Ta'angafala Kailahi (SP2'17)",
            "sender_id": 100771,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "Issues with Current Music Notation Software",
            "submessages": [],
            "timestamp": 1493803138,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/009427e1b56c85d4a70a091905cf7a305c109dc6?x=x&version=5",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"paul@paulwmorris.com\" data-user-id=\"100524\">@Paul Morris (SP1'17)</span> too</p>",
            "content_type": "text/html",
            "display_recipient": "music software",
            "flags": [
                "read",
                "historical"
            ],
            "id": 110358462,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 23607,
            "sender_email": "heneli@kailahi.com",
            "sender_full_name": "Heneli Ta'angafala Kailahi (SP2'17)",
            "sender_id": 100771,
            "sender_realm_str": "recurse",
            "stream_id": 20663,
            "subject": "Issues with Current Music Notation Software",
            "submessages": [],
            "timestamp": 1493803161,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
