{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/9fd9de59f964f6e3af477006ddd0116211347010?x=x&version=2",
            "client": "Internal",
            "content": "<p>Stream created by <span class=\"user-mention silent\" data-user-id=\"221832\">Evy Kassirer (she) (m4'19)</span>.</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214217796,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "notification-bot@zulip.com",
            "sender_full_name": "Notification Bot",
            "sender_id": 100006,
            "sender_realm_str": "zulipcore",
            "stream_id": 262381,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1603386632,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>does anyone recommend videos or general strategies for practicing my uke? I've mostly just been learning chords for songs, but I feel like it would be cool to be more deliberate around learning picking techniques or particular strumming patterns or something</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214219379,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603387360,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>[oct 21]</p>\n<p>working on Venetian Boat Song no. 2 by Mendelssohn. I have some old sheet music with notes from when I was taking lessons in high school</p>\n<p><a href=\"https://michaelkravchuk.com/wp-content/uploads/2019/01/Mendelssohn-Venetian-Boat-Song-Op-30-No.-6-1-Page-Version.pdf\">a mostly-the-same-as-mine score pdf</a></p>\n<p>trying to focus mostly measures 1-22 for now.</p>\n<p>dynamics to practice / be aware of</p>\n<ul>\n<li>it gets quieter over m3,4,5<ul>\n<li>why does it have the \"&gt;\" and then spelled out \"dim\" after that? am i supposed to interpret those differently? (interestingly, the pdf I linked to only has the \"&gt;\", so I'm guessing it doesn't matter)</li>\n</ul>\n</li>\n<li>LH (left hand) should generally be soft (it's accompaniment, background support), RH should generally be louder (a melody that is song-like, \"cantabile\")</li>\n<li>m17: the RH does a \"&lt; &gt;\" but the LH should stay constant (or so an old piano teacher said, seems reasonable)</li>\n<li>can I make the <em>sf</em> in m13 sound more sudden/striking?</li>\n<li>can do a lot more contrast between that <em>sf</em> in m13 and the <em>p</em> in m14</li>\n</ul>\n<p>other notes</p>\n<ul>\n<li>in m10 there's an eighth rest in RH - but is there even a meaningful way to play that when there's pedal for the whole bar?<ul>\n<li>oh maybe it's more to show me phrasing, like the dotted half is a lead into the next phrase instead of the end of the last phrase! def wasn't thinking that way before!</li>\n</ul>\n</li>\n<li>wanting to keep LH really steady and smooth without some notes poking out, that's hard! (esp bc i'm trying not to be too loud in general out of fear of disturbing neighbours lol)<ul>\n<li>hard with the octave jumps back down to c#, my pinky jumps back down and plunks the note, can practice being more soft there</li>\n</ul>\n</li>\n<li>thinking more carefully about pedal, want to pedal in the right places, am I following the markings? oh huh the internet has some scores with slightly different pedal markings, I guess I'll do whatever I think sounds good lol</li>\n</ul>\n<p>ok actual practice plan:</p>\n<ul>\n<li>going over 12-14 a lot, both for dynamics and note accuracy - maybe I'll focus on not fucking up the notes first, and then add dynamics :p  <ul>\n<li>just LH first, looping the section (plus a bit before and after) slowly</li>\n<li>ok I ran out of time, will continue on this tomorrow!</li>\n</ul>\n</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214219879,
            "is_me_message": false,
            "last_edit_timestamp": 1603387671,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1603387608,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Skimmed through <a href=\"https://ukuguides.com/beginner/ultimate-ukulele-strumming-tips-and-guide/\">https://ukuguides.com/beginner/ultimate-ukulele-strumming-tips-and-guide/</a> just now, seemed useful. It would probably be a helpful exercise to explore how strumming on my uke sounds from different parts of the neck</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214258514,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603408308,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7de60303f6bb47bc3e678e090f9de36d?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ping <span class=\"user-mention\" data-user-id=\"100049\">@Alicja Karolina Raszkowska (she/they) (W2'18)</span> :)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214296768,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "jeremiejost@gmail.com",
            "sender_full_name": "J\u00e9r\u00e9mie Jost (he) (m5'20)",
            "sender_id": 9326,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603449119,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>[oct 23]</p>\n<p>Wasn't feeling super able to focus on harder things, so went back to a pop song I learned well in high school and am relearning (Where I Stood by Missy Higgens). It would be fun to have it memorized again, cause it makes it more likely I'd be able to remember it and play it on any piano I encounter in the future.</p>\n<p>Strategy for today was to do a play through and note places where I messed up. I took little cuts of sticky notes and marked those places. They were in in general categories of sections of a piece that would usually be under-practiced</p>\n<ol>\n<li>transitions (page turns, jumps to second endings)</li>\n<li>sections that get repeated less (the bridge, the ending)</li>\n</ol>\n<p>I went over each of the mistakes until I had them smooth again (for today at least). I think I could have repeated it even more to really get it locked in, but lost patience and kept wanting to just play through the song :p </p>\n<p>Was also noticing that some of the things I play wrong I don't want to fix. I like the way it sounds when I add a note or don't play some notes or whatever. So psh, I guess I'll just leave it  like that</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214399244,
            "is_me_message": false,
            "last_edit_timestamp": 1603499177,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1603498451,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/N4EpdNX2Ri6XmQfKMufJ6w96/skinny-love-piano.pdf\">skinny-love-piano.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214452983,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1603578427,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>[oct 24]</p>\n<ul>\n<li>practiced skinny love (birdy cover)</li>\n<li>was a balance between \"oh it's fun to just try to play it even with mistakes\" and \"actually going over the tricky parts and correcting the mistakes will feel more satisfying even if it's also sometimes boring\" - a few times i wanted to sing along but that didn't go so well so I'll wait longer on that heh. much easier while playing slowly and no singing (duh)</li>\n<li>focused on only a little section of it (until C) and split up just LH or just RH sometimes</li>\n<li>used metronome to practice for accuracy, force myself to slow down (kinda meditative when i really get into it)</li>\n<li>went to half speed (40ish, then tried near the end at 46)</li>\n<li>looped measures 12-21 a lot, I think I could play from start to to [C] at 46bpm with only a few mistakes now</li>\n<li>line breaks keep getting me -- good to look ahead to the next measure on the next line in case it's tricky (or leave a note at the end of the last line if the next measure usually gets me)</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214453050,
            "is_me_message": false,
            "last_edit_timestamp": 1603578542,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1603578511,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>oooh, I have a bunch! gonna write a little later as I have a busy morning, marking it on my calendar &lt;3</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214503831,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2764",
                    "emoji_name": "heart",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "evy.kassirer@gmail.com",
                        "full_name": "Evy Kassirer (she) (m4'19)",
                        "id": 221832
                    },
                    "user_id": 221832
                }
            ],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603649671,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>there are four major techniques with ukulele:</p>\n<ul>\n<li>strumming</li>\n<li>fingerpicking</li>\n<li>melody</li>\n<li>chord melody (strumming + melody)</li>\n</ul>\n<p>I think starting with strumming makes sense, as it gets you familiar with the sound of the uke and lets you play songs really fast!</p>\n<p>quick tips for each type:<br>\n<em>strumming</em></p>\n<ul>\n<li>don't strum over the soundhole - it's not comfortable, as uke is a bit too small for it, you'll get a better sound above the hole on the neck</li>\n<li>the higher on the neck you strum, the more quiet it gets - I like to finish songs by strumming lighter up the neck</li>\n<li>keep strumming the whole time - don't just strum when you need to hear the sound, keep that hand moving! you'll learn to pick up the strums when you need them</li>\n<li>learn to strum with your thumb and at least one other finger - I prefer strumming with my middle finger, you want to be able to strum with the thumb and index/middle/ring to be able to have both a fleshy sound (going down with thumb, up with other fingers) and a fingernail sound (reverse)</li>\n<li>learn different patterns - island strum (down-down-up-up-down-up) is by far the most prevalent and something I keep having to get my head out of :) a useful one in-between for half-measures is down-up-down (I have no idea how to write music notation in Zulip)</li>\n<li>to make a strum louder, make your movement bigger - I usually accent my first and third strum with a bigger movement at the same speed</li>\n</ul>\n<p><em>fingerpicking</em> (playing chords with fingerpicking patterns)</p>\n<ul>\n<li>there are two styles - Travis (thumb-thumb-index-middle) and classical (thumb-index-middle-ring), learn both - if you're on a high G, you'll probably prefer Travis, low G usually works better with classical</li>\n<li>folk ukulele is often played similar to banjo, with Travis picking and your thumb jumping between the two top strings - it's a nice rhythm to get into!</li>\n<li>learn one pattern at a time and practice it over short melodies - I love Daniel Ward's \"Arpeggio Meditations\" for it, once you memorize one of them, you can play different picking patterns to warm up</li>\n<li>keep your fingers at the same distance from the strings</li>\n<li>try not to use your free finger for support, especially not pinky, it's too short! some folks do use ring finger when Travis picking</li>\n</ul>\n<p><em>melody</em> (playing a melody)</p>\n<ul>\n<li>folks have different opinions on it - some play with Travis picking, some play with just the thumb, I prefer the thumb, because it let's me focus on my neck hand; pick one you like</li>\n<li>find the scale that your melody is in and warm up there before playing - ukulele scales are moveable (I'll share a resource on that), so if you find your root note, you should be able to always find the right spot for your melody; I usually play melodies that have two-three scales around the neck (my music theory terms are muddy, hope it's not too unclear)</li>\n<li>try to find arpeggios where you can - makes your melody so much nicer :)</li>\n</ul>\n<p><em>chord melody</em> (playing melody and chords)</p>\n<ul>\n<li>chord shapes here are going to be often out of whack - you're going to be strumming/fingerpicking and playing the melody on top of it!</li>\n<li>your melody note is usually the highest note you play in the chord - some chords get shortened because of that, or sometimes inverted, strummed from the bottom etc.</li>\n<li>you don't have to strum all the time, once/twice every measure is more than enough</li>\n<li>practice your melody so you know it well, without the chords</li>\n<li>practice your chords so you can react to them without thinking</li>\n<li>practice them both together (chord melody takes me 3 times as much to practice a piece, because I always practice all three ways)</li>\n<li>if you're strumming, I'd recommend playing with your thumb only (both melody and chords), if you're fingerpicking, you probably want more fingers involved</li>\n</ul>\n<p>quick tips for holding the uke:</p>\n<ul>\n<li>don't hold it straight, it needs to be at an angle - about 30-40 degrees from your face</li>\n<li>point your fingers on the neck towards the sound hole, make sure your wrist angle is comfy and consistent</li>\n<li>your index should usually be the closest to your chin and your pinky the furthest - don't cross over fingers unless you really really have to, when learning a chord, start with the index on the lowest fret (from the head) and highest string (highest meaning closest to your chin), then middle accordingly either on the lower string or higher fret</li>\n<li>don't hold the neck with your whole thumb, holding with just the tip will give more room for your fingers to move</li>\n<li>pinky is very important! don't skimp on training it</li>\n<li>consider getting a strap, I find them super comfy</li>\n<li>when barring chords, push the hand toward the fretboard and feel the pressure on your whole instrument, instead of just using the muscle of the finger</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510573,
            "is_me_message": false,
            "last_edit_timestamp": 1603659439,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603657998,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>now, for resources! that's gonna be a long list, because I'm a bit of a hobby hoarder</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510582,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658018,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>James Hill is a wonderful teacher and a ukulele master - he has a series of books and courses for ukulele players, whichever you prefer either getting the books or registering at Uketropolis <a href=\"https://www.uketropolis.com/\">https://www.uketropolis.com/</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510654,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658089,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>Daniel Ward has two great books - Arpeggio Meditations for Ukulele and Melodic Meditations for Ukulele (<a href=\"https://danielward.net/book-store\">https://danielward.net/book-store</a>), he also does lessons for the Ukulele magazine that are often free to read online on the magazine website (loads of other great teachers there too) <a href=\"https://www.ukulelemag.com/\">https://www.ukulelemag.com/</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510738,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658187,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>when I first started learning, I used Yousician - it's really pricey, but it was worth for the first year, as it got me strumming and playing every day</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510763,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658224,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>Aaron Keim and his wife create wonderful handwritten books for fingerstyle uke and folk uke, they play uke together and he's a luthier, wonderful couple, I really like this book <a href=\"https://store.ukulelemag.com/collections/lesson-books/products/fingerstyle-ukulele\">https://store.ukulelemag.com/collections/lesson-books/products/fingerstyle-ukulele</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510837,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658295,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>Brad Bordessa has a good website - <a href=\"https://liveukulele.com/\">https://liveukulele.com/</a> - and a few books I really enjoyed, for right and left-hand technique (meaning strumming and neck hand), and for chord shapes (chord shapes are soooo useful later on!)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510894,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658383,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>Eduardo, my teacher, will have a Patreon soon, in the meantime his YT is full of arrangements <a href=\"https://www.youtube.com/channel/UCE93tArSDRUiruc4QU1oBjQ\">https://www.youtube.com/channel/UCE93tArSDRUiruc4QU1oBjQ</a> :)</p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"channel\" href=\"https://www.youtube.com/channel/UCE93tArSDRUiruc4QU1oBjQ\"><img src=\"https://i.ytimg.com/vi/channel/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510955,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658422,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>I really enjoy going to uke school - I have classes once a week and twice a month I meet with my teacher for a private lesson (I pay for those separately), he helps me and challenges me in all the right ways, making sure to account for all the things I need to learn (including music theory, but I think you got that covered)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214510980,
            "is_me_message": false,
            "last_edit_timestamp": 1603659028,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658472,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>Ruby's Ukes is a uke school in Vancouver, currently doing all their classes online, if you're looking to meet some uke folks and learn from great teachers, I highly recommend it <a href=\"https://www.rubysukes.ca/\">https://www.rubysukes.ca/</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511003,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658517,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>and for some specific resources, let me dig into pdfs from class - we have a few warmups and handouts that would be useful for any player</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511054,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658552,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/EDMMu-1XqyrTEpTiO3dne8pR/scale_patterns.pdf\">scale_patterns.pdf</a> <a href=\"/user_uploads/13/leOHya95rik_bcSFBNppZk4b/scales.pdf\">scales.pdf</a> <a href=\"/user_uploads/13/ycObKvTjldHGeZcwWmURJwx2/transposing.pdf\">transposing.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511160,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658660,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>scale patterns - moveable scales on the neck<br>\nscales - basic scales on the uke<br>\ntransposing - to adjust songs to your voice range :)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511169,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658684,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>I can't find two additional pdfs, I have printouts for basic strumming and fingerpicking patterns, they're useful for warmups</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511185,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658708,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>for warmup I:</p>\n<ul>\n<li>play a major scale up and down the neck, while singing (my teacher always talks about how important it is to find your voice on the uke)</li>\n<li>do one meditation exercise from Daniel Ward's books</li>\n<li>play a chord progression with one of the strumming patterns</li>\n<li>play two-three songs I love (chord, fingerpicking, and melody)</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511262,
            "is_me_message": false,
            "last_edit_timestamp": 1603659093,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658801,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>okay, that was a LOT! I'm so excited whenever someone learns the uke</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511269,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f419",
                    "emoji_name": "octopus",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "evy.kassirer@gmail.com",
                        "full_name": "Evy Kassirer (she) (m4'19)",
                        "id": 221832
                    },
                    "user_id": 221832
                }
            ],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658818,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>I should write a blog post :)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511273,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f4af",
                    "emoji_name": "100",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "evy.kassirer@gmail.com",
                        "full_name": "Evy Kassirer (she) (m4'19)",
                        "id": 221832
                    },
                    "user_id": 221832
                }
            ],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658823,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>most importantly - pick songs you like and play them! I don't do it enough, because my teacher keeps giving me more songs and I have so much learning already, but it's one of my goals, to play more of the music I like - my teacher is great, but I think I learned enough American songs from 30-60s for now ;)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511369,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603658939,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>a songbook is pretty good for that, I know <span class=\"user-mention\" data-user-id=\"9326\">@J\u00e9r\u00e9mie Jost (he) (m5'20)</span>  has a great one to share :)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511474,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603659070,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>one thing my teacher mentioned, that as a musician it was easier for him to learn uke by considering each string a tiny piano, starting on a different note - I'm not sure if that concept helps</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214511861,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "14067",
                    "emoji_name": "thinking_face_3d",
                    "reaction_type": "realm_emoji",
                    "user": {
                        "email": "evy.kassirer@gmail.com",
                        "full_name": "Evy Kassirer (she) (m4'19)",
                        "id": 221832
                    },
                    "user_id": 221832
                }
            ],
            "recipient_id": 570783,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603659518,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>wow this is amazing <span class=\"user-mention\" data-user-id=\"100049\">@Alicja Karolina Raszkowska (she/they) (W2'18)</span> thanks so much for the recs!!</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214757553,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2764",
                    "emoji_name": "heart",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rc@alicja.dev",
                        "full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
                        "id": 100049
                    },
                    "user_id": 100049
                }
            ],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "uke learning resources",
            "submessages": [],
            "timestamp": 1603829550,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>[oct 27]</p>\n<p>didn't leave much time for practice today but I wanted to do a bit. went over Where I Stood, which I'd like to be able to play through consistently without making mistakes. right now most of my mistakes are in transitions between sections, so I'll spend a bit of time working specifically on those. I really enjoy that I have most of the notes muscle-memorized and can focus my energy on phrasing and the <em>feeling</em> of the music, which is what I much prefer to think about when playing</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214792984,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1603855928,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>[oct 28]</p>\n<p>Where I Stood: went over the parts I more often mess up</p>\n<p>Skinny Love</p>\n<ul>\n<li>at it with the metronome, starting still at 46bpm</li>\n<li>there are 3 places between the start and C that I mess up consistently so went over those in particular, looping a lot to get my fingers used to it</li>\n<li>sometimes in places I know better I want to rush, I like that the metronome makes me stay steady, gives me time to think about what's ahead, or to think about how I want to play the current notes better -- taking time to appreciate the feeling of space, to not be worrying about what notes to play, to sit in the music</li>\n<li>thinkin about: which notes are most important? e.g. in m11 the A in the RH is part of the melody and the F# is just harmonizing the A, so the A should louder</li>\n<li>got 2 perfect runs at 46bpm! moved up to 50bpm and got two more, 55 feels not too bad but I started having trouble focusing and messed up more :p (the goal is 77 so there's still a fair bit to go)</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 214923761,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1603943527,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>!!! My first run-through of Where I Stood with essentially no mistakes! <span aria-label=\"smiling face\" class=\"emoji emoji-263a\" role=\"img\" title=\"smiling face\">:smiling_face:</span>\ufe0f<span aria-label=\"smiling face\" class=\"emoji emoji-263a\" role=\"img\" title=\"smiling face\">:smiling_face:</span>\ufe0f<span aria-label=\"smiling face\" class=\"emoji emoji-263a\" role=\"img\" title=\"smiling face\">:smiling_face:</span>\ufe0f</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215045883,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2764",
                    "emoji_name": "heart",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jeremiejost@gmail.com",
                        "full_name": "J\u00e9r\u00e9mie Jost (he) (m5'20)",
                        "id": 9326
                    },
                    "user_id": 9326
                }
            ],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604018617,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Went over the first third of Skinny Love again and it feels more comfortable now. Also went over the rest of it and it's super repetitive and similar to the first third! I feel like I know all the sections similarly well now. Future session I'll focus in on various sections to clean them up, and it would also be nice to start trying to add singing to it :)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215202977,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604166684,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Really cool to see how muscle memory can build so quickly, I can play the first section of Skinny Love (that I was struggling to play half tempo) now full tempo with barely any mistakes!</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215378017,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604350832,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>I do want to separately get better at sight-reading though</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215378056,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604350854,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>one detail I was noticing while practicing today is sometimes there is a held note on my left hand that is, immediately after I lift my LH finger, played by  my RH -- and if I don't lift my LH fast enough then the RH doesn't really get a chance to fully play it (like, the key is still half pressed). So I circled the few places where that happens</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215404371,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604368327,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>this sheet music doesn't have words written in, and I don't have the piece memorized, so I wrote in most of the words (sometimes I only wrote some of the words to queue myself, where I knew it better)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215404387,
            "is_me_message": false,
            "last_edit_timestamp": 1604368457,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604368344,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>the song is fairly repetitive (as are most pop songs) so I might want to start thinking about how I'm going to vary the different verses and choruses to make them more interesting and meaningful</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215404419,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604368375,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>ALsO i can totally focus mostly on words now and there are only a few parts of the piece that I keep messing up on piano :D</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215404463,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604368427,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention silent\" data-user-id=\"221832\">Evy Kassirer (she) (m4'19)</span> <a href=\"#narrow/stream/262381-music-playing/topic/evy's.20piano.20practice.20log/near/215378056\">said</a>:</p>\n<blockquote>\n<p>I do want to separately get better at sight-reading though</p>\n</blockquote>\n<p>so today I did a google search and found <a href=\"https://sightreadingmastery.com/blog/how-i-learned-to-sight-read\">https://sightreadingmastery.com/blog/how-i-learned-to-sight-read</a> which seems like reasonable advice</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215538455,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604461915,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>so I need to find way easier sheet music, think about it before playing, play it slowly and deliberately, move on after trying it twice</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215538508,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604461961,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.sightreadingfactory.com/practice/sr/level?mediumId=piano\">https://www.sightreadingfactory.com/practice/sr/level?mediumId=piano</a> looks like it could be really good for this</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215538522,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604461985,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>another reason to buy an ipad (I also want to draw with procreate) but using my laptop seems fine and also using incognito lets me not pay for it until I try it a bunch more</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215538531,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604462017,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>why do I want to get better at sight-reading? mostly because it's really helpful for leading music ensembles (e.g. choir conducting) because I can play people's parts for them without having to practice that all first</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215538585,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604462067,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>but I also think it levels up my musical abilities in general, might make it easier to learn new pieces (without messing up as much) and is good training for very deliberate practice</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215538597,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604462093,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>yeah this app is pretty good so far, it has enough fine-tuneable settings that I can work on things just on the edge of my ability (things that seem way too simple but I still mess up pretty often). </p>\n<p>and when I get pretty solid at what i'm doing rn (SRF 3, random time signatures, Cmajor, tempo at like 50), I could make it harder in a lot of different ways</p>\n<ul>\n<li>faster tempo</li>\n<li>use more key signatures than C major</li>\n<li>or could go up a level</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215642749,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604524773,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>I feel like it will be easy to see progress and that will feel good</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215642767,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604524786,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>also when I got this piano tuned I paid less to only tune it relative to itself so now when I play along with the website it sounds painful lol</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215642841,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604524813,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>nov 5:</p>\n<p>Heh, should probs be practicing sightreading in more than one key. Right now it only has 5 note range, so I was associating certain spaces on the clef with fingerings for Cmajor (e.g. middle C always means RH thumb), and when I tried adding another key I started having to actually read the notes again and think about what finger to use to play it. I guess it maybe could be fine to have that be out of scope and only do Cmajor, but I'd rather do simpler things in multiple keys than only learn how to do things in one key without paying attention to notes/fingerings</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215802095,
            "is_me_message": false,
            "last_edit_timestamp": 1604632696,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604632439,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>nov 7:</p>\n<p>Went over Skinny Love today and practiced some of the areas where I mess up. Didn't feel like using the metronome, tired to play slowly and deliberately (with varying success :p). Tried not to sing -- I notice it's a bit high for me, and I don't want to build muscle memory where I'm singing it with tension, so i want to add the singing pretty carefully and deliberately using good technique. So just focusing on getting the piano part locked in for now</p>\n<p>thought a little more carefully about fingerings for some places. even if I use pedal it really does make a big difference in how legato something sounds if I can play the next note before lifting the current note, and there were a few places where my fingers were in whatever felt easiest for the notes earlier in the bar, without really planning transitions to other notes. e.g. in <a href=\"https://zulip-uploads.s3.amazonaws.com/13/N4EpdNX2Ri6XmQfKMufJ6w96/skinny-love-piano.pdf?AWSAccessKeyId=AKIAIEVMBCAT2WD3M5KQ&amp;Signature=fZHzoWuUQDG%2BKSrBNuXp02yGn7g%3D&amp;Expires=1604816587\">measure 29 here</a> I'd play the E with my pinky (since that works for most other places where this chord shows up) and then when I got the F I also played it with my pinky, but that sounds kinda jarring, and is much smoother if the E is played with my fourth finger (leaving pinky free for the F), so I practiced that for a bit. Would have probably been good to have realized this earlier, since I had muscle memory for the old fingering already</p>\n<p>Also thought about some LH fingering - like I could keep my LH in the same position for almost the whole piece (five fingers on A to E), but I kept moving my LH down when the RH played the E (e.g. measure 13, but also in many other places). But I don't actually have to do that, I can just lift my thumb to make space, and then I can play the left hand notes more smoothly and also more accurately (cause I'm not moving my hand around to new positions as much). So, trying to relearn that too <span aria-label=\"sweat smile\" class=\"emoji emoji-1f605\" role=\"img\" title=\"sweat smile\">:sweat_smile:</span></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215992121,
            "is_me_message": false,
            "last_edit_timestamp": 1604817265,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604816805,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>also, wrote about practicing today for my notebook writing! :) <a href=\"https://evy.garden/notebook/the-skill-of-practicing/\">https://evy.garden/notebook/the-skill-of-practicing/</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215992138,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604816859,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>my dad found my royal conservatory grade 8 piano books! :D he's gonna see if it's easy to mail them to me (i brought a lot of choir sheet music with me but had figured i wouldn't have access to a piano)</p>\n<p>i'd been trying to find this piece I played for my piano exam (back in high school) and now I know it's Nocturne (Op. 88, No. 3) - Heinrich Hofmann</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216040195,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604891633,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/sjdzUV_HLAYWS6hqrSlUnHKu/nocturne.pdf\">nocturne.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216040211,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604891644,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>awww playing through this is so nice and nostalgic. when i was practicing for that piano exam i was playing the same four pieces for at least an hour every day for months, and i got sick of most of them but always loved that song :)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216040675,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604892356,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>sort of regretting putting my printer in storage, but i'll just pick a few pieces to work on and go get them printed at fedex or whatever</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216040717,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604892381,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>just calling out there's an interesting conversation being had about this in <a class=\"stream-topic\" data-stream-id=\"251148\" href=\"/#narrow/stream/251148-music-discussion/topic/Practicing\">#music-discussion &gt; Practicing</a></p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216166092,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "pete@peterlyons.com",
                        "full_name": "Peter Lyons (he) (W1'17)",
                        "id": 103052
                    },
                    "user_id": 103052
                }
            ],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "practice and skill-building",
            "submessages": [],
            "timestamp": 1604974330,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e30b9e7d531d60960da4c58b24cf7e7c5aff03f0?x=x&version=5",
            "client": "ZulipElectron",
            "content": "<p>The Mendelssohn Songs Without Words are at the top of my list to work on when I start piano again. Which might be like tomorrow as I'm trying to craigslist a Casio Privia right now. Even the easiest is like 3 grades above my ability but I don't care and I was able to get the first page or 2 of one of them learned by sheer determination a while back.</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216168320,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "pete@peterlyons.com",
            "sender_full_name": "Peter Lyons (he) (W1'17)",
            "sender_id": 103052,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604977180,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>ooo yay!! yeah tbh I think I learn most of my music through sheer determination. Like, when I sit down and copy the same few measures again and again, my fingers eventually figure it out. That's how I ended up doing a grade 8 RCM exam with extremely limited sightreading ability (well, I do think that music experience from other instruments helps with the reading + musicality pieces. but I feel like you can get pretty far on \"get fingers to play the right notes\" through sheer determination to a fairly high grade level?)</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216168547,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604977449,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>today's practice was just going through <a href=\"/user_uploads/13/N4EpdNX2Ri6XmQfKMufJ6w96/skinny-love-piano.pdf\">skinny-love-piano.pdf</a> for mistakes and taking clear note of them</p>\n<p>i went a bit under tempo - 69 (:p) instead of 77</p>\n<p>areas where I made mistakes:</p>\n<ul>\n<li>m9-11 where it transitions to moving faster, I always think \"ahhh get ready\" and don't actually think about what i'm about to play</li>\n<li>m19-20, forgot to move LH up to the f#, also sometimes I miss the jump to the hand positions at 20</li>\n<li>m32 - it's just a bit different than the usual pattern, and also at a line break</li>\n<li>m37-38 - similar to issues with m19-20</li>\n<li>m47 - I actually have it down pretty well but forgot it was coming, part of the problem is the measure is so stretched out on my page and I don't look far enough ahead :p</li>\n<li>going into m49 (moving my hands way up) and getting my thumb down to the g# in 50</li>\n<li>m53-54 is a lot of sparse and repeated notes and I always want to play more than there is there</li>\n<li>m57 - sneaky d# at the end!! there are quite a few of these \"repeat the pattern almost identically except a small change\" that i was totally missing before, oops! circling the notes on the page has been helping a bit</li>\n<li>and the ending m63-onwards, just cause it's different and I haven't practiced it as much</li>\n</ul>\n<p>other thoughts</p>\n<ul>\n<li>practicing with a metronome makes it so much more obvious when i don't know things as well, if I just pause for a moment to try to remember what to do, i'm already behind</li>\n<li>the fingerings i'm moving to are so much nicer, it's not just more legato but also so nice to not move my hand around as much, easier to play accurately</li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216173789,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1604986118,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/22a26ea43a6ad80dc294adbc8d4406ac?d=identicon&version=1",
            "client": "website",
            "content": "<p>today went over my skinny love mistake list from yesterday <strong>but in reverse chronological order</strong></p>\n<p>this was great because when i was like \"i dun wanna drill this section anymore, i'll just keep playing, i would get to a section i had practiced earlier\"</p>\n<p>got through all the sections with metronome practice, then did a run through without metronome (i'm a bit worried the piece will lose it's ~~~feeling if i play it with metronome too much) and got through without too much mistake-making, so yay!</p>",
            "content_type": "text/html",
            "display_recipient": "music-playing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216283343,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 570783,
            "sender_email": "evy.kassirer@gmail.com",
            "sender_full_name": "Evy Kassirer (she) (m4'19)",
            "sender_id": 221832,
            "sender_realm_str": "recurse",
            "stream_id": 262381,
            "subject": "evy's piano practice log",
            "submessages": [],
            "timestamp": 1605047116,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
