{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"124692\" href=\"/#narrow/stream/124692-neat\">#neat</a>.</p>\n<p><strong>Description</strong>: A stream for neat stuff, of any description.</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001799,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 124692,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1527115645,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>An absolutely fascinating presentation on hardware and software failures of all kinds:<br>\n<a href=\"https://c3.nasa.gov/dashlink/static/media/other/ObservedFailures1.html\" target=\"_blank\" title=\"https://c3.nasa.gov/dashlink/static/media/other/ObservedFailures1.html\">https://c3.nasa.gov/dashlink/static/media/other/ObservedFailures1.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001866,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Observed Failures",
            "submessages": [],
            "timestamp": 1527115701,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/21e323ed2620c550c1f3497f5f5d33f6979c77a3?x=x&version=2",
            "client": "website",
            "content": "<p>hi</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001889,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "ashley.blewer@gmail.com",
            "sender_full_name": "Ashley Blewer (she) (SP2'18)",
            "sender_id": 111914,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1527115752,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Sometimes I find random things that I want to share, but I don't know which stream to put them in. I created this stream so that they will have a home. Feel free to add the things that you find as well!</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001901,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2728",
                    "emoji_name": "sparkles",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "sory.rawyer@gmail.com",
                        "full_name": "Rory Sawyer (he) (SP2'18)",
                        "id": 111920
                    },
                    "user_id": 111920
                },
                {
                    "emoji_code": "2728",
                    "emoji_name": "sparkles",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "ashley.blewer@gmail.com",
                        "full_name": "Ashley Blewer (she) (SP2'18)",
                        "id": 111914
                    },
                    "user_id": 111914
                }
            ],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1527115770,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/200183991cd15d8c08fc2f29cc78fa65e7b2f5ae?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>neat</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001909,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "sory.rawyer@gmail.com",
            "sender_full_name": "Rory Sawyer (he) (SP2'18)",
            "sender_id": 111920,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1527115778,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>A music video composed of satellite imagery:<br>\n<a href=\"https://vimeo.com/259989412\" target=\"_blank\" title=\"https://vimeo.com/259989412\">https://vimeo.com/259989412</a></p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001972,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Arena",
            "submessages": [],
            "timestamp": 1527115827,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/21e323ed2620c550c1f3497f5f5d33f6979c77a3?x=x&version=2",
            "client": "website",
            "content": "<p>happy to be here!</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001979,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "ashley.blewer@gmail.com",
            "sender_full_name": "Ashley Blewer (she) (SP2'18)",
            "sender_id": 111914,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1527115851,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/200183991cd15d8c08fc2f29cc78fa65e7b2f5ae?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p><a href=\"https://c3.nasa.gov/dashlink/static/media/other/ObservedFailures5.html\" target=\"_blank\" title=\"https://c3.nasa.gov/dashlink/static/media/other/ObservedFailures5.html\">https://c3.nasa.gov/dashlink/static/media/other/ObservedFailures5.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001986,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "sory.rawyer@gmail.com",
            "sender_full_name": "Rory Sawyer (he) (SP2'18)",
            "sender_id": 111920,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Observed Failures",
            "submessages": [],
            "timestamp": 1527115860,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>12 minute short about The Mauritania Railway:<br>\n<a href=\"https://vimeo.com/225516052\" target=\"_blank\" title=\"https://vimeo.com/225516052\">https://vimeo.com/225516052</a></p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127001989,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Arena",
            "submessages": [],
            "timestamp": 1527115864,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Yea, isn't that wild?</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127002000,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Observed Failures",
            "submessages": [],
            "timestamp": 1527115876,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/200183991cd15d8c08fc2f29cc78fa65e7b2f5ae?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>circuits: it can turn into anything, any time</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127002008,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "sory.rawyer@gmail.com",
            "sender_full_name": "Rory Sawyer (he) (SP2'18)",
            "sender_id": 111920,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Observed Failures",
            "submessages": [],
            "timestamp": 1527115895,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p>Electrical engineering should take the \"dismal science\" title away from economics.</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127002022,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Observed Failures",
            "submessages": [],
            "timestamp": 1527115918,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4d074af6cc341ef51b25bb2f738cdb11?d=identicon&version=1",
            "client": "website",
            "content": "<p><a class=\"stream\" data-stream-id=\"22932\" href=\"/#narrow/stream/22932-off-topic\">#off-topic</a> meets this need for me</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127003963,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "vaibhavsagar@gmail.com",
            "sender_full_name": "Vaibhav Sagar (he) (F1'16)",
            "sender_id": 100041,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1527119136,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4d074af6cc341ef51b25bb2f738cdb11?d=identicon&version=1",
            "client": "website",
            "content": "<p>Remember that time the Australian Army tried to fight a bunch of emus and lost? <a href=\"https://en.wikipedia.org/wiki/Emu_War\" target=\"_blank\" title=\"https://en.wikipedia.org/wiki/Emu_War\">https://en.wikipedia.org/wiki/Emu_War</a></p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127004026,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f426",
                    "emoji_name": "bird",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "casey@rodarmor.com",
                        "full_name": "Casey Rodarmor (SP2'18)",
                        "id": 6935
                    },
                    "user_id": 6935
                }
            ],
            "recipient_id": 147289,
            "sender_email": "vaibhavsagar@gmail.com",
            "sender_full_name": "Vaibhav Sagar (he) (F1'16)",
            "sender_id": 100041,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "The Great Emu War",
            "submessages": [],
            "timestamp": 1527119238,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/49093b3a95ef503c3792e0c507f07ffb3f04e115?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>neat</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127006743,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f419",
                    "emoji_name": "octopus",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "stevenli42@gmail.com",
                        "full_name": "Steven Li (he) (SP2'18)",
                        "id": 112084
                    },
                    "user_id": 112084
                }
            ],
            "recipient_id": 147289,
            "sender_email": "erin.kimberly.shaw@gmail.com",
            "sender_full_name": "Erin Shaw (she) (SP1'18)",
            "sender_id": 109160,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1527124228,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>i joined this stream and was thinking of something to post, weirdly enough it was this exact same video</p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127041642,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Arena",
            "submessages": [],
            "timestamp": 1527185940,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>related: <a href=\"https://lines.chromeexperiments.com\" target=\"_blank\" title=\"https://lines.chromeexperiments.com\">https://lines.chromeexperiments.com</a></p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127041658,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Arena",
            "submessages": [],
            "timestamp": 1527185964,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p><a href=\"https://vimeo.com/77330591\" target=\"_blank\" title=\"https://vimeo.com/77330591\">https://vimeo.com/77330591</a></p>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127041670,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Arena",
            "submessages": [],
            "timestamp": 1527185993,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>oldie but goodie <a href=\"https://www.youtube.com/watch?v=wO61D9x6lNY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=wO61D9x6lNY\">https://www.youtube.com/watch?v=wO61D9x6lNY</a></p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"wO61D9x6lNY\" href=\"https://www.youtube.com/watch?v=wO61D9x6lNY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=wO61D9x6lNY\"><img src=\"https://i.ytimg.com/vi/wO61D9x6lNY/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 127041744,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "sphere eversion",
            "submessages": [],
            "timestamp": 1527186059,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"https://en.wikipedia.org/wiki/IBM_System_i#Instruction_set\" target=\"_blank\" title=\"https://en.wikipedia.org/wiki/IBM_System_i#Instruction_set\">https://en.wikipedia.org/wiki/IBM_System_i#Instruction_set</a></p>\n<blockquote>\n<p>Unlike some other virtual-machine architectures in which the virtual instructions are interpreted at run time, TIMI instructions are never interpreted. They constitute an intermediate compile time step and are translated into the processor's instruction set as the final compilation step. The TIMI instructions are stored within the final program object, in addition to the executable machine instructions. This is how application objects compiled on one processor family (e.g., the original CISC AS/400 48-bit processors) could be moved to a new processor (e.g., PowerPC 64-bit) without re-compilation. An application saved from the older 48-bit platform can simply be restored onto the new 64-bit platform where the operating system discards the old machine instructions and re-translates the TIMI instructions into 64-bit instructions for the new processor.</p>\n</blockquote>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 150717729,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "IBM System I Instruction Set",
            "submessages": [],
            "timestamp": 1543744486,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/423a5327ed896db2dfd052de561709d0e6ae2689?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.youtube.com/watch?v=FXZJ6jrpIKU\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FXZJ6jrpIKU\">https://www.youtube.com/watch?v=FXZJ6jrpIKU</a></p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"FXZJ6jrpIKU\" href=\"https://www.youtube.com/watch?v=FXZJ6jrpIKU\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FXZJ6jrpIKU\"><img src=\"https://i.ytimg.com/vi/FXZJ6jrpIKU/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "neat",
            "flags": [
                "read",
                "historical"
            ],
            "id": 150825244,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 147289,
            "sender_email": "casey@rodarmor.com",
            "sender_full_name": "Casey Rodarmor (SP2'18)",
            "sender_id": 6935,
            "sender_realm_str": "recurse",
            "stream_id": 124692,
            "subject": "Blessed Motherboard Schematic Review / Unintentional ASMR",
            "submessages": [],
            "timestamp": 1543901668,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
