{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"101929\" href=\"/#narrow/stream/Neuroscience\">#Neuroscience</a>.</p>\n<p><strong>Description</strong>: For any and all discussion around brains, biotech involving brains, and machine learning + brains.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929691,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 101929,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1501274252,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>hey guys, sorry if I subscribed you and you're not a fan of neuroscience!  I copied over some of the subscribers to related streams like Biotech &amp; Machine Learning</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929739,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "ormatt@outlook.com",
                        "full_name": "Or Mattatia (SP2'17)",
                        "id": 100918
                    },
                    "user_id": 100918
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "andrew@mrdrozdov.com",
                        "full_name": "Andrew Drozdov (S2'16)",
                        "id": 7630
                    },
                    "user_id": 7630
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "dleonardotn@gmail.com",
                        "full_name": "Leo Torres (he) (SP2'16)",
                        "id": 9247
                    },
                    "user_id": 9247
                }
            ],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1501274314,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>feel free to unsubscribe, we wont be offended</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929741,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1501274325,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>There's an amazing conference every year that's a cross-over between neuroscience research and coding, it's called CodeNeuro.  It's free and I highly recommend going if you get the chance! <a href=\"http://codeneuro.org\" target=\"_blank\" title=\"http://codeneuro.org\">http://codeneuro.org</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929763,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "codeneuro",
            "submessages": [],
            "timestamp": 1501274372,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>I went two years ago and learned more about Neuroscience in three days than I thought was possible.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929769,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "codeneuro",
            "submessages": [],
            "timestamp": 1501274391,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>State of the art ML and neuro research was also presented by several top labs, and there were talks by the head of the photo ML team at Google that works on the Nexus cameras.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929837,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "codeneuro",
            "submessages": [],
            "timestamp": 1501274441,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>if you know any good online courses for neuro, post 'em here!</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929991,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "online courses",
            "submessages": [],
            "timestamp": 1501274724,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>I really like this one: <a href=\"https://www.coursera.org/learn/drugs-and-brain\" target=\"_blank\" title=\"https://www.coursera.org/learn/drugs-and-brain\">https://www.coursera.org/learn/drugs-and-brain</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113929993,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "dabbagh.aos@gmail.com",
                        "full_name": "Aos Dabbagh (S2'17)",
                        "id": 101320
                    },
                    "user_id": 101320
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "ad@lamarque.fr",
                        "full_name": "Adrien Lamarque (they/he) (S1'16)",
                        "id": 9335
                    },
                    "user_id": 9335
                }
            ],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "online courses",
            "submessages": [],
            "timestamp": 1501274731,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>A friend of mine and <span class=\"user-mention\" data-user-email=\"mcaoxol@gmail.com\" data-user-id=\"6177\">@Max McCrea (W1'15)</span>'s did a study at McGill on the detrimental effects of adolescent amphetamine (aka adderall) use:<br>\n<a href=\"https://www.reddit.com/r/DrugNerds/comments/4qsjok/amphetamine_in_adolescence_disrupts_development/\" target=\"_blank\" title=\"https://www.reddit.com/r/DrugNerds/comments/4qsjok/amphetamine_in_adolescence_disrupts_development/\">https://www.reddit.com/r/DrugNerds/comments/4qsjok/amphetamine_in_adolescence_disrupts_development/</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113930070,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "dabbagh.aos@gmail.com",
                        "full_name": "Aos Dabbagh (S2'17)",
                        "id": 101320
                    },
                    "user_id": 101320
                }
            ],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501274875,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>the paper: <a href=\"http://www.nature.com/npp/journal/v40/n5/full/npp2014287a.html\" target=\"_blank\" title=\"http://www.nature.com/npp/journal/v40/n5/full/npp2014287a.html\">Amphetamine in Adolescence Disrupts the Development of Medial Prefrontal Cortex Dopamine Connectivity in a dcc-Dependent Manner</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113930114,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501274897,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>Not sure how I feel about this, as a person with bad ADHD who requires amphetamines to function and couldn't tolerate Ritalin</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932502,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279101,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>this research only applies to adolescent use, not adult</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932505,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279132,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>iirc the bad effects on learning ability taper off after age 25</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932511,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279146,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>Yeah but before the age of 25 I was repeatedly homeless because I couldn't (still can't) do paperwork.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932552,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279205,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>Was it better for me to have gone through the trauma of having no roof over my head/eating out of dumpsters while preserving my learning ability, or losing a little learning ability and never having been homeless</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932561,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279232,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>It's interesting and useful to quantify these things like long-term effects of psychoactive med use, but that's not the first link I would have posted to a stream about neuroscience and CS</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932598,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279322,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>probably not, but there's a whole spectrum of kids with cases not as severe</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932621,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279325,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>I hear you. Unfortunately undermedication is an endemic issue for the neurodivergent community, especially in the cases of scheduled prescriptions or when the neurodivergent person is woman-aligned/high melanin. This is veering into subtle ism territory and I'm doing my best to call that out while acknowledging that the science is interesting and useful</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932639,
            "is_me_message": false,
            "last_edit_timestamp": 1501280128,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279413,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>it was just the most recent neuro paper I read, if you have some better ones please do share  :D</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932640,
            "is_me_message": false,
            "last_edit_timestamp": 1501279425,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279416,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>When one raises a panic about overmedicated wealthy white boys, it harms access to necessary medication for those who aren't considered worth it in the first place.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932687,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279497,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>ok thats a good point</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932704,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rosenzweig.ea@gmail.com",
                        "full_name": "Elizabeth Rosenzweig (she) (S2'17)",
                        "id": 101481
                    },
                    "user_id": 101481
                }
            ],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279519,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>I think it's not reason to withhold sharing research like this though.  In fact I think it's ideal for discussions like this which make people aware that undermedication is an issue ( I didn't know it was, and I think I'm better off now that I know it's sensitive to some people).</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932767,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279632,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>and it's great for people who see this link to know that there's good reason to keep prescribing amphets <strong>despite</strong> research like this</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932773,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279667,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>Yeah! I'm always happy to have discussions. It was just like \"oh no, I like neuroscience, but I'm feeling unwelcome within two minutes of starting to engage with the stream\"</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932775,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279669,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>Ah, ok, thanks for pointing that out in a nice way :)</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932815,
            "is_me_message": false,
            "last_edit_timestamp": 1501279718,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279684,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>Even if I hadn't pointed it out in a nice way, I would still have been valid in objecting</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932824,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279733,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>But yes, I've been through about eight years of therapy at this point and one of my primary traumas was being forced to be a peacemaker, so I'm a lot better at keeping a cool head than some of my compatriots</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932836,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279802,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>Sure, I was trying to say I appreciate your points, and I thank you for using the RC rules to call me out.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932880,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2764",
                    "emoji_name": "heart",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rosenzweig.ea@gmail.com",
                        "full_name": "Elizabeth Rosenzweig (she) (S2'17)",
                        "id": 101481
                    },
                    "user_id": 101481
                }
            ],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279805,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>Can you post anything from the ML and neuro conference you attended? I'd love to see the kinds of things you learned there</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932902,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279902,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>Yeah actually I'm working on a blog post summarzing stuff I learned, although it's now 2 years overdue haha, and I cant promise that I'll finish it soon.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932948,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279945,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>I'll post some of the links first, and the post once I finish it later.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932951,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279956,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>Cool I look forward to checking those out <img alt=\":smiling_face_with_sunglasses:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/unicode/1f60e.png\" title=\"smiling face with sunglasses\"></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932964,
            "is_me_message": false,
            "last_edit_timestamp": 1501280005,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "amphetamines to kids",
            "submessages": [],
            "timestamp": 1501279991,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p><a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22612281\" target=\"_blank\" title=\"http://www.ncbi.nlm.nih.gov/pubmed/22612281\">http://www.ncbi.nlm.nih.gov/pubmed/22612281</a> <span class=\"user-mention\" data-user-email=\"rosenzweig.ea@gmail.com\" data-user-id=\"101481\">@Elizabeth Rosenzweig (S2'17)</span></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932967,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "visual cortex research",
            "submessages": [],
            "timestamp": 1501279999,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>Check out this guy's wiring diagrams of the visual areas: </p>\n<p><a href=\"http://redwood.berkeley.edu/bruno/\" target=\"_blank\" title=\"http://redwood.berkeley.edu/bruno/\">http://redwood.berkeley.edu/bruno/</a> <br>\nSpecifically: <br>\n    VSS 2015 keynote, \"Vision in Brains and Machines\" slides, references<br>\n    \"Do V1 Neurons Have Receptive Fields?\" slides</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113932972,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "visual cortex research",
            "submessages": [],
            "timestamp": 1501280035,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p><a href=\"http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0003046\" target=\"_blank\" title=\"http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0003046\">http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0003046</a> (slightly old)</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933014,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "visual cortex research",
            "submessages": [],
            "timestamp": 1501280057,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>!!!!</p>\n<p>good stuff!!!</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933015,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "visual cortex research",
            "submessages": [],
            "timestamp": 1501280060,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>I also have ~10 PDFs of pretty good papers, not sure if zulip will take them though</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933019,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "visual cortex research",
            "submessages": [],
            "timestamp": 1501280082,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d386ca9ceecb72eedf550e721095fb84e7c22df?x=x&version=2",
            "client": "website",
            "content": "<p>If not then a link to a public Google Drive/Dropbox/SpiderOak folder could work</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933093,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "recurse@sweeting.me",
                        "full_name": "Nick Sweeting (he) (S1'14)",
                        "id": 5883
                    },
                    "user_id": 5883
                }
            ],
            "recipient_id": 105811,
            "sender_email": "rosenzweig.ea@gmail.com",
            "sender_full_name": "Elizabeth Rosenzweig (she) (S2'17)",
            "sender_id": 101481,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "visual cortex research",
            "submessages": [],
            "timestamp": 1501280197,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p><a href=\"https://nicksweeting.com/d/visual_cortex/\" target=\"_blank\" title=\"https://nicksweeting.com/d/visual_cortex/\">https://nicksweeting.com/d/visual_cortex/</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933297,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "visual cortex research",
            "submessages": [],
            "timestamp": 1501280624,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>super cool research that found out that Ketamine <del>and MXE</del>'s lasting antidepressant effects come from a metabolite, not from the primary dissosciation-causing chemical: <a href=\"https://www.ncbi.nlm.nih.gov/pubmed/27144355\" target=\"_blank\" title=\"https://www.ncbi.nlm.nih.gov/pubmed/27144355\">https://www.ncbi.nlm.nih.gov/pubmed/27144355</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933406,
            "is_me_message": false,
            "last_edit_timestamp": 1501281021,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "dabbagh.aos@gmail.com",
                        "full_name": "Aos Dabbagh (S2'17)",
                        "id": 101320
                    },
                    "user_id": 101320
                }
            ],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "NMDA inhibitors",
            "submessages": [],
            "timestamp": 1501280770,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p><a href=\"http://www.nature.com/nature/journal/v546/n7659/full/nature22084.html?WT.feed_name=subjects_biological-sciences\" target=\"_blank\" title=\"http://www.nature.com/nature/journal/v546/n7659/full/nature22084.html?WT.feed_name=subjects_biological-sciences\">http://www.nature.com/nature/journal/v546/n7659/full/nature22084.html?WT.feed_name=subjects_biological-sciences</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933407,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "NMDA inhibitors",
            "submessages": [],
            "timestamp": 1501280789,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p><a href=\"https://en.wikipedia.org/wiki/Hydroxynorketamine\" target=\"_blank\" title=\"https://en.wikipedia.org/wiki/Hydroxynorketamine\">https://en.wikipedia.org/wiki/Hydroxynorketamine</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 113933411,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "NMDA inhibitors",
            "submessages": [],
            "timestamp": 1501280803,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>There's a really exciting book out about how brains work, \"Surfing Uncertainty\". A long review is at <a href=\"http://slatestarcodex.com/2017/09/05/book-review-surfing-uncertainty/\" target=\"_blank\" title=\"http://slatestarcodex.com/2017/09/05/book-review-surfing-uncertainty/\">http://slatestarcodex.com/2017/09/05/book-review-surfing-uncertainty/</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 119332725,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Surfing Uncertainty",
            "submessages": [],
            "timestamp": 1512429565,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>Cool conference happening in March: <a href=\"http://www.cosyne.org/c/index.php?title=Cosyne_18\" target=\"_blank\" title=\"http://www.cosyne.org/c/index.php?title=Cosyne_18\">Computational and Systems Neuroscience</a></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 119584517,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Cosyne 2018",
            "submessages": [],
            "timestamp": 1512939466,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<blockquote>\n<p>The annual Cosyne meeting provides an inclusive forum for the exchange of experimental and theoretical/computational approaches to problems in systems neuroscience.<br>\nTo encourage interdisciplinary interactions, the main meeting is arranged in a single track. A set of invited talks are selected by the Executive Committee and Organizing Committee, and additional talks and posters are selected by the Program Committee, based on submitted abstracts.<br>\nCosyne topics include (but are not limited to): neural coding, natural scene statistics, dendritic computation, neural basis of persistent activity, nonlinear receptive field mapping, representations of time and sequence, reward systems, decision-making, synaptic plasticity, map formation and plasticity, population coding, attention, and computation with spiking networks. Participants include pure experimentalists, pure theorists, and everything in between.</p>\n</blockquote>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 119584519,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Cosyne 2018",
            "submessages": [],
            "timestamp": 1512939473,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>super expensive unfortunatley, but it looks worth it if you're working in the space</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 119584558,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Cosyne 2018",
            "submessages": [],
            "timestamp": 1512939524,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p><a href=\"http://codeneuro.org\" target=\"_blank\" title=\"http://codeneuro.org\">codeneuro.org</a> was awesome and it looks like this could be similar</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 119584565,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Cosyne 2018",
            "submessages": [],
            "timestamp": 1512939551,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"mcaoxol@gmail.com\" data-user-id=\"6177\">@Max McCrea (W1'15)</span> ^</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 119584567,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Cosyne 2018",
            "submessages": [],
            "timestamp": 1512939569,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8d9ed5f596714f4f3946f0896c9247b7686db1f6?x=x&version=4",
            "client": "website",
            "content": "<p>Yoshua Bengio was a speaker at the 2017 one</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 119584616,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "recurse@sweeting.me",
            "sender_full_name": "Nick Sweeting (he) (S1'14)",
            "sender_id": 5883,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Cosyne 2018",
            "submessages": [],
            "timestamp": 1512939616,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p><a href=\"http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005268\" target=\"_blank\" title=\"http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005268\">http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005268</a></p>\n<p>Just ran across this - really interesting take on our approach to neuroscience - a study of applying neuroscience techniques to understanding a microprocessor.</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 126124499,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "thumbs_up",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "recurse@sweeting.me",
                        "full_name": "Nick Sweeting (he) (S1'14)",
                        "id": 5883
                    },
                    "user_id": 5883
                }
            ],
            "recipient_id": 105811,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Could a neuroscientist understand a microprocessor?",
            "submessages": [],
            "timestamp": 1525486500,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/47d545529e036682e7075910a2489214?d=identicon&version=1",
            "client": "website",
            "content": "<p>Great Read! Thanks <span class=\"user-mention\" data-user-id=\"101330\">@Wesley Aptekar-Cassels (F2'17)</span></p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 126143180,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "ondoheer@gmail.com",
            "sender_full_name": "Pedro Alejandro Baumann Cornejo (he) (W2'18)",
            "sender_id": 105145,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "Could a neuroscientist understand a microprocessor?",
            "submessages": [],
            "timestamp": 1525531730,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/72772603199ba79a1635578c419b06361d921199?x=x&version=1",
            "client": "website",
            "content": "<p>does anyone have resources on adhd specifically for programmers/this industry?  I\u2019m also interested in your favorite articles about the subject in general</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 151613844,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "tn.pablo@gmail.com",
            "sender_full_name": "Pablo Torres (W'14)",
            "sender_id": 4997,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "adhd",
            "submessages": [],
            "timestamp": 1544713970,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/da27a2081fcf44c802c1806cdb5bb881310dfe7c?x=x&version=5",
            "client": "website",
            "content": "<p>Are you looking for resources about ADHD in general or for dealing with ADHD?</p>",
            "content_type": "text/html",
            "display_recipient": "neuroscience",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154137967,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 105811,
            "sender_email": "ad@lamarque.fr",
            "sender_full_name": "Adrien Lamarque (they/he) (S1'16)",
            "sender_id": 9335,
            "sender_realm_str": "recurse",
            "stream_id": 101929,
            "subject": "adhd",
            "submessages": [],
            "timestamp": 1546367433,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
