{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/9fd9de59f964f6e3af477006ddd0116211347010?x=x&version=2",
            "client": "Internal",
            "content": "<p>Stream created by <span class=\"user-mention silent\" data-user-id=\"226525\">Alex Calderwood (he) (S2'19)</span>.</p>",
            "content_type": "text/html",
            "display_recipient": "nlp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171901031,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 352959,
            "sender_email": "notification-bot@zulip.com",
            "sender_full_name": "Notification Bot",
            "sender_id": 100006,
            "sender_realm_str": "zulipcore",
            "stream_id": 204967,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1564342272,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/faaabd4ba334cd73017e5e55a7891cc2?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I didn't see an NLP stream! Feel free to leave or invite others</p>",
            "content_type": "text/html",
            "display_recipient": "nlp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171901101,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 352959,
            "sender_email": "alexander.d.calderwood@gmail.com",
            "sender_full_name": "Alex Calderwood (he/they) (S2'19)",
            "sender_id": 226525,
            "sender_realm_str": "recurse",
            "stream_id": 204967,
            "subject": "New Stream",
            "submessages": [],
            "timestamp": 1564342317,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/fb56b59547d4bdab81957ad5b62321da2ed54ab6?x=x&version=2",
            "client": "website",
            "content": "<p>there is a nlp stream <a class=\"stream\" data-stream-id=\"27684\" href=\"/#narrow/stream/27684-natural-language-processing\">#natural language processing</a> . I'd recommend you delete this one so there's less confusion. <span class=\"user-mention\" data-user-id=\"226525\">@Alex Calderwood (he) (S2'19)</span></p>",
            "content_type": "text/html",
            "display_recipient": "nlp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175704057,
            "is_me_message": false,
            "last_edit_timestamp": 1568471958,
            "reactions": [],
            "recipient_id": 352959,
            "sender_email": "jennyxing27@gmail.com",
            "sender_full_name": "Jenny Xing (S1'19)",
            "sender_id": 221839,
            "sender_realm_str": "recurse",
            "stream_id": 204967,
            "subject": "New Stream",
            "submessages": [],
            "timestamp": 1568471948,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/faaabd4ba334cd73017e5e55a7891cc2?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Ah. Thanks</p>",
            "content_type": "text/html",
            "display_recipient": "nlp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 175704119,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 352959,
            "sender_email": "alexander.d.calderwood@gmail.com",
            "sender_full_name": "Alex Calderwood (he/they) (S2'19)",
            "sender_id": 226525,
            "sender_realm_str": "recurse",
            "stream_id": 204967,
            "subject": "New Stream",
            "submessages": [],
            "timestamp": 1568472024,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
