{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"114816\" href=\"/#narrow/stream/114816-owg\">#owg</a>.</p>\n<p><strong>Description</strong>: Occult Working Group</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682317,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 114816,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1520993127,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>@all did I forget anyone?</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682363,
            "is_me_message": false,
            "last_edit_timestamp": 1520996022,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993171,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>also please invite others</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682365,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993185,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"105710\">@Bryan Chu (W2'18)</span> now you are over here</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682369,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993203,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"5866\">@Michael Arntzenius (SP1'18)</span> I think you said maybe at one point</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682379,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993253,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"100801\">@Naomi Saphra (SP2'17)</span> it'll be at your house so i should invite you</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682384,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993266,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>it turns out that this might collide with Passover</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682425,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993321,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>which is unfortunate</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682431,
            "is_me_message": false,
            "last_edit_timestamp": 1521428682,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993341,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>Dang I want to change the name of this topic</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682439,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993371,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>So the discussion is whether this will happen on the 24th or the 31st</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682560,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993581,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>Or perhaps on the Fridays prior to that</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682567,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520993589,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"103187\">@nicole leffel (SP1'18)</span> i summon thee</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123682906,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1520994254,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9d14ecfbfce9dea2c4f4b482d09344bea0fcd20e?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>hellooo</p>\n<p>should we get a doodle going? Sat 31 is best for me :) may also be able to do Fri 23</p>\n<p>for the record tho, i'm a lil wary of summoning generally. i could be convinced tho</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123721448,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "nicole.leffel@gmail.com",
            "sender_full_name": "nicole leffel (they) (SP1'18)",
            "sender_id": 103187,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1521061449,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6026a80c57f6d1d949cee04bcd1ad817?d=identicon&version=1",
            "client": "website",
            "content": "<p>hi all, I have some preference for not the 31st, since that's the second night of Passover, but also, if that's best for everyone else I can just decide what's more important to me.</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123722041,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "tiburona@gmail.com",
            "sender_full_name": "Katie Surrence (she) (W2'18)",
            "sender_id": 105443,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521062420,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b08b367b726fe19144e009125698285f7b7c0d2d?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>31 is probably not a good date -- my whole family might be away at a second night seder,  and having a large group over while they're not even around might be asking a lot even from my ridiculously hospitable parents :P</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123799720,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "n.saphra@ed.ac.uk",
            "sender_full_name": "Naomi Saphra (m3'18)",
            "sender_id": 100801,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521212473,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>here is the doodle</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123898556,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521428859,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>@all Please fill out your favorite time for Just Hanging Out In The Woods And Playing With Bear The Dog, or JHOITWAPWBTD for short: <a href=\"https://doodle.com/poll/cz5maryg5zshzqa9\" target=\"_blank\" title=\"https://doodle.com/poll/cz5maryg5zshzqa9\">https://doodle.com/poll/cz5maryg5zshzqa9</a></p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123898598,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521428932,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"*\">@all</span> ok this should ping. I think this is going to end up being just like, actually normal Nice Day Hiking.</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123898606,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "thumbs_up",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "nicole.leffel@gmail.com",
                        "full_name": "nicole leffel (they) (SP1'18)",
                        "id": 103187
                    },
                    "user_id": 103187
                }
            ],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521428989,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "ZulipMobile",
            "content": "<p>Dang, this might not work out until May</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123963118,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521552555,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c4e6637707ff62601f3dd21ec7626095?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"8478\">@Jacob Kozak (W1'17)</span>  the doodle is not loading for me :( it just endlessly displays a loading screen</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123974560,
            "is_me_message": false,
            "last_edit_timestamp": 1521569419,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "daekharel@gmail.com",
            "sender_full_name": "Michael 'rntz' Arntzenius (he) (S2'20)",
            "sender_id": 5866,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521569396,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c4e6637707ff62601f3dd21ec7626095?d=identicon&version=1",
            "client": "website",
            "content": "<p>jeez, it loaded after like 5 minutes. what the hell is up with doodle. and it managed to open a popup? argh.</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123974713,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "daekharel@gmail.com",
            "sender_full_name": "Michael 'rntz' Arntzenius (he) (S2'20)",
            "sender_id": 5866,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521569634,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "ZulipMobile",
            "content": "<p><span class=\"user-mention\" data-user-id=\"*\">@all</span> Good news and bad news: I found an apartment in the city! Bad news: I\u2019m moving in April 1st, so THIS WEEKEND is the only viable time in the near future.</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 123991221,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521598458,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "ZulipMobile",
            "content": "<p><span class=\"user-mention\" data-user-id=\"5866\">@Michael Arntzenius (SP1'18)</span> <span class=\"user-mention\" data-user-id=\"*\">@all</span> So this is indeed happening but it will have to be TOMORROW Saturday (or sunday if that is better for people)</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124130065,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521845667,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d78ab1df3a0ad57e48ac2f39be4af853ddb1db17?x=x&version=3",
            "client": "ZulipElectron",
            "content": "<p>What's the approximate time frame?</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124130596,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "logan.williams@alum.mit.edu",
            "sender_full_name": "Logan Williams (he) (W2'18)",
            "sender_id": 105229,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521846784,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d78ab1df3a0ad57e48ac2f39be4af853ddb1db17?x=x&version=3",
            "client": "ZulipElectron",
            "content": "<p>(I think I probably have too many commitments this weekend to make it work, but I'm asking anyway)</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124130600,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "logan.williams@alum.mit.edu",
            "sender_full_name": "Logan Williams (he) (W2'18)",
            "sender_id": 105229,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521846798,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c4e6637707ff62601f3dd21ec7626095?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"8478\">@Jacob Kozak (W1'17)</span> I am interested, but yeah, whenabouts would this happen? How does getting there work?</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124130717,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "daekharel@gmail.com",
            "sender_full_name": "Michael 'rntz' Arntzenius (he) (S2'20)",
            "sender_id": 5866,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521847041,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "ZulipMobile",
            "content": "<p>The metronorth from grand central to irvington. It costs $12-20 for a round trip ticket and the ride is about 40 minutes. I put the start time as 12pm and I figure we\u2019ll hang out a bit, walk around in the woods, play some board games or something, and then people will go home.</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124130834,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521847242,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "ZulipMobile",
            "content": "<p>There\u2019s not enough people to do a ritual but we can still hang out at the altar.</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124130843,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521847269,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "ZulipMobile",
            "content": "<p>If people are going to come tomorrow, please 1. Let me know before 12pm and 2. Try to travel together so we can pick you up from the train at the same time</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124135939,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521858495,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/c4e6637707ff62601f3dd21ec7626095?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"8478\">@Jacob Kozak (W1'17)</span> I'll come! Dunno whether anyone else is, though. I'll try to arrive at Irvington around noon.</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124136108,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "daekharel@gmail.com",
            "sender_full_name": "Michael 'rntz' Arntzenius (he) (S2'20)",
            "sender_id": 5866,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521858916,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "ZulipMobile",
            "content": "<p><span class=\"user-mention\" data-user-id=\"105229\">@Logan Williams (W2'18)</span> you still down?</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124136154,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521859031,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d78ab1df3a0ad57e48ac2f39be4af853ddb1db17?x=x&version=3",
            "client": "ZulipMobile",
            "content": "<p>can't make it tomorrow...</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124136194,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f61e",
                    "emoji_name": "disappointed",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jkozak@fmail.co.uk",
                        "full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
                        "id": 8478
                    },
                    "user_id": 8478
                }
            ],
            "recipient_id": 129863,
            "sender_email": "logan.williams@alum.mit.edu",
            "sender_full_name": "Logan Williams (he) (W2'18)",
            "sender_id": 105229,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521859132,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>I'm going to try to still figure out if we can do something April 1st since that date worked for so many people. Maybe instead we can do a housewarming at my new apartment which is only 20 minutes walking distance from RC! :D</p>",
            "content_type": "text/html",
            "display_recipient": "owg",
            "flags": [
                "read",
                "historical"
            ],
            "id": 124152722,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 129863,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 114816,
            "subject": "Planning a normal ceremony",
            "submessages": [],
            "timestamp": 1521901417,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
