{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"180459\" href=\"/#narrow/stream/180459-philosophy\">#philosophy</a>.</p>\n<p><strong>Description</strong>: Philosophical discussions, especially around the nature of consciousness and the brain.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154764568,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 180459,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1547074630,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>(Copied thread over from the consciousness channel, which is used for a different purpose.)</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154764854,
            "is_me_message": false,
            "last_edit_timestamp": 1547074907,
            "reactions": [
                {
                    "emoji_code": "1f44b",
                    "emoji_name": "wave",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "justin.c.kao@gmail.com",
                        "full_name": "Justin Kao (he) (W1'18)",
                        "id": 134205
                    },
                    "user_id": 134205
                }
            ],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547074849,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>If you're interested in reading more about predictive processing, <a href=\"https://slatestarcodex.com/2017/09/05/book-review-surfing-uncertainty/\" target=\"_blank\" title=\"https://slatestarcodex.com/2017/09/05/book-review-surfing-uncertainty/\">this blog post</a> is a great place to start!</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154764859,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547074854,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Also, <a href=\"https://en.wikipedia.org/wiki/Asch_conformity_experiments#Attitudes_of_responders_conforming_on_one_or_more_trials\" target=\"_blank\" title=\"https://en.wikipedia.org/wiki/Asch_conformity_experiments#Attitudes_of_responders_conforming_on_one_or_more_trials\">this section of the Wikipedia article</a> discusses what conforming participants in the Asch conformity experiments experienced.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154764875,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547074878,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>A topic I'm interested in - the \"explanatory gap\" <a href=\"https://plato.stanford.edu/entries/consciousness/#ExpGap\" target=\"_blank\" title=\"https://plato.stanford.edu/entries/consciousness/#ExpGap\">https://plato.stanford.edu/entries/consciousness/#ExpGap</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154765029,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547075021,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>also a cool new paper on virtual reality - <a href=\"http://consc.net/papers/virtual.pdf\" target=\"_blank\" title=\"http://consc.net/papers/virtual.pdf\">http://consc.net/papers/virtual.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154765097,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547075060,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>on why cognitive science and neuroscience have failed to give us an answer about why we have conscious experience - <a href=\"http://consc.net/papers/facing.html\" target=\"_blank\" title=\"http://consc.net/papers/facing.html\">http://consc.net/papers/facing.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154765255,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547075241,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>Here's a good paper on the Attention Schema Theory, which was apparently published as part of a larger compendium on consciousness called Illusionism: <a href=\"/user_uploads/13/lG38bbCucwts8QZmlQeG_Ibf/2016_Consciousness-Engineered.pdf\" target=\"_blank\" title=\"2016_Consciousness-Engineered.pdf\">2016_Consciousness-Engineered.pdf</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154768451,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547079222,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>Does anyone else have papers that they'd be interested in reading and talking about as a group? We were thinking that we could vote tomorrow or Friday on one to talk about for the first half (or so) of next week.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154768759,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547079527,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Margot mentioned the Sleeping Beauty Problem in the last meeting, and I've found it super interesting to think about!  A good introduction is <a href=\"https://en.wikipedia.org/wiki/Sleeping_Beauty_problem\" target=\"_blank\" title=\"https://en.wikipedia.org/wiki/Sleeping_Beauty_problem\">the Wikipedia article</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154892791,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "sleeping beauty problem",
            "submessages": [],
            "timestamp": 1547179790,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>If you want to read more about it after that, I liked <a href=\"https://www.princeton.edu/~adame/papers/sleeping/sleeping.html\" target=\"_blank\" title=\"https://www.princeton.edu/~adame/papers/sleeping/sleeping.html\">this paper by Adam Elga</a>, who argues for the thirder position.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154892852,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "sleeping beauty problem",
            "submessages": [],
            "timestamp": 1547179916,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>I also really liked <a href=\"https://ac.els-cdn.com/S0888613X09001285/1-s2.0-S0888613X09001285-main.pdf?_tid=7974afa0-ec3c-4b82-ba1d-3aea7bf9917b&amp;acdnat=1547180122_69ae3ebc359f7ce0f17dca370e8fc8c6\" target=\"_blank\" title=\"https://ac.els-cdn.com/S0888613X09001285/1-s2.0-S0888613X09001285-main.pdf?_tid=7974afa0-ec3c-4b82-ba1d-3aea7bf9917b&amp;acdnat=1547180122_69ae3ebc359f7ce0f17dca370e8fc8c6\">this paper by Mika\u00ebl Cozic</a>, who makes a case for the exciting double-halfer position.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154892909,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "sleeping beauty problem",
            "submessages": [],
            "timestamp": 1547180005,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/95eb11b4d11f06cdb3001ff6e17d64de5f38bb28?x=x&version=12",
            "client": "website",
            "content": "<p>If you prefer a video, I really liked this overview by Julia Galef =)</p>\n<p><a href=\"https://www.youtube.com/watch?v=zL52lG6aNIY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=zL52lG6aNIY\">https://www.youtube.com/watch?v=zL52lG6aNIY</a></p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"zL52lG6aNIY\" href=\"https://www.youtube.com/watch?v=zL52lG6aNIY\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=zL52lG6aNIY\"><img src=\"https://i.ytimg.com/vi/zL52lG6aNIY/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154893110,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "anja.kefala@gmail.com",
            "sender_full_name": "Anja Boskovic (SP1'17)",
            "sender_id": 100514,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "sleeping beauty problem",
            "submessages": [],
            "timestamp": 1547180320,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>Does this group meet every Wednesday? I have several books and papers on my computer that I would like to share/discuss. How would you all feel about setting up a google drive or something similar in order to easily share consciousness-related pdfs with the group?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154999112,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547326075,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"134181\">@Douglas Lerner (W1'18)</span> Yes, we'll meet again on Wednesday. I'm just planning on posting PDFs to this stream but if you wanted to set up a repository of everything that would probably be better for organization</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155107125,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1547492396,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"*\">@all</span>  Poll: what should we read and talk about Wednesday? We've got some papers about consciousness and a few about a logic problem (Sleeping Beauty problem) proposed. Use the corresponding animal emoji to vote for which you want!</p>\n<p><a href=\"https://plato.stanford.edu/entries/consciousness/#ExpQueHowConExi\" target=\"_blank\" title=\"https://plato.stanford.edu/entries/consciousness/#ExpQueHowConExi\">Stanford Encyclopedia of Philosophy, \"Consciousness\", ch 5: How Can Consciousness Exist / Explanatory Gap</a> <span class=\"emoji emoji-1f435\" title=\"monkey face\">:monkey_face:</span></p>\n<p><a href=\"http://consc.net/papers/virtual.pdf\" target=\"_blank\" title=\"http://consc.net/papers/virtual.pdf\">\"The Virtual and the Real\"</a> <span class=\"emoji emoji-1f43a\" title=\"wolf\">:wolf:</span></p>\n<p><a href=\"http://consc.net/papers/facing.html\" target=\"_blank\" title=\"http://consc.net/papers/facing.html\">\"Facing Up to the Problem of Consciousness\"</a> <span class=\"emoji emoji-1f405\" title=\"tiger\">:tiger:</span> </p>\n<p><a href=\"user_uploads/13/lG38bbCucwts8QZmlQeG_Ibf/2016_Consciousness-Engineered.pdf\" target=\"_blank\" title=\"user_uploads/13/lG38bbCucwts8QZmlQeG_Ibf/2016_Consciousness-Engineered.pdf\">\"Consciousness Engineered\"</a> <span class=\"emoji emoji-1f42e\" title=\"calf\">:calf:</span></p>\n<p><a href=\"https://www.princeton.edu/~adame/papers/sleeping/sleeping.html\" target=\"_blank\" title=\"https://www.princeton.edu/~adame/papers/sleeping/sleeping.html\">\"Self-locating belief and the Sleeping Beauty problem\"</a> <span class=\"emoji emoji-1f417\" title=\"boar\">:boar:</span></p>\n<p><a href=\"https://www.sciencedirect.com/science/article/pii/S0888613X09001285\" target=\"_blank\" title=\"https://www.sciencedirect.com/science/article/pii/S0888613X09001285\">\"Imaging and Sleeping Beauty: A case for double-halfers\"</a> <span class=\"emoji emoji-1f42b\" title=\"camel\">:camel:</span></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155115288,
            "is_me_message": false,
            "last_edit_timestamp": 1547498975,
            "reactions": [
                {
                    "emoji_code": "1f405",
                    "emoji_name": "tiger",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jeremy.fine.hartman@gmail.com",
                        "full_name": "Jeremy Hartman (he) (W1'18)",
                        "id": 136998
                    },
                    "user_id": 136998
                },
                {
                    "emoji_code": "1f43a",
                    "emoji_name": "wolf",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "meredith@paom.com",
                        "full_name": "Meredith Finkelstein (W2'19)",
                        "id": 198453
                    },
                    "user_id": 198453
                },
                {
                    "emoji_code": "1f43a",
                    "emoji_name": "wolf",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "galiciera@gmail.com",
                        "full_name": "Mari Galicer (she) (W2'19)",
                        "id": 198446
                    },
                    "user_id": 198446
                },
                {
                    "emoji_code": "1f405",
                    "emoji_name": "tiger",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rowan.copley@gmail.com",
                        "full_name": "Rowan Copley (he) (W1'18)",
                        "id": 134191
                    },
                    "user_id": 134191
                }
            ],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547498577,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"*\">@all</span> hey everyone, don't forget to vote! I'll count up how many we have tomorrow at lunch time and make a post</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155135173,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547514290,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"*\">@all</span> it was a tie so after flipping a coin (insert Sleeping Beauty joke here) decided we'll read \"The Virtual and the Real\"! I'm going to put it down for 4:30 tomorrow unless anyone objects.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155202284,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1271",
                    "emoji_name": "coin",
                    "reaction_type": "realm_emoji",
                    "user": {
                        "email": "marmotmcmahon@gmail.com",
                        "full_name": "Margot Mcmahon (she) (W1'18)",
                        "id": 134178
                    },
                    "user_id": 134178
                },
                {
                    "emoji_code": "1f4a4",
                    "emoji_name": "zzz",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "marmotmcmahon@gmail.com",
                        "full_name": "Margot Mcmahon (she) (W1'18)",
                        "id": 134178
                    },
                    "user_id": 134178
                },
                {
                    "emoji_code": "1f478",
                    "emoji_name": "princess",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "marmotmcmahon@gmail.com",
                        "full_name": "Margot Mcmahon (she) (W1'18)",
                        "id": 134178
                    },
                    "user_id": 134178
                }
            ],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547584752,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e163537cd1a596369636913991f46a37?d=identicon&version=1",
            "client": "website",
            "content": "<p>does earlier work for others?  like 3pm or anytime before?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155202776,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "jeremy.fine.hartman@gmail.com",
            "sender_full_name": "Jeremy Hartman (he) (W1'18)",
            "sender_id": 136998,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547585144,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I'd like to go to the Terraform workshop from 2:30 - 3:30. I'm ok doing it at 1:30 but 4:30 would give more people a chance to read the paper last minute ;)</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155203315,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547585600,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e163537cd1a596369636913991f46a37?d=identicon&version=1",
            "client": "website",
            "content": "<p>3:30 or 3:45 after the terraform workshop maybe?  I could do 4:30, but would need to leave a early <span class=\"emoji emoji-1f642\" title=\"slight smile\">:slight_smile:</span></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155203752,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "jeremy.fine.hartman@gmail.com",
            "sender_full_name": "Jeremy Hartman (he) (W1'18)",
            "sender_id": 136998,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547585976,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>That seems good to me. I'll put it on the calendar in a bit unless someone else objects</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155203902,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jeremy.fine.hartman@gmail.com",
                        "full_name": "Jeremy Hartman (he) (W1'18)",
                        "id": 136998
                    },
                    "user_id": 136998
                }
            ],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547586079,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I'm sick and won't be able to make it today :/</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155265297,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547655106,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Oh no! I hope you feel better soon :(</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155270864,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547659276,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e163537cd1a596369636913991f46a37?d=identicon&version=1",
            "client": "website",
            "content": "<p>feel better rowan! <span class=\"emoji emoji-1f912\" title=\"sick\">:sick:</span></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155273316,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "jeremy.fine.hartman@gmail.com",
            "sender_full_name": "Jeremy Hartman (he) (W1'18)",
            "sender_id": 136998,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547661308,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>happening now in Turing!</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155285626,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547670623,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "website",
            "content": "<p>:( see you all next week - I was terraforming</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155287062,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547671783,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>hello everyone! please post any papers you're interested in reading for next week. some guidelines: short-ish, accessible writing + concepts, related to philosophy of mind, consciousness, tech, etc. It seems like there's some interest in reading something cog-sci related next session.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155365468,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547756176,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/BfsIT4SnyBSzg8NDD3pmNFZP/Theories-and-models-of-consciousness-in-neuroscience.pdf\" target=\"_blank\" title=\"Theories-and-models-of-consciousness-in-neuroscience.pdf\">Theories-and-models-of-consciousness-in-neuroscience.pdf</a> </p>\n<p><a href=\"/user_uploads/13/tj5MI3x_vH5qiZDS8P3foxqG/conceptual-blending.pdf\" target=\"_blank\" title=\"conceptual-blending.pdf\">conceptual-blending.pdf</a> </p>\n<p><a href=\"/user_uploads/13/Q_4d-GutgSfE-iASkKXGv-W5/The-thalamus-gateway-to-the-mind.pdf\" target=\"_blank\" title=\"The-thalamus-gateway-to-the-mind.pdf\">The-thalamus-gateway-to-the-mind.pdf</a></p>\n<p><a href=\"/user_uploads/13/lwLFfBRdC81VW8YJu2Az4aUa/What-is-the-function-of-the-claustrum.pdf\" target=\"_blank\" title=\"What-is-the-function-of-the-claustrum.pdf\">What-is-the-function-of-the-claustrum.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155366096,
            "is_me_message": false,
            "last_edit_timestamp": 1547756740,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547756712,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/26OLsZ7kU-ySWVV53iUUANOa/A-thalamic-reticular-networking-model-of-consciousness.pdf\" target=\"_blank\" title=\"A-thalamic-reticular-networking-model-of-consciousness.pdf\">A-thalamic-reticular-networking-model-of-consciousness.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155366188,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547756788,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>I've uploaded a few papers discussing: general neurological theories of consciousness, theories of consciousness based around the role of the thalamus, and the theory of conceptual blending (my personal theory is that the thalamus is a conceptual blender). Let me know if you find them interesting and/or confusing.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 155366364,
            "is_me_message": false,
            "last_edit_timestamp": 1547757043,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "meredith@paom.com",
                        "full_name": "Meredith Finkelstein (W2'19)",
                        "id": 198453
                    },
                    "user_id": 198453
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "galiciera@gmail.com",
                        "full_name": "Mari Galicer (she) (W2'19)",
                        "id": 198446
                    },
                    "user_id": 198446
                }
            ],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547756956,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>If you read and understand all of these papers and interpret them correctly, you will possibly understand both why the brain produces consciousness and how to create general artificial intelligence.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156335791,
            "is_me_message": false,
            "last_edit_timestamp": 1547773960,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1547773901,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I'm still interested in reading <a href=\"user_uploads/13/lG38bbCucwts8QZmlQeG_Ibf/2016_Consciousness-Engineered.pdf\" target=\"_blank\" title=\"user_uploads/13/lG38bbCucwts8QZmlQeG_Ibf/2016_Consciousness-Engineered.pdf\">https://recurse.zulipchat.com/user_uploads/13/lG38bbCucwts8QZmlQeG_Ibf/2016_Consciousness-Engineered.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156637162,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "meredith@paom.com",
                        "full_name": "Meredith Finkelstein (W2'19)",
                        "id": 198453
                    },
                    "user_id": 198453
                }
            ],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548189334,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>Tho the first and last links Douglas posted look good</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156637309,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548189474,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Okay as benevolent dictator of the consciousness reading group I say we should read the first one Doug posted: <a href=\"http://users.sussex.ac.uk/~anils/Papers/BaarsSethElsevierEncyc.pdf\" target=\"_blank\" title=\"http://users.sussex.ac.uk/~anils/Papers/BaarsSethElsevierEncyc.pdf\">http://users.sussex.ac.uk/~anils/Papers/BaarsSethElsevierEncyc.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156644304,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548194796,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>I am also going to link to this in case folks want a wider view: <a href=\"https://plato.stanford.edu/entries/consciousness-neuroscience/\" target=\"_blank\" title=\"https://plato.stanford.edu/entries/consciousness-neuroscience/\">https://plato.stanford.edu/entries/consciousness-neuroscience/</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156644340,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548194824,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "website",
            "content": "<p>What is the final decision for tomorrow reading?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156646688,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548196723,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/66fb9787e52d39715ef7b1f5cc6cc75ca303bb9a?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p><span class=\"user-mention\" data-user-id=\"198453\">@Meredith Finkelstein (W2'19)</span> see above!</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156655787,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jeremy.fine.hartman@gmail.com",
                        "full_name": "Jeremy Hartman (he) (W1'18)",
                        "id": 136998
                    },
                    "user_id": 136998
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rowan.copley@gmail.com",
                        "full_name": "Rowan Copley (he) (W1'18)",
                        "id": 134191
                    },
                    "user_id": 134191
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "meredith@paom.com",
                        "full_name": "Meredith Finkelstein (W2'19)",
                        "id": 198453
                    },
                    "user_id": 198453
                }
            ],
            "recipient_id": 284867,
            "sender_email": "galiciera@gmail.com",
            "sender_full_name": "Mari Galicer (she) (W2'19)",
            "sender_id": 198446,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548205992,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>List of every theory of consciousness: <a href=\"https://canonizer.com/topic/88-Theories-of-Consciousness/1\" target=\"_blank\" title=\"https://canonizer.com/topic/88-Theories-of-Consciousness/1\">https://canonizer.com/topic/88-Theories-of-Consciousness/1</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156727909,
            "is_me_message": false,
            "last_edit_timestamp": 1548527815,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548279902,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e163537cd1a596369636913991f46a37?d=identicon&version=1",
            "client": "website",
            "content": "<p>i am intiruged by \"coded ordered water\"  <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156803564,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "jeremy.fine.hartman@gmail.com",
            "sender_full_name": "Jeremy Hartman (he) (W1'18)",
            "sender_id": 136998,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548361691,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>They link to studies, so it must be true.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156936227,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group 1/16",
            "submessages": [],
            "timestamp": 1548527880,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>Here is an excerpt from one of my favorite sci-fi novels, which depicts the process that a newly create AI being undergoes of gradually gaining consciousness and self-awareness: <a href=\"http://www.gregegan.net/DIASPORA/01/Orphanogenesis.html\" target=\"_blank\" title=\"http://www.gregegan.net/DIASPORA/01/Orphanogenesis.html\">http://www.gregegan.net/DIASPORA/01/Orphanogenesis.html</a></p>\n<p>Could anyone recommend other good consciousness-related fiction?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156936311,
            "is_me_message": false,
            "last_edit_timestamp": 1548528161,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548528002,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Have you read the lifecycle of software objects - really more about Eros and consciousness</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156937203,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548529520,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Have you read any Rudy Rucker I recall a conscious ice cream truck but it has been a while</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156937272,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548529626,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>I still love the foundation &amp; robot series - love the idea of a robot psychologist</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156937403,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548529909,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>Yes I've read  the lifecycle of software objects. Everything by Ted Chiang is good.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156942701,
            "is_me_message": false,
            "last_edit_timestamp": 1548539384,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548539293,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>I will check out Rudy Rucker.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 156942721,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548539354,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"134181\">@Douglas Lerner (W1'18)</span> Ted Chiang is my favorite scifi author, and yes everything he writes is good. <span class=\"user-mention\" data-user-id=\"198453\">@Meredith Finkelstein (W2'19)</span> I loved The Lifebox, the Seashell, and the Soul, what have you read by him?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157068825,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548720213,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"134181\">@Douglas Lerner (W1'18)</span> One consciousness related novel I really enjoyed is Ancillary Justice (and the whole trilogy). It's only partially about consciousness, but the main character used to be a ship's AI that embodied hundreds of human automatons simultaneously and is now down to just one body. Have you read Permutation City by Greg Egan? That's an exploration of consciousness as it could exist in a simulation.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157069526,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548721010,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>Man, now I'm wondering what other fiction is out there that's deeply motivated by an exploration of consciousness.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157069557,
            "is_me_message": false,
            "last_edit_timestamp": 1548721478,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548721045,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/60ad8feea8094a0a855dac429748135184293d81?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Ooh, I have two strong recommendations for fiction that touches on consciousness.<br>\n1) Axiomatic by Greg Egan -- a collection of philosophical sci-fi short stories, many touching on the nature of consciousness and identity.  I read it a few years ago and still think about it reasonably frequently.<br>\n2) Blindsight by Peter Watts -- a novel with consciousness as a central theme.  A super interesting read.  Not sure I can say much more without spoilers.  Has a references section with studies at the end.  The author has made <a href=\"https://rifters.com/real/Blindsight.htm\" target=\"_blank\" title=\"https://rifters.com/real/Blindsight.htm\">the novel freely available online</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157070611,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "ddf1991@gmail.com",
            "sender_full_name": "Day Fisher (they/she) (W2'19)",
            "sender_id": 198445,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548722375,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>I will check out your suggestions. I haven't read any of them yet.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157076312,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548730608,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "website",
            "content": "<p>Blindsight is great! I have never read Axiomatic - def want to check it out</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157076683,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548731246,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "website",
            "content": "<blockquote>\n<p><span class=\"user-mention silent\" data-user-id=\"134181\">@Douglas Lerner (W1'18)</span> Ted Chiang is my favorite scifi author, and yes everything he writes is good. <span class=\"user-mention silent\" data-user-id=\"198453\">@Meredith Finkelstein (W2'19)</span> I loved The Lifebox, the Seashell, and the Soul, what have you read by him?</p>\n</blockquote>\n<p>I have not read Lifebox, the Seashell, and the Soul - want to check that out</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157076737,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness related fiction",
            "submessages": [],
            "timestamp": 1548731306,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "website",
            "content": "<p>lets do this again - does anyone have any good papers on networked consciousness (e.g., microbiome/mycelium etc)</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157602870,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1549369971,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a8755809612b3b2e2b30b65bd71786d8?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>I feel odd resurrecting this Zulip stream which has been in hibernation for over a year. But, here goes!</p>\n<p>There's a nice philosophy podcast with a big back catalog called Partially Examined Life. This recent episode on Simone Weil, a philosopher I had never heard of prior, I found pretty fascinating especially for programmers and Recurse Center folks.</p>\n<p><a href=\"https://pca.st/episode/46ef86e6-36a9-45db-a263-e278b150b2a4\">https://pca.st/episode/46ef86e6-36a9-45db-a263-e278b150b2a4</a></p>\n<p>It was surprisingly timely/relevant to a conversation I recently had with a friend about the \"psychology of work\". (In fact, at one point, the group in the podcast concrerely discusses the idea of a business manager who is formerly an individually contributor, who mechanizes his business, moves up and up in the \"abstraction\" of all aspects of the business operations, and then rather than being fulfilled in the end, finds himself with no creative work to do. This is eerily personal for me. <span aria-label=\"grinning face with smiling eyes\" class=\"emoji emoji-1f601\" role=\"img\" title=\"grinning face with smiling eyes\">:grinning_face_with_smiling_eyes:</span>)</p>\n<p>I also think it's a nice conversation because it explains, without explicitly referencing it, why programming is such a satisfying creative activity, even if automation of labor is ultimately dehumanizing to laborers unless the automation is \"total\" or \"'complete\".</p>\n<p>Finally, it relates the idea of flow and creativity to the concept of individual &amp; human liberty, a connection that had never really occurred to me before.</p>\n<p>Enjoy! (p.s. one can find the essay they discuss online in PDF form, buried in a much longer book, with careful Googling)</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 209940119,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "andrew.montalenti@gmail.com",
            "sender_full_name": "Andrew Montalenti (he) (m7'19)",
            "sender_id": 247727,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Simone Weil",
            "submessages": [],
            "timestamp": 1600016851,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4334a59d02d66348593e46832ca73ae071f23b5e?x=x&version=7",
            "client": "ZulipElectron",
            "content": "<p>(deleted)</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210797919,
            "is_me_message": false,
            "last_edit_timestamp": 1600723884,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "victoria@unconventionaldata.ai",
            "sender_full_name": "Victoria Levchenko (she) (W2'19)",
            "sender_id": 198466,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Simone Weil",
            "submessages": [],
            "timestamp": 1600721341,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4334a59d02d66348593e46832ca73ae071f23b5e?x=x&version=7",
            "client": "ZulipElectron",
            "content": "<p>Were you able to understand the podcast without reading the chapter?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210797940,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "victoria@unconventionaldata.ai",
            "sender_full_name": "Victoria Levchenko (she) (W2'19)",
            "sender_id": 198466,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Simone Weil",
            "submessages": [],
            "timestamp": 1600721359,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a8755809612b3b2e2b30b65bd71786d8?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>I was! I did end up tracking down an ebook/PDF that contained the chapter discussed. I'll see if I can extract out a copy for you and share here when I do. But I enjoyed the podcast muchly without having read it.</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210816822,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f419",
                    "emoji_name": "octopus",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "victoria@unconventionaldata.ai",
                        "full_name": "Victoria Levchenko (she) (W2'19)",
                        "id": 198466
                    },
                    "user_id": 198466
                }
            ],
            "recipient_id": 284867,
            "sender_email": "andrew.montalenti@gmail.com",
            "sender_full_name": "Andrew Montalenti (he) (m7'19)",
            "sender_id": 247727,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Simone Weil",
            "submessages": [],
            "timestamp": 1600734410,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/17cc9e2bc66dfd8fa02944eb84c6c1aba10235e0?x=x&version=2",
            "client": "website",
            "content": "<p>It's a few years old but I found a blog post with what seems to be a pretty solid argument for why we don't live in a simulation, or if we do live in a simulation, why it's likely not far removed from a base reality: <a href=\"http://bach.ai/Do-we-live-in-a-simulation/\">http://bach.ai/Do-we-live-in-a-simulation/</a></p>\n<p>Do you find his argument convincing?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210888393,
            "is_me_message": false,
            "last_edit_timestamp": 1600802016,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "doug012310@yahoo.com",
            "sender_full_name": "Douglas Lerner (he) (W1'18)",
            "sender_id": 134181,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Why we don't live in a simulation",
            "submessages": [],
            "timestamp": 1600788931,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a8755809612b3b2e2b30b65bd71786d8?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"198466\">@Victoria Levchenko (she) (W2'19)</span> Here's the essay in PDF form, BTW.</p>\n<p><a href=\"/user_uploads/13/U1bpTwe6HtPAESIS_87uQMIr/simone-weil-theoretical-picture-of-a-free-society.pdf\">simone-weil-theoretical-picture-of-a-free-society.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210944349,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "andrew.montalenti@gmail.com",
            "sender_full_name": "Andrew Montalenti (he) (m7'19)",
            "sender_id": 247727,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Simone Weil",
            "submessages": [],
            "timestamp": 1600817954,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4334a59d02d66348593e46832ca73ae071f23b5e?x=x&version=7",
            "client": "ZulipElectron",
            "content": "<p>\\o/ wooooo! Thank you :) Gonna try to read it tonight</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210944981,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "victoria@unconventionaldata.ai",
            "sender_full_name": "Victoria Levchenko (she) (W2'19)",
            "sender_id": 198466,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Simone Weil",
            "submessages": [],
            "timestamp": 1600818594,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15f1d27c330f216d0d1722411c39ef187d2b5943?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Anyone looking at integral studies (gebser, Murray, Wilber and others on the woo spectrum) ?</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 212342203,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "meredith@paom.com",
            "sender_full_name": "Meredith Finkelstein (W2'19)",
            "sender_id": 198453,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1601924296,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/3f6bef626649c46b4cc3fd9f67c151a19170da5e?x=x&version=21",
            "client": "website",
            "content": "<p>i'm into it</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 213091462,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 284867,
            "sender_email": "jkozak@fmail.co.uk",
            "sender_full_name": "Jake \u26e4 Prozvyshe (they) (W1'17)",
            "sender_id": 8478,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "consciousness reading group",
            "submessages": [],
            "timestamp": 1602540880,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/89dca067bdf75771429ee72733022d0d?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.edx.org/course/minds-and-machines\">MITx - 24.09x</a> starts Nov 17th!</p>",
            "content_type": "text/html",
            "display_recipient": "philosophy",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216338498,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2763",
                    "emoji_name": "heart_exclamation",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "victoria@unconventionaldata.ai",
                        "full_name": "Victoria Levchenko (she) (W2'19)",
                        "id": 198466
                    },
                    "user_id": 198466
                }
            ],
            "recipient_id": 284867,
            "sender_email": "zarak@hey.com",
            "sender_full_name": "Zarak Mahmud (he) (F2'20)",
            "sender_id": 341780,
            "sender_realm_str": "recurse",
            "stream_id": 180459,
            "subject": "Minds and Machines",
            "submessages": [],
            "timestamp": 1605097387,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
