{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>I don't know this deserves a whole stream</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454821,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "hi",
            "submessages": [],
            "timestamp": 1393261900,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/0fc5778d097c3ce0d085a4e5d2115fdf89a5ce55?x=x&version=1",
            "client": "website",
            "content": "<p>I think it definitely deserves a stream if we get one :P</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454833,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "mindy.preston@yomimono.org",
            "sender_full_name": "Mindy Preston (she) (F2'19)",
            "sender_id": 4994,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "hi",
            "submessages": [],
            "timestamp": 1393261920,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>exactly.</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454860,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "hi",
            "submessages": [],
            "timestamp": 1393261925,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>I'm being optimistic</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454870,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "hi",
            "submessages": [],
            "timestamp": 1393261928,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>I thinka  great idae that would get us a Tango</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454884,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393261942,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>would be</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454886,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393261943,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>assisted environmental and object identification and maneuverability queues for the blind</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454892,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393261957,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>*cues</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454894,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393261962,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>(too much programming haha)</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454896,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393261970,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>Ooh. I worked on <a href=\"http://www.knfbreader.com/products-classic.php\" target=\"_blank\" title=\"http://www.knfbreader.com/products-classic.php\">this product</a> 10 years ago</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17454912,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393261990,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Inspired by <a href=\"http://www.medgadget.com/2012/05/medgadget-interviews-eric-berdinis-and-jeff-kiske-creators-of-the-kinecthesia-haptic-belt-for-blind-people.html\" target=\"_blank\" title=\"http://www.medgadget.com/2012/05/medgadget-interviews-eric-berdinis-and-jeff-kiske-creators-of-the-kinecthesia-haptic-belt-for-blind-people.html\">http://www.medgadget.com/2012/05/medgadget-interviews-eric-berdinis-and-jeff-kiske-creators-of-the-kinecthesia-haptic-belt-for-blind-people.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455122,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262233,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Some kids at my school did this</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455128,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262238,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>I think something liek that wuodl be absolutely lifechanging for some people</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455134,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262245,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>can you imagine?</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455140,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262250,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>like, evenf or ergular people</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455142,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262254,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>if you dont know what a device isand youe ximaine it with the phoen and then serach google for that object profile</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455149,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262266,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>beyond image search</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455151,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262267,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>actual dimesntion search</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455153,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262269,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>or you dont know what screw size somethign is</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455155,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262273,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>or like ikea pieces</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455159,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262275,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>i thinka p erfect use case for this at the small level would be getting a whole list of all the ikea pieces and sizes so thaty ou couldn simply scan ap iece from an ikea thing and it willt ell ylou what it is</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455205,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262294,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>i bet i kea would be willing to donate that kind of stuff ot usf or us to be able to examine it and put it into thes system and train it</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455212,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262308,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>anyone else interested in this?</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17455690,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393262810,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5f2bd39fb8e08a6434c2e8fd32669de1?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'd love to get involved!</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17456017,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "patricia.j.estridge@gmail.com",
            "sender_full_name": "Patricia Estridge (W'14)",
            "sender_id": 5013,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1393263147,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5f2bd39fb8e08a6434c2e8fd32669de1?d=identicon&version=1",
            "client": "website",
            "content": "<p>oops, just posted to the wrong subject - this looks awesome, I'd love to get involved.</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17456123,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "patricia.j.estridge@gmail.com",
            "sender_full_name": "Patricia Estridge (W'14)",
            "sender_id": 5013,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393263278,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>do you like the idea i suggested or do you haev another noe/</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17456430,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393263670,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>one?</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17456433,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393263672,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5f2bd39fb8e08a6434c2e8fd32669de1?d=identicon&version=1",
            "client": "website",
            "content": "<p>I love your idea, sure I could come up with others, but I'm pretty sure they wouldn't be better!</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17464352,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "patricia.j.estridge@gmail.com",
            "sender_full_name": "Patricia Estridge (W'14)",
            "sender_id": 5013,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393273011,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Cool!  Would you be in for trying and goign for it?  And would you want to do the Ikea thing, or smoething more generalized, or something else?</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17465863,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393274729,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"patricia.j.estridge@gmail.com\">@Patricia Estridge (W'14)</span>  ^^</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17465873,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393274743,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5f2bd39fb8e08a6434c2e8fd32669de1?d=identicon&version=1",
            "client": "website",
            "content": "<p>Totally - Ikea would be cool, though we could probably start with any object at first?</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17468191,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "patricia.j.estridge@gmail.com",
            "sender_full_name": "Patricia Estridge (W'14)",
            "sender_id": 5013,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393277073,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>we could absolutely start with anythign, I just thought of Ikea as a nice standardized object</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17468810,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1393277730,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f80e82961fd40bbe816456cc26d427559d50f032?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"patricia.j.estridge@gmail.com\">@Patricia Estridge (W'14)</span> <span class=\"user-mention\" data-user-email=\"JJ@ebnj.net\">@J.J. (Joel) Fliegelman (W'14)</span> <span class=\"user-mention\" data-user-email=\"david@dalrymple.co\">@David Dalrymple (W'14)</span> I have one if you guys are still interested....</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38436190,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "mykolasmith@gmail.com",
            "sender_full_name": "Mykola Smith (SP2'15)",
            "sender_id": 7849,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1429629640,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5fc7d5d7b6d64132767d534055e319fc?d=identicon&version=1",
            "client": "website",
            "content": "<p>That's great!  Do you not need yours anymore?  Or is it RC's?</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38437555,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "JJ@ebnj.net",
            "sender_full_name": "J.J. (Joel) Fliegelman (W'14)",
            "sender_id": 5006,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1429631192,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f80e82961fd40bbe816456cc26d427559d50f032?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"JJ@ebnj.net\">@J.J. (Joel) Fliegelman (W'14)</span> Neither, I actively use it but am willing to loan it out to RCers that are interested in computer vision.</p>",
            "content_type": "text/html",
            "display_recipient": "project tango",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38721439,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 32021,
            "sender_email": "mykolasmith@gmail.com",
            "sender_full_name": "Mykola Smith (SP2'15)",
            "sender_id": 7849,
            "sender_realm_str": "recurse",
            "stream_id": 25217,
            "subject": "ideas",
            "submessages": [],
            "timestamp": 1430158541,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
