{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"https://gist.github.com/anfedorov/7330b4bb30fecd76e255\" target=\"_blank\" title=\"https://gist.github.com/anfedorov/7330b4bb30fecd76e255\">https://gist.github.com/anfedorov/7330b4bb30fecd76e255</a></p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43267443,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438268460,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>Prisoners in hats problem:</p>\n<p>N prisoners are notified that they will be playing a game tomorrow morning.<br>\nFirst they will stand in a circle and close their eyes.<br>\nHats of one of N colors will be put on their heads (hat colors may repeat).<br>\nThey will open their eyes and see the colors of everyone else's hat.<br>\nThey will close their eyes and simultaneously guess what their own hat color is.<br>\nIf any one of them guesses correctly, they all go free.<br>\nOtherwise they all die.</p>\n<p>The prisoners may work together to form a strategy beforehand.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43267455,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438268486,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/85dc0b246ada79f7d5c331440c5cb387?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Related:</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43268643,
            "is_me_message": false,
            "last_edit_timestamp": 1438270342,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "smitha.milli@gmail.com",
            "sender_full_name": "Smitha Milli (S2'15)",
            "sender_id": 8307,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438270334,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/85dc0b246ada79f7d5c331440c5cb387?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Each prisoner either wears a red or a blue hat.<br>\nThey are arranged in a line such that they can see the hats on all the prisoners in front of them.<br>\nStarting from the prisoner at the end, they say their own hat color in order<br>\nIf the prisoner gets it right, then they are set free, otherwise they are executed on the spot.<br>\nThe prisoners come up with a strategy that sacrifices at most one person, what is it?</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43268867,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "smitha.milli@gmail.com",
            "sender_full_name": "Smitha Milli (S2'15)",
            "sender_id": 8307,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438270581,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/85dc0b246ada79f7d5c331440c5cb387?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>(this one is much easier :P)</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43268874,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "smitha.milli@gmail.com",
            "sender_full_name": "Smitha Milli (S2'15)",
            "sender_id": 8307,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438270597,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>1. Can 77 slabs, each 3\u00d73x1, be packed into a 7\u00d79\u00d711 carton?</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43269287,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Blocks in boxes",
            "submessages": [],
            "timestamp": 1438271226,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>2. Can 6 slabs, each 2\u00d72\u00d71, be packed into a 3\u00d73\u00d73 carton?</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43269297,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Blocks in boxes",
            "submessages": [],
            "timestamp": 1438271259,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>Do you know the infinite version of that?<br>\nA countably infinite set of prisoners, say p1, p2, p3, \u2026 are lined up so that each prisoner can only see the (black or white) hats on the heads of the prisoners with a larger number; for example p5 can see p6, p7, p10000, etc. but not p1..p4.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43269522,
            "is_me_message": false,
            "last_edit_timestamp": 1438272446,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438271584,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>They can conspire beforehand, and work out a joint strategy, but not once the hats are revealed.  Moreover, prisoners cannot hear one another's guesses; they must all guess simultaneously.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43269539,
            "is_me_message": false,
            "last_edit_timestamp": 1438272457,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438271623,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>If all but a finite number of prisoners guess correctly, they all go free.   If an infinite number of prisoners are wrong, they all remain in prison.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43269580,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438271649,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>(For mathematicians only.)</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43269585,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438271659,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>\"on the heads of the prisoners with a larger number\"?</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43271187,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438274391,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4c0051e8b52b9030d03a079f19e461c474bf2b16?x=x&version=1",
            "client": "website",
            "content": "<p>so each prisoner can see the hats of a large, but finite, number of prisoners directly in front of them</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43271239,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "me@anfedorov.com",
            "sender_full_name": "Andrey Fedorov (S2'15)",
            "sender_id": 8323,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438274436,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>No, just the opposite.  Each prisoner can see the hats of all but a finite number of prisoners.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43275136,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438280036,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>Prisoner p1 can see everyone's hat.  p2 can see every hat except the one on p1.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43275176,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438280052,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>p1000 can see the infinite hats on p1001, p1002, p1003, \u2026 but not any of the 999 hats on p1\u2026p999.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 43275184,
            "is_me_message": false,
            "last_edit_timestamp": 1438280088,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "hats!",
            "submessages": [],
            "timestamp": 1438280078,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>The Mystery Hunt is this weekend!  Anyone else going?</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105684631,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484166199,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/04ca5a14273f759166bbbfc15e3e400910e7a053?x=x&version=1",
            "client": "website",
            "content": "<p>I think I am! (Still making last minute arrangements for a place to crash.) I'll be puzzling (pretty casually) with Death &amp; Mayhem.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105690849,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "jdherg@gmail.com",
            "sender_full_name": "John Hergenroeder (he) (SP2'15)",
            "sender_id": 7851,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484176610,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/04ca5a14273f759166bbbfc15e3e400910e7a053?x=x&version=1",
            "client": "website",
            "content": "<p>(If I don't hunt locally, I'll definitely do it remotely.)</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105690857,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "jdherg@gmail.com",
            "sender_full_name": "John Hergenroeder (he) (SP2'15)",
            "sender_id": 7851,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484176627,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8ef0cc9607b07f392f70560a43dbbb2d0efd6328?x=x&version=1",
            "client": "website",
            "content": "<p>Yep, hunting with Random Fish</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105721039,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "brian.kihoon.lee@gmail.com",
            "sender_full_name": "Brian Lee (F1'16)",
            "sender_id": 100043,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484236673,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "website",
            "content": "<p>Sweet, good luck.  I'm on Codex, I'll be on-site.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105721098,
            "is_me_message": false,
            "last_edit_timestamp": 1484236759,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484236740,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/04ca5a14273f759166bbbfc15e3e400910e7a053?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"nelhage@nelhage.com\">@Nelson Elhage</span>  ^</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105740865,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "jdherg@gmail.com",
            "sender_full_name": "John Hergenroeder (he) (SP2'15)",
            "sender_id": 7851,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484271035,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/04ca5a14273f759166bbbfc15e3e400910e7a053?x=x&version=1",
            "client": "website",
            "content": "<p>Wait actually let's bring back <a class=\"stream\" data-stream-id=\"32187\" href=\"/#narrow/stream/mysteryhunt\">#mysteryhunt</a> </p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105740873,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "jdherg@gmail.com",
            "sender_full_name": "John Hergenroeder (he) (SP2'15)",
            "sender_id": 7851,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484271106,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7d2ab014ebf55e99afffba1a3d92be8155754f0f?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"novalis@novalis.org\">@David Turner</span> is, according to a message in the git stream.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105787853,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "kamal@marhubi.com",
            "sender_full_name": "Kamal Marhubi (he) (m2'18)",
            "sender_id": 8090,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484363964,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7af0a4685e93e44ffcd2935fa31ff1c4?d=identicon&version=1",
            "client": "website",
            "content": "<p>oops, wrong stream!</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105787854,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "novalis@novalis.org",
            "sender_full_name": "David Turner",
            "sender_id": 8449,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484363977,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7af0a4685e93e44ffcd2935fa31ff1c4?d=identicon&version=1",
            "client": "website",
            "content": "<p>oh, no, right stream</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105787855,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "novalis@novalis.org",
            "sender_full_name": "David Turner",
            "sender_id": 8449,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484363986,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7af0a4685e93e44ffcd2935fa31ff1c4?d=identicon&version=1",
            "client": "website",
            "content": "<p>just forgot what I said</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 105787856,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "novalis@novalis.org",
            "sender_full_name": "David Turner",
            "sender_id": 8449,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "MIT Mystery Hunt",
            "submessages": [],
            "timestamp": 1484363989,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/95eb11b4d11f06cdb3001ff6e17d64de5f38bb28?x=x&version=12",
            "client": "website",
            "content": "<p>This is my first Zulip message........So I hope I do it right.<br>\nI recently read this article about the first setter for the Hindu crossword and it delighted me, so I thought I'd share.<br>\n<a href=\"http://www.crosswordunclued.com/2012/10/admiral-katari-hindu-crossword-setter.html\" target=\"_blank\" title=\"http://www.crosswordunclued.com/2012/10/admiral-katari-hindu-crossword-setter.html\">http://www.crosswordunclued.com/2012/10/admiral-katari-hindu-crossword-setter.html</a></p>\n<p>He made the crosswords by hand and there are some beautiful photos of his process. He made at least 1400 of them and was very particular about not repeating words and not having similar sounding clues.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 106953862,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "anja.kefala@gmail.com",
            "sender_full_name": "Anja Boskovic (SP1'17)",
            "sender_id": 100514,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Admiral Katari",
            "submessages": [],
            "timestamp": 1486683199,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7d2ab014ebf55e99afffba1a3d92be8155754f0f?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"anja.kefala@gmail.com\" data-user-id=\"100514\">@Anja Boskovic (SP1'17)</span>!! Hi!!</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 106957067,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f60a",
                    "emoji_name": "blush",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "anja.kefala@gmail.com",
                        "full_name": "Anja Boskovic (SP1'17)",
                        "id": 100514
                    },
                    "user_id": 100514
                }
            ],
            "recipient_id": 42371,
            "sender_email": "kamal@marhubi.com",
            "sender_full_name": "Kamal Marhubi (he) (m2'18)",
            "sender_id": 8090,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Admiral Katari",
            "submessages": [],
            "timestamp": 1486689355,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/95eb11b4d11f06cdb3001ff6e17d64de5f38bb28?x=x&version=12",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"husseinfarah93@gmail.com\" data-user-id=\"100449\">@Hussein Farah (W2'17)</span> wants to start a puzzle-of-the-day in RC. To aid that endeavour, I am going to share some of my favourite puzzle resources<br>\n<a href=\"https://tierneylab.blogs.nytimes.com/2009/05/18/monday-puzzle-the-amazing-obamas-card-trick/?_r=0\" target=\"_blank\" title=\"https://tierneylab.blogs.nytimes.com/2009/05/18/monday-puzzle-the-amazing-obamas-card-trick/?_r=0\">https://tierneylab.blogs.nytimes.com/2009/05/18/monday-puzzle-the-amazing-obamas-card-trick/?_r=0</a> --&gt; You have to scroll through though. There's no easy way to index into the puzzles.<br>\n<a href=\"https://wordplay.blogs.nytimes.com/2012/01/03/numberplay-2011-the-year-in-puzzles/?_r=0\" target=\"_blank\" title=\"https://wordplay.blogs.nytimes.com/2012/01/03/numberplay-2011-the-year-in-puzzles/?_r=0\">https://wordplay.blogs.nytimes.com/2012/01/03/numberplay-2011-the-year-in-puzzles/?_r=0</a> --&gt; For each year there's a \"Year in Puzzles\" compilation. 2011 is the earlier one.<br>\n<a href=\"https://www.futilitycloset.com/category/puzzles/page/85/\" target=\"_blank\" title=\"https://www.futilitycloset.com/category/puzzles/page/85/\">https://www.futilitycloset.com/category/puzzles/page/85/</a> --&gt; Easily indexable and searchable puzzles. Delightful blog in general.<br>\n<a href=\"http://puzzlebomb.co.uk/\" target=\"_blank\" title=\"http://puzzlebomb.co.uk/\">http://puzzlebomb.co.uk/</a><br>\n<a href=\"https://www.quantamagazine.org/tag/Insights-Puzzle/\" target=\"_blank\" title=\"https://www.quantamagazine.org/tag/Insights-Puzzle/\">https://www.quantamagazine.org/tag/Insights-Puzzle/</a><br>\n<a href=\"http://www.mathistopheles.co.uk/puzzles/\" target=\"_blank\" title=\"http://www.mathistopheles.co.uk/puzzles/\">http://www.mathistopheles.co.uk/puzzles/</a><br>\n<a href=\"https://fivethirtyeight.com/tag/the-riddler/\" target=\"_blank\" title=\"https://fivethirtyeight.com/tag/the-riddler/\">https://fivethirtyeight.com/tag/the-riddler/</a><br>\n<a href=\"https://www.janestreet.com/puzzles/archive/page/4/\" target=\"_blank\" title=\"https://www.janestreet.com/puzzles/archive/page/4/\">https://www.janestreet.com/puzzles/archive/page/4/</a><br>\nBONUS:<br>\nthis cryptic (<a href=\"http://www.daniellesucher.com/tag/puzzles/\" target=\"_blank\" title=\"http://www.daniellesucher.com/tag/puzzles/\">http://www.daniellesucher.com/tag/puzzles/</a>) was made by an RC alumn and I found it delightful to puzzle through. It's definitely my favourite cryptic. Even though I think in general crosswords may not be the most elegant for whiteboard posting, I think this one is very fun and we should make an exception : D.<br>\nAnd a git-themed cryptic crossword that I haven't solved yet: <a href=\"https://thorehusfeldt.net/2015/04/03/conflicting-git-merge-runs-for-several-minutes-35/\" target=\"_blank\" title=\"https://thorehusfeldt.net/2015/04/03/conflicting-git-merge-runs-for-several-minutes-35/\">https://thorehusfeldt.net/2015/04/03/conflicting-git-merge-runs-for-several-minutes-35/</a></p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107243193,
            "is_me_message": false,
            "last_edit_timestamp": 1487294413,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "anja.kefala@gmail.com",
            "sender_full_name": "Anja Boskovic (SP1'17)",
            "sender_id": 100514,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Puzzle Compilations",
            "submessages": [],
            "timestamp": 1487294326,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "ZulipAndroid",
            "content": "<p>Hah, I saw the URL to \"the amazing obamas card trick\" and it reminded me that I should share my favourite card trick but it's the same one.  :)</p>\n<p>The paper about it is one of my favorite CompSci papers ever:  <a href=\"http://people.brandeis.edu/~kleber/Papers/card.pdf\" target=\"_blank\" title=\"http://people.brandeis.edu/~kleber/Papers/card.pdf\">http://people.brandeis.edu/~kleber/Papers/card.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107243519,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Puzzle Compilations",
            "submessages": [],
            "timestamp": 1487295085,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/2de9901913d2f414b7b174d2c2c69a88?d=identicon&version=1",
            "client": "ZulipAndroid",
            "content": "<p>Or rather <a href=\"http://www.apprendre-en-ligne.net/crypto/magie/card.pdf\" target=\"_blank\" title=\"http://www.apprendre-en-ligne.net/crypto/magie/card.pdf\">http://www.apprendre-en-ligne.net/crypto/magie/card.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107243563,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "chris@printf.net",
            "sender_full_name": "Chris Ball (SP2'15)",
            "sender_id": 7857,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Puzzle Compilations",
            "submessages": [],
            "timestamp": 1487295144,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e5845e045f9bcd4c95b82b01366893ed8b219f00?x=x&version=1",
            "client": "website",
            "content": "<p>I love this guy's blog.  He's one of the people who reliably makes me say \u201cI wish I was that clever.\u201d <a href=\"http://puzzlezapper.com/blog/\" target=\"_blank\" title=\"http://puzzlezapper.com/blog/\">http://puzzlezapper.com/blog/</a></p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107282979,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "mjd@plover.com",
            "sender_full_name": "Mark Dominus (indifferent)",
            "sender_id": 7912,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Puzzle Compilations",
            "submessages": [],
            "timestamp": 1487377095,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/95eb11b4d11f06cdb3001ff6e17d64de5f38bb28?x=x&version=12",
            "client": "website",
            "content": "<p>Ooooooo!! Thank you for sharing Mark! I love recreational mathematics. &lt;3</p>\n<p>Oh my goodness. SOMEBODY WROTE A PAPER? I am full of delight. : D I a excited to read it.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107287119,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "anja.kefala@gmail.com",
            "sender_full_name": "Anja Boskovic (SP1'17)",
            "sender_id": 100514,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Puzzle Compilations",
            "submessages": [],
            "timestamp": 1487386086,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7d2ab014ebf55e99afffba1a3d92be8155754f0f?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"anja.kefala@gmail.com\" data-user-id=\"100514\">@Anja Boskovic (SP1'17)</span> there's a thing called <a href=\"http://www.puzzledpint.com/\" target=\"_blank\" title=\"http://www.puzzledpint.com/\">Puzzled Pint</a>. <span class=\"user-mention\" data-user-email=\"jdherg@gmail.com\" data-user-id=\"7851\">@John Hergenroeder (SP2'15)</span> went while I was at RC, not sure if he still does or not.</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107405627,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 42371,
            "sender_email": "kamal@marhubi.com",
            "sender_full_name": "Kamal Marhubi (he) (m2'18)",
            "sender_id": 8090,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Puzzle Compilations",
            "submessages": [],
            "timestamp": 1487660324,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/04ca5a14273f759166bbbfc15e3e400910e7a053?x=x&version=1",
            "client": "website",
            "content": "<p>I do! You can find us over in <a href=\"https://recurse.zulipchat.com/#narrow/stream/Social.20(New.20York)/topic/Puzzled.20Pint\" target=\"_blank\" title=\"https://recurse.zulipchat.com/#narrow/stream/Social.20(New.20York)/topic/Puzzled.20Pint\">https://recurse.zulipchat.com/#narrow/stream/Social.20(New.20York)/topic/Puzzled.20Pint</a> and the next one is \u03c0 day (March 14)</p>",
            "content_type": "text/html",
            "display_recipient": "puzzles",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107406038,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f37b",
                    "emoji_name": "beers",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "anja.kefala@gmail.com",
                        "full_name": "Anja Boskovic (SP1'17)",
                        "id": 100514
                    },
                    "user_id": 100514
                }
            ],
            "recipient_id": 42371,
            "sender_email": "jdherg@gmail.com",
            "sender_full_name": "John Hergenroeder (he) (SP2'15)",
            "sender_id": 7851,
            "sender_realm_str": "recurse",
            "stream_id": 27477,
            "subject": "Puzzle Compilations",
            "submessages": [],
            "timestamp": 1487661340,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
