{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/eec06302c81ec67af2c64dc9036d3c3bed15a7e3?x=x&version=1",
            "client": "website",
            "content": "<p>figured we could share our favorite regexp references, learning  and suff</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 26106049,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "steinkirch@gmail.com",
            "sender_full_name": "Marina Wahl (S2'14)",
            "sender_id": 6179,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "why not",
            "submessages": [],
            "timestamp": 1407784039,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/eec06302c81ec67af2c64dc9036d3c3bed15a7e3?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/Xkno1LOeAicsJDg4ThoEFkxT/love_regex.jpg\" target=\"_blank\" title=\"love_regex.jpg\">love_regex.jpg</a> </p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/Xkno1LOeAicsJDg4ThoEFkxT/love_regex.jpg\" target=\"_blank\" title=\"love_regex.jpg\"><img src=\"/user_uploads/13/Xkno1LOeAicsJDg4ThoEFkxT/love_regex.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 26106138,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "steinkirch@gmail.com",
            "sender_full_name": "Marina Wahl (S2'14)",
            "sender_id": 6179,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "why not",
            "submessages": [],
            "timestamp": 1407784165,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c55d5b0f6b48fe10eae3bd82fdc9ec479c66f7b7?x=x&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>Anyone want to help me puzzle through building a regex to match only words (<code>/\\b(w+)\\b/</code>) not surrounded by quotes?  </p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36043671,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "msteigerwalt@gmail.com",
            "sender_full_name": "Michelle Steigerwalt (she/her) (W2'17)",
            "sender_id": 7655,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425490362,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c55d5b0f6b48fe10eae3bd82fdc9ec479c66f7b7?x=x&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>(It's working with programatic keywords, so the \\w is sufficient to match words, since there will never be a valid apostrophe or anything in any of these keywords.)</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36043673,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "msteigerwalt@gmail.com",
            "sender_full_name": "Michelle Steigerwalt (she/her) (W2'17)",
            "sender_id": 7655,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425490366,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c55d5b0f6b48fe10eae3bd82fdc9ec479c66f7b7?x=x&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>I'm also building the entire string myself, so I don't really have to worry about edge cases.</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36043679,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "msteigerwalt@gmail.com",
            "sender_full_name": "Michelle Steigerwalt (she/her) (W2'17)",
            "sender_id": 7655,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425490377,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/d6cab6171548c32c373976c18a311520?d=identicon&version=1",
            "client": "website",
            "content": "<p>if your conditions is no quotes on either side, you can do /(?&lt;!')\\b(\\w+)\\b(?!')/</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36044146,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "moiseyev.nikita@gmail.com",
            "sender_full_name": "Nikita Moiseyev (W1'14)",
            "sender_id": 6922,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425491031,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/d6cab6171548c32c373976c18a311520?d=identicon&version=1",
            "client": "website",
            "content": "<p>if you want any words that aren't surrounded on both sides by quotes, then this might do: /(?&lt;!')\\b(\\w+)\\b|(?&lt;=')\\b(\\w+)\\b(?!')/</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36044458,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "moiseyev.nikita@gmail.com",
            "sender_full_name": "Nikita Moiseyev (W1'14)",
            "sender_id": 6922,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425491429,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c55d5b0f6b48fe10eae3bd82fdc9ec479c66f7b7?x=x&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>Look behinds aren't supported in JavaScript. :(  (Womp, womp.)</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36044570,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "msteigerwalt@gmail.com",
            "sender_full_name": "Michelle Steigerwalt (she/her) (W2'17)",
            "sender_id": 7655,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425491561,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/d6cab6171548c32c373976c18a311520?d=identicon&version=1",
            "client": "website",
            "content": "<p>that's solvable but the workaround is a lot of work</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36044617,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "moiseyev.nikita@gmail.com",
            "sender_full_name": "Nikita Moiseyev (W1'14)",
            "sender_id": 6922,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425491637,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/d6cab6171548c32c373976c18a311520?d=identicon&version=1",
            "client": "website",
            "content": "<p>basically, you'd need to match on a [^'], then backtrack through your own code by 1 character</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36044676,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "moiseyev.nikita@gmail.com",
            "sender_full_name": "Nikita Moiseyev (W1'14)",
            "sender_id": 6922,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425491669,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c55d5b0f6b48fe10eae3bd82fdc9ec479c66f7b7?x=x&version=1",
            "client": "desktop app Windows 0.4.4",
            "content": "<p>Yeah, I'll probably just create some secondary strings or something.</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 36044678,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "msteigerwalt@gmail.com",
            "sender_full_name": "Michelle Steigerwalt (she/her) (W2'17)",
            "sender_id": 7655,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Not Within Strings",
            "submessages": [],
            "timestamp": 1425491673,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/68ded0820264fbe7eb0a296144f8aa85?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm trying to capture text that is either the beginning or end of a quote. I tried the following on regexr: /\\b['\"][\\w]+|[\\w]+['\"]\\b/ but it's not working. If I eliminate the /b it works, but I want to distinguish between quotes and apostrophe's! Why doesn't this work? </p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41826510,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "sfrapoport@gmail.com",
            "sender_full_name": "Sophie Rapoport (S1'15)",
            "sender_id": 8074,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Capturing quotations",
            "submessages": [],
            "timestamp": 1435767043,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4726703a7f93ec4a8da91f62b1fe7ade?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"sfrapoport@gmail.com\">@Sophie Rapoport (S1'15)</span> could you post the inputs you're testing with and the results you expect?</p>",
            "content_type": "text/html",
            "display_recipient": "regexp",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42176343,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 35617,
            "sender_email": "mudit.ameta@gmail.com",
            "sender_full_name": "Mudit Ameta (he) (SP2'15)",
            "sender_id": 7865,
            "sender_realm_str": "recurse",
            "stream_id": 26028,
            "subject": "Capturing quotations",
            "submessages": [],
            "timestamp": 1436200041,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
