{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"146536\" href=\"/#narrow/stream/146536-retro-computer-lab\">#retro computer lab</a>.</p>\n<p><strong>Description</strong>: Coordinating the RC Retro Computer Lab</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136119885,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 146536,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1539963948,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>notes: <a href=\"https://docs.google.com/document/d/1i0Gjgx51sfuiqhKTToVx99sHAZXNPYQ-pGzoTalBzSQ/edit#heading=h.z0sysidrhz44\" target=\"_blank\" title=\"https://docs.google.com/document/d/1i0Gjgx51sfuiqhKTToVx99sHAZXNPYQ-pGzoTalBzSQ/edit#heading=h.z0sysidrhz44\">https://docs.google.com/document/d/1i0Gjgx51sfuiqhKTToVx99sHAZXNPYQ-pGzoTalBzSQ/edit#heading=h.z0sysidrhz44</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136120099,
            "is_me_message": false,
            "last_edit_timestamp": 1539964901,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "first meeting",
            "submessages": [],
            "timestamp": 1539964148,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's a spreadsheet for things we want to buy: <a href=\"https://docs.google.com/spreadsheets/d/1jLj0_pf_U2mzTPDufVWfTIvLCnn8o4q9TfMbM27B6wo/edit#gid=0\" target=\"_blank\" title=\"https://docs.google.com/spreadsheets/d/1jLj0_pf_U2mzTPDufVWfTIvLCnn8o4q9TfMbM27B6wo/edit#gid=0\">https://docs.google.com/spreadsheets/d/1jLj0_pf_U2mzTPDufVWfTIvLCnn8o4q9TfMbM27B6wo/edit#gid=0</a>. Please add to it.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136120903,
            "is_me_message": false,
            "last_edit_timestamp": 1539964948,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "first meeting",
            "submessages": [],
            "timestamp": 1539964938,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p><a href=\"https://www.lesecologycenter.org/programs/ewaste/reuse-store/\" target=\"_blank\" title=\"https://www.lesecologycenter.org/programs/ewaste/reuse-store/\">https://www.lesecologycenter.org/programs/ewaste/reuse-store/</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136121507,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "first meeting",
            "submessages": [],
            "timestamp": 1539965575,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Danilo thinks the rectifier diode might be the thing wrong with the analog board. He has extras. We're going to try replacing it before buying a new analog board (or new Mac Plus, which seems to be around the same price)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136121953,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "mac plus",
            "submessages": [],
            "timestamp": 1539966012,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's <span class=\"user-mention\" data-user-id=\"101701\">@Raph Levien (F1'17)</span>'s <a href=\"https://github.com/raphlinus/c2t/commits/prototype_23k\" target=\"_blank\" title=\"https://github.com/raphlinus/c2t/commits/prototype_23k\">fast Apple II audio code</a> and <a href=\"https://github.com/datajerk/c2t/issues/4\" target=\"_blank\" title=\"https://github.com/datajerk/c2t/issues/4\">a discussion about it</a>.</p>\n<p>Here's <span class=\"user-mention\" data-user-id=\"2132\">@Alex Clemmer (S'13)</span> and <span class=\"user-mention\" data-user-id=\"2124\">@Martin T\u00f6rnwall (S'13)</span>'s <a href=\"https://github.com/hausdorff/turtles\" target=\"_blank\" title=\"https://github.com/hausdorff/turtles\">Lisp interpreter</a> and <a href=\"https://github.com/hausdorff/apple2e-audio-transport\" target=\"_blank\" title=\"https://github.com/hausdorff/apple2e-audio-transport\">audio transfer library</a></p>\n<p>Raph, Alex, and Martin, we're starting a Retro Computer Lab, and I wanted people to see the stuff you had worked on. Feel free to unsubscribe from this stream if you'd like to.</p>\n<p>cc <span class=\"user-mention\" data-user-id=\"124995\">@Charlie Tran (F1'18)</span> <span class=\"user-mention\" data-user-id=\"130218\">@Adam Tigar (F2'18)</span> <span class=\"user-mention\" data-user-id=\"129929\">@Douglas Gordon (F2'18)</span></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136122877,
            "is_me_message": false,
            "last_edit_timestamp": 1539966991,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539966927,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"emoji emoji-1f62e\" title=\"open mouth\">:open_mouth:</span></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123358,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967338,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "website",
            "content": "<p>YAY!!!!!!!!!!!!!!!!!!</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123362,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967342,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "website",
            "content": "<p>What kind of retro computers??</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123380,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967363,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Will you have a Xerox Alto?????</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123385,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967369,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Right now we have a Macintosh Color Classic (working, with an SSD inside), Nick's Apple II, a broken Mac Plus (we're working on repairing or replacing it), a working iMac G4</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123728,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967616,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>and a TI 99 (missing a monitor)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123742,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967627,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'd love an Alto, and a PDP-11, but those probably aren't our next purchases <span class=\"emoji emoji-1f600\" title=\"grinning\">:grinning:</span></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123750,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967643,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"2132\">@Alex Clemmer (S'13)</span> ^</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123773,
            "is_me_message": false,
            "last_edit_timestamp": 1539967698,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539967680,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>cc <span class=\"user-mention\" data-user-id=\"6188\">@Jonathan Dahan (S'14)</span></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123843,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "first meeting",
            "submessages": [],
            "timestamp": 1539967732,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Forked from Apple II:</p>\n<p>We also want a LISP machine (Symbolics preferable <span class=\"emoji emoji-1f600\" title=\"grinning\">:grinning:</span>), and a Cray</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136123923,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1539967805,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"*\">@all</span> here are the next steps:</p>\n<ul>\n<li>Add things you think we should get to the <a href=\"https://docs.google.com/spreadsheets/d/1jLj0_pf_U2mzTPDufVWfTIvLCnn8o4q9TfMbM27B6wo/edit#gid=0\" target=\"_blank\" title=\"https://docs.google.com/spreadsheets/d/1jLj0_pf_U2mzTPDufVWfTIvLCnn8o4q9TfMbM27B6wo/edit#gid=0\">wishlist</a></li>\n<li><span class=\"user-mention\" data-user-id=\"125275\">@Danilo Campos (F1'18)</span> is going to be in next week to get the Mac Plus up and running. If we can't make it work, either we'll borrow <span class=\"user-mention\" data-user-id=\"6188\">@Jonathan Dahan (S'14)</span>'s or buy a new one on eBay.</li>\n<li>I'll order Localtalk network adapters for the Mac Plus and Color Classic</li>\n<li>We need to figure out a way to prioritize what we purchase. For now, I'll just do it, but longer term, it would be good to have a process. I'm going to prioritize purchasing things for the computers we already have.</li>\n<li><span class=\"user-mention\" data-user-id=\"6188\">@Jonathan Dahan (S'14)</span> is going to bring in a scsi2sd for the Mac Plus</li>\n<li><span class=\"user-mention\" data-user-id=\"111910\">@Brandon Liu (SP2'18)</span> is researching a monitor for the TI 99</li>\n</ul>\n<p>We should pick a time to meet next, once some of the parts have arrived. What works for all of you</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136124689,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1539968501,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/db3bb2e8cfa9c62e206a0fa100a024da6f6e41df?x=x&version=4",
            "client": "website",
            "content": "<p>(Ooops, should have posted in Apple II thread, will do that)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136126027,
            "is_me_message": false,
            "last_edit_timestamp": 1539969742,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "raph.levien@gmail.com",
            "sender_full_name": "Raph Levien (F1'17)",
            "sender_id": 101701,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1539969636,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/db3bb2e8cfa9c62e206a0fa100a024da6f6e41df?x=x&version=4",
            "client": "website",
            "content": "<p>Sounds like fun! Also don't forget <span class=\"user-mention\" data-user-id=\"811\">@Nick Bergson-Shilcock</span> 's <a href=\"https://github.com/nicholasbs/appletoo\" target=\"_blank\" title=\"https://github.com/nicholasbs/appletoo\">appletoo</a> project, which I hacked on a bit and is nice for 6502 fans. One project I could recommend is getting the <a href=\"https://github.com/Klaus2m5/6502_65C02_functional_tests\" target=\"_blank\" title=\"https://github.com/Klaus2m5/6502_65C02_functional_tests\">6502 functional tests</a> passing on it.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136126125,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "raph.levien@gmail.com",
            "sender_full_name": "Raph Levien (F1'17)",
            "sender_id": 101701,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539969747,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>:)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136131985,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539975620,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"810\">@David Albert</span> the Living Computer Museum here in Seattle allows you to request accounts that you can SSH into on the PDP-11</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136132042,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539975682,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "website",
            "content": "<p>It's sick.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136132048,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539975689,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4f5279e356a105513701942b5b6af05f?d=identicon&version=1",
            "client": "website",
            "content": "<p>No vim, no emacs, no anything. Just ed.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136132056,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "clemmer.alexander@gmail.com",
            "sender_full_name": "Alex Clemmer (S'13)",
            "sender_id": 2132,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539975697,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>That's so cool! I'm glad there's precedent for that. We'd like to support something similar for our old machines (have a modern SSH daemon that's terminated at the edge of our network, and then have telnet from there to the old computers)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136132122,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1539975746,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>We should get a VT100 and hook it up to <a href=\"https://github.com/recursecenter/wiki/wiki/Heap-Community-Cluster\" target=\"_blank\" title=\"https://github.com/recursecenter/wiki/wiki/Heap-Community-Cluster\">the cluster</a>. I've added it to the wishlist.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136133191,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "VT100",
            "submessages": [],
            "timestamp": 1539976990,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>oh, lispm... interested parties should check out fare's post on the subject if they haven't already: <a href=\"http://fare.tunes.org/LispM.html\" target=\"_blank\" title=\"http://fare.tunes.org/LispM.html\">http://fare.tunes.org/LispM.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136135760,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1539979874,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>dks was apparently still shipping machines and fulfilling maintenance agreements for the remnants of symbolics <a href=\"http://symbolics-dks.com/\" target=\"_blank\" title=\"http://symbolics-dks.com/\">http://symbolics-dks.com/</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136135774,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1539979915,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Looks interesting. Thanks for sharing. Excited to read.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136135955,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1539980098,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>If you want to allow outside access (like described in another thread) it might make sense to go the virtual route for this, booting a fresh world upon ssh connection, since lispm were designed to be single-user systems. The VLM code was released by someone a while back, I was trying to fix it up for a bit but never finished.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136136680,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1539980936,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"810\">@David Albert</span> These are perhaps less \"retro\" than \"niche\", but I have a (PowerPC) PowerBook laptop and an OLPC XO-1 that need a good home.  Do you want either of them?</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136152160,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540005705,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>So <span class=\"user-mention\" data-user-id=\"129939\">@Marina Inina (F2'18)</span> and I got the apple II working</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136152798,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1540006949,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>There are two small screws that need to be re-screwed in on the disk drive side of the cable</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136152799,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1540006975,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>(any flathead will do)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136152803,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1540006984,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>One of the disks has Woz's escape game, the other disk had some loading issues</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136152807,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1540007001,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"810\">@David Albert</span> is the apple a IIe?</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136152906,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1540007205,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>I believe it is</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136153060,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1540007594,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Unsure as of yet, but thank you for the offer :). Can you let me know what model the PowerBook is?</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136153061,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540007641,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"https://www.tindie.com/\" target=\"_blank\" title=\"https://www.tindie.com/\">https://www.tindie.com/</a> is a very good place for tools for interfacing with older machines as well is new hobbyist computers</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136178254,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540057735,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>With sellers like <a href=\"https://www.tindie.com/stores/tynemouthsw/\" target=\"_blank\" title=\"https://www.tindie.com/stores/tynemouthsw/\">https://www.tindie.com/stores/tynemouthsw/</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136178309,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540057805,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"https://www.tindie.com/stores/Semachthemonkey/\" target=\"_blank\" title=\"https://www.tindie.com/stores/Semachthemonkey/\">https://www.tindie.com/stores/Semachthemonkey/</a> for a modern z80 machine</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136178325,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f913",
                    "emoji_name": "nerd",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "marianne.bellotti@gmail.com",
                        "full_name": "Marianne Bellotti (she) (m1'18)",
                        "id": 105102
                    },
                    "user_id": 105102
                }
            ],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540057865,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>and <a href=\"https://www.tindie.com/stores/linc/\" target=\"_blank\" title=\"https://www.tindie.com/stores/linc/\">https://www.tindie.com/stores/linc/</a> and others</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136178394,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540058021,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"810\">@David Albert</span> It's <a href=\"https://everymac.com/systems/apple/powerbook_g4/specs/powerbook_g4_1.67_15_hr.html\" target=\"_blank\" title=\"https://everymac.com/systems/apple/powerbook_g4/specs/powerbook_g4_1.67_15_hr.html\">this one</a>.  <a href=\"https://lindseykuper.livejournal.com/309085.html\" target=\"_blank\" title=\"https://lindseykuper.livejournal.com/309085.html\">Here's the love letter I wrote to it in 2009.</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136248343,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540189876,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b4b9e2320f242abf40bf5391ee07269f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Cool thanks <span class=\"user-mention\" data-user-id=\"2170\">@Lindsey Kuper</span>! We'll pass for now, but I'll let you know if that changes.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136271920,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "dave@recurse.com",
            "sender_full_name": "David Albert (he)",
            "sender_id": 810,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540219456,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"810\">@David Albert</span> OK!  It's not going anywhere. :)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136314256,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540268451,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0d3a1755b1e2bb0552c4fbb42bd02ef0?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm going to bring in my first computer, a working TRS-80 Model I.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136371207,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "lindsey@composition.al",
                        "full_name": "Lindsey Kuper (she)",
                        "id": 2170
                    },
                    "user_id": 2170
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "raph.levien@gmail.com",
                        "full_name": "Raph Levien (F1'17)",
                        "id": 101701
                    },
                    "user_id": 101701
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "nick@recurse.com",
                        "full_name": "Nick Bergson-Shilcock (he)",
                        "id": 811
                    },
                    "user_id": 811
                }
            ],
            "recipient_id": 187614,
            "sender_email": "staceysern@gmail.com",
            "sender_full_name": "Stacey Sern (she) (m1'20)",
            "sender_id": 855,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "TRS-80",
            "submessages": [],
            "timestamp": 1540333196,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3f4785d95e43ecfb2f20d49e6ec824dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>I can't wait to see it!</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136371665,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "nick@recurse.com",
            "sender_full_name": "Nick Bergson-Shilcock (he)",
            "sender_id": 811,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "TRS-80",
            "submessages": [],
            "timestamp": 1540333772,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>I totally forgot to bring my hardware in, will aim for friday</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136425064,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540403096,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>The museum consultancy I write for ( <a href=\"https://smalldata.industries\" target=\"_blank\" title=\"https://smalldata.industries\">https://smalldata.industries</a> ) is interested in a field trip to visit the lab once we are comfortable showing it all off. Should we plan for another meeting this friday to keep things going?</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136425205,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "second meeting",
            "submessages": [],
            "timestamp": 1540403221,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/891c5d6bae21ab007ad7c3f1e766d79325be55e1?x=x&version=2",
            "client": "website",
            "content": "<p>I have an applewriter (printer) I can bring in friday if we want to play with that too</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136425218,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "recurse.zulipchat@jonathan.is",
            "sender_full_name": "Jonathan Dahan (S2'14)",
            "sender_id": 6188,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "wishlist",
            "submessages": [],
            "timestamp": 1540403238,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6326636eaf7076f31b0e414f983340ab?d=identicon&version=1",
            "client": "website",
            "content": "<p>No love yet. All the rectifiers checked out. Found a resister that appeared blown, but replacing it didn\u2019t yield an improvement. There are two \u201czeener diodes\u201d that weren\u2019t showing in-circuit values that matched the repair manual\u2019s references, so they may also be part of the problem. I\u2019ll see about some appropriate replacements and try it again</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136567231,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "mail@danilocampos.com",
            "sender_full_name": "Danilo Campos (he) (F1'18)",
            "sender_id": 125275,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "mac plus",
            "submessages": [],
            "timestamp": 1540580592,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6326636eaf7076f31b0e414f983340ab?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here is the guide, btw. Very helpful reference for first generation all-in-one Macs. There\u2019s another for stuff like the SE, if that\u2019s ever relevant</p>\n<p><a href=\"http://www.maccaps.com/MacCaps/Repair_books_files/Macintosh%20Repair%20and%20Upgrade%20Secrets.pdf\" target=\"_blank\" title=\"http://www.maccaps.com/MacCaps/Repair_books_files/Macintosh%20Repair%20and%20Upgrade%20Secrets.pdf\">http://www.maccaps.com/MacCaps/Repair_books_files/Macintosh%20Repair%20and%20Upgrade%20Secrets.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 136567306,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "mail@danilocampos.com",
            "sender_full_name": "Danilo Campos (he) (F1'18)",
            "sender_id": 125275,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "mac plus",
            "submessages": [],
            "timestamp": 1540580668,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/f244e3545a6792c557adf5475475c0cc2e6d5d7b?x=x&version=3",
            "client": "ZulipElectron",
            "content": "<p>I've been fiddling with an Apple II emulator recently and am finishing a game rn, hope to be typing it into the machine this afternoon!</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147327753,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "aatigar@gmail.com",
            "sender_full_name": "Adam Avery Tigar (he) (F2'18)",
            "sender_id": 130218,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Apple II",
            "submessages": [],
            "timestamp": 1541709704,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>I found someone local selling CRTs, Sony BVM 8021 (8\") or Samsung SMC-150FN (15\"). Price is negotiable but definitely &lt; $50. I ~think~ composite video should just work with the TI-99 right?</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147454430,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1541895429,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/db3bb2e8cfa9c62e206a0fa100a024da6f6e41df?x=x&version=4",
            "client": "website",
            "content": "<p>Yes, about 99% sure composite is what you want. I believe the US version does only composite, the European version can do component which is higher quality, but I don't think that's going to happen.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147454710,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "raph.levien@gmail.com",
            "sender_full_name": "Raph Levien (F1'17)",
            "sender_id": 101701,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1541895827,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/db3bb2e8cfa9c62e206a0fa100a024da6f6e41df?x=x&version=4",
            "client": "website",
            "content": "<p>(I bought the video cable for it last fall)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147454754,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "raph.levien@gmail.com",
            "sender_full_name": "Raph Levien (F1'17)",
            "sender_id": 101701,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1541895845,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>I see, great. Were you working with the one at RC? myself and David couldn't verify that it's functioning since we don't have a display for it. I suppose an easier approach may be to get a composite -&gt; HDMI converter.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147455108,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1541896403,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/db3bb2e8cfa9c62e206a0fa100a024da6f6e41df?x=x&version=4",
            "client": "website",
            "content": "<p>Yes. We did get it working but I seem to remember it was a little tricky. Also, I think we were able to plug it into the display that's on the Apple. A color monitor would be better though.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147456122,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "raph.levien@gmail.com",
            "sender_full_name": "Raph Levien (F1'17)",
            "sender_id": 101701,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1541897959,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>That's good to hear. IMO, It would be neat to have a retro CRT to go with the TI-99. Though they are bulky and the programming experience might suffer on an 8\" CRT.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147456901,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1541899193,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/db3bb2e8cfa9c62e206a0fa100a024da6f6e41df?x=x&version=4",
            "client": "website",
            "content": "<p>The resolution is not that high, I think 8\" would be ok, but yeah, bigger would be better, especially for crowds of people looking at it.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147456961,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "raph.levien@gmail.com",
            "sender_full_name": "Raph Levien (F1'17)",
            "sender_id": 101701,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1541899245,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>I'm planning on picking up the TI-99 from RC on Thursday, will go test it on the CRTs before making any buying decision. Hopefully the right cable is somewhere in the box with it.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147690151,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1542221158,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipMobile",
            "content": "<p><a href=\"/user_uploads/13/N38oCbB2NbGjCrVlHIFECdsi/IMG_0035.jpeg\" target=\"_blank\" title=\"IMG_0035.jpeg\">IMG_0035.jpeg</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/N38oCbB2NbGjCrVlHIFECdsi/IMG_0035.jpeg\" target=\"_blank\" title=\"IMG_0035.jpeg\"><img src=\"/user_uploads/13/N38oCbB2NbGjCrVlHIFECdsi/IMG_0035.jpeg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147768218,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "aatigar@gmail.com",
                        "full_name": "Adam Avery Tigar (he) (F2'18)",
                        "id": 130218
                    },
                    "user_id": 130218
                },
                {
                    "emoji_code": "1f60e",
                    "emoji_name": "sunglasses",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "aaron_wood@protonmail.com",
                        "full_name": "Aaron Wood (he) (F1'18)",
                        "id": 125145
                    },
                    "user_id": 125145
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "nick@recurse.com",
                        "full_name": "Nick Bergson-Shilcock (he)",
                        "id": 811
                    },
                    "user_id": 811
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "rowan.copley@gmail.com",
                        "full_name": "Rowan Copley (he) (W1'18)",
                        "id": 134191
                    },
                    "user_id": 134191
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "nicolas@stonespring.org",
                        "full_name": "Nick Hahn (he) (S1'18)",
                        "id": 116358
                    },
                    "user_id": 116358
                }
            ],
            "recipient_id": 187614,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1542311319,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/33de48db54cb67ad74fa1b8991b6e790a7941300?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>next: need a RCA to 3.5mm adapter for audio</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147770084,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "liu.brandon@gmail.com",
            "sender_full_name": "Brandon Liu (SP2'18)",
            "sender_id": 111910,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1542312942,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/35351c8d4dee64d54b92fe38875cb762854d9299?x=x&version=2",
            "client": "website",
            "content": "<p>I have a commodore 64 that I would like to donate. It has the computer/keyboard as well as a CRT monitor. It does not have a power supply for the computer itself, which I've added to the wishlist. I'll drive it over... eventually.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147794603,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "ertysdl@gmail.com",
            "sender_full_name": "Erty Seidohl (he) (S'13)",
            "sender_id": 2154,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Commodore 64",
            "submessages": [],
            "timestamp": 1542341559,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/35351c8d4dee64d54b92fe38875cb762854d9299?x=x&version=2",
            "client": "website",
            "content": "<p>Let me know if the lab already has one or doesn't need one and I'll find another good home for it :)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147794607,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "ertysdl@gmail.com",
            "sender_full_name": "Erty Seidohl (he) (S'13)",
            "sender_id": 2154,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Commodore 64",
            "submessages": [],
            "timestamp": 1542341577,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3f4785d95e43ecfb2f20d49e6ec824dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Eeee, that looks awesome!</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147821732,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "nick@recurse.com",
            "sender_full_name": "Nick Bergson-Shilcock (he)",
            "sender_id": 811,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "next steps",
            "submessages": [],
            "timestamp": 1542380468,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/35351c8d4dee64d54b92fe38875cb762854d9299?x=x&version=2",
            "client": "website",
            "content": "<p>The commodore 64 has been delivered! I'll message <span class=\"user-mention\" data-user-id=\"810\">@David Albert</span> about getting a power cable :)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 152268476,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "ertysdl@gmail.com",
            "sender_full_name": "Erty Seidohl (he) (S'13)",
            "sender_id": 2154,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Commodore 64",
            "submessages": [],
            "timestamp": 1545323671,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>What model Macs are currently at RC? I was thinking about ordering a MacIvory board from DKS. These boards need several NuBus slots, and only mac II, IIfx and quadra 950 have sufficient if you have slots occupied by video and network cards.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154421492,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546621340,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>In case I wasn't clear: I would happily donate such a board to the lab for general use, at least once I'm done reversing it ;)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154430508,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546629863,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>Unfortunately I may have jumped the gun: heard back from DKS who informed me they only occasionally sell refurbished machines on ebay. Considering going the virtual lispm on DEC alpha route; the emulator I was able to get running is not quite stable enough for serious use.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154433820,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546632713,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>Still, if one becomes available it will be good to know if it could slot into one of the machines currently in the lab.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154433883,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546632740,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8756446588cfc2014859f5f1fa68c850?d=identicon&version=1",
            "client": "website",
            "content": "<p>Neat, I hadn't heard of such a thing before: <a href=\"http://fare.tunes.org/LispM.html\" target=\"_blank\" title=\"http://fare.tunes.org/LispM.html\">http://fare.tunes.org/LispM.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154501287,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "jason.a.owen@gmail.com",
            "sender_full_name": "Jason Owen (SP2'19)",
            "sender_id": 100450,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546751218,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8756446588cfc2014859f5f1fa68c850?d=identicon&version=1",
            "client": "website",
            "content": "<p>(Oh, and you posted that exact link much earlier in this stream; how did I miss it)</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154501732,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "jason.a.owen@gmail.com",
            "sender_full_name": "Jason Owen (SP2'19)",
            "sender_id": 100450,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546752131,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>Yes, it's good info,  and I'd recommend flipping through some fare's thoughts on computing systems generally. I sent a few questions back to DKS about Open Genera, but so long as I qualify for the noncommercial discount, I think I'll pull the trigger on it. I'm trying to track down a suitable alpha machine, because apparently qemu-system-alpha can't run Tru64 Unix... d'oh.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154533448,
            "is_me_message": false,
            "last_edit_timestamp": 1546813076,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546813049,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>It seems like kind of a silly thing to do... but you know, I wouldn't mind having an alpha machine around. The end result is quite nice. Even with the subpar emulation, Open Genera is a real pleasure to work within.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154533559,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546813211,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>Plus, the more hosts I have running, the more useful setting up stuff like NFS and directory services will be. I always wanted to learn proper sysadmin stuff but never really had cause to with just one laptop and one desktop computer.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154533643,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546813413,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8651a8565e010cd3aebcd360badf2a92?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'll also need to figure out a good way to create a VPN accessible from the internet... Gotta be able to hack on the lisp machine from anywhere.</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 154533807,
            "is_me_message": false,
            "last_edit_timestamp": 1546813729,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "e.alexander.segura@gmail.com",
            "sender_full_name": "Alex Segura (SP1'19)",
            "sender_id": 2899,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Currently in the lab",
            "submessages": [],
            "timestamp": 1546813721,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/579b93544758f42fb3b56b731feaf2f8e703f79c?x=x&version=2",
            "client": "website",
            "content": "<p>While visiting my parents I picked up a large number of old DOS formatted 5.25 floppies. Some may have some old files that I'd like to try and archive.</p>\n<p>Does anyone know the best way to get the files off the disks? Or else does anyone in NYC have a working DOS computer with a 5.25 and 3.5 inch floppy disk?</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 160537670,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "ed.jburnett@gmail.com",
            "sender_full_name": "Edward J Burnett (he) (m7'18)",
            "sender_id": 134588,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Vintage computer needed",
            "submessages": [],
            "timestamp": 1552358230,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1588fc084a150438206141abca2a434daa4c8fa5?x=x&version=2",
            "client": "website",
            "content": "<p>At Artexte in Montreal, there is this great video about <em>Computerese: The Electronic Media Magazine</em> that speaks of Telidon, the Canadian version of Videotex tech... <a href=\"https://www.youtube.com/watch?v=PqdqPQlg7jc\">here is the video</a></p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"PqdqPQlg7jc\" href=\"https://www.youtube.com/watch?v=PqdqPQlg7jc\"><img src=\"https://i.ytimg.com/vi/PqdqPQlg7jc/default.jpg\"></a></div><p>Is there any Videotex enthusiast here ?</p>",
            "content_type": "text/html",
            "display_recipient": "retro computer lab",
            "flags": [
                "read",
                "historical"
            ],
            "id": 211784100,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 187614,
            "sender_email": "finartcialist@gmail.com",
            "sender_full_name": "Edith Viau (she) (F2'20)",
            "sender_id": 341049,
            "sender_realm_str": "recurse",
            "stream_id": 146536,
            "subject": "Videotex technologies?",
            "submessages": [],
            "timestamp": 1601482250,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
