{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>Does anyone have any first meeting RFC suggestions? Since I've been focusing on security stuff, this one has been on my mind for a while: <a href=\"https://tools.ietf.org/html/rfc4953\" target=\"_blank\" title=\"https://tools.ietf.org/html/rfc4953\">https://tools.ietf.org/html/rfc4953</a></p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107472407,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487789091,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>Would we be all reading the same RFC, or would we each read a different RFC and do some presentation?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107472560,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487789376,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a14b1ce259d12e772ae65d5079742a5f25cc805?x=x&version=1",
            "client": "website",
            "content": "<p>I'd be interested to discuss this:               TOTP: Time-Based One-Time Password Algorithm<br>\n<a href=\"https://tools.ietf.org/html/rfc6238\" target=\"_blank\" title=\"https://tools.ietf.org/html/rfc6238\">https://tools.ietf.org/html/rfc6238</a></p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107475446,
            "is_me_message": false,
            "last_edit_timestamp": 1487793865,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "tansengming@me.com",
            "sender_full_name": "SengMing Tan (he) (W1'16)",
            "sender_id": 100336,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487793850,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a14b1ce259d12e772ae65d5079742a5f25cc805?x=x&version=1",
            "client": "website",
            "content": "<blockquote>\n<p>Would we be all reading the same RFC, or would we each read a different RFC and do some presentation?</p>\n</blockquote>\n<p>Good question ... I'm not sure really I've never been part of a reading group before <img alt=\":sweat_smile:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/sweat_smile.png\" title=\":sweat_smile:\"></p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107475478,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "tansengming@me.com",
            "sender_full_name": "SengMing Tan (he) (W1'16)",
            "sender_id": 100336,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487793922,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a14b1ce259d12e772ae65d5079742a5f25cc805?x=x&version=1",
            "client": "website",
            "content": "<p>I sort of assumed that we just hung out and silently read it together, then talk about it? What do y'all think about that?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107475551,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "tansengming@me.com",
            "sender_full_name": "SengMing Tan (he) (W1'16)",
            "sender_id": 100336,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487794013,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/70201dad8f30b376c8e9f8ede010e43b63266850?x=x&version=6",
            "client": "website",
            "content": "<p>.</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107475904,
            "is_me_message": false,
            "last_edit_timestamp": 1605727233,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "stanley@zheng.nyc",
            "sender_full_name": "Stanley Zheng (they) (W1'19)",
            "sender_id": 100315,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487794505,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"stanley@stanzheng.com\" data-user-id=\"100315\">@Stanley Zheng (W1'16)</span> thanks for looping him in :)</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107476858,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487795847,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>this was actually inspired by me seeing RFCs We Love in the blogging stream</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107476865,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487795860,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tansengming@gmail.com\" data-user-id=\"100336\">@SengMing Tan (W1'16)</span> <span class=\"user-mention\" data-user-email=\"hi@xmunoz.com\" data-user-id=\"100520\">@Cristina Munoz (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"katarina_berg@hotmail.com\" data-user-id=\"100538\">@Katarina Berg (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"moritz.neeb@posteo.net\" data-user-id=\"100515\">@Moritz Neeb (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"eliasdorneles@gmail.com\" data-user-id=\"100512\">@Elias Dorneles Silveira Junior (SP1'17)</span> can we find a time to meet in the space? I find it's usually way easier to flesh things out in person rather than over Zulip</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107476935,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487795972,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>perhaps sometime Friday or Thursday?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107476940,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487795981,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>Tomorrow 2:30 - 3:30?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107477356,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487796593,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>on second thought Thursday is <em>very</em> crowded</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107477359,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487796600,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"hi@xmunoz.com\" data-user-id=\"100520\">@Cristina Munoz (SP1'17)</span> webdev 101 is at that time</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107477407,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487796620,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>webdev starts at 3:30</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107477425,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487796662,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"tansengming@gmail.com\" data-user-id=\"100336\">@SengMing Tan (W1'16)</span> <span class=\"user-mention\" data-user-email=\"hi@xmunoz.com\" data-user-id=\"100520\">@Cristina Munoz (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"katarina_berg@hotmail.com\" data-user-id=\"100538\">@Katarina Berg (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"moritz.neeb@posteo.net\" data-user-id=\"100515\">@Moritz Neeb (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"eliasdorneles@gmail.com\" data-user-id=\"100512\">@Elias Dorneles Silveira Junior (SP1'17)</span> can anyone <strong>not</strong> make it to the space on Friday?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107477495,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487796731,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"hi@xmunoz.com\" data-user-id=\"100520\">@Cristina Munoz (SP1'17)</span> yeah but it might get moved to 3 to not conflict with feelings checkin and even if it doesn't there's just a lot going on tomorrow</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107477505,
            "is_me_message": false,
            "last_edit_timestamp": 1487796781,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487796757,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>friday sounds good</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107478526,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487798087,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>Is this happening today?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107556610,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487951396,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>hopefully... I'll be in in an hour or two, sorry</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107560704,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487958349,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>had some stuff to take care of at home</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107560705,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487958355,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f2793e7c0de9bb00c6c88c585bc865c5?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"stanley@stanzheng.com\" data-user-id=\"100315\">@Stanley Zheng (W1'16)</span> Thanks for linking me!</p>\n<p>I found one approach useful. RFC and side by side code reading. Read TOTP and look into your favorite lang library implementation. </p>\n<p>I'd love to see what new ways others prefer.</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107561993,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "alex@strugee.net",
                        "full_name": "AJ Jordan (he/they) (SP2'17)",
                        "id": 100461
                    },
                    "user_id": 100461
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "stanley@zheng.nyc",
                        "full_name": "Stanley Zheng (they) (W1'19)",
                        "id": 100315
                    },
                    "user_id": 100315
                }
            ],
            "recipient_id": 102216,
            "sender_email": "me@kracekumar.com",
            "sender_full_name": "Kracekumar R (F2'16)",
            "sender_id": 100188,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487960717,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>Is this happening now (or soon)?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107564510,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487964772,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15cc6e65f5cb0faac87d0b88dae865281ba57899?x=x&version=2",
            "client": "desktop app Linux 0.5.1",
            "content": "<p>I guess we have to wait for <span class=\"user-mention\" data-user-email=\"alex@strugee.net\" data-user-id=\"100461\">@AJ Jordan (W2'17)</span>  to arrive and then decide for a time?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107564720,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "moritz.neeb@posteo.net",
            "sender_full_name": "Moritz Neeb (he) (SP1'17)",
            "sender_id": 100515,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487965130,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>ugh sorry guys</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107565669,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487966664,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'll be in by 3:45; any time after that works for me</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107565672,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487966674,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"eliasdorneles@gmail.com\" data-user-id=\"100512\">@Elias Dorneles Silveira Junior (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"moritz.neeb@posteo.net\" data-user-id=\"100515\">@Moritz Neeb (SP1'17)</span></p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107565675,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487966680,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>So, here are some short RFCs that we might read today together:<br>\n<a href=\"https://tools.ietf.org/html/rfc1925\" target=\"_blank\" title=\"https://tools.ietf.org/html/rfc1925\">https://tools.ietf.org/html/rfc1925</a> (The Twelve Networking Truths)<br>\n<a href=\"https://tools.ietf.org/html/rfc2119\" target=\"_blank\" title=\"https://tools.ietf.org/html/rfc2119\">https://tools.ietf.org/html/rfc2119</a> (Key words for use in RFCs to Indicate Requirement Levels)</p>\n<p>Not that short, but light reading:<br>\n<a href=\"https://tools.ietf.org/html/rfc1178\" target=\"_blank\" title=\"https://tools.ietf.org/html/rfc1178\">https://tools.ietf.org/html/rfc1178</a> (Choosing a Name for Your Computer)</p>\n<p>And here is a bigger one that looks interesting:<br>\n<a href=\"https://tools.ietf.org/html/rfc2196\" target=\"_blank\" title=\"https://tools.ietf.org/html/rfc2196\">https://tools.ietf.org/html/rfc2196</a> (Site Security Handbook)</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107567264,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "me@kracekumar.com",
                        "full_name": "Kracekumar R (F2'16)",
                        "id": 100188
                    },
                    "user_id": 100188
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "alex@strugee.net",
                        "full_name": "AJ Jordan (he/they) (SP2'17)",
                        "id": 100461
                    },
                    "user_id": 100461
                }
            ],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487969266,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>Also long-and-looks-interesting:<br>\n<a href=\"https://www.ietf.org/rfc/rfc3439.txt\" target=\"_blank\" title=\"https://www.ietf.org/rfc/rfc3439.txt\">https://www.ietf.org/rfc/rfc3439.txt</a> (Some Internet Architectural Guidelines and Philosophy)<br>\n<a href=\"https://tools.ietf.org/rfc/rfc6250.txt\" target=\"_blank\" title=\"https://tools.ietf.org/rfc/rfc6250.txt\">https://tools.ietf.org/rfc/rfc6250.txt</a> (Evolution of the IP Model)</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107567321,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487969373,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>are we meeting? or</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107567390,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487969455,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>lez do it</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107567469,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487969562,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.rfc-editor.org/rfc/rfc6797.txt\" target=\"_blank\" title=\"https://www.rfc-editor.org/rfc/rfc6797.txt\">https://www.rfc-editor.org/rfc/rfc6797.txt</a></p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107567902,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487970341,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>In case anyone wants to meet, we're at Lovelace right now</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107568163,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487970791,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"https://gist.github.com/xmunoz/1fde824725cbd7b4014010c38ffd3312\" target=\"_blank\" title=\"https://gist.github.com/xmunoz/1fde824725cbd7b4014010c38ffd3312\">https://gist.github.com/xmunoz/1fde824725cbd7b4014010c38ffd3312</a></p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107568302,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1487971014,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f2793e7c0de9bb00c6c88c585bc865c5?d=identicon&version=1",
            "client": "website",
            "content": "<blockquote>\n<p><a href=\"https://tools.ietf.org/html/rfc1178\" target=\"_blank\" title=\"https://tools.ietf.org/html/rfc1178\">https://tools.ietf.org/html/rfc1178</a> (Choosing a Name for Your Computer)</p>\n</blockquote>\n<p>Thanks for sharing this.</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107583131,
            "is_me_message": false,
            "last_edit_timestamp": 1488002845,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "stanley@zheng.nyc",
                        "full_name": "Stanley Zheng (they) (W1'19)",
                        "id": 100315
                    },
                    "user_id": 100315
                }
            ],
            "recipient_id": 102216,
            "sender_email": "me@kracekumar.com",
            "sender_full_name": "Kracekumar R (F2'16)",
            "sender_id": 100188,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "First meeting + RFC",
            "submessages": [],
            "timestamp": 1488002127,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>yo! are we meeting today? <span class=\"user-mention\" data-user-email=\"hi@xmunoz.com\" data-user-id=\"100520\">@Cristina Munoz (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"me@kracekumar.com\" data-user-id=\"100188\">@Kracekumar R (F2'16)</span> <span class=\"user-mention\" data-user-email=\"eliasdorneles@gmail.com\" data-user-id=\"100512\">@Elias Dorneles Silveira Junior (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"moritz.neeb@posteo.net\" data-user-id=\"100515\">@Moritz Neeb (SP1'17)</span></p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107853711,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488572767,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>oh whoops didn't mean to mention Kracekumar :P</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107853719,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488572813,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>ah well</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107853722,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488572816,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>hey, sorry folks, I'm jumping ship :/</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107854648,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488574281,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>too much things to read</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107854649,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488574285,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"eliasdorneles@gmail.com\" data-user-id=\"100512\">@Elias Dorneles Silveira Junior (SP1'17)</span> no worries! sorry to see you go :)</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107854773,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488574556,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>sorry I bailed yesterday! I was working on iCTF all day, so I didn't have zulip open. Next week I should be able to make it.</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107882911,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488639837,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/15cc6e65f5cb0faac87d0b88dae865281ba57899?x=x&version=2",
            "client": "website",
            "content": "<blockquote>\n<p>sorry I bailed yesterday! I was working on iCTF all day, so I didn't have zulip open<br>\nme too</p>\n</blockquote>\n<p>But rather than joining next week, I might go Elias' way. At least I can't commit to join regularly, but I'll see what papers are on the reading list and then decide.</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107883672,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "moritz.neeb@posteo.net",
            "sender_full_name": "Moritz Neeb (he) (SP1'17)",
            "sender_id": 100515,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488641739,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p><img alt=\":thumbsup:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/thumbsup.png\" title=\":thumbsup:\"> np</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107964146,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488826819,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>I think that means it's just us <span class=\"user-mention\" data-user-email=\"hi@xmunoz.com\" data-user-id=\"100520\">@Cristina Munoz (SP1'17)</span>?</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107964149,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488826830,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>I'm cool with that. Since it's just us, can we move it to Thursday this week? I'm taking a little road trip on Friday.</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107964310,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488827121,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>PS sorry that my previous message was a lie</p>\n<blockquote>\n<p>Next week I should be able to make it.</p>\n</blockquote>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107964379,
            "is_me_message": false,
            "last_edit_timestamp": 1488827297,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488827275,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>heh, np</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107966438,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488830663,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8f076e5e03c30a36d598445308926598?d=identicon&version=1",
            "client": "website",
            "content": "<p>Thursday sounds good</p>",
            "content_type": "text/html",
            "display_recipient": "rfc reading group",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107966445,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102216,
            "sender_email": "alex@strugee.net",
            "sender_full_name": "AJ Jordan (he/they) (SP2'17)",
            "sender_id": 100461,
            "sender_realm_str": "recurse",
            "stream_id": 100494,
            "subject": "TOTP",
            "submessages": [],
            "timestamp": 1488830675,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
