{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"184435\" href=\"/#narrow/stream/184435-Scholarships\">#Scholarships</a>.</p>\n<p><strong>Description</strong>: A stream to share information for scholarships and grants on tech</p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157541792,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 184435,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1549303189,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>This grant opportunity is open to anyone who is currently contributing to an open source project aimed at improving the lives of others (social good, developer tools, etc.). We value true representation in open source (we know we all have a long way to go), and we especially encourage those who are underrepresented in the open source community to apply.</p>\n<p><a href=\"https://blog.sentry.io/2019/01/29/apply-sentry-open-source-grant\" target=\"_blank\" title=\"https://blog.sentry.io/2019/01/29/apply-sentry-open-source-grant\">https://blog.sentry.io/2019/01/29/apply-sentry-open-source-grant</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157541927,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "wylieconlon@gmail.com",
                        "full_name": "Wylie Conlon (he) (F2'18)",
                        "id": 130475
                    },
                    "user_id": 130475
                }
            ],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "open source",
            "submessages": [],
            "timestamp": 1549303268,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://labs.robinhood.org/fellowship/\" target=\"_blank\" title=\"https://labs.robinhood.org/fellowship/\">https://labs.robinhood.org/fellowship/</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 157937931,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "build high impact products",
            "submessages": [],
            "timestamp": 1549732757,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.diversifytech.co/tech-conference-scholarships\" target=\"_blank\" title=\"https://www.diversifytech.co/tech-conference-scholarships\">https://www.diversifytech.co/tech-conference-scholarships</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 159204870,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "Diversify Tech",
            "submessages": [],
            "timestamp": 1550882811,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Pirple is now offering scholarships<br>\n<a href=\"https://pirple.thinkific.com/pages/membership\" target=\"_blank\" title=\"https://pirple.thinkific.com/pages/membership\">https://pirple.thinkific.com/pages/membership</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 159389818,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "pirple",
            "submessages": [],
            "timestamp": 1551145043,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.outreachy.org/\" target=\"_blank\" title=\"https://www.outreachy.org/\">https://www.outreachy.org/</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 159421597,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "Interns get paid to work on FOSS",
            "submessages": [],
            "timestamp": 1551185887,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfuLlqzrDRirMLjlfFso_MKzf746xbiLNVkWz-eZ0QfLFdMqw/viewform\" target=\"_blank\" title=\"https://docs.google.com/forms/d/e/1FAIpQLSfuLlqzrDRirMLjlfFso_MKzf746xbiLNVkWz-eZ0QfLFdMqw/viewform\">https://docs.google.com/forms/d/e/1FAIpQLSfuLlqzrDRirMLjlfFso_MKzf746xbiLNVkWz-eZ0QfLFdMqw/viewform</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 159453293,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "Women Who Code Connect",
            "submessages": [],
            "timestamp": 1551211337,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://buildyourfuture.withgoogle.com/scholarships/google-travel-and-conference-grants\" target=\"_blank\" title=\"https://buildyourfuture.withgoogle.com/scholarships/google-travel-and-conference-grants\">https://buildyourfuture.withgoogle.com/scholarships/google-travel-and-conference-grants</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 159864295,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "Google conferences scholarships",
            "submessages": [],
            "timestamp": 1551646214,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ab772058030721ef1c85f4d7692609dc?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.surveymonkey.com/r/CSCJ9TB\" target=\"_blank\" title=\"https://www.surveymonkey.com/r/CSCJ9TB\">https://www.surveymonkey.com/r/CSCJ9TB</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 163592803,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "hola@michelletorres.mx",
            "sender_full_name": "Michelle Torres (she) (W2'19)",
            "sender_id": 198461,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "Blockchain intership program",
            "submessages": [],
            "timestamp": 1555528710,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6b5fe2f87b37afbbfe2a6aa4a84b7f97ebd6679f?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p><a href=\"http://codelandconf.com/\" target=\"_blank\" title=\"http://codelandconf.com/\">http://codelandconf.com/</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scholarships",
            "flags": [
                "read",
                "historical"
            ],
            "id": 166763442,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 293361,
            "sender_email": "eileenm@gmail.com",
            "sender_full_name": "Eileen McFarland (she) (SP1'19)",
            "sender_id": 203637,
            "sender_realm_str": "recurse",
            "stream_id": 184435,
            "subject": "Codeland",
            "submessages": [],
            "timestamp": 1559080526,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
