{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/9fd9de59f964f6e3af477006ddd0116211347010?x=x&version=2",
            "client": "Internal",
            "content": "<p>Stream created by <span class=\"user-mention silent\" data-user-id=\"241291\">Cory Levinson (F2'19)</span>.</p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177094330,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 372391,
            "sender_email": "notification-bot@zulip.com",
            "sender_full_name": "Notification Bot",
            "sender_id": 100006,
            "sender_realm_str": "zulipcore",
            "stream_id": 210464,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1569961458,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a40cd9cd52ed9481320b55f346ffdf3a0c6db296?x=x&version=3",
            "client": "website",
            "content": "<p><span aria-label=\"+1\" class=\"emoji emoji-1f44d\" role=\"img\" title=\"+1\">:+1:</span></p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177094697,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 372391,
            "sender_email": "hello@tomlisankie.com",
            "sender_full_name": "Thomas Francis Lisankie (he) (F1'19)",
            "sender_id": 233915,
            "sender_realm_str": "recurse",
            "stream_id": 210464,
            "subject": "stream events",
            "submessages": [],
            "timestamp": 1569961591,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/24a4a5034f6fd2513bdc0b8fd7fc2408?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>hey y'all !! starting an SSB stream with <span class=\"user-mention\" data-user-id=\"240570\">@Scott Nelson (he) (F2'19)</span> and <span class=\"user-mention\" data-user-id=\"233915\">@Thomas Francis Lisankie (he) (F1'19)</span> <img alt=\":pixtopus:\" class=\"emoji\" src=\"https://zulip-avatars.s3.amazonaws.com/13/emoji/images/1234.gif\" title=\"pixtopus\"> <img alt=\":parrot:\" class=\"emoji\" src=\"https://zulip-avatars.s3.amazonaws.com/13/emoji/images/1240.gif\" title=\"parrot\"> <img alt=\":parrot:\" class=\"emoji\" src=\"https://zulip-avatars.s3.amazonaws.com/13/emoji/images/1240.gif\" title=\"parrot\"> </p>\n<p>If you haven't used scuttlebutt before, you can:<br>\n- read about it =&gt; <a href=\"http://scuttlebutt.nz\" target=\"_blank\" title=\"http://scuttlebutt.nz\">scuttlebutt.nz</a><br>\n- download a client =&gt; <a href=\"https://github.com/ssbc/patchwork/releases\" target=\"_blank\" title=\"https://github.com/ssbc/patchwork/releases\">https://github.com/ssbc/patchwork/releases</a><br>\n- join my pub! =&gt; <a href=\"https://pub.planetary.computer\" target=\"_blank\" title=\"https://pub.planetary.computer\">https://pub.planetary.computer</a></p>\n<p>Feel free to drop in this thread with your SSB public key so we  can follow eachother. Also, <span class=\"user-mention\" data-user-id=\"240570\">@Scott Nelson (he) (F2'19)</span> <span class=\"user-mention\" data-user-id=\"233915\">@Thomas Francis Lisankie (he) (F1'19)</span> and I were talking about getting a ssb pub setup on our heap cluster. If anyone wants to help, let us know!</p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177094844,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 372391,
            "sender_email": "cjlevinson@gmail.com",
            "sender_full_name": "Cory Levinson (F2'19)",
            "sender_id": 241291,
            "sender_realm_str": "recurse",
            "stream_id": 210464,
            "subject": "Welcome!",
            "submessages": [],
            "timestamp": 1569961688,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/24a4a5034f6fd2513bdc0b8fd7fc2408?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>My ssb id: <code>@sHFNLAao6phQ5AN17ecYNUbszDa4Qf6DhyQsjtQfdmY=.ed25519</code></p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177094882,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 372391,
            "sender_email": "cjlevinson@gmail.com",
            "sender_full_name": "Cory Levinson (F2'19)",
            "sender_id": 241291,
            "sender_realm_str": "recurse",
            "stream_id": 210464,
            "subject": "Welcome!",
            "submessages": [],
            "timestamp": 1569961727,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/dac88dd1cf8a26fd2e8da2b6bff2238f049d037c?x=x&version=3",
            "client": "website",
            "content": "<p><span aria-label=\"+1\" class=\"emoji emoji-1f44d\" role=\"img\" title=\"+1\">:+1:</span> My public key is <code>@4/zy0uD6x+SWaQkGIx4okVbm/wA13jI+fcc+nQ9ie40=.ed25519</code></p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177094885,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 372391,
            "sender_email": "scott@scottnelson.co",
            "sender_full_name": "Scott Nelson (he) (F2'19)",
            "sender_id": 240570,
            "sender_realm_str": "recurse",
            "stream_id": 210464,
            "subject": "Welcome!",
            "submessages": [],
            "timestamp": 1569961730,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a40cd9cd52ed9481320b55f346ffdf3a0c6db296?x=x&version=3",
            "client": "website",
            "content": "<p>Mine is <code>@pat8iVHeG3B6LLkDReMvY9YdN3sWql+CRLONNxyn3Iw=.ed25519</code></p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177094957,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 372391,
            "sender_email": "hello@tomlisankie.com",
            "sender_full_name": "Thomas Francis Lisankie (he) (F1'19)",
            "sender_id": 233915,
            "sender_realm_str": "recurse",
            "stream_id": 210464,
            "subject": "Welcome!",
            "submessages": [],
            "timestamp": 1569961793,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/24a4a5034f6fd2513bdc0b8fd7fc2408?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"233915\">@Thomas Francis Lisankie (he) (F1'19)</span> here's the Arena Channel where I found the image for my pub: <a href=\"https://www.are.na/sam-hart/cybernetics-image-library\" target=\"_blank\" title=\"https://www.are.na/sam-hart/cybernetics-image-library\">https://www.are.na/sam-hart/cybernetics-image-library</a></p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 177095640,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "hello@tomlisankie.com",
                        "full_name": "Thomas Francis Lisankie (he) (F1'19)",
                        "id": 233915
                    },
                    "user_id": 233915
                }
            ],
            "recipient_id": 372391,
            "sender_email": "cjlevinson@gmail.com",
            "sender_full_name": "Cory Levinson (F2'19)",
            "sender_id": 241291,
            "sender_realm_str": "recurse",
            "stream_id": 210464,
            "subject": "so u like my pub image?",
            "submessages": [],
            "timestamp": 1569962265,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d50800fce7a8da51126c7e6f1b8c74ecc70ee207?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Hi, I'm late to the party. My public key is @E9UvatPXsnaHeEMaGba0hCqAx50+oHn8u6E1rZOA/8M=.ed25519 :).<br>\nAlso, I tried to generate an invite to your pub on your page <span class=\"user-mention\" data-user-id=\"241291\">@Cory Levinson (F2'19)</span> but it didn't work (tried Firefox, Brave, Safari). Can you send me one?</p>",
            "content_type": "text/html",
            "display_recipient": "Scuttlebutt",
            "flags": [
                "read",
                "historical"
            ],
            "id": 183640678,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 372391,
            "sender_email": "mail@isabelpaehr.com",
            "sender_full_name": "Isabel Paehr (she) (SP1'19)",
            "sender_id": 203512,
            "sender_realm_str": "recurse",
            "stream_id": 210464,
            "subject": "Welcome!",
            "submessages": [],
            "timestamp": 1576583268,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
