{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"196330\" href=\"/#narrow/stream/196330-sex\">#sex</a>.</p>\n<p><strong>Description</strong>: A stream for discussing things related to sex: sex education, toys, sexual health + safety, etc</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 164045861,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 196330,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1556070689,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "website",
            "content": "<p>how do you store lube so that it doesn't get all over the place and muss everything up? particularly silicone based lube, which won't dry up and is really annoying to clean if it spills. most of the lube that i've bought comes in a shampoo-style bottle, is there another style of bottle that works better? or some material to wrap the bottle in so that it won't get sticky and slippery forever if you ever touch the bottle while you have lube on your hands?</p>\n<p>this question brought to you by packing up all my sex stuff and discovering a giant silicone lube explosion over everything :(</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217219707,
            "is_me_message": false,
            "last_edit_timestamp": 1605749603,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605749458,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>re: the bottle getting sticky, I usually just resort to wiping off the container later, while in-the-moment setting it on hard surfaces like a counter or side table (totally feel you on the pain of shampoo-style bottles). Other than that, I generally keep it in a ziploc bag in hopes of negating explosions\u2122</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217220268,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605750148,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>which I guess is to say, I just treat it like {sunscreen,toothpaste,lotion}, anything that can be messy</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217220298,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605750210,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>do my eyes deceive me?</p>\n<p>are...are we finally using the sex channel?</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217297065,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605804395,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>I don't know what quantity you're working with, but something we used to use for massage oil, essential oils, and other stuff in that similar domain of \"slippery but also a pain in the ass to clean up\" was glass bottles with corks or little flip-top lids</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217297320,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605804498,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>swiss navy iirc had a lube bottle with a little locking mechanism to prevent accidental discharge</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217297427,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605804549,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>also, reminder that silicone lube can eat certain silicone toys</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217297472,
            "is_me_message": false,
            "last_edit_timestamp": 1605804579,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605804569,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "ZulipMobile",
            "content": "<p>gotta start sometime :)</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217299987,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605805598,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "ZulipMobile",
            "content": "<p>i usually do keep the bottles in a ziplock bag, but i guess i got lazy and that's when it bites you :/</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217300055,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605805633,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "ZulipMobile",
            "content": "<p>do you find that corks are nicer than shampoo-style bottle tops?</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217300126,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605805669,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>it looks nicer on the shelves, and if you push on it by accident it's less likely to pop open</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217344444,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605828257,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>oh wait, are you talking the lid-style shampoo ones, or the toggle-open ones?</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217344459,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605828272,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5d6a7a4735c43e9dae0e3f9ef82919706728452a?x=x&version=3",
            "client": "ZulipMobile",
            "content": "<p>the ones i usually see are like <a href=\"https://image.made-in-china.com/2f0j00tUkRgGDBIAoQ/Plastic-Bottle-Lid-for-Shampoo-Bottle.jpg\">this</a></p>\n<div class=\"message_inline_image\"><a href=\"https://image.made-in-china.com/2f0j00tUkRgGDBIAoQ/Plastic-Bottle-Lid-for-Shampoo-Bottle.jpg\" title=\"this\"><img src=\"https://image.made-in-china.com/2f0j00tUkRgGDBIAoQ/Plastic-Bottle-Lid-for-Shampoo-Bottle.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217345134,
            "is_me_message": false,
            "last_edit_timestamp": 1605828785,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "me@wesleyac.com",
            "sender_full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
            "sender_id": 101330,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605828755,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>oh yeah gross</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217438627,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605896002,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/af4823dc0c1278b09771a37fca3a75a0562dcb3b?x=x&version=2",
            "client": "website",
            "content": "<p>the one complaint i have with the bottle approach was when one fell on my floor, which at the time was bare concrete. wasn't tempered glass, so it sharded and went <em>everywhere</em>. partner and I had a laugh cleaning it up, but was annoying.</p>",
            "content_type": "text/html",
            "display_recipient": "sex",
            "flags": [
                "read",
                "historical"
            ],
            "id": 217438777,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f62c",
                    "emoji_name": "grimacing",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "me@wesleyac.com",
                        "full_name": "Wesley Aptekar-Cassels (they) (m8'20)",
                        "id": 101330
                    },
                    "user_id": 101330
                }
            ],
            "recipient_id": 325496,
            "sender_email": "ertel.chris@gmail.com",
            "sender_full_name": "Christopher Ray Ertel (he) (S1'19)",
            "sender_id": 221817,
            "sender_realm_str": "recurse",
            "stream_id": 196330,
            "subject": "how do you store lube?",
            "submessages": [],
            "timestamp": 1605896054,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
