{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/813126b0289ae35cb6de4ee22d838f962dcfadac?x=x&version=1",
            "client": "website",
            "content": "<p>Hi all, I created this stream for people who've expressed an interest in working on SICP this summer. I'm currently just starting Chapter 2, and am wondering about a few things:<br>\n1) Is there some mechanism for organizing the code in DrRacket to not have to copy common functions into a new .rkt script every time I want to use them?<br>\n2) I have no experience with pairing, but would like to do so ... any suggestions for problems that would be good? (A lot of them seem too trivial - typing time is way less than the time required to read and think about the problem, and the solution is &lt; 10 lines)</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6689676,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindzey@gmail.com",
            "sender_full_name": "Laura Lindzey (she) (m1'19)",
            "sender_id": 2131,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "Hi!",
            "submessages": [],
            "timestamp": 1370877376,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/aa92b21f4a06f87dae635ed43f9595f5?d=identicon&version=1",
            "client": "website",
            "content": "<p>Thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6690135,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "robert.buonpastore@gmail.com",
            "sender_full_name": "Robert Buonpastore (S'13)",
            "sender_id": 2126,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "Hi!",
            "submessages": [],
            "timestamp": 1370878209,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/aa92b21f4a06f87dae635ed43f9595f5?d=identicon&version=1",
            "client": "website",
            "content": "<p>Modules may be helpful in organizing your code. If you search for messages by Lindsey Kuper, she provides a quick example</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6690277,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "robert.buonpastore@gmail.com",
            "sender_full_name": "Robert Buonpastore (S'13)",
            "sender_id": 2126,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "Hi!",
            "submessages": [],
            "timestamp": 1370878412,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/813126b0289ae35cb6de4ee22d838f962dcfadac?x=x&version=1",
            "client": "website",
            "content": "<p>Gah! Search functionality is lacking .... I can't figure out how to get \"from: Lindsey and contains modules\" </p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6691671,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindzey@gmail.com",
            "sender_full_name": "Laura Lindzey (she) (m1'19)",
            "sender_id": 2131,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "Hi!",
            "submessages": [],
            "timestamp": 1370880869,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Laura Lindzey</strong> Try \"sender:lindsey@composition.al modules\"</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6692295,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "Hi!",
            "submessages": [],
            "timestamp": 1370882120,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>Any SICPers have questions I can help with?</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6701693,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370899696,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>We figured out what was wrong: it turns out that if you do a search, then you'll only see search results *in streams you're following*.  It's like an extreme form of filter bubble.   So @<strong>Laura Lindzey</strong> didn't see what I wrote about modules because she wasn't following the \"racket\" stream.</p>\n<p>If there's anyone else in this thread who's using Racket to do SICP, then I recommend following that stream as well.</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6701773,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "hi!",
            "submessages": [],
            "timestamp": 1370899833,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f8c6c9a889b4b593ce9c846c5f022de8?d=identicon&version=1",
            "client": "website",
            "content": "<p>hi everyone, i was just introduced to SICP and wanted to see if anyone else is just starting as well! i'd love to be able to go over problems and exercises if you are!</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6778777,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "willson.mock@gmail.com",
            "sender_full_name": "Willson Mock (S'13)",
            "sender_id": 2105,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "just starting",
            "submessages": [],
            "timestamp": 1371071924,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/813126b0289ae35cb6de4ee22d838f962dcfadac?x=x&version=1",
            "client": "website",
            "content": "<p>Yay! I'm loving SICP. I'm a bit ahead of you (just starting Chapter 2), but would love to talk about Scheme/SICP. I understand it well enough to do the problems, but think that I'll learn it a lot better if I talk with somebody about them. So - ping me if you have any questions / want to discuss any of the concepts!</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6778850,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindzey@gmail.com",
            "sender_full_name": "Laura Lindzey (she) (m1'19)",
            "sender_id": 2131,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "just starting",
            "submessages": [],
            "timestamp": 1371072044,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Willson Mock</strong> woohoo!  lemme know if you want to pair.</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6779037,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "just starting",
            "submessages": [],
            "timestamp": 1371072373,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f8c6c9a889b4b593ce9c846c5f022de8?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Laura Lindzey</strong>@<strong>Lindsey Kuper</strong>thanks! definitely would like to speak with both of you once i do some initial reading!</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6779062,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "willson.mock@gmail.com",
            "sender_full_name": "Willson Mock (S'13)",
            "sender_id": 2105,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "just starting",
            "submessages": [],
            "timestamp": 1371072469,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f8c6c9a889b4b593ce9c846c5f022de8?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Javier Olaechea</strong> you're right about chapter 3 of SICP, really good information in there and it's helping me better understand how python environments work!</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6949546,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "willson.mock@gmail.com",
            "sender_full_name": "Willson Mock (S'13)",
            "sender_id": 2105,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371494290,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/813126b0289ae35cb6de4ee22d838f962dcfadac?x=x&version=1",
            "client": "website",
            "content": "<p>@<strong>Rob B</strong> - figured it out =) For some reason, looking at their scaffolding didn't work for me, but as soon as I tried to design the function from scratch I understood it.</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6989655,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindzey@gmail.com",
            "sender_full_name": "Laura Lindzey (she) (m1'19)",
            "sender_id": 2131,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "prob 2.32",
            "submessages": [],
            "timestamp": 1371583805,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/813126b0289ae35cb6de4ee22d838f962dcfadac?x=x&version=1",
            "client": "website",
            "content": "<p>If any of y'all are interested in pairing on SICP problems, I've skipped (and would love to go back and work on!):<br>\n1.28<br>\n1.45-1.46<br>\n2.13-2.16<br>\n2.38-2.39</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7219456,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "lindzey@gmail.com",
            "sender_full_name": "Laura Lindzey (she) (m1'19)",
            "sender_id": 2131,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "pairing",
            "submessages": [],
            "timestamp": 1372141316,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/513b96bfef3dcbee7604880ad96b4062?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'd be interested</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 61193787,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "Dwaynekj@gmail.com",
            "sender_full_name": "Dwayne Khallique Jones (F'12)",
            "sender_id": 915,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "pairing",
            "submessages": [],
            "timestamp": 1467147312,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/513b96bfef3dcbee7604880ad96b4062?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm redoing Chapter 1 and starting Chapter 2 in a couple of weeks. I'd love to work with you @Willson Mock</p>",
            "content_type": "text/html",
            "display_recipient": "sicp-summer2013",
            "flags": [
                "read",
                "historical"
            ],
            "id": 61193833,
            "is_me_message": false,
            "last_edit_timestamp": 1467147849,
            "reactions": [],
            "recipient_id": 22732,
            "sender_email": "Dwaynekj@gmail.com",
            "sender_full_name": "Dwayne Khallique Jones (F'12)",
            "sender_id": 915,
            "sender_realm_str": "recurse",
            "stream_id": 20332,
            "subject": "just starting",
            "submessages": [],
            "timestamp": 1467147367,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
