{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a3cd73ab58a2e01f6dada4ab99f3ae1b?d=identicon&version=1",
            "client": "desktop app Mac 0.4.3",
            "content": "<p>Oh man, David! are we really starting a group? I really can\u2019t sing btw, but i really like doing it. :) we all should go karaoke sometime!</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17343642,
            "is_me_message": false,
            "last_edit_timestamp": 1393027802,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "lita.cho@gmail.com",
            "sender_full_name": "Lita Cho (she) (W'14)",
            "sender_id": 5017,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "songs",
            "submessages": [],
            "timestamp": 1393027751,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/49d4d9cfe438630a83d7dc2ef9c3d35d174dbd5b?x=x&version=1",
            "client": "website",
            "content": "<p>(karaoke!)</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17344281,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "maja.frydrychowicz@gmail.com",
            "sender_full_name": "Maja Frydrychowicz (she) (W'14)",
            "sender_id": 5040,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "songs",
            "submessages": [],
            "timestamp": 1393028866,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "Android",
            "content": "<p>I guess so! We should come up with a traditional punny name. The Algorhythms?</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17357542,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "songs",
            "submessages": [],
            "timestamp": 1393054638,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "Android",
            "content": "<p>Is everyone interested in Let It Go as a first song? I might be able to put together an arrangement for five voices by Sunday afternoon...</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17357589,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "songs",
            "submessages": [],
            "timestamp": 1393054749,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "Android",
            "content": "<p>Do Sundays work for everyone as a regular singing time? What time of day might work best? I'm thinking something like 5pm, and go for an hour or until people get bored and hungry</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17357641,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1393054860,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "Android",
            "content": "<p>I can do PDFs engraved with Lilypond, but it's actually less work for me to make a bunch of audio tracks, one for each part, where that part is louder than the rest but still situated in context. (That's largely because I'm personally not fully fluent in Western musical notation so it takes a while for me to read and write.) I'm wondering what others' preferences might be for sheet-music vs. by-ear. (Are you a visual or auditory learner? :D)</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17357748,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "arrangement formats",
            "submessages": [],
            "timestamp": 1393055113,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/37641655de3d5700215259f7bbefe3cd?d=identicon&version=1",
            "client": "desktop app Mac 0.4.3",
            "content": "<p>I'd be down to sing on Sundays. Audio tracks would be way easier for me (I'm awfully slow at reading music). I'm a Baritone btw</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17378344,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "neeraj.wahi@gmail.com",
            "sender_full_name": "Neeraj Wahi (W'14)",
            "sender_id": 5037,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "arrangement formats",
            "submessages": [],
            "timestamp": 1393104076,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/49d4d9cfe438630a83d7dc2ef9c3d35d174dbd5b?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"david@dalrymple.co\">@David Dalrymple (W'14)</span> After much humming along with an Android piano app, I think my range is F3 to F5.  Wikipedia tells me this is contralto.</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17386928,
            "is_me_message": false,
            "last_edit_timestamp": 1393123184,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "maja.frydrychowicz@gmail.com",
            "sender_full_name": "Maja Frydrychowicz (she) (W'14)",
            "sender_id": 5040,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "songs",
            "submessages": [],
            "timestamp": 1393121823,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/49d4d9cfe438630a83d7dc2ef9c3d35d174dbd5b?x=x&version=1",
            "client": "website",
            "content": "<p>Climbing might be a recurring activity for some on Sunday afternoons. </p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17387824,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "maja.frydrychowicz@gmail.com",
            "sender_full_name": "Maja Frydrychowicz (she) (W'14)",
            "sender_id": 5040,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1393123601,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>Cool, thanks!</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17388135,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "songs",
            "submessages": [],
            "timestamp": 1393124160,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>BTW everyone, this is not going to happen today, due to lack of both (a) me having an arrangement for us yet and (b) responses about whether Sundays would be a good time / what time of day specifically might be good. But if it works for everyone, then we'll begin next Sunday <img alt=\":smiley:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/smiley.png\" title=\":smiley:\"></p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17412731,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1393183022,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b5e611f8d18382b05fa0a5b7e7517fdfa5b4c7c9?x=x&version=1",
            "client": "website",
            "content": "<p>Sundays in general are fine with me, although I will be out of town next Sunday (the 2nd). I also am highly amused by \"The Algorhythms\".</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17415969,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "matthew.avant@gmail.com",
            "sender_full_name": "Matthew Avant (W'14)",
            "sender_id": 5002,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1393190326,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/49d4d9cfe438630a83d7dc2ef9c3d35d174dbd5b?x=x&version=1",
            "client": "website",
            "content": "<p>Really any time is fine for me. Sundays are are fine but I will try to go climbing on Sunday mornings/early afternoons. </p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 17422528,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "maja.frydrychowicz@gmail.com",
            "sender_full_name": "Maja Frydrychowicz (she) (W'14)",
            "sender_id": 5040,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "schedule",
            "submessages": [],
            "timestamp": 1393202211,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>Hey <span class=\"user-mention\" data-user-email=\"*\">@all</span>! I'm going to try to finish my arrangement of \"Let it Go\" by 5pm today (Saturday) so that you'll have 24 hours to listen to the tracks. Hopefully there will be a one-to-one mapping of parts in the arrangement to people who want to sing such that everyone's in a range they're comfortable with.</p>\n<p>Does anyone who can come on Sunday have a solid F2? E2? I only go as low as F#2 and I prefer to stay above G2, but I also want to make use of any bass resources we might have ;)</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18090190,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "Singing March 9 at 5pm",
            "submessages": [],
            "timestamp": 1394264076,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/49d4d9cfe438630a83d7dc2ef9c3d35d174dbd5b?x=x&version=1",
            "client": "Android",
            "content": "<p>Exceptionally, I must miss this due to visitors. I hope there's another session in the future! </p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18099316,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "maja.frydrychowicz@gmail.com",
            "sender_full_name": "Maja Frydrychowicz (she) (W'14)",
            "sender_id": 5040,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "Singing March 9 at 5pm",
            "submessages": [],
            "timestamp": 1394286938,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a3cd73ab58a2e01f6dada4ab99f3ae1b?d=identicon&version=1",
            "client": "desktop app Mac 0.4.3",
            "content": "<p>excited to see what you come up with!</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18114003,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "lita.cho@gmail.com",
            "sender_full_name": "Lita Cho (she) (W'14)",
            "sender_id": 5017,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "Singing March 9 at 5pm",
            "submessages": [],
            "timestamp": 1394319047,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>thanks! yeah, sorry I didn't meet my deadline, didn't look like many people were on board with short notice anyway...</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18114013,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "Singing March 9 at 5pm",
            "submessages": [],
            "timestamp": 1394319080,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a3cd73ab58a2e01f6dada4ab99f3ae1b?d=identicon&version=1",
            "client": "desktop app Mac 0.4.3",
            "content": "<p>womp womp</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18114017,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "lita.cho@gmail.com",
            "sender_full_name": "Lita Cho (she) (W'14)",
            "sender_id": 5017,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "Singing March 9 at 5pm",
            "submessages": [],
            "timestamp": 1394319090,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"*\">@all</span> If anyone's planning to join me for singing today, let me know -- otherwise I'll punt to next weekend</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18138728,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "Singing March 9 at 5pm",
            "submessages": [],
            "timestamp": 1394373370,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b5e611f8d18382b05fa0a5b7e7517fdfa5b4c7c9?x=x&version=1",
            "client": "website",
            "content": "<p>Ah sorry, I just saw this. I could be there by six?</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18149500,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "matthew.avant@gmail.com",
            "sender_full_name": "Matthew Avant (W'14)",
            "sender_id": 5002,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "Singing March 9 at 5pm",
            "submessages": [],
            "timestamp": 1394398074,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"lita.cho@gmail.com\">@Lita Cho (W'14)</span> - check out this <a href=\"https://soundcloud.com/david-dalrymple-1/let-it-go-for-5-voices-draft/s-QwQuz\" target=\"_blank\" title=\"https://soundcloud.com/david-dalrymple-1/let-it-go-for-5-voices-draft/s-QwQuz\">preview</a></p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18163553,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1394427107,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a3cd73ab58a2e01f6dada4ab99f3ae1b?d=identicon&version=1",
            "client": "desktop app Mac 0.4.3",
            "content": "<p>I just saw your message, David!! This sounds AWESOME!! We should try to get this arranged! I am willing to participate in whatever range you think I would be good for! :D</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18183749,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "lita.cho@gmail.com",
            "sender_full_name": "Lita Cho (she) (W'14)",
            "sender_id": 5017,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1394465732,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>Thanks! :D By \"get this arranged,\" do you mean logistically? This audio is the direct result of me working on the musical arrangement ;)</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18183826,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1394465811,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a3cd73ab58a2e01f6dada4ab99f3ae1b?d=identicon&version=1",
            "client": "desktop app Mac 0.4.3",
            "content": "<p>yes!! logisically! Hopefully we can find enough people to be able to fulfill your musical arrangement! :D</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18184685,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "lita.cho@gmail.com",
            "sender_full_name": "Lita Cho (she) (W'14)",
            "sender_id": 5017,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1394466679,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "website",
            "content": "<p>gotcha (-:</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18184695,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1394466702,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b5e611f8d18382b05fa0a5b7e7517fdfa5b4c7c9?x=x&version=1",
            "client": "desktop app Linux 0.4.0",
            "content": "<p>Is there still interest in getting together and recording this?</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18514925,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "matthew.avant@gmail.com",
            "sender_full_name": "Matthew Avant (W'14)",
            "sender_id": 5002,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1395015347,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7fa3c19ae8d00435e94afd1ff19d92553c66eefa?x=x&version=1",
            "client": "Android",
            "content": "<p>Yeah, I've been a music slacker and haven't finished the arrangement (that preview is like half of it). But definitely still interested (=</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18515868,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "david@dalrymple.co",
            "sender_full_name": "David Dalrymple (W'14)",
            "sender_id": 5039,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1395017426,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a3cd73ab58a2e01f6dada4ab99f3ae1b?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>yea! can we practice what we have?</p>",
            "content_type": "text/html",
            "display_recipient": "singing",
            "flags": [
                "read",
                "historical"
            ],
            "id": 18787684,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 31985,
            "sender_email": "lita.cho@gmail.com",
            "sender_full_name": "Lita Cho (she) (W'14)",
            "sender_id": 5017,
            "sender_realm_str": "recurse",
            "stream_id": 25208,
            "subject": "\"Let  It Go\" arrangement",
            "submessages": [],
            "timestamp": 1395441500,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
