{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"130418\" href=\"/#narrow/stream/130418-social-.28los-angeles.29\">#social (los angeles)</a>.</p>\n<p><strong>Description</strong>: For real-life stuff in Los Angeles</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 129573369,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 130418,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1531443344,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>Ironically, though I just created this stream, I'm going to be out of town (that is, not in LA) until around the first of August. But after that, I'll be in Van Nuys/Lake Balboa.</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 129573492,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "Who's here?",
            "submessages": [],
            "timestamp": 1531443513,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>My wife and I were terrified that August was going to be a blast furnace after winter being so warm, but jeez, it's been really nice.</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 133083444,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "Who's here?",
            "submessages": [],
            "timestamp": 1535660150,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/541aab26abf25ac195df55d7e6c0f2daf3f00c70?x=x&version=1",
            "client": "website",
            "content": "<p>Hi y'all -- <a href=\"http://rubyconf.org/program#session-704\" target=\"_blank\" title=\"http://rubyconf.org/program#session-704\">this afternoon</a> <span class=\"user-mention\" data-user-id=\"100450\">@Jason Owen (W2'17)</span> and I present at RubyConf at the Millennium Biltmore, and then tonight we could hang out in the swanky lobby with Recursers if folks want to swing by!</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147686065,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "sumanah@fastmail.com",
            "sender_full_name": "Sumana Harihareswara (she) (F2'14)",
            "sender_id": 2909,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542217417,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>I would love to do this!</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147689207,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542220201,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>I can come to the Biltmore any time after 5 or 6, I'd say? Earlier would probably also be possible, I just have some errands to do.</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147694159,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542224790,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/541aab26abf25ac195df55d7e6c0f2daf3f00c70?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"9097\">@Joe Ardent (SP1'17)</span> Argh, I was looking out for @ mentions but did not see this, apologies. What neighborhood are you in?</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147757831,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "sumanah@fastmail.com",
            "sender_full_name": "Sumana Harihareswara (she) (F2'14)",
            "sender_id": 2909,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542302482,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/541aab26abf25ac195df55d7e6c0f2daf3f00c70?x=x&version=1",
            "client": "website",
            "content": "<p>Oh I just saw you said you are in Van Nuys</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147757906,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "sumanah@fastmail.com",
            "sender_full_name": "Sumana Harihareswara (she) (F2'14)",
            "sender_id": 2909,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542302552,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/541aab26abf25ac195df55d7e6c0f2daf3f00c70?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"9097\">@Joe Ardent (SP1'17)</span> I have dinner plans tonight but then actually need to find a place to sleep - my train out of LA Union Station is at 10am. On the off chance that you want to host me and then help me get to Union Station in the morning, let me know? I'm sorry for not seeing your message last night</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147758071,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "sumanah@fastmail.com",
            "sender_full_name": "Sumana Harihareswara (she) (F2'14)",
            "sender_id": 2909,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542302707,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"2909\">@Sumana Harihareswara (F2'14)</span> oh no! I'm sorry, I should have @'d . I didn't have the most spoons, though, so I'm marking all this under \"gave ol' college try: CHECK\".</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147765012,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "sumanah@fastmail.com",
                        "full_name": "Sumana Harihareswara (she) (F2'14)",
                        "id": 2909
                    },
                    "user_id": 2909
                }
            ],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542308937,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>I wish I could offer you a place, though, but alas, we live in 180 square feet :(</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147765046,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542308987,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/541aab26abf25ac195df55d7e6c0f2daf3f00c70?x=x&version=1",
            "client": "website",
            "content": "<p>No prob <span class=\"user-mention\" data-user-id=\"9097\">@Joe Ardent (SP1'17)</span>!</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 147765612,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "sumanah@fastmail.com",
            "sender_full_name": "Sumana Harihareswara (she) (F2'14)",
            "sender_id": 2909,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1542309458,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b202f821f765c631a1e6c253318e63b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Can I invite people to streams like this? <span class=\"user-mention\" data-user-id=\"2110\">@Eric Weinstein (S'13)</span></p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 165746274,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "sasha.laundy@gmail.com",
            "sender_full_name": "Sasha Laundy (she) (W'13)",
            "sender_id": 858,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1557948406,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b202f821f765c631a1e6c253318e63b?d=identicon&version=1",
            "client": "website",
            "content": "<p>looks like I can! (note that I didn't mean to put it in this topic, sorry!)</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 165746322,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "sasha.laundy@gmail.com",
            "sender_full_name": "Sasha Laundy (she) (W'13)",
            "sender_id": 858,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "hang out tonight?",
            "submessages": [],
            "timestamp": 1557948432,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5aabd314ef04424f0c9bba47684515639f3f07a8?x=x&version=2",
            "client": "website",
            "content": "<p>So I'm actually based in San Diego right now, but I was in LA for over a decade and I visit frequently. My batch recently ended and I'll be heading back to Cali next week. I was feeling very sad to leave RC, but then the weather took a turn and now I am SUPER EXCITED to be back where the temperatures are acceptable, haha. Anyway, just wanted to say hi and say that if anyone is in San Diego I'd love to chill sometime, and if there are ever any events in LA ya'll are going to, RC or otherwise, I'd love to know about them!</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 180672237,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "grassfedfarmboi@gmail.com",
            "sender_full_name": "Kristen C Ridley (any) (F1'19)",
            "sender_id": 234665,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "what's up SoCal?",
            "submessages": [],
            "timestamp": 1573678938,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/de77f903078392f528c684b8d0fed0aa8e641f51?x=x&version=4",
            "client": "website",
            "content": "<p>Welcome back Sten! Just found this  stream on zulip <span aria-label=\"joy\" class=\"emoji emoji-1f602\" role=\"img\" title=\"joy\">:joy:</span></p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 183770590,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "maryanne.wachter@gmail.com",
            "sender_full_name": "Maryanne Wachter (she) (F1'19)",
            "sender_id": 234168,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "what's up SoCal?",
            "submessages": [],
            "timestamp": 1576689848,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>/me waves hello from Los Angeles (Van Nuys, really, but I work in Playa Vista)</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 183771683,
            "is_me_message": true,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "what's up SoCal?",
            "submessages": [],
            "timestamp": 1576690608,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/de77f903078392f528c684b8d0fed0aa8e641f51?x=x&version=4",
            "client": "website",
            "content": "<p>I work in DTLA but live in Fullerton.</p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 183805896,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "maryanne.wachter@gmail.com",
            "sender_full_name": "Maryanne Wachter (she) (F1'19)",
            "sender_id": 234168,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "what's up SoCal?",
            "submessages": [],
            "timestamp": 1576716383,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>If the directory is not terribly out of date, there are a few of us in the area <a href=\"https://www.recurse.com/directory?location=Los+Angeles%2C+CA\" target=\"_blank\" title=\"https://www.recurse.com/directory?location=Los+Angeles%2C+CA\">https://www.recurse.com/directory?location=Los+Angeles%2C+CA</a></p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 183806139,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "what's up SoCal?",
            "submessages": [],
            "timestamp": 1576716717,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8f3e3f13689ac077fe4ae537e33bde345a57cb22?x=x&version=2",
            "client": "website",
            "content": "<p>Opening in West Hollywood, selling slices.</p>\n<p><a href=\"https://la.eater.com/2020/11/13/21564251/prince-street-pizza-new-york-city-open-inside-photos-pepperoni-famous-west-hollywood\">https://la.eater.com/2020/11/13/21564251/prince-street-pizza-new-york-city-open-inside-photos-pepperoni-famous-west-hollywood</a></p>",
            "content_type": "text/html",
            "display_recipient": "social (los angeles)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 216680882,
            "is_me_message": false,
            "last_edit_timestamp": 1605305491,
            "reactions": [],
            "recipient_id": 157779,
            "sender_email": "recurse@ardent.nebcorp.com",
            "sender_full_name": "Joe Ardent (he) (SP1'17)",
            "sender_id": 9097,
            "sender_realm_str": "recurse",
            "stream_id": 130418,
            "subject": "Prince Street Pizza",
            "submessages": [],
            "timestamp": 1605305436,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
