{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4a640d570251bb87bb6b20d02bd6f59e?d=identicon&version=1",
            "client": "website",
            "content": "<p>How'd Monday evenings work for you all? Maybe 6 PM EST every week?</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107202296,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "adityavkk@gmail.com",
            "sender_full_name": "Aditya Kumarakrishnan (SP1'17)",
            "sender_id": 100340,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Meeting days",
            "submessages": [],
            "timestamp": 1487212596,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a20417223b79ec491d7055be401b805573e86b35?x=x&version=1",
            "client": "website",
            "content": "<p>Works for me.</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107202528,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "arjan.singh@aya.yale.edu",
            "sender_full_name": "Arjan Singh (W1'16)",
            "sender_id": 895,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Meeting days",
            "submessages": [],
            "timestamp": 1487213101,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a20417223b79ec491d7055be401b805573e86b35?x=x&version=1",
            "client": "website",
            "content": "<p>How about material for the first meeting? Maybe the preface, basics, and induction sections? As for format: I'm thinking we'd each do however many exercises we have time for individually. Then, when we meet, we start with some discussion and end with working through a more difficult exercise together. How's that sound?</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107239575,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "arjan.singh@aya.yale.edu",
            "sender_full_name": "Arjan Singh (W1'16)",
            "sender_id": 895,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Meeting days",
            "submessages": [],
            "timestamp": 1487286693,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/4a640d570251bb87bb6b20d02bd6f59e?d=identicon&version=1",
            "client": "website",
            "content": "<p>Yeah, basics and induction sounds good</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107245400,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "adityavkk@gmail.com",
            "sender_full_name": "Aditya Kumarakrishnan (SP1'17)",
            "sender_id": 100340,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Meeting days",
            "submessages": [],
            "timestamp": 1487299419,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3510573a5aa248c6a2f1fcd58b043af7?d=identicon&version=1",
            "client": "website",
            "content": "<p><img alt=\":thumbs_up:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/thumbs_up.png\" title=\":thumbs_up:\">   Took me about 2 days to get my dev environment set up in emacs and work through those chapters.  Look forward to meeting on Monday!</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107275577,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "ajay.tungare@gmail.com",
            "sender_full_name": "Ajay Tungare (W2'17)",
            "sender_id": 100464,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Meeting days",
            "submessages": [],
            "timestamp": 1487363543,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6485c74622306264ff53449c6f0ca540?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hey folks; I'm starting at Recurse tomorrow and have worked through a bunch of the Software Foundations book (up to Hoare part 1, it looks like). Feel free to hit me up if you have questions and I'll try to help!</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 108811417,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "iain@mccoy.id.au",
            "sender_full_name": "Iain McCoy (he) (SP2'17)",
            "sender_id": 100806,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Incoming!",
            "submessages": [],
            "timestamp": 1490535533,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3510573a5aa248c6a2f1fcd58b043af7?d=identicon&version=1",
            "client": "website",
            "content": "<p>Hey Iain!  I worked up to just about the same point (through Equiv) over the last few weeks.  Would love to chat at some point --  I'll let you know when I'm around RC in the coming weeks!</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 108830040,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "ajay.tungare@gmail.com",
            "sender_full_name": "Ajay Tungare (W2'17)",
            "sender_id": 100464,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Incoming!",
            "submessages": [],
            "timestamp": 1490581089,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3510573a5aa248c6a2f1fcd58b043af7?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"iain@mccoy.id.au\" data-user-id=\"100806\">@Iain McCoy</span> enjoy your first day tomorrow!</p>",
            "content_type": "text/html",
            "display_recipient": "software foundations (cis 500)",
            "flags": [
                "read",
                "historical"
            ],
            "id": 108830041,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 102157,
            "sender_email": "ajay.tungare@gmail.com",
            "sender_full_name": "Ajay Tungare (W2'17)",
            "sender_id": 100464,
            "sender_realm_str": "recurse",
            "stream_id": 100487,
            "subject": "Incoming!",
            "submessages": [],
            "timestamp": 1490581105,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
