{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey guys! created the stream for stanford algos - shout out here if you ever want an algos break :)</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2400848,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1360684385,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f6bd929465d6d225def8062d5a9d3f3f?d=identicon&version=1",
            "client": "website",
            "content": "<p>I figured out what was confusing me. So, 2^(ab) = (2^a)^b, no? So, in our example, 2^(2n) = (2^2)^n = 4^n, which is why you need the f(n) vs. g(n) condition</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2415373,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "danluu@gmail.com",
            "sender_full_name": "Dan Luu (W'13)",
            "sender_id": 820,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1360712478,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f6bd929465d6d225def8062d5a9d3f3f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Thinking about it further, taking the log was making it more complicated. 4^n is obviously not O(2^n), but when we had 2n vs. n, 2n is O(n), but, since we took the log, and log(xy) = log(x) + log(y), the constant we get to choose is an additive constant [we have log(c) + n], which clearly isn't sufficient to 'beat' 2n.</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2434000,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "danluu@gmail.com",
            "sender_full_name": "Dan Luu (W'13)",
            "sender_id": 820,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1360762063,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey Dan - thanks! yeah I agree for the counterexample taking log was making it more complicated:<br>\nto show 2^(2n) &lt;= c * (2^n) for some constant c<br>\nsame as saying: (2^2)^n &lt;= c * (2^n)<br>\nso take the (1/n) root of both sides, leaving us with:<br>\n4 &lt;= c^(1/n) * 2<br>\ndivide 2 out, leaving us with 2 &lt;= c^(1/n)<br>\nraise both sides to the nth power, leaving us with 2^n &lt;= c which def can't be true for all n greater than some n_0.<br>\ni dont know if i did my math right =) but now i'd like to show this rigorously for the initial Q</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2434448,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1360763327,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>hmm ok so i think i have an idea of going about the original problem (i'm just trying to see how he derived f(n) needs to be less than g(n)) - i think it'll be easier to do on the board tho - let's meet!</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2434562,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1360763708,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f6bd929465d6d225def8062d5a9d3f3f?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm around now, if you want to meet before the check-in; otherwise, we could get together later, in case anyone else is interested.</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2436306,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "danluu@gmail.com",
            "sender_full_name": "Dan Luu (W'13)",
            "sender_id": 820,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1360768497,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey guys - we're gonna solve the problem right after checkin - hopefully in the same room we were in yesterday!</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2436762,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1360769439,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey guys - reminder for algos tmrw at 9:30a! as for status for me, i've finished week 2 mandatory lectures, hw, programming assignment - hopefully get to review the optional lectures tonight</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2607757,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1361221946,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b542b3a37377f22f8377a926b4bb88f6?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey guys - we are NOT having the 9:30a meeting tomorrow! we'll switch the time to be some point during the day going forward</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2619279,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "jin.chung17@gmail.com",
            "sender_full_name": "Jin Chung (m1'17)",
            "sender_id": 860,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1361251080,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b202f821f765c631a1e6c253318e63b?d=identicon&version=1",
            "client": "website",
            "content": "<p>To folks who have taken/are taking this course: I'm trying to decide whether to take the course or spend my time on other projects. <strong>Anyone up for chatting briefly to give me some perspective?</strong> Any time today would be great. </p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2633362,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "sasha.laundy@gmail.com",
            "sender_full_name": "Sasha Laundy (she) (W'13)",
            "sender_id": 858,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "pros and cons?",
            "submessages": [],
            "timestamp": 1361290513,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f6bd929465d6d225def8062d5a9d3f3f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Anyone want to go over last week's problems? I'm falling asleep and could use a break :-).</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2642581,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "danluu@gmail.com",
            "sender_full_name": "Dan Luu (W'13)",
            "sender_id": 820,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1361308999,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f583488b0ceaaef4a19844132a81ec9?d=identicon&version=1",
            "client": "website",
            "content": "<p>if anyone is interested in a few theory problems, we're heading to the side room to tackle them</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 2682017,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "dschobel@gmail.com",
            "sender_full_name": "Daniel Schobel (W'13)",
            "sender_id": 837,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "theory break",
            "submessages": [],
            "timestamp": 1361400931,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b202f821f765c631a1e6c253318e63b?d=identicon&version=1",
            "client": "website",
            "content": "<p>hey folks - am just starting week 1 of this course. am i supposed to watch all the videos before attempting the problem sets?</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3408236,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "sasha.laundy@gmail.com",
            "sender_full_name": "Sasha Laundy (she) (W'13)",
            "sender_id": 858,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "order?",
            "submessages": [],
            "timestamp": 1363123270,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f583488b0ceaaef4a19844132a81ec9?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Sasha</strong> yep</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3408612,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "dschobel@gmail.com",
            "sender_full_name": "Daniel Schobel (W'13)",
            "sender_id": 837,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "order?",
            "submessages": [],
            "timestamp": 1363123851,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b202f821f765c631a1e6c253318e63b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Wow, I found his explanation of big-O notation super confusing. This chapter makes it really straightforward.</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3443316,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "sasha.laundy@gmail.com",
            "sender_full_name": "Sasha Laundy (she) (W'13)",
            "sender_id": 858,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "O(n)",
            "submessages": [],
            "timestamp": 1363202265,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b202f821f765c631a1e6c253318e63b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Is anyone still working on this? It's only open for 10 more days</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3443323,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "sasha.laundy@gmail.com",
            "sender_full_name": "Sasha Laundy (she) (W'13)",
            "sender_id": 858,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "order?",
            "submessages": [],
            "timestamp": 1363202280,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/7b202f821f765c631a1e6c253318e63b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ugh forgot the link <a href=\"http://www.cs.berkeley.edu/~vazirani/algorithms/chap0.pdf\" target=\"_blank\" title=\"http://www.cs.berkeley.edu/~vazirani/algorithms/chap0.pdf\">http://www.cs.berkeley.edu/~vazirani/algorithms/chap0.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3443354,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "sasha.laundy@gmail.com",
            "sender_full_name": "Sasha Laundy (she) (W'13)",
            "sender_id": 858,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "O(n)",
            "submessages": [],
            "timestamp": 1363202291,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f583488b0ceaaef4a19844132a81ec9?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Sasha</strong> I think most of us fell off. I'm going to watch the videos + do the assignments after the PL class ends and I have more time</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3445830,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "dschobel@gmail.com",
            "sender_full_name": "Daniel Schobel (W'13)",
            "sender_id": 837,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "order?",
            "submessages": [],
            "timestamp": 1363206514,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/f6bd929465d6d225def8062d5a9d3f3f?d=identicon&version=1",
            "client": "website",
            "content": "<p>Oh, I missed this message, but, yeah, I'm still working on it. I just started the week 6 lectures. If anyone's caught up, I'm curious if it's possible to generalize the 2-SUM solution (provided in the lecture) to an N-SUM problem.</p>",
            "content_type": "text/html",
            "display_recipient": "stanford algos coursera",
            "flags": [
                "read",
                "historical"
            ],
            "id": 3586244,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 20215,
            "sender_email": "danluu@gmail.com",
            "sender_full_name": "Dan Luu (W'13)",
            "sender_id": 820,
            "sender_realm_str": "recurse",
            "stream_id": 18958,
            "subject": "order?",
            "submessages": [],
            "timestamp": 1363544899,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
