{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm in for a TAPL study group.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6547795,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370533062,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>sweet! @<strong>Javier Olaechea</strong> did you put your copy on the library bookshelf? If not, I think HS has a copy too, which brings us up to 3 copies locally</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6547914,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370533266,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p>Yeah I brought my Copy, the other copy is also right next to me, Muhaimin got it. He also wants to join us</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6547950,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370533327,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'd like to listen in with you guys too. Don't have a book, but hopefully I can figure something out.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548223,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370533841,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>Any idea when you'll start?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548285,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370534031,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>We could share books, right?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548294,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370534043,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>yes we can definitely share copies. we're planning to meet this evening (at 6:30) to talk about getting started. I'd like to cover at least the intro and prelim chapters before monday, to get out of the way any brushing up I need to do :)</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548374,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370534192,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>planning to meet at 6:30, unless someone has a conflict. we can resched if so, it was mostly arbitrary</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548381,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370534233,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>Any way we can start a bit earlier? I need to leave by 6:30...</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548803,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370535034,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>sure, is 6 ok for everyone? I don't think we will need to spend a lot of time, I just thought it might help to touch base as a group and organize sharing of the books for the weekend</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548850,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370535131,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>6 sounds good for me.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548861,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370535172,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>works for me too</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6548862,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370535178,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e91990a05dae45146efabc2920ea4e98?d=identicon&version=1",
            "client": "website",
            "content": "<p>Sounds good.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6549346,
            "is_me_message": false,
            "last_edit_timestamp": 1370536177,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "recurse@fezrev.com",
            "sender_full_name": "Muhaimin Ahsan (S'13)",
            "sender_id": 2135,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370536156,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm excited that people at HS want to read TAPL!  I'll bring my copy along for next week.  I had to read the whole thing for quals a couple of years ago and I refer to it pretty often, so I'd be happy to answer questions or just listen in.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6551321,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370539544,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>My cat is also interested in joining the study group: <a href=\"http://www.flickr.com/photos/lindseykuper/5254738681/\" target=\"_blank\" title=\"http://www.flickr.com/photos/lindseykuper/5254738681/\">http://www.flickr.com/photos/lindseykuper/5254738681/</a></p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6551330,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370539560,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Lindsey Kuper</strong> I think I'll be dropping out before Chapter 22, so your cat can borrow my copy after Chapter 9 or so.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6558021,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370551314,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p>6 is good for me</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6558077,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370551434,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>let's meet now to coordinate our first reading and how we're going to share books, in the main space</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6561052,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370557077,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p>*nods*</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6561286,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370557506,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p>BTW for reference, we reached agreemeent on reading the 3rd Chapter for tuesday and get toghther to discuss it</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6569610,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "B",
            "submessages": [],
            "timestamp": 1370576277,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>any TAPLers have questions I can help with?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6701790,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370899867,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>I certainly have a lot, though it might be best to save them for tomorrow when we meet to talk about chapt 3.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6701855,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370899959,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Peter France</strong> Sure, whatever you prefer.  What time does that meeting happen?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702104,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370900406,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>How about 4:30. Does that work @<strong>Javier Olaechea</strong> @<strong>Aki Yamada</strong> @<strong>Richard Harrington</strong>@<strong>Muhaimin Ahsan</strong> ?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702329,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "B",
            "submessages": [],
            "timestamp": 1370900853,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p>Sure thing</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702336,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370900872,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>that sounds good</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702377,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370900898,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>unless someone else was planning to, I'll send an email to the mailing list reserving the aquarium</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702395,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1370900960,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Peter France</strong> @<strong>Lindsey Kuper</strong> @<strong>Javier Olaechea</strong> @<strong>Aki Yamada</strong> @<strong>Muhaimin Ahsan</strong> @<strong>Sebastian Bauersfeld</strong> That works for me. Aki had talked earlier about trying to reserve the central room for 5, but 4:30 would be good too. We might need a lot of time.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702501,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370901150,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'd be happy with 5, too.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702504,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370901165,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Lindsey Kuper</strong> I have one quick question: When going over the set theory chapter (chapter 2), do you think it's important that I understand every little thing, or can I just skim it? I'm getting the basic gist; but a lot of the stuff is just new to me so I'll have to digest it as I go along.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702514,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370901229,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>If you did understand it perfectly you'd likely be the only one.<br>\nMaybe we could borrow @<strong>Erik Taubeneck</strong> if we have some problems with that part of it...</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702661,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370901490,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>@<strong>Richard Harrington</strong> can I see the part you're confused about?  want to come over?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702672,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "b",
            "submessages": [],
            "timestamp": 1370901504,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>I'm going to join in.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6702763,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "B",
            "submessages": [],
            "timestamp": 1370901694,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Took me *forever* to find this, but here's a good intro to Coq that, rather conveniently, covers more or less Chapter 3 of TAPL :)</p>\n<p><a href=\"http://www.cis.upenn.edu/~plclub/popl08-tutorial/code/coqdoc/CoqIntro.html\" target=\"_blank\" title=\"http://www.cis.upenn.edu/~plclub/popl08-tutorial/code/coqdoc/CoqIntro.html\">http://www.cis.upenn.edu/~plclub/popl08-tutorial/code/coqdoc/CoqIntro.html</a></p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6734780,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "coq intro",
            "submessages": [],
            "timestamp": 1370976193,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Man, I forgot how amazing this tutorial is. It blew my mind the first time, then I forgot everything, now it's blowing it again :)</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6735223,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "coq intro",
            "submessages": [],
            "timestamp": 1370976957,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>we're meeting in the aquarium now</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6738551,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "aquarium",
            "submessages": [],
            "timestamp": 1370982819,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>Anyone up for reading a chapter or two for Monday?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6820282,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "weekend-reading",
            "submessages": [],
            "timestamp": 1371165288,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Certified Programming with Dependent Types, another Coq resource: <a href=\"http://adam.chlipala.net/cpdt/\" target=\"_blank\" title=\"http://adam.chlipala.net/cpdt/\">http://adam.chlipala.net/cpdt/</a></p>\n<p>Insert my usual thing about mind blowing etc.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6881134,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "cpdt",
            "submessages": [],
            "timestamp": 1371316473,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>forgot to post this before, but after talking to a couple of people I think we should try to read through chapter 5 (ch 4 is an implementation chapter, and is short) for Tuesday. let's plan to touch base monday morning after checkins, if we're behind we can plan to meet wednesday instead</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6881706,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "next-steps",
            "submessages": [],
            "timestamp": 1371318107,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>This sounds good. </p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6882754,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "next-steps",
            "submessages": [],
            "timestamp": 1371321047,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's a verbose implementation of the exercise in Chapt 4 using python (as I'm not fluent enough in any pattern-matching language). It's probably a weird way to do it, but it works. <br>\nI'd be interested in any feedback. <a href=\"https://gist.github.com/ewestern/5789207\" target=\"_blank\" title=\"https://gist.github.com/ewestern/5789207\">https://gist.github.com/ewestern/5789207</a></p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6883752,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "chpt4",
            "submessages": [],
            "timestamp": 1371323811,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>Oops, the right link: <a href=\"https://gist.github.com/ewestern/5789237\" target=\"_blank\" title=\"https://gist.github.com/ewestern/5789237\">https://gist.github.com/ewestern/5789237</a></p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6883757,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "chpt4",
            "submessages": [],
            "timestamp": 1371323854,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>very nice! I've never used ply but I like how concise the parser/lexer looks. I don't really know much Python but could you refactor it so that <code>isnumerical</code> and <code>eval1</code> is a method on Term and its subclasses, removing the need for instanceof? That might be a more OOP and less verbose way to do it in Python, since you don't have pattern matching etc.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6883904,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "chpt4",
            "submessages": [],
            "timestamp": 1371324246,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>Good point. Couldn't get rid of all the isinstance but gist refactored as suggested.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6884533,
            "is_me_message": false,
            "last_edit_timestamp": 1371325967,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "chpt4",
            "submessages": [],
            "timestamp": 1371325954,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>cool, tbh I'm kind of an OOP noob, so I'm not sure how else to improve it :)</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6884705,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "chpt4",
            "submessages": [],
            "timestamp": 1371326432,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>You guys want to plan to meet on chapters 4&amp;5 this week? How does Wednesday @ 4 sound?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6962028,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "4&5",
            "submessages": [],
            "timestamp": 1371519452,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>@<strong>Peter France</strong> that sounds good to me</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 6962071,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "4&5",
            "submessages": [],
            "timestamp": 1371519562,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>Sounds good to me.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7020340,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371655828,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p>So at what time is the meeting today? 4?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7028544,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371671047,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>yes, I plan to start a little early to talk about the lambda calculus with some people who expressed interest but have not been following along with TAPL</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7028631,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371671194,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0f54d6b36e7d83288a5f02d33bafa014?d=identicon&version=1",
            "client": "website",
            "content": "<p>So at what time are you going to start?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7028840,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pirata@gmail.com",
            "sender_full_name": "Javier Ernesto Olaechea (S'13)",
            "sender_id": 2157,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371671548,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/8fd1196806c87c4732993c77362452f3?d=identicon&version=1",
            "client": "website",
            "content": "<p>Just to review: Tentatively planning on meeting next Wednesday with a functional interpreter based on chapts 5-7. Will touch base on Tuesday to make sure everyone is on track.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7031336,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "pfrance@gmail.com",
            "sender_full_name": "Peter France (S'13)",
            "sender_id": 2164,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "(no subject)",
            "submessages": [],
            "timestamp": 1371676320,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>hey guys, this kind of slipped off my radar for today, shall we meet tomorrow?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7279844,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "tomorrow?",
            "submessages": [],
            "timestamp": 1372277659,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5b65284e717ae0b857be0040ec9649840d256672?x=x&version=1",
            "client": "website",
            "content": "<p>sounds good to me</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7279854,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "veriathon@gmail.com",
            "sender_full_name": "James Wang (S'13)",
            "sender_id": 2103,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "tomorrow?",
            "submessages": [],
            "timestamp": 1372277695,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5b65284e717ae0b857be0040ec9649840d256672?x=x&version=1",
            "client": "website",
            "content": "<p>I've been writing my lambda interpreter and have discovered that I don't understand a rather fundamental property in lambda calculus notation. For lambda expressions, are the terms of the abstraction denoted by parentheses? Must they ONLY be denoted by parentheses?</p>\n<p>e.g.  \u03bbz. z x<br>\nIs this an expression with \"z\" as a binder and \"z x\" as its body/term?  If this is so, this is the full reduction of the expression.</p>\n<p>Or is this equivalent to:</p>\n<p>(\u03bbz. z) x<br>\nwhere this is actually an identity function that reduces ultimately to \"x\"</p>\n<p>Is it specifically and ONLY parentheses that denote lambda-abstraction bodies?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7694924,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "veriathon@gmail.com",
            "sender_full_name": "James Wang (S'13)",
            "sender_id": 2103,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373304405,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5b65284e717ae0b857be0040ec9649840d256672?x=x&version=1",
            "client": "website",
            "content": "<p>Eh, I'm currently incorporating paren-required as part of my interpreter, since it makes more sense to me, but is anyone else still on this stream? :P</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7698603,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "veriathon@gmail.com",
            "sender_full_name": "James Wang (S'13)",
            "sender_id": 2103,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373311181,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>I think that <code>\u03bbz. z x</code> would be an abstraction with <code>z x</code> as it's body. anything else would require parens to differentiate</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699371,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373312630,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>The usual concrete syntax I've seen is that the body of the abstraction extends as far left as possible after the <code>.</code></p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699419,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373312663,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>that is, after the \"dot\"</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699420,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373312673,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>furthermore, cheating and looking at B Pierce's parser, it looks like parens are not required for an abstraction:</p>\n<div class=\"codehilite\"><pre>Term :\n    AppTerm\n      { $1 }\n  | LAMBDA LCID DOT Term \n      { fun ctx -&gt;\n          let ctx1 = addname ctx $2.v in\n          TmAbs($1, $2.v, $4 ctx1) }\n  | LAMBDA USCORE DOT Term \n      { fun ctx -&gt;\n          let ctx1 = addname ctx &quot;_&quot; in\n          TmAbs($1, &quot;_&quot;, $4 ctx1) }\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699612,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313106,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>This is some kind of YACC-like parser generator code... I don't know ocaml-yacc or whatever it is but I think this is saying a <code>Term</code> is an <code>AppTerm</code> or something starting with <code>LAMBDA</code>. notice how the body of the lambda is just a <code>Term</code>.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699666,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313180,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"spacemanaki@gmail.com\">@Aki Yamada</span> <span class=\"user-mention\" data-user-email=\"veriathon@gmail.com\">@James Wang</span> I believe Aki meant to say that the body of the abstraction extends as far RIGHT as possible after the dot. That's about as much as I remember from before I stopped reading TAPL, but I remember it very well because I had to keep reminding myself of that rule while parsing expressions in my head.  With that rule, and with left associativity in function application, parentheses are unnecessary. I think.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699863,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313575,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"harrington.richard@gmail.com\">@Richard Harrington</span> right you are, I meant right ;) my other left.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699914,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313614,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>That's correct; if there's a dot, the body of the abstraction extends as far right as possible after that.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699924,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313638,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>The Wikipedia page actually has an excellent set of bullet points on this exact topic:</p>\n<p>Outermost parentheses are dropped: M N instead of (M N)<br>\nApplications are left associative: M N P may be written instead of ((M N) P)[6]<br>\nThe body of an abstraction extends as far right as possible: \u03bbx.M N means \u03bbx.(M N) and not (\u03bbx.M) N<br>\nA sequence of abstractions is contracted: \u03bbx.\u03bby.\u03bbz.N may be abbreviated as \u03bbxyz.N[7][8]</p>\n<p><a href=\"http://en.wikipedia.org/wiki/Lambda_calculus#Definition\" target=\"_blank\" title=\"http://en.wikipedia.org/wiki/Lambda_calculus#Definition\">http://en.wikipedia.org/wiki/Lambda_calculus#Definition</a> (scroll down to \"Notational Conventions\")</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7699945,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313679,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's an article from one of my undergrad profs that I found helpful when I was first learning (and re-learning) this stuff: <a href=\"http://www.math.grin.edu/~stone/courses/languages/lambda-calculus.pdf\" target=\"_blank\" title=\"http://www.math.grin.edu/~stone/courses/languages/lambda-calculus.pdf\">http://www.math.grin.edu/~stone/courses/languages/lambda-calculus.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700053,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313853,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/57ad6b289d2b066f6497c2c7a542f246?d=identicon&version=1",
            "client": "website",
            "content": "<p>(I like the historical sidebar about the lambda and the circumflex.  It makes it clear just how arbitrary notation is.)</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700061,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "lindsey@composition.al",
            "sender_full_name": "Lindsey Kuper (she)",
            "sender_id": 2170,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313887,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>(please ignore the wikipedia footnotes in brackets, in my cut and paste from wikipedia)</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700063,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313889,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"lindsey@composition.al\">@Lindsey Kuper</span> I will definitely read that.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700075,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373313919,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5b65284e717ae0b857be0040ec9649840d256672?x=x&version=1",
            "client": "website",
            "content": "<p>Great, that makes sense to me. It looked like TAPL basically did that, but I couldn't be entirely sure based on the examples given (I'm really not familiar with trying to mentally parse these types of symbolic notations... for some reason, even though I've done a fair amount of formal logic).</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700269,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "veriathon@gmail.com",
            "sender_full_name": "James Wang (S'13)",
            "sender_id": 2103,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373314243,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/5b65284e717ae0b857be0040ec9649840d256672?x=x&version=1",
            "client": "website",
            "content": "<p>Also wanted to see if anyone else was still on this stream, since I don't think I heard about the TAPL meeting the past Wed... is the group still going?</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700272,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "veriathon@gmail.com",
            "sender_full_name": "James Wang (S'13)",
            "sender_id": 2103,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373314255,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/b9cde908e7fad091591e1063c830b9be?d=identicon&version=1",
            "client": "website",
            "content": "<p>Oh my god that's crazy (I just read the beginning of the paper about the lambdas and the circumflexes).<br>\nI have always thought that the reckless and rampant use of the Greek alphabet in math and the sciences has turned many people away from those disciplines over the years. When trying to do something at the limits of one's intellectual capacity, having to deal with symbols expressed in what is, to almost all students in the modern world, gibberish, can be the straw the breaks the camel's back.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700284,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "harrington.richard@gmail.com",
            "sender_full_name": "Richard Harrington (S'13)",
            "sender_id": 2162,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373314269,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7a59c708d63d6e411127984a042dfe273ce90e04?x=x&version=1",
            "client": "website",
            "content": "<p>I haven't given up on TAPL yet</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7700408,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "spacemanaki@gmail.com",
            "sender_full_name": "Aki Yamada (S'13)",
            "sender_id": 2118,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "lambda-expressions",
            "submessages": [],
            "timestamp": 1373314490,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6fcf78ff016b9e89d65cf5108925915a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Some of Simon Peyton-Jones papers are nice at giving intuition about type systems for people with more of a compiler rather than formal background. I like these two: <a href=\"http://research.microsoft.com/apps/pubs/default.aspx?id=67066\" target=\"_blank\" title=\"http://research.microsoft.com/apps/pubs/default.aspx?id=67066\">http://research.microsoft.com/apps/pubs/default.aspx?id=67066</a> and <a href=\"http://research.microsoft.com/en-us/um/people/simonpj/papers/higher-rank/\" target=\"_blank\" title=\"http://research.microsoft.com/en-us/um/people/simonpj/papers/higher-rank/\">http://research.microsoft.com/en-us/um/people/simonpj/papers/higher-rank/</a> -- it should be fun to try writing a small dependent type system based on Henk.</p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7753205,
            "is_me_message": false,
            "last_edit_timestamp": 1373427607,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "nada.amin@gmail.com",
            "sender_full_name": "Nada Amin",
            "sender_id": 2178,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1373427588,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6fcf78ff016b9e89d65cf5108925915a?d=identicon&version=1",
            "client": "website",
            "content": "<p>Here's a link to the Henk pdf: <a href=\"http://research.microsoft.com/en-us/um/people/emeijer/Papers/Henk.pdf\" target=\"_blank\" title=\"http://research.microsoft.com/en-us/um/people/emeijer/Papers/Henk.pdf\">http://research.microsoft.com/en-us/um/people/emeijer/Papers/Henk.pdf</a></p>",
            "content_type": "text/html",
            "display_recipient": "tapl",
            "flags": [
                "read",
                "historical"
            ],
            "id": 7755381,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 22698,
            "sender_email": "nada.amin@gmail.com",
            "sender_full_name": "Nada Amin",
            "sender_id": 2178,
            "sender_realm_str": "recurse",
            "stream_id": 20318,
            "subject": "resources",
            "submessages": [],
            "timestamp": 1373432488,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
