{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/588ed93f75988b1639513ccd77a2f1930ed980a1?x=x&version=4",
            "client": "website",
            "content": "<p>A while ago I transitioned from being most comfortable doing backend development to being comfortable doing \"full-stack\" development. By this I mean I got a lot of experience using things like Compass/Sass, CSS, Twitter Bootstrap, AngularJS, Bower, Yeoman, etc., and in general would be able to make a decent-looking web site from back to front by myself (including user interface and interaction design) rather than having to get someone else to help.</p>\n<p>But my current visual design skills only take me so far. I can effectively put together fonts, stock photos, and Twitter Bootstrap building blocks and create a decent custom theme / overall style, but if I had to design a logo or otherwise do any serious Photoshop- or Illustrator-type work, I think I'd be out of my depth.</p>\n<p>It'd be great to make progress in this last frontier of \"full-stack\"ness! (\"Full-stack design\"?)</p>\n<p>If anyone who already has these skills has any recommendations for leveling up, or just wants to share their path to enlightenment, I'd much appreciate hearing! I was originally just going to ask <span class=\"user-mention\" data-user-email=\"sonali@hackerschool.com\">@Sonali Sridhar</span> in a private message, but then I figured others might have or want tips too.</p>\n<p>Thanks for reading!</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33553833,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "jabronson@gmail.com",
            "sender_full_name": "Josh Bronson (he) (m1'17)",
            "sender_id": 910,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421080992,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/588ed93f75988b1639513ccd77a2f1930ed980a1?x=x&version=4",
            "client": "website",
            "content": "<p>P.S. I just created this stream specially for this question as there didn't seem to be a place for it already. Hope people find the new stream useful!</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33553924,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "jabronson@gmail.com",
            "sender_full_name": "Josh Bronson (he) (m1'17)",
            "sender_id": 910,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "new stream!",
            "submessages": [],
            "timestamp": 1421081115,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/c6ce30644b997263ca5bcdd28f1c26f1b772d87d?x=x&version=1",
            "client": "website",
            "content": "<p>Universal Principles of Design is a great reference <br>\n<a href=\"http://www.amazon.com/Universal-Principles-Design-William-Lidwell/dp/1592530079\" target=\"_blank\" title=\"http://www.amazon.com/Universal-Principles-Design-William-Lidwell/dp/1592530079\">http://www.amazon.com/Universal-Principles-Design-William-Lidwell/dp/1592530079</a></p>\n<p>Inkscape is a great free tool you can use to create  SVG designs and logos</p>\n<p>This is a cool video of one designer's process. <a href=\"http://sploid.gizmodo.com/this-is-how-professional-designers-create-their-logos-1670238403\" target=\"_blank\" title=\"http://sploid.gizmodo.com/this-is-how-professional-designers-create-their-logos-1670238403\">http://sploid.gizmodo.com/this-is-how-professional-designers-create-their-logos-1670238403</a></p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33554012,
            "is_me_message": false,
            "last_edit_timestamp": 1421081646,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "nate@nfoster.net",
            "sender_full_name": "Nathaniel Joshua Foster (W2'15)",
            "sender_id": 7101,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421081206,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/588ed93f75988b1639513ccd77a2f1930ed980a1?x=x&version=4",
            "client": "website",
            "content": "<p>Thanks <span class=\"user-mention\" data-user-email=\"nate@nfoster.net\">@Nathaniel Foster</span>, look forward to checking those out!</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33554695,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "jabronson@gmail.com",
            "sender_full_name": "Josh Bronson (he) (m1'17)",
            "sender_id": 910,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421082187,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f8ddedf593eefcabbc13434b183e7d7?d=identicon&version=1",
            "client": "website",
            "content": "<p>You're basically the target audience for <a href=\"http://designforhackers.com/\" target=\"_blank\" title=\"http://designforhackers.com/\">Design for Hackers</a>. :) I haven't read the whole book but I liked his blog/email content. (I am a designer-turned-developer, though not really a graphic designer.)</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33554803,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "allie.jones@gmail.com",
            "sender_full_name": "Allie Jones (she/they) (W'13)",
            "sender_id": 821,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421082346,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f8ddedf593eefcabbc13434b183e7d7?d=identicon&version=1",
            "client": "website",
            "content": "<p>Though I think most of it is about typography, so maybe that's not what you'd need help with.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33554851,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "allie.jones@gmail.com",
            "sender_full_name": "Allie Jones (she/they) (W'13)",
            "sender_id": 821,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421082382,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f8ddedf593eefcabbc13434b183e7d7?d=identicon&version=1",
            "client": "website",
            "content": "<p>I learned Photoshop and Illustrator from <a href=\"http://Lynda.com\" target=\"_blank\" title=\"http://Lynda.com\">Lynda.com</a> tutorials, but beyond knowing the tools, I feel like being a good designer mostly requires looking at a lot of good/interesting work by others, practicing a lot and trying to get feedback from other people.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33554955,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "allie.jones@gmail.com",
            "sender_full_name": "Allie Jones (she/they) (W'13)",
            "sender_id": 821,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421082548,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f8ddedf593eefcabbc13434b183e7d7?d=identicon&version=1",
            "client": "website",
            "content": "<p>Logo Design Love is an interesting book about designing logos, specifically, also.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33555037,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "allie.jones@gmail.com",
            "sender_full_name": "Allie Jones (she/they) (W'13)",
            "sender_id": 821,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421082649,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a604f6425b41d724539755eb2c457f29536f16d9?x=x&version=2",
            "client": "website",
            "content": "<p>+1 to all of what <span class=\"user-mention\" data-user-email=\"allie.jones@gmail.com\">@Allie Jones (W'13)</span> says here. I'm a  pretty conservative (classical) designer. I spent a lot of my youth rebelling the grid and now I'm +1000 for it. I think most of the huge image, bootstrap sites struggle to be interesting. Looking at a lot of interactions and seeing what capture you is interesting. So basically it's a lot more research than actual drawing.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33555850,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "sonali@recurse.com",
            "sender_full_name": "Sonali Sridhar",
            "sender_id": 812,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421083608,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f8ddedf593eefcabbc13434b183e7d7?d=identicon&version=1",
            "client": "website",
            "content": "<p>Also, as far as modern web stuff is concerned, animation and UI transitions seem so important! I'm currently working on learning more about motion design myself. :)</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33556074,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "allie.jones@gmail.com",
            "sender_full_name": "Allie Jones (she/they) (W'13)",
            "sender_id": 821,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421083897,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6f8ddedf593eefcabbc13434b183e7d7?d=identicon&version=1",
            "client": "website",
            "content": "<p>Things like <a href=\"http://metafizzy.co/blog/initial-demos/\" target=\"_blank\" title=\"http://metafizzy.co/blog/initial-demos/\">this blog post series</a> or all of the demos on <a href=\"http://tympanus.net/codrops/\" target=\"_blank\" title=\"http://tympanus.net/codrops/\">Codrops</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 33556128,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "allie.jones@gmail.com",
            "sender_full_name": "Allie Jones (she/they) (W'13)",
            "sender_id": 821,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "leveling up",
            "submessages": [],
            "timestamp": 1421083935,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Anyone here? What\u2019s the logo that comes into your mind when you think about <strong>gist/summary</strong> of something?</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37794272,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428422732,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>I would think of somthing like an <a href=\"http://thumb7.shutterstock.com/display_pic_with_logo/1071689/133826249/stock-vector-black-silhouette-of-open-book-vector-illustration-133826249.jpg\" target=\"_blank\" title=\"http://thumb7.shutterstock.com/display_pic_with_logo/1071689/133826249/stock-vector-black-silhouette-of-open-book-vector-illustration-133826249.jpg\">open book</a></p>\n<div class=\"message_inline_image\"><a href=\"http://thumb7.shutterstock.com/display_pic_with_logo/1071689/133826249/stock-vector-black-silhouette-of-open-book-vector-illustration-133826249.jpg\" target=\"_blank\" title=\"http://thumb7.shutterstock.com/display_pic_with_logo/1071689/133826249/stock-vector-black-silhouette-of-open-book-vector-illustration-133826249.jpg\"><img src=\"https://external-content.zulipcdn.net/dbf74f35f12ebea939d9acf2fdaa07adc397537a/687474703a2f2f7468756d62372e7368757474657273746f636b2e636f6d2f646973706c61795f7069635f776974685f6c6f676f2f313037313638392f3133333832363234392f73746f636b2d766563746f722d626c61636b2d73696c686f75657474652d6f662d6f70656e2d626f6f6b2d766563746f722d696c6c757374726174696f6e2d3133333832363234392e6a7067\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37794493,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428423015,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>otherwise, when I searched for images of 'summary' I got this <a href=\"http://www.bregsforum.com/wp-content/uploads/2015/01/summary1.png\" target=\"_blank\" title=\"http://www.bregsforum.com/wp-content/uploads/2015/01/summary1.png\">check list</a> which isn't great, but isn't too bad, either</p>\n<div class=\"message_inline_image\"><a href=\"http://www.bregsforum.com/wp-content/uploads/2015/01/summary1.png\" target=\"_blank\" title=\"http://www.bregsforum.com/wp-content/uploads/2015/01/summary1.png\"><img src=\"https://external-content.zulipcdn.net/3b262d39669b9934ae73c53f12431735fb805957/687474703a2f2f7777772e6272656773666f72756d2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031352f30312f73756d6d617279312e706e67\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37794520,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428423066,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e08fe80fd3eb696b931b953b25d789d9?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>I would think of something more like a list.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37794523,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "coleamurphy@gmail.com",
            "sender_full_name": "Cole Murphy (she) (m2'18)",
            "sender_id": 7859,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428423072,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e08fe80fd3eb696b931b953b25d789d9?d=identicon&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Right, something less involved than a book. Something you can consult and get answers from quickly.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37794540,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "coleamurphy@gmail.com",
            "sender_full_name": "Cole Murphy (she) (m2'18)",
            "sender_id": 7859,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428423095,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Hm, I\u2019d never thought of a list\u2026</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37794595,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428423146,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Interesting\u2026</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37794603,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428423164,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>The project is called <strong>Music Gist</strong>.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795607,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424607,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>What do you think of something like this?</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795613,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424615,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><a href=\"https://www.dropbox.com/s/70esvdk0vnnrjuh/Screenshot%202015-04-07%2012.36.08.png?dl=0\" target=\"_blank\" title=\"https://www.dropbox.com/s/70esvdk0vnnrjuh/Screenshot%202015-04-07%2012.36.08.png?dl=0\">https://www.dropbox.com/s/70esvdk0vnnrjuh/Screenshot%202015-04-07%2012.36.08.png?dl=0</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.dropbox.com/s/70esvdk0vnnrjuh/Screenshot%202015-04-07%2012.36.08.png?dl=0\" target=\"_blank\" title=\"Screenshot 2015-04-07 12.36.08.png\"><img src=\"https://www.dropbox.com/s/70esvdk0vnnrjuh/Screenshot%202015-04-07%2012.36.08.png?dl=1\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795614,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424616,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>old school</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795720,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424768,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>maybe a little too much, people might not recognize the cassette tape :P</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795735,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424785,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>True :P</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795737,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424793,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>I do like it, though</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795803,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424845,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>and hipsters would love the cassette tape vibe</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795810,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424867,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>:D</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37795830,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428424918,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Well, for now, I think I\u2019ll work using this, I believe it will fit perfectly on the design: <a href=\"https://www.dropbox.com/s/byhdba7g4me86hx/Screenshot%202015-04-07%2012.45.29.png?dl=0\" target=\"_blank\" title=\"https://www.dropbox.com/s/byhdba7g4me86hx/Screenshot%202015-04-07%2012.45.29.png?dl=0\">https://www.dropbox.com/s/byhdba7g4me86hx/Screenshot%202015-04-07%2012.45.29.png?dl=0</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.dropbox.com/s/byhdba7g4me86hx/Screenshot%202015-04-07%2012.45.29.png?dl=0\" target=\"_blank\" title=\"Screenshot 2015-04-07 12.45.29.png\"><img src=\"https://www.dropbox.com/s/byhdba7g4me86hx/Screenshot%202015-04-07%2012.45.29.png?dl=1\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 37796000,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "Logo ideas",
            "submessages": [],
            "timestamp": 1428425157,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><a href=\"http://100daysoffonts.com\" target=\"_blank\" title=\"http://100daysoffonts.com\">This is amazing</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38429993,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429619826,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>beautiful!</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38433808,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429626366,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>when designing websites, I still don't fully understand how you can ensure that the browser will be able to display the exact font - isn't it a licensing issue?</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38433860,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429626437,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>is that different with google fonts?</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38433867,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429626450,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>The implementation is pretty na\u00efve (I\u2019m wondering how long it will take for the full website to load in a few more weeks, since (s)he\u2019s requesting every font at the start), but nevertheless it looks amazing\u2026</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38433872,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429626461,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"heidi.kasemir@gmail.com\">@Heidi Kasemir (SP2'15)</span>, yeah, most of the fonts are from Google:</p>\n<div class=\"codehilite\"><pre>&lt;!--Start Day Thirteen Google Fonts--&gt;\n&lt;link href=&#39;http://fonts.googleapis.com/css?family=Playfair+Display+SC:700italic&#39; rel=&#39;stylesheet&#39; type=&#39;text/css&#39;&gt;\n&lt;link href=&#39;http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&#39; rel=&#39;stylesheet&#39; type=&#39;text/css&#39;&gt;\n&lt;link href=&#39;http://weloveiconfonts.com/api/?family=fontawesome&#39; rel=&#39;stylesheet&#39; type=&#39;text/css&#39;&gt;\n</pre></div>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38434040,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429626633,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ba7bc529cc30f74dd3c34c1805f02cb9c16d087c?x=x&version=1",
            "client": "website",
            "content": "<p>oh I see, like she's linking the fonts in through google - by the end she'll have 200 links</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38434042,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "heidi.kasemir@gmail.com",
            "sender_full_name": "Heidi Kasemir (SP2'15)",
            "sender_id": 7853,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429626641,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Yeah, I\u2019m wondering if it will even work when (s)he gets to ~70 fonts\u2026</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38434711,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429627679,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a604f6425b41d724539755eb2c457f29536f16d9?x=x&version=2",
            "client": "website",
            "content": "<p>interesting!!!</p>",
            "content_type": "text/html",
            "display_recipient": "visual design",
            "flags": [
                "read",
                "historical"
            ],
            "id": 38455097,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 38154,
            "sender_email": "sonali@recurse.com",
            "sender_full_name": "Sonali Sridhar",
            "sender_id": 812,
            "sender_realm_str": "recurse",
            "stream_id": 26433,
            "subject": "#100daysoffonts",
            "submessages": [],
            "timestamp": 1429651457,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
