{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://secure.gravatar.com/avatar/48bee62bf5815a31a0102e4f7110b630?d=identicon&version=1",
            "client": "website",
            "content": "<p>is this the right stream?</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 52928712,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "matthewhl@gmail.com",
            "sender_full_name": "Matthew Long (W'14)",
            "sender_id": 5018,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1454425199,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>YAAASSS!!!! announcement forthcoming tomorrow to invite more folks to join! (we had a lot of resting and catching up to do after a weekend full of prepping to give a Big Scary Talk :D)</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 52956034,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1454470912,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/7d2ab014ebf55e99afffba1a3d92be8155754f0f?x=x&version=1",
            "client": "website",
            "content": "<p>did I miss a thing?</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 52957390,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "kamal@marhubi.com",
            "sender_full_name": "Kamal Marhubi (he) (m2'18)",
            "sender_id": 8090,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1454474017,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>we gave a Monday Night Talk!</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 52972053,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1454509432,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>it was scary but everyone loved us so it turned out to be fine! &lt;3</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 52972073,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1454509444,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>also, we created this stream at the end of the talk for people who wanted to learn more about / contribute to the project.</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 52972091,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1454509468,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>first thing on my to-do list this AM is to subscribe <span class=\"user-mention\" data-user-email=\"outofthemadness@gmail.com\">@James A. Keene (W1'14)</span> and <span class=\"user-mention\" data-user-email=\"madelyn.freed@gmail.com\">@Madelyn Ruth Freed (S2'15)</span> (check!) and properly announce it to the rest of zulip. (pending.)</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 52972115,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1454509519,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a78e978f32de66044a4fb81c65744abd?d=identicon&version=1",
            "client": "website",
            "content": "<p>Would like to test it, but play store not allowed me to instal, says it not available in your country. (Russia)</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53264143,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "kl.vlad@gmail.com",
            "sender_full_name": "Vladimir Klekovkin (W2'16)",
            "sender_id": 8977,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1455141961,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/1c860d00a4cedc01147fbb2e0533c37b?d=identicon&version=1",
            "client": "desktop app Mac 0.5.1",
            "content": "<p>I would love to contribute, do you have a place where you track issues and diagram bugs that are fodder for outside contributors?</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53264821,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "corydominguez@gmail.com",
            "sender_full_name": "Cory Michael Dominguez (he) (SP1'15)",
            "sender_id": 7625,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455143372,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/a78e978f32de66044a4fb81c65744abd?d=identicon&version=1",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"corydominguez@gmail.com\">@Cory Dominguez (SP1'15)</span> , probably you should check <a href=\"https://github.com/whereat\" target=\"_blank\" title=\"https://github.com/whereat\">https://github.com/whereat</a></p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53265052,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "kl.vlad@gmail.com",
            "sender_full_name": "Vladimir Klekovkin (W2'16)",
            "sender_id": 8977,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455143813,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/1c860d00a4cedc01147fbb2e0533c37b?d=identicon&version=1",
            "client": "desktop app Mac 0.5.1",
            "content": "<p>You're right I found it in the wiki</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53265373,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "corydominguez@gmail.com",
            "sender_full_name": "Cory Michael Dominguez (he) (SP1'15)",
            "sender_id": 7625,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455144461,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/1c860d00a4cedc01147fbb2e0533c37b?d=identicon&version=1",
            "client": "desktop app Mac 0.5.1",
            "content": "<p>I still don't see any bugs or product proposals for contributors to sink their teeth into.</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53267247,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "corydominguez@gmail.com",
            "sender_full_name": "Cory Michael Dominguez (he) (SP1'15)",
            "sender_id": 7625,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455148931,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/1c860d00a4cedc01147fbb2e0533c37b?d=identicon&version=1",
            "client": "desktop app Mac 0.5.1",
            "content": "<p>Although I guess with all the documentation I can get curious</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53267266,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "corydominguez@gmail.com",
            "sender_full_name": "Cory Michael Dominguez (he) (SP1'15)",
            "sender_id": 7625,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455148965,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>^^^ <span class=\"user-mention\" data-user-email=\"corydominguez@gmail.com\">@Cory Dominguez (SP1'15)</span> we're working hard on this! right now the main thing we're working on re: contributors is making sure we can get a nice hassle-free dev box (docker, etc...) for folks. turns out that takes a while.... but it's high on the to-do list to start translating our user story cards to github issues that folks outside the team could pickup!</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53271540,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455162352,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>ATM: we also just onboarded 10 amazing pro bono developers from <a href=\"https://www.thoughtworks.com/\" target=\"_blank\" title=\"https://www.thoughtworks.com/\">Thoughtworks</a>, so we've sort of got our hands full figuring out swimlanes for all those folks, etc...</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53271573,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455162410,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>Is there an area you'd be particularly interested in looking into so we could prioritizing making work in that area pick-up-able?</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53271578,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455162444,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>One major thing that <span class=\"user-mention\" data-user-email=\"kl.vlad@gmail.com\">@Vladimir Klekovkin (W2'16)</span> stumbled right on is that we don't have a great story for preventing spamming... (our main strategy is to implement verified PGP-encrypted comms channels as fast as we can and drive people to use that instead of the anonymous map... but that's gonna take a minute...)</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53271609,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455162504,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>Some of the more interesting Scala-related stuff is going on in <a href=\"https://github.com/ajablonski/whereat-location-server/commits/single-server-websockets\" target=\"_blank\" title=\"https://github.com/ajablonski/whereat-location-server/commits/single-server-websockets\">this branch</a>, where we're digging into implementing websockets on the backend -- to eliminate all state / DB writes and make the backend a pure relay server...</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53271680,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455162701,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>also: if you've got feedback for how other succesful F/OSS projects you've worked on have handled community management, we'd love to hear it and incorporate those practices into our workflow!</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53271719,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455162761,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/1c860d00a4cedc01147fbb2e0533c37b?d=identicon&version=1",
            "client": "desktop app Mac 0.5.1",
            "content": "<p>Great! My background lends to scala/java/android work, but I would tackle anything you outline for me. Being remote makes the cost of communication much higher I know, so get those Thoughtworks people sorted and you'll probably figure out something for me to do. If you are inclined to skype your planning meetings I would be interested in joining.</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 53285191,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "corydominguez@gmail.com",
            "sender_full_name": "Cory Michael Dominguez (he) (SP1'15)",
            "sender_id": 7625,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1455207230,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4b6aae6cae274fb83b0d155f0255298c2d3b22b7?x=x&version=2",
            "client": "website",
            "content": "<p>Hey <span class=\"user-mention\" data-user-email=\"guest.austin@gmail.com\">@Austin Guest (W1'14)</span> , what's the status of this project? Is <a href=\"http://whereat.io\" target=\"_blank\" title=\"http://whereat.io\">whereat.io</a> working?</p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 101220819,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "fundirap@gmail.com",
            "sender_full_name": "Panashe Machinda Fundira (he) (S1'16)",
            "sender_id": 9339,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1474138934,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>Hey <span class=\"user-mention\" data-user-email=\"fundirap@gmail.com\">@Panashe Machinda Fundira (S1'16)</span> Sorry I never replied to this! See this recent Community Post for update on why I was MIA and what the current state of play is / might be... <a href=\"https://community.recurse.com/t/where-says-hello-world-we-d-like-your-help/1525\" target=\"_blank\" title=\"https://community.recurse.com/t/where-says-hello-world-we-d-like-your-help/1525\">https://community.recurse.com/t/where-says-hello-world-we-d-like-your-help/1525</a></p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 103296801,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1478815263,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/4b6aae6cae274fb83b0d155f0255298c2d3b22b7?x=x&version=2",
            "client": "website",
            "content": "<p>np, thanks for responding <img alt=\":slightly_smiling_face:\" class=\"emoji\" src=\"/static/third/gemoji/images/emoji/slightly_smiling_face.png\" title=\":slightly_smiling_face:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 103327175,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "fundirap@gmail.com",
            "sender_full_name": "Panashe Machinda Fundira (he) (S1'16)",
            "sender_id": 9339,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1478885049,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "website",
            "content": "<p><span class=\"emoji emoji-1f47c\" title=\"angel\">:angel:</span></p>",
            "content_type": "text/html",
            "display_recipient": "where@",
            "flags": [
                "read",
                "historical"
            ],
            "id": 134700020,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 48954,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 32279,
            "subject": "Contributing",
            "submessages": [],
            "timestamp": 1537992730,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
