{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"192171\" href=\"/#narrow/stream/192171-workflow-hacks\">#workflow hacks</a>.</p>\n<p><strong>Description</strong>: geek out about window managers, tmux/vim/emacs configs, random linux thingies</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 161175142,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 192171,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1553018485,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a897e9d6a0e8aff13a39e0515c38ee2d9482c809?x=x&version=1",
            "client": "website",
            "content": "<p>i can haz linkz 2yr i3 config filezzzz?</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 161175219,
            "is_me_message": false,
            "last_edit_timestamp": 1553018548,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "guest.austin@gmail.com",
            "sender_full_name": "Austin Guest (they) (SP2'19)",
            "sender_id": 6930,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "i3 config files",
            "submessages": [],
            "timestamp": 1553018535,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/86f87d8c43e01b254ce156f3a4ffd6a2?d=identicon&version=1",
            "client": "website",
            "content": "<blockquote>\n<p>the reason why you want to still be able to float windows in i3</p>\n</blockquote>\n<p><a href=\"https://github.com/cpdean/cpd.dotfiles/blob/master/.config/i3/config#L90-L91\" target=\"_blank\" title=\"https://github.com/cpdean/cpd.dotfiles/blob/master/.config/i3/config#L90-L91\">https://github.com/cpdean/cpd.dotfiles/blob/master/.config/i3/config#L90-L91</a></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 161175302,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "conrad.p.dean@gmail.com",
            "sender_full_name": "Conrad Dean (he) (W2'19)",
            "sender_id": 158539,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "i3 config files",
            "submessages": [],
            "timestamp": 1553018595,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8bc3517d69989cc6dbb26da057d45191cee7510e?x=x&version=2",
            "client": "website",
            "content": "<p>You have to set up your own screen lock in i3, <code>i3lock</code> is a common tool.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 161182833,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "galenosullivan@gmail.com",
            "sender_full_name": "Galen O'Sullivan (he/they) (SP1'19)",
            "sender_id": 203854,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "i3 locking",
            "submessages": [],
            "timestamp": 1553024034,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8bc3517d69989cc6dbb26da057d45191cee7510e?x=x&version=2",
            "client": "website",
            "content": "<p>I just noticed there's a <a class=\"stream\" data-stream-id=\"20565\" href=\"/#narrow/stream/20565-unix-commands\">#unix commands</a> channel, probably related to this one.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 161182900,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "galenosullivan@gmail.com",
            "sender_full_name": "Galen O'Sullivan (he/they) (SP1'19)",
            "sender_id": 203854,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "unix commands",
            "submessages": [],
            "timestamp": 1553024056,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/86f87d8c43e01b254ce156f3a4ffd6a2?d=identicon&version=1",
            "client": "website",
            "content": "<p>i use a script built on top of i3lock that takes a screenshot so that it doesn't look my screen is broken</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 161184868,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "conrad.p.dean@gmail.com",
            "sender_full_name": "Conrad Dean (he) (W2'19)",
            "sender_id": 158539,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "i3 locking",
            "submessages": [],
            "timestamp": 1553025648,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/86f87d8c43e01b254ce156f3a4ffd6a2?d=identicon&version=1",
            "client": "website",
            "content": "<p>I have a Trello board that acts as my infinite and ever-growing todolist (unhealthy).  Whenever I see a thing that I want to follow up on, I have the following habit:</p>\n<p>1. hit the key to switch to my 'web' workspace <code>$mod+p</code><br>\n2. hit <code>ctrl+t</code> to open a new tab<br>\n3. type something like \"trello now\" and arrow down to my trello board named \"now\".<br>\n4. enter the card for the thing i want to do.</p>\n<hr>\n<p><strong>You can automate a lot of this with an i3 binding!</strong></p>\n<p>Here are some bindings for either opening trello in a dedicated workspace, or just opening it wherever you currently are:</p>\n<div class=\"codehilite\"><pre><span></span>mode &quot;applaunch&quot; {\n        bindsym t exec --no-startup-id &quot;firefox -new-window https://trello.com/b/.../now&quot;; mode &quot;default&quot;\n        # commented out so I stay in the same context of mind while jotting down the note\n        #bindsym t exec --no-startup-id &quot;i3-msg &#39;workspace 5; exec --no-startup-id firefox -new-window https://trello.com/b/.../now&#39;&quot;; mode &quot;default&quot;\n\n        # back to normal: Enter or Escape\n        bindsym Return mode &quot;default&quot;\n        bindsym Escape mode &quot;default&quot;\n}\n\nbindsym $mod+n mode &quot;applaunch&quot;\n</pre></div>\n\n\n<p>Now I hit <code>$mod+n, t</code> and trello opens.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 162147664,
            "is_me_message": false,
            "last_edit_timestamp": 1553994528,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "conrad.p.dean@gmail.com",
            "sender_full_name": "Conrad Dean (he) (W2'19)",
            "sender_id": 158539,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Opening a frequently-used tool/webpage",
            "submessages": [],
            "timestamp": 1553994017,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8bc3517d69989cc6dbb26da057d45191cee7510e?x=x&version=2",
            "client": "website",
            "content": "<p><a href=\"https://github.com/gosulliv/dotconfig\" target=\"_blank\" title=\"https://github.com/gosulliv/dotconfig\">https://github.com/gosulliv/dotconfig</a></p>\n<p>I just got a shortcut and script working to dynamically rename windows while keeping their numbers. I'm feeling a bit proud of myself, even if it feels like a hack.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 162833996,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "galenosullivan@gmail.com",
            "sender_full_name": "Galen O'Sullivan (he/they) (SP1'19)",
            "sender_id": 203854,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "i3 config files",
            "submessages": [],
            "timestamp": 1554741863,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>How did I miss this stream. Hello everyone -- I've been a BSPWM user for a few years and have been using shell scripts + emacs to build my integrated/themed environment (I'm W2'2020 batch). Dots at a vanity url: <a href=\"http://noriceno.life\" target=\"_blank\" title=\"http://noriceno.life\">http://noriceno.life</a> . AMA/I'll feel free to post whatever here.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 186329633,
            "is_me_message": false,
            "last_edit_timestamp": 1579726438,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1579726370,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/afcff71a280c619fe7f45af5df2f66b9617479fc?x=x&version=4",
            "client": "website",
            "content": "<p>I've forever been wanting to properly manage my dotfiles, and will probably do this today. Research threw up the \"bare git repo\" technique which I find very elegant (<a href=\"https://news.ycombinator.com/item?id=11071754\" title=\"https://news.ycombinator.com/item?id=11071754\">HN thread comment</a>, <a href=\"https://www.atlassian.com/git/tutorials/dotfiles\" title=\"https://www.atlassian.com/git/tutorials/dotfiles\">explained in a blog post</a>).</p>\n<p>Has anyone here used this technique? I'm keen to hear your experience, especially the drawbacks.</p>\n<p>As the HN user notes, the benefits of the bare repo technique include:</p>\n<blockquote>\n<p>No extra tooling, no symlinks, files are tracked on a version control system, you can use different branches for different computers, you can replicate you configuration easily on new installation.</p>\n</blockquote>\n<p>I extremely like such dependency-free, niche-concepts-unencumbered approaches very much. </p>\n<p>Plus, the bare repo technique opens doors to managing things that are part-config (version) part-config-dependent-binary (don't version), and for straightforward ways of managing secrets (encrypt-&gt;commit).</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 192951006,
            "is_me_message": false,
            "last_edit_timestamp": 1586080168,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "aditya.athalye@gmail.com",
            "sender_full_name": "Aditya Athalye (he) (SP1'20)",
            "sender_id": 263547,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586079905,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Omg I never thought to use branches for different computers. That's smart. I use a GitHub, but with symlinks, not like this approach.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 192966059,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586102912,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>I prefer the symlink approach (with a stow-like script as a fallback for when stow isn't installed yet, rather than have my $HOME be a git repo, even a bare one -- with opt-in files that might be nice though. So far I use the same set of dotfiles across computers, but I do have some checks against hostname in places</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 192981702,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586126224,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>will be interested to see what you come up with!</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 192981706,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586126241,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>looking up stow right now</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 193000057,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586155307,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/628b146946f3ed6c02f911f01f2e6046?d=identicon&version=1",
            "client": "ZulipMobile",
            "content": "<p>Hm, glanced over the gnu page. Nathan, what does your setup look like for using Stow for dotfiles? I have a feeling what I did is hack my own symlink automator :)</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 193000245,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "natquaylenelson@gmail.com",
            "sender_full_name": "Nat Quayle Nelson (she) (S1'18)",
            "sender_id": 116520,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586155482,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/afcff71a280c619fe7f45af5df2f66b9617479fc?x=x&version=4",
            "client": "ZulipElectron",
            "content": "<p>Here are two nice explanations of using GNU stow + version control to manage dotfiles:</p>\n<ul>\n<li>This one, linked directly from the GNU Stow homepage: <a href=\"http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html\" title=\"http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html\">http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html</a></li>\n<li>And this additional technique to also manage encrypted secret dotfiles: <a href=\"https://abdullah.today/encrypted-dotfiles/\" title=\"https://abdullah.today/encrypted-dotfiles/\">https://abdullah.today/encrypted-dotfiles/</a></li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 193003009,
            "is_me_message": false,
            "last_edit_timestamp": 1586157693,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "aditya.athalye@gmail.com",
            "sender_full_name": "Aditya Athalye (he) (SP1'20)",
            "sender_id": 263547,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586157655,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"116520\">@Nat Quayle Nelson (she) (S1'18)</span> in addition to what Aditya mentioned, my dotfiles repo is here: <a href=\"https://github.com/neeasade/dotfiles\" title=\"https://github.com/neeasade/dotfiles\">https://github.com/neeasade/dotfiles</a> -- my stow workflow is usually put my dotfiles repo in <code>~/.dotfiles</code>, and then if I want to setup say, shell links, <code>cd ~/.dotfiles; stow shell</code> (the default stow link target is <code>..</code>, else I'd have to like <code>stow shell -t \"$HOME\"</code>, I think</p>\n<blockquote>\n<p>I have a feeling what I did is hack my own symlink automator :)</p>\n</blockquote>\n<p>nothing wrong with that! those hacks can be fun and informative</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 193050145,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1586183486,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/440414e0085768284bd44c33c4d184cfd8cf1456?x=x&version=2",
            "client": "website",
            "content": "<p>We're doing a Desktop Dazzle on Zoom right now and it was suggested that I post some of the recommendations here <span aria-label=\"slight smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"slight smile\">:slight_smile:</span> </p>\n<ul>\n<li><a href=\"https://github.com/wting/autojump\">Autojump</a> - Do you hate navigating your directory structure all the time. Wish you could just jump to a directory and just have the computer figure out where it is. That\u2019s autojump!\u2029</li>\n<li><a href=\"https://github.com/sorin-ionescu/prezto\">zprezto</a> - \u2028Want a pretty looking terminal that is fast and not very fiddly, consider using zprezto and zsh\u2029</li>\n<li><a href=\"https://github.com/sharkdp/bat\">bat</a> - The \u2018cat\u2019 tool but with line numbers and syntax highlighting\u2029</li>\n<li><a href=\"https://github.com/sharkdp/fd\">fd</a> - \u2028Can\u2019t find where you put that pesky file, check out fd\u2029</li>\n<li><a href=\"https://github.com/ogham/exa\">exa</a> - A much nicer looking <code>ls</code></li>\n</ul>\n<p>Looking for a good terminal font that's easy to read, check out <a href=\"https://github.com/microsoft/cascadia-code\">Cascadia Code</a> by Microsoft, an open source monospaced font</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202710183,
            "is_me_message": false,
            "last_edit_timestamp": 1593707050,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "me@suhailpatel.com",
            "sender_full_name": "Suhail Patel (he) (m5'20)",
            "sender_id": 314648,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Desktop Dazzle",
            "submessages": [],
            "timestamp": 1593706625,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/440414e0085768284bd44c33c4d184cfd8cf1456?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"315058\">@Justin Holzmann (he) (S2'20)</span> my recommendations as requested <span aria-label=\"grinning\" class=\"emoji emoji-1f600\" role=\"img\" title=\"grinning\">:grinning:</span></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202710230,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f64f",
                    "emoji_name": "thank_you",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "awchen@fastmail.com",
                        "full_name": "Alex Chen (he) (SP1'20)",
                        "id": 264095
                    },
                    "user_id": 264095
                },
                {
                    "emoji_code": "1f64f",
                    "emoji_name": "thank_you",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "see.yishu@gmail.com",
                        "full_name": "Yishu See (she) (m5'20)",
                        "id": 315102
                    },
                    "user_id": 315102
                },
                {
                    "emoji_code": "1f64f",
                    "emoji_name": "thank_you",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "monaxwang@gmail.com",
                        "full_name": "Mona W (she) (S2'20)",
                        "id": 314660
                    },
                    "user_id": 314660
                },
                {
                    "emoji_code": "1f64f",
                    "emoji_name": "thank_you",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jpholzmann@gmail.com",
                        "full_name": "Justin Holzmann (he) (S2'20)",
                        "id": 315058
                    },
                    "user_id": 315058
                }
            ],
            "recipient_id": 314519,
            "sender_email": "me@suhailpatel.com",
            "sender_full_name": "Suhail Patel (he) (m5'20)",
            "sender_id": 314648,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Desktop Dazzle",
            "submessages": [],
            "timestamp": 1593706656,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/620d0eb7fcb87b272b387cf33e4ed314?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I did a twitter thread recently a few unix-y tool recommendations: <a href=\"https://twitter.com/captn3m0/status/1272166319274594304\">https://twitter.com/captn3m0/status/1272166319274594304</a>.</p>\n<div class=\"inline-preview-twitter\"><div class=\"twitter-tweet\"><a href=\"https://twitter.com/captn3m0/status/1272166319274594304\"><img class=\"twitter-avatar\" src=\"https://pbs.twimg.com/profile_images/955382485356957698/gT25sBIC_normal.jpg\"></a><p>Cool tools promotion thread. (Stuff I use and like, mostly dev/cli/linux stuff):\n\n<a href=\"https://t.co/ANPmr2ES8F\">https://github.com/ericchiang/pup</a>\n\npup is jq for HTML. Pipe your HTML and parser/filter it on the terminal. If you do a lot of web scraping - this is very nifty. <a href=\"https://t.co/k0pfuuYF9R\">https://twitter.com/captn3m0/status/1272166319274594304/photo/1</a></p><span>- Nemo (@captn3m0)</span><div class=\"twitter-image\"><a href=\"https://t.co/k0pfuuYF9R\"><img src=\"https://pbs.twimg.com/media/EaekhU4VcAERQrv.png:small\"></a></div></div></div>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202713164,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "me@captnemo.in",
            "sender_full_name": "Nemo (he) (S1'20)",
            "sender_id": 301256,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Desktop Dazzle",
            "submessages": [],
            "timestamp": 1593708065,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/df3e763d4bdb1ff66587b0dedbad087428449923?x=x&version=7",
            "client": "website",
            "content": "<p>I have scraped the transcript for links and semi-organized them!</p>\n<p>Command-line improvments: </p>\n<ul>\n<li>Autojump: <a href=\"https://github.com/wting/autojump\">https://github.com/wting/autojump</a></li>\n<li>Zprezto: <a href=\"https://github.com/sorin-ionescu/prezto\">https://github.com/sorin-ionescu/prezto</a></li>\n<li>bat: <a href=\"https://github.com/sharkdp/bat\">https://github.com/sharkdp/bat</a></li>\n<li>fd: <a href=\"https://github.com/sharkdp/fd\">https://github.com/sharkdp/fd</a></li>\n<li>fzf: <a href=\"https://github.com/junegunn/fzf\">https://github.com/junegunn/fzf</a></li>\n</ul>\n<p>Window Managers:</p>\n<ul>\n<li>bspwm: <a href=\"https://github.com/baskerville/bspwm\">https://github.com/baskerville/bspwm</a></li>\n<li>i3: <a href=\"https://i3wm.org/\">https://i3wm.org/</a> </li>\n<li>Spectacle (macOS): <a href=\"https://www.spectacleapp.com/\">https://www.spectacleapp.com/</a></li>\n<li>Rectangle (macOS): <a href=\"https://rectangleapp.com/\">https://rectangleapp.com/</a></li>\n</ul>\n<p>Color themes:</p>\n<ul>\n<li>GruvBox: <a href=\"https://github.com/morhetz/gruvbox\">https://github.com/morhetz/gruvbox</a></li>\n<li>FairyFloss: <a href=\"https://github.com/sailorhg/fairyfloss\">https://github.com/sailorhg/fairyfloss</a></li>\n<li>Yonce theme: <a href=\"https://yoncetheme.com/\">https://yoncetheme.com/</a></li>\n<li>Nord: <a href=\"https://www.nordtheme.com/\">https://www.nordtheme.com/</a></li>\n</ul>\n<p>Fonts:</p>\n<ul>\n<li>Programming Fonts: <a href=\"https://www.programmingfonts.org/\">https://www.programmingfonts.org/</a></li>\n<li>Cascadia Code: <a href=\"https://github.com/microsoft/cascadia-code\">https://github.com/microsoft/cascadia-code</a></li>\n</ul>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202713553,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "me@suhailpatel.com",
                        "full_name": "Suhail Patel (he) (m5'20)",
                        "id": 314648
                    },
                    "user_id": 314648
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "see.yishu@gmail.com",
                        "full_name": "Yishu See (she) (m5'20)",
                        "id": 315102
                    },
                    "user_id": 315102
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jpholzmann@gmail.com",
                        "full_name": "Justin Holzmann (he) (S2'20)",
                        "id": 315058
                    },
                    "user_id": 315058
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "me@captnemo.in",
                        "full_name": "Nemo (he) (S1'20)",
                        "id": 301256
                    },
                    "user_id": 301256
                },
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "nathanisom27@gmail.com",
                        "full_name": "Nathan Isom (he) (W2'20)",
                        "id": 255190
                    },
                    "user_id": 255190
                }
            ],
            "recipient_id": 314519,
            "sender_email": "monaxwang@gmail.com",
            "sender_full_name": "Mona W (she) (S2'20)",
            "sender_id": 314660,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Desktop Dazzle",
            "submessages": [],
            "timestamp": 1593708278,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>I've been meaning to use fd more, if just for the 'intuitive' exec syntax</p>\n<p>fwiw this tool recently went around again: <a href=\"http://eradman.com/entrproject/\">http://eradman.com/entrproject/</a></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202714003,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "2795",
                    "emoji_name": "plus",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "adam@cthulahoops.org",
                        "full_name": "Adam Kelly (they/he) (S1'20)",
                        "id": 301014
                    },
                    "user_id": 301014
                },
                {
                    "emoji_code": "2795",
                    "emoji_name": "plus",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "jpholzmann@gmail.com",
                        "full_name": "Justin Holzmann (he) (S2'20)",
                        "id": 315058
                    },
                    "user_id": 315058
                }
            ],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Desktop Dazzle",
            "submessages": [],
            "timestamp": 1593708495,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>updating this thread -- I made a script that has the luxury of assuming the dotfiles location and creates symlinks in the same style as stow -- <a href=\"https://github.com/neeasade/dotfiles/blob/master/bin/bin/stowo\">stOwO</a></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202714711,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "dotfiles",
            "submessages": [],
            "timestamp": 1593708888,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/df3e763d4bdb1ff66587b0dedbad087428449923?x=x&version=7",
            "client": "website",
            "content": "<p><a href=\"/user_uploads/13/OYw0vSIELU5Fpd24h7w2u-lS/dazzleterm.png\">dazzleterm.png</a> yay!!! gaps, new theme, new bar, and new shell!</p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/13/OYw0vSIELU5Fpd24h7w2u-lS/dazzleterm.png\" title=\"dazzleterm.png\"><img src=\"/user_uploads/13/OYw0vSIELU5Fpd24h7w2u-lS/dazzleterm.png\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202748512,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "monaxwang@gmail.com",
            "sender_full_name": "Mona W (she) (S2'20)",
            "sender_id": 314660,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Desktop Dazzle",
            "submessages": [],
            "timestamp": 1593726668,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>fun prompt ^^</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202757820,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Desktop Dazzle",
            "submessages": [],
            "timestamp": 1593735061,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/635ab4f3efb5c26f8276373d9767320104538f85?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>I've wanted this one for a while. . . happy to have finally taken the time to write it:</p>\n<div class=\"codehilite\"><pre><span></span><code>alias 7copy=&quot;history 2 | grep -v &#39;history&#39; | grep -v &#39;7copy&#39; | xargs | sed -E &#39;s/^[0-9]+ (.*)$/\\1/&#39; | pbcopy&quot;\n</code></pre></div>\n\n\n<p>The use case is if you are coding along in the terminal working on a unix thing. . . and then you choose to script it (because its getting complex). So then just run that and then you will have your work in your clipboard to write your script. . . without touching your mouse.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202820975,
            "is_me_message": false,
            "last_edit_timestamp": 1593794162,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "jpholzmann@gmail.com",
            "sender_full_name": "Justin Holzmann (he) (S2'20)",
            "sender_id": 315058,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "aliases",
            "submessages": [],
            "timestamp": 1593794094,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/635ab4f3efb5c26f8276373d9767320104538f85?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Very much an intermediate at bash scripting and would value any other ways to do this. . . or how to do it better :)</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202821213,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "jpholzmann@gmail.com",
            "sender_full_name": "Justin Holzmann (he) (S2'20)",
            "sender_id": 315058,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "aliases",
            "submessages": [],
            "timestamp": 1593794288,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/afcff71a280c619fe7f45af5df2f66b9617479fc?x=x&version=4",
            "client": "website",
            "content": "<p>Nice trick +1 </p>\n<p>If that's your use case, then you're going to love this video <a href=\"https://www.youtube.com/watch?v=gU5nFonVEh0\">Advanced Tips for the Bash Command-Line</a></p>\n<p><code>!!</code> for \"last command\" expansion, and <code>fc</code> to recall previous &lt;range&gt; of commands in $EDITOR buffer</p>\n<p>Accompanying blog post here: <a href=\"https://jeffterrell.tech/posts/2018-08-16-advanced-cli-tips/\">https://jeffterrell.tech/posts/2018-08-16-advanced-cli-tips/</a></p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"gU5nFonVEh0\" href=\"https://www.youtube.com/watch?v=gU5nFonVEh0\"><img src=\"https://i.ytimg.com/vi/gU5nFonVEh0/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202823786,
            "is_me_message": false,
            "last_edit_timestamp": 1593796957,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "aditya.athalye@gmail.com",
            "sender_full_name": "Aditya Athalye (he) (SP1'20)",
            "sender_id": 263547,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "aliases",
            "submessages": [],
            "timestamp": 1593796757,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/afcff71a280c619fe7f45af5df2f66b9617479fc?x=x&version=4",
            "client": "website",
            "content": "<p>Also, if you're keen on bash/shell scripting to construct workflows, in general, I would highly recommend these. I refer to them from time to time to pick up new skills and refresh details that I tend to forget:</p>\n<ul>\n<li><a href=\"https://www.youtube.com/watch?v=BJ0uHhBkzOQ\">Concise GNU Bash: An Introduction to Advanced Usage - James Panacciulli</a></li>\n<li><a href=\"https://www.youtube.com/channel/UC_hrdZOVs5P-XSxNBdhqvDQ/playlists\">In-depth screencasts by Dana French</a></li>\n</ul>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"BJ0uHhBkzOQ\" href=\"https://www.youtube.com/watch?v=BJ0uHhBkzOQ\"><img src=\"https://i.ytimg.com/vi/BJ0uHhBkzOQ/default.jpg\"></a></div><div class=\"youtube-video message_inline_image\"><a data-id=\"channel\" href=\"https://www.youtube.com/channel/UC_hrdZOVs5P-XSxNBdhqvDQ/playlists\"><img src=\"https://i.ytimg.com/vi/channel/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202824381,
            "is_me_message": false,
            "last_edit_timestamp": 1593980097,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "aditya.athalye@gmail.com",
            "sender_full_name": "Aditya Athalye (he) (SP1'20)",
            "sender_id": 263547,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "aliases",
            "submessages": [],
            "timestamp": 1593797269,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/635ab4f3efb5c26f8276373d9767320104538f85?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Nice! So with <code>fc</code> I could hop into vim and then save it as a new file directly. That's already an improvement for that use case. I will bookmark all of these <span aria-label=\"pray\" class=\"emoji emoji-1f64f\" role=\"img\" title=\"pray\">:pray:</span></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 202824908,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f389",
                    "emoji_name": "tada",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "aditya.athalye@gmail.com",
                        "full_name": "Aditya Athalye (he) (SP1'20)",
                        "id": 263547
                    },
                    "user_id": 263547
                }
            ],
            "recipient_id": 314519,
            "sender_email": "jpholzmann@gmail.com",
            "sender_full_name": "Justin Holzmann (he) (S2'20)",
            "sender_id": 315058,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "aliases",
            "submessages": [],
            "timestamp": 1593797704,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e4e0b8da64d9af566e9c99caee83ca90?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I just learned about this cool vim/tmux plugin that lets you navigate inside your tmux splits and vim splits as if they are the same thing. <a href=\"https://github.com/christoomey/vim-tmux-navigator\">https://github.com/christoomey/vim-tmux-navigator</a> its pretty awesome. Ex: C-l will go right in vim but if there are no more vim splits it will traverse the tmux one too. Its awesome!</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 204830468,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "jacoblevgw@gmail.com",
            "sender_full_name": "Jacob Lev Goldman-Wetlzer (he) (m2'20)",
            "sender_id": 264901,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really Cool Vim plugin",
            "submessages": [],
            "timestamp": 1595526761,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>hey! thanks for sharing, that's cool</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 204917005,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really Cool Vim plugin",
            "submessages": [],
            "timestamp": 1595598524,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6263e852a5789e39c4bacd700eeba2cce3fe6f8f?x=x&version=5",
            "client": "website",
            "content": "<p>I did something very similar in emacs -- emacs panes --&gt; fallback to select next window in the window manager (bspwm) <a href=\"https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/interact/focus.sh#L17-L21\">https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/interact/focus.sh#L17-L21</a></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 204917081,
            "is_me_message": false,
            "last_edit_timestamp": 1595598608,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "nathanisom27@gmail.com",
            "sender_full_name": "Nathan Isom (he) (W2'20)",
            "sender_id": 255190,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really Cool Vim plugin",
            "submessages": [],
            "timestamp": 1595598584,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/e4e0b8da64d9af566e9c99caee83ca90?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I also use bspwm so Ill try to incorporate that too with vim and tmux.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 204970136,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "jacoblevgw@gmail.com",
            "sender_full_name": "Jacob Lev Goldman-Wetlzer (he) (m2'20)",
            "sender_id": 264901,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really Cool Vim plugin",
            "submessages": [],
            "timestamp": 1595627117,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5c9f6b47dcb9445449eefb07bc719483?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I just installed this awesome window manager which completely changes the appearance of your GNOME setup: <a href=\"https://material-shell.com\">https://material-shell.com</a> I found it to be much nicer to work with compared to the classic GNOME interface!</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210577869,
            "is_me_message": false,
            "last_edit_timestamp": 1600464803,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "vmehta94@gmail.com",
            "sender_full_name": "Vinayak Mehta (he) (F1'20)",
            "sender_id": 327359,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really cool window manager",
            "submessages": [],
            "timestamp": 1600464742,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5c9f6b47dcb9445449eefb07bc719483?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I had to exclude some window classes (guake, peek, screenshot app) from tiling by default so that they appear as overlays, <a href=\"https://github.com/material-shell/material-shell/issues/66#issuecomment-695033161\">GitHub comment on how to do that</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210578175,
            "is_me_message": false,
            "last_edit_timestamp": 1600464976,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "vmehta94@gmail.com",
            "sender_full_name": "Vinayak Mehta (he) (F1'20)",
            "sender_id": 327359,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really cool window manager",
            "submessages": [],
            "timestamp": 1600464968,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e30b9e7d531d60960da4c58b24cf7e7c5aff03f0?x=x&version=5",
            "client": "ZulipElectron",
            "content": "<p>I saw an announcement about that and it looked really interesting. Let us know how it goes. I'm on awesomewm right now and generally don't need anything too fancy from my desktop environment so I try not to go into rabbit holes with too much tiling, layers and modes of hundreds of keybindings, etc.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 210624626,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "vmehta94@gmail.com",
                        "full_name": "Vinayak Mehta (he) (F1'20)",
                        "id": 327359
                    },
                    "user_id": 327359
                }
            ],
            "recipient_id": 314519,
            "sender_email": "pete@peterlyons.com",
            "sender_full_name": "Peter Lyons (he) (W1'17)",
            "sender_id": 103052,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really cool window manager",
            "submessages": [],
            "timestamp": 1600534944,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/32721626292fa2708ee74d852696e44f426cd631?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>That looks pretty cool.</p>\n<p>I\u2019ve been using the pop_os! shell: <a href=\"https://github.com/pop-os/shell\">https://github.com/pop-os/shell</a></p>\n<p>I used i3wm in the past but tbh I miss a lot of the niceties that come with gnome. This feels like a nice in-between for me. It\u2019s pretty customizable as you can just clone the repo, make some changes, and run the <code>rebuild.sh</code></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 211861138,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "vmehta94@gmail.com",
                        "full_name": "Vinayak Mehta (he) (F1'20)",
                        "id": 327359
                    },
                    "user_id": 327359
                }
            ],
            "recipient_id": 314519,
            "sender_email": "dabbagh.aos@gmail.com",
            "sender_full_name": "Aos Dabbagh (S2'17)",
            "sender_id": 101320,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really cool window manager",
            "submessages": [],
            "timestamp": 1601517163,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/32721626292fa2708ee74d852696e44f426cd631?x=x&version=2",
            "client": "ZulipMobile",
            "content": "<p>Fwiw I\u2019m running Ubuntu 20.04</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 211861151,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "dabbagh.aos@gmail.com",
            "sender_full_name": "Aos Dabbagh (S2'17)",
            "sender_id": 101320,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really cool window manager",
            "submessages": [],
            "timestamp": 1601517185,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/5c9f6b47dcb9445449eefb07bc719483?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>I upgraded to Ubuntu 20.04 just to get the latest version of the GNOME shell that material-shell supports. I've been using it since the day I posted this, and it's been pretty great! I love how each app opens in a foreground window unlike GNOME classic (no Alt + Tab anymore!), and how these keyboard shortcuts work:</p>\n<ul>\n<li><code>&lt;Super&gt;</code> + W/S: To move between workspaces</li>\n<li><code>&lt;Super&gt;</code> + A/D: To move between windows</li>\n<li><code>&lt;Super&gt;</code> + Q: Close a window</li>\n<li><code>&lt;Super&gt;</code> + Esc: Go into \"focus\" mode (hides the status bar and everything becomes full screen)</li>\n<li><code>&lt;Super&gt;</code> + Space: Change tiling layouts</li>\n</ul>\n<p><span class=\"user-mention\" data-user-id=\"101320\">@Aos Dabbagh (S2'17)</span>  I tried the pop_os! shell but couldn't move to it after using the above shortcuts on material-shell as they fit my workflow pretty nicely. I like how it's so easy to install/remove with just a toggle on <a href=\"http://extensions.gnome.org\">extensions.gnome.org</a>. I also tried <a href=\"https://regolith-linux.org\">https://regolith-linux.org</a> but it required me to learn a lot of new keyboard shortcuts.</p>\n<p>material-shell still has some bugs but they aren't major enough for me to move away from it yet <span aria-label=\"grinning\" class=\"emoji emoji-1f600\" role=\"img\" title=\"grinning\">:grinning:</span></p>\n<p><span class=\"user-mention\" data-user-id=\"103052\">@Peter Lyons (he) (W1'17)</span> I've used awesomewm in the past, it's really good! I like how you can write your own widgets with Lua!</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 211881546,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "vmehta94@gmail.com",
            "sender_full_name": "Vinayak Mehta (he) (F1'20)",
            "sender_id": 327359,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "Really cool window manager",
            "submessages": [],
            "timestamp": 1601541037,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/e30b9e7d531d60960da4c58b24cf7e7c5aff03f0?x=x&version=5",
            "client": "ZulipElectron",
            "content": "<p>I wrote up my new keyboard modifier shortcut system I use for navigating/controlling my window manager and application tabs/panes. I've been unsatisfied with my options for a long time and this feels like it has the potential to spend a long time on my tool belt. <a href=\"https://www.reddit.com/r/KeyboardLayouts/comments/j8hui9/home_row_pinkie_modtap_for_2tier_navigation/\">https://www.reddit.com/r/KeyboardLayouts/comments/j8hui9/home_row_pinkie_modtap_for_2tier_navigation/</a></p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 212985252,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "pete@peterlyons.com",
            "sender_full_name": "Peter Lyons (he) (W1'17)",
            "sender_id": 103052,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "home row mod-taps with kmonad",
            "submessages": [],
            "timestamp": 1602456465,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/b4a0313a5b4da07f6dda63ed2885e1c2de660cba?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>I have tried a couple of times to use modifier keys on the home row with kmonad but could never figure out the right timeout and ended up switching back. For example, I put <code>CTRL_R</code> as a modifier on the <code>;</code> key but that made typing <code>:</code> super hard and broke my flow.</p>",
            "content_type": "text/html",
            "display_recipient": "workflow hacks",
            "flags": [
                "read",
                "historical"
            ],
            "id": 215812331,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 314519,
            "sender_email": "7rat13@gmail.com",
            "sender_full_name": "Sayan Sarkar (they) (W1'20)",
            "sender_id": 361862,
            "sender_realm_str": "recurse",
            "stream_id": 192171,
            "subject": "home row mod-taps with kmonad",
            "submessages": [],
            "timestamp": 1604647016,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
