{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"173941\" href=\"/#narrow/stream/173941-ZeroPhone\">#ZeroPhone</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "ZeroPhone",
            "flags": [
                "read",
                "historical"
            ],
            "id": 150804409,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 220868,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 173941,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1543874870,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/bd5a1efc383987e7f7a6b3cf4d56d409c23a1394?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>A good start for our group could be the upcoming Soldering Workshop this Wednesday 12/5 @ 2pm in Sammet.</p>",
            "content_type": "text/html",
            "display_recipient": "ZeroPhone",
            "flags": [
                "read",
                "historical"
            ],
            "id": 150804519,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 220868,
            "sender_email": "pschneeweis@protonmail.com",
            "sender_full_name": "Patrick Schneeweis (he) (W1'18)",
            "sender_id": 134214,
            "sender_realm_str": "recurse",
            "stream_id": 173941,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1543874989,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/ef039ebebe21b975d2459f92aa693722?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p><span class=\"user-mention\" data-user-id=\"134214\">@Patrick Schneeweis (W1'18)</span> <a href=\"https://www.youtube.com/watch?v=FlRa-iH7PGw\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FlRa-iH7PGw\">https://www.youtube.com/watch?v=FlRa-iH7PGw</a> Found this talk in the #hardware stream</p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"FlRa-iH7PGw\" href=\"https://www.youtube.com/watch?v=FlRa-iH7PGw\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=FlRa-iH7PGw\"><img src=\"https://i.ytimg.com/vi/FlRa-iH7PGw/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "ZeroPhone",
            "flags": [
                "read",
                "historical"
            ],
            "id": 152142986,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 220868,
            "sender_email": "aaronstrick@gmail.com",
            "sender_full_name": "Aaron Strick (he) (F2'18)",
            "sender_id": 129958,
            "sender_realm_str": "recurse",
            "stream_id": 173941,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1545171518,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/205f6d09582a777f36bf64862634dd28?d=identicon&version=1",
            "client": "ZulipElectron",
            "content": "<p>Reposting this from 397 Bridge: <a href=\"https://bleepbloopbleep.net/index.php/s/S2spFXaL9iGzxzd\" target=\"_blank\" title=\"https://bleepbloopbleep.net/index.php/s/S2spFXaL9iGzxzd\">https://bleepbloopbleep.net/index.php/s/S2spFXaL9iGzxzd</a></p>",
            "content_type": "text/html",
            "display_recipient": "ZeroPhone",
            "flags": [
                "read",
                "historical"
            ],
            "id": 158558336,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 220868,
            "sender_email": "rowan.copley@gmail.com",
            "sender_full_name": "Rowan Copley (he) (W1'18)",
            "sender_id": 134191,
            "sender_realm_str": "recurse",
            "stream_id": 173941,
            "subject": "missing parts list",
            "submessages": [],
            "timestamp": 1550173524,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
