{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Bom dia a tudos</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545430,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181093,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Bom dia, Carlos. Obrigado!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545444,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181112,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Boa noite, que aqui j\u00e1 s\u00e3o 22h25!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545459,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181141,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Mais umas horas e vou dormir.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545463,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181151,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Es la 23:25 aqui! :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545475,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181164,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>E a forma correcta de escrever \u201cwelcome\u201d in Portuguese is \u201cbem-vindos\u201d <img alt=\":smiley:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/smiley.png\" title=\":smiley:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545508,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181180,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>:)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545517,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181214,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Bem-vindos, <span class=\"user-mention\" data-user-email=\"gnclmorais@gmail.com\">@Gon\u00e7alo Morais (SP1'15)</span> :-)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545521,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181230,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Perfeito, <span class=\"user-mention\" data-user-email=\"katerinab@gmail.com\">@Katerina Barone-Adesi (F'13)</span>!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545526,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181240,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>:D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545529,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181249,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Ver tanta gente a falar v\u00e1rias l\u00ednguas d\u00e1-me vontade de continuar a aprender\u2026! Obrigado!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545538,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181282,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Essa \u00e9 boa..!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545598,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Bemvindos",
            "submessages": [],
            "timestamp": 1435181353,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>precisamos criar um grupo de aprendizagem de l\u00ednguas somente para RCers</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545602,
            "is_me_message": false,
            "last_edit_timestamp": 1435181407,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435181383,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>como pair-programming pero para l\u00ednguas</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545665,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435181430,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>huehue</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545667,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435181433,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Boa ideia!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545680,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435181469,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Eu estou a ver na GitHub wiki o melhor s\u00edtio para apontar estes streams.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545685,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435181487,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Boa id\u00e9ia, gostei.:)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41545688,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435181495,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Eu sempre quis criar esse grupo, mas nunca achei que ia ter gente</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546079,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435182147,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Eu estava olhando a p\u00e1gina do novo Batch e eu encontrei a uma RCer que vem do Brasil</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546659,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183129,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><a href=\"https://www.recurse.com/people/1281-lais-varej%C3%A3o-vital\" target=\"_blank\" title=\"https://www.recurse.com/people/1281-lais-varej%C3%A3o-vital\">https://www.recurse.com/people/1281-lais-varej%C3%A3o-vital</a></p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546664,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183139,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Bem!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546672,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183157,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>PD: Eu n\u00e3o sou um stalker huehue</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546674,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183165,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Claro que n\u00e3o!  :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546688,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183194,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"pietromenna@gmail.com\">@Pietro Menna (SP2'15)</span> fala portugu\u00eas tamb\u00e9m</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546736,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183209,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Porreiro!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546794,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183312,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Creio que ainda sou o \u00fanico Portugu\u00eas, no entanto. <img alt=\":stuck_out_tongue:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/stuck_out_tongue.png\" title=\":stuck_out_tongue:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546837,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183339,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><span class=\"user-mention\" data-user-email=\"alicescarpa@gmail.com\">@Alice Duarte Scarpa (W1'14)</span>, j\u00e1 est\u00e1! <img alt=\":smile:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/smile.png\" title=\":smile:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546847,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435183374,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>at\u00e9 agora... :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546849,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183376,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>E ainda creiei uma p\u00e1gina na wiki para <a href=\"https://github.com/recursecenter/wiki/wiki/Interesting-Zulip-streams\" target=\"_blank\" title=\"https://github.com/recursecenter/wiki/wiki/Interesting-Zulip-streams\">stream interessantes</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546854,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Reviviendo \u00f1",
            "submessages": [],
            "timestamp": 1435183386,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p><img alt=\":thumbsup:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/thumbsup.png\" title=\":thumbsup:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41546858,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183394,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>O Fernando <a href=\"https://www.recurse.com/people/949-fernando-andrade\" target=\"_blank\" title=\"https://www.recurse.com/people/949-fernando-andrade\">https://www.recurse.com/people/949-fernando-andrade</a> e o Pedro <a href=\"https://www.recurse.com/people/909-pedro-tacla-yamada\" target=\"_blank\" title=\"https://www.recurse.com/people/909-pedro-tacla-yamada\">https://www.recurse.com/people/909-pedro-tacla-yamada</a> tamb\u00e9m s\u00e3o brasileiros, mas eles n\u00e3o frequentam muito o zulip.<br>\nEm novembro e dezembro de 2014 havia 3 brasileiros no RC</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547009,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183627,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Fixe!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547156,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183824,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Eu ando a espalhar a exist\u00eancia do RC por onde passo, a ver se meto mais gente de Portugal ou Londres por l\u00e1. :P</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547164,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183848,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>ou Su\u00ed\u00e7a? :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547231,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435183933,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Claro, porque n\u00e3o? Mas essa fun\u00e7\u00e3o \u00e9 tua. <img alt=\":stuck_out_tongue:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/stuck_out_tongue.png\" title=\":stuck_out_tongue:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547301,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184067,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Porque? :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547312,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184127,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>N\u00e3o \u00e9 onde est\u00e1s\u2026? <img alt=\":stuck_out_tongue:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/stuck_out_tongue.png\" title=\":stuck_out_tongue:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547372,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184221,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Si... :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547377,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184236,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Eu estou por Portugal, e frequentemente vou a Londres para ver bons amigos que deixei l\u00e1\u2026 Pronto, espalho a semente do RC por onde costumo andar. :P Era isso que queria dizer.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547386,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184258,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Ahhh... bem. :) Eu frequentemente vou a Cambridge.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547445,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184345,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Adoro! Fui l\u00e1 uma vez e amei. Andar l\u00e1 de barco foi o m\u00e1ximo.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547462,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184399,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>Si, es muy muy bem. :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 41547505,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1435184430,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/19cf1b085f140a8344906c91d69664dd?d=identicon&version=1",
            "client": "website",
            "content": "<p>Opa! Sim, vim do Brasil :) Ainda n\u00e3o tinha visto isso aqui!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42391602,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "laisvarejao@gmail.com",
            "sender_full_name": "Lais Varej\u00e3o Vital (she) (S2'15)",
            "sender_id": 8319,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1436457723,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Creio que ainda sou o \u00fanico Portugu\u00eas de gema por aqui\u2026 Sinto-me sozinho. <img alt=\":crying_cat_face:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/crying_cat_face.png\" title=\":crying_cat_face:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42645627,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1436986285,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>\u00c9 s\u00f3 voc\u00ea convencer seus amigos de Portugal a aplicarem para o RC e o problema se resolve <img alt=\":smile:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/smile.png\" title=\":smile:\"></p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42648815,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "Novos RCers",
            "submessages": [],
            "timestamp": 1436990617,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Em homenagem ao nome da stream, uma m\u00fasica cheia de '\u00e3os': <a href=\"https://www.youtube.com/watch?v=SSOJfdSMPng\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=SSOJfdSMPng\">https://www.youtube.com/watch?v=SSOJfdSMPng</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=SSOJfdSMPng\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=SSOJfdSMPng\"><img src=\"https://i.ytimg.com/vi/SSOJfdSMPng/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42690158,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437067806,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Boa\u2026! :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42690414,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437068205,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Bem lembrado, acho que vou come\u00e7ar a colocar aqui m\u00fasica Portuguesa, volta e meia.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42690418,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437068221,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Eu adoraria conhecer mais de m\u00fasica Portuguesa <img alt=\":smile_cat:\" class=\"emoji\" src=\"static/third/gemoji/images/emoji/smile_cat.png\" title=\":smile_cat:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42690509,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437068370,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Boa! Temos artistas <strong>incr\u00edveis</strong>, bandas que apareceram nos \u00faltimos 5 a 10 anos.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42690589,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437068452,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Essa m\u00fasica \u00e9 sobre um p\u00e1ssaro do sert\u00e3o*:  <a href=\"https://www.youtube.com/watch?v=ITmqGj-sRUo\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=ITmqGj-sRUo\">https://www.youtube.com/watch?v=ITmqGj-sRUo</a></p>\n<ul>\n<li>sert\u00e3o \u00e9 como se fosse o deserto brasileiro, apesar de n\u00e3o ser um deserto propriamente dito</li>\n</ul>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=ITmqGj-sRUo\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=ITmqGj-sRUo\"><img src=\"https://i.ytimg.com/vi/ITmqGj-sRUo/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42739182,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437158801,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>A <a href=\"https://pt.wikipedia.org/wiki/Sert%C3%A3o\" target=\"_blank\" title=\"https://pt.wikipedia.org/wiki/Sert%C3%A3o\">descri\u00e7\u00e3o da Wikip\u00e9dia</a> parece interessante. :) Nunca tinha pensado exactamente sobre o que seria.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42838388,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437402057,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>E boa m\u00fasica! Nunca tinha ouvido algo deste g\u00e9nero de folclore brasileiro.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42838394,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437402091,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Falando de m\u00fasica em Portugu\u00eas, preciso de apresentar uma das melhores bandas dos \u00faltimos 5-10 anos em Portugal, <strong>Linda Martini</strong>. <a href=\"https://www.youtube.com/watch?v=_69Gve9ZJ_8&amp;hd=1\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_69Gve9ZJ_8&amp;hd=1\">\u2018Dez Tost\u00f5es\u2019</a> \u00e9 a m\u00fasica mais recente deles, onde apresentam um tipo de rock diferente do que predomina na sua discografia (s\u00e3o uma banda maioritariamente de post-rock). Para quem usa Spotify, poder\u00e1 encontr\u00e1-los <a href=\"https://open.spotify.com/artist/4Pv6qAkea25i2DlW1quQ8t\" target=\"_blank\" title=\"https://open.spotify.com/artist/4Pv6qAkea25i2DlW1quQ8t\">aqui</a>.</p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=_69Gve9ZJ_8&amp;hd=1\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=_69Gve9ZJ_8&amp;hd=1\"><img src=\"https://i.ytimg.com/vi/_69Gve9ZJ_8/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42838461,
            "is_me_message": false,
            "last_edit_timestamp": 1437402446,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437402223,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Gostei dessa banda! Devo confessar que \u00e9 a primeira vez que escuto rock Portugu\u00eas, agora fiquei com vontade de procurar mais.</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 42931652,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1437577445,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "desktop app Mac 0.4.4",
            "content": "<p>Em Portugal tamb\u00e9m se faz m\u00fasica \u00e0 la Balc\u00e3s! <a href=\"https://youtu.be/fGdSw79nuMQ?t=1m11s\" target=\"_blank\" title=\"https://youtu.be/fGdSw79nuMQ?t=1m11s\">https://youtu.be/fGdSw79nuMQ?t=1m11s</a></p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 47930447,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1444063045,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p>Acabei de descobrir que existe uma stream em portugu\u00eas :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102164434,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476311527,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p>Essa mulher \u00e9 bem incr\u00edvel. Ela \u00e9 do cabo verde e canta com um sotaque que pra mim soa perfeito, tanto em m\u00fasica brasileira quando em m\u00fasica portuguesa</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102164498,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476311681,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.youtube.com/watch?v=eadBZWgCtKc\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=eadBZWgCtKc\">https://www.youtube.com/watch?v=eadBZWgCtKc</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=eadBZWgCtKc\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=eadBZWgCtKc\"><img src=\"https://i.ytimg.com/vi/eadBZWgCtKc/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102164499,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476311682,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p><a href=\"https://www.youtube.com/watch?v=LV09kQlGxHU\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=LV09kQlGxHU\">https://www.youtube.com/watch?v=LV09kQlGxHU</a></p>\n<div class=\"message_inline_image\"><a href=\"https://www.youtube.com/watch?v=LV09kQlGxHU\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=LV09kQlGxHU\"><img src=\"https://i.ytimg.com/vi/LV09kQlGxHU/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102164504,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476311705,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>Que lindo!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102196464,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476382388,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p>Dominguinhos at\u00e9 teve que enxugar as l\u00e1grimas :~</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102196515,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476382450,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p>Ali\u00e1s, eu n\u00e3o conhecia Pedro Moutinho e esse g\u00eanero de m\u00fasica portuguesa, achei bem incr\u00edvel a voz dele!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102196590,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476382583,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3b819440e9721e34d662fe498f8138bc?d=identicon&version=1",
            "client": "website",
            "content": "<p>M\u00fasica portuguesa est\u00e1 na longa lista de coisas que eu queria conhecer melhor, mas que acabo n\u00e3o priorizando. Agora o YouTube est\u00e1 tocando m\u00fasicas relacionadas e \u00e9 t\u00e3o bonito!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 102196886,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "alicescarpa@gmail.com",
            "sender_full_name": "Alice Duarte Scarpa (W1'14)",
            "sender_id": 6920,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasica",
            "submessages": [],
            "timestamp": 1476383112,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "website",
            "content": "<p>cora\u00e7a\u00f5s pra tudos</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 104437750,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "cora\u00e7a\u00f5s",
            "submessages": [],
            "timestamp": 1481310216,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p>cora\u00e7\u00f5ezinhos Carlinhos <img alt=\":revolving_hearts:\" class=\"emoji\" src=\"/static/third/gemoji/images/emoji/revolving_hearts.png\" title=\":revolving_hearts:\"></p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 104437832,
            "is_me_message": false,
            "last_edit_timestamp": 1481310374,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "cora\u00e7a\u00f5s",
            "submessages": [],
            "timestamp": 1481310325,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/3ca604eb0c0cfa22b4a10fc739c056c8?d=identicon&version=1",
            "client": "website",
            "content": "<p>cora\u00e7a\u00f5s pra ti, <span class=\"user-mention\" data-user-email=\"darthmincho@gmail.com\">@Carlos Rey (SP2'15)</span> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 104439770,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "lukeadba@gmail.com",
            "sender_full_name": "Luke Barone-Adesi (he) (F'13)",
            "sender_id": 2903,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "cora\u00e7a\u00f5s",
            "submessages": [],
            "timestamp": 1481313584,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "website",
            "content": "<p><img alt=\":heart_eyes:\" class=\"emoji\" src=\"/static/third/gemoji/images/emoji/heart_eyes.png\" title=\":heart_eyes:\"> <img alt=\":heart_eyes:\" class=\"emoji\" src=\"/static/third/gemoji/images/emoji/heart_eyes.png\" title=\":heart_eyes:\"> <img alt=\":heart_eyes:\" class=\"emoji\" src=\"/static/third/gemoji/images/emoji/heart_eyes.png\" title=\":heart_eyes:\"> </p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 104440114,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "cora\u00e7a\u00f5s",
            "submessages": [],
            "timestamp": 1481314067,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>Ol\u00e1, pessoal!<br>\nMais um falante de portugu\u00eas aqui.<br>\nLegal saber que tem gente interessada no idioma. :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107065161,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "mais um",
            "submessages": [],
            "timestamp": 1486930769,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/6d5e5a94fd7ae55388dd64dbf4da7b2732b8348e?x=x&version=1",
            "client": "website",
            "content": "<p>Opa! Bem vindo Elias :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107097719,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "juliano.solanho@gmail.com",
            "sender_full_name": "Juliano Bortolozzo Solanho (he) (F1'16)",
            "sender_id": 100035,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "mais um",
            "submessages": [],
            "timestamp": 1487002301,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>Valeu =)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107117479,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "mais um",
            "submessages": [],
            "timestamp": 1487039522,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "website",
            "content": "<p>Viva! :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107384630,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "mais um",
            "submessages": [],
            "timestamp": 1487615785,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-email=\"hi@xmunoz.com\" data-user-id=\"100520\">@Cristina Munoz (SP1'17)</span> <span class=\"user-mention\" data-user-email=\"xianny@gmail.com\" data-user-id=\"100527\">@Xianny Ng (SP1'17)</span> bora ressucitar esse stream! :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107386358,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487619181,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/0e5310d577f719e57009db6273218242?d=identicon&version=1",
            "client": "website",
            "content": "<p>muito bem!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107386364,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "xianny@gmail.com",
            "sender_full_name": "Xianny Ng (SP1'17)",
            "sender_id": 100527,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487619200,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>estou animada!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107386742,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487619933,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>legal!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107386846,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487620127,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>Gostaria de saber dos outros brasileiros do grupo se era s\u00f3 eu que n\u00e3o conhecia a banda CSS <img alt=\":simple_smile:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/simple_smile.png\" title=\":simple_smile:\"></p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107386852,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487620156,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>Pq uma pessoa fingiu surpresa quando eu disse que n\u00e3o conhecia, haha!<br>\nSou s\u00f3 eu o alienado?</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107386867,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487620202,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>jaja foi uma surpresa real, n\u00e3o fingido</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107386993,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487620417,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>desculpe se eu te ofendi <img alt=\":peace_symbol:\" class=\"emoji\" src=\"/static/generated/emoji/images/emoji/peace_symbol.png\" title=\":peace_symbol:\"></p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107387041,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487620477,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>devemos fazer no almo\u00e7o portugu\u00eas esta semana? eu necesito practicar!</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107390932,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487627863,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>haha, n\u00e3o ofendeu, s\u00f3 estou brincando :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107392551,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487630648,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>+1 pro almo\u00e7o brasileiro</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107392553,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487630664,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>s\u00f3 escolher a data :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107397645,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487641609,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "website",
            "content": "<p>Eu sou Portugu\u00eas e conhecia CSS. :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107411523,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487673839,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "website",
            "content": "<p>\u00c9 bom saber que boa m\u00fasica Brasileira consegue atravessar o oceano! :D</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107411564,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487673862,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/42d35e1484ccf00222c531d7bd51c46142ee9ef4?x=x&version=1",
            "client": "website",
            "content": "<p>Conhecem <a href=\"https://www.youtube.com/watch?v=vquqHCK3I1E&amp;hd=1\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=vquqHCK3I1E&amp;hd=1\">Labirinto</a>?</p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"vquqHCK3I1E\" href=\"https://www.youtube.com/watch?v=vquqHCK3I1E&amp;hd=1\" target=\"_blank\" title=\"https://www.youtube.com/watch?v=vquqHCK3I1E&amp;hd=1\"><img src=\"https://i.ytimg.com/vi/vquqHCK3I1E/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107411622,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "gnclmorais@gmail.com",
            "sender_full_name": "Gon\u00e7alo Morais (SP1'15)",
            "sender_id": 7631,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487674005,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/1d560dd62d4e447972276e2cc6b9dfdad0e35c2e?x=x&version=2",
            "client": "website",
            "content": "<p>isso soa como Black Sabbath</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107416104,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "hi@xmunoz.com",
            "sender_full_name": "Cristina Mu\u00f1oz (SP1'17)",
            "sender_id": 100520,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487683786,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/2863327b03645a13df4fa6fdc9ce671b3e88047f?x=x&version=3",
            "client": "website",
            "content": "<p>ahh, Labirinto eu j\u00e1 tinha ouvido (casualmente), mas n\u00e3o conhe\u00e7o de verdade, vou ver depois :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 107417303,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "eliasdorneles@gmail.com",
            "sender_full_name": "Elias Dorneles (he) (SP1'17)",
            "sender_id": 100512,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "(no topic)",
            "submessages": [],
            "timestamp": 1487686243,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ef80dcc578c3d972e3bec8113e3cc65873e8a109?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>V\u00ed essa \"thread\" na era da quarentena! \"Hoje eu n\u00e3o saio n\u00e3o\" por Marisa Monte n\u00e3o poderia ser mais relevante! Kkkk</p>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 195737991,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "c.sofiatti@gmail.com",
            "sender_full_name": "Caroline Sofiatti (she) (S1'15)",
            "sender_id": 232566,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1588178589,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/ef80dcc578c3d972e3bec8113e3cc65873e8a109?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>Descobr\u00ed O Terno recentemente e morr\u00ed de rir com a m\u00fasica 66: <a href=\"https://www.youtube.com/watch?v=Pn7_y7gmLnU\" title=\"https://www.youtube.com/watch?v=Pn7_y7gmLnU\">https://www.youtube.com/watch?v=Pn7_y7gmLnU</a></p>\n<div class=\"youtube-video message_inline_image\"><a data-id=\"Pn7_y7gmLnU\" href=\"https://www.youtube.com/watch?v=Pn7_y7gmLnU\" title=\"https://www.youtube.com/watch?v=Pn7_y7gmLnU\"><img src=\"https://i.ytimg.com/vi/Pn7_y7gmLnU/default.jpg\"></a></div>",
            "content_type": "text/html",
            "display_recipient": "\u00e3o",
            "flags": [
                "read",
                "historical"
            ],
            "id": 195738715,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 41873,
            "sender_email": "c.sofiatti@gmail.com",
            "sender_full_name": "Caroline Sofiatti (she) (S1'15)",
            "sender_id": 232566,
            "sender_realm_str": "recurse",
            "stream_id": 27386,
            "subject": "M\u00fasicas em portugu\u00eas",
            "submessages": [],
            "timestamp": 1588178896,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
