{
    "anchor": 0,
    "found_anchor": false,
    "found_newest": true,
    "found_oldest": true,
    "history_limited": false,
    "messages": [
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/1000/1cd87892343b6620726b112851f0b66cbda4a68f?x=x&version=4",
            "client": "Internal",
            "content": "<p>Welcome to <a class=\"stream\" data-stream-id=\"172975\" href=\"/#narrow/stream/172975-.E2.88.80.F0.9F.91.85\">#\u2200<span class=\"emoji emoji-1f445\" title=\"tongue\"><span class=\"emoji emoji-1f445\" title=\"tongue\">:tongue:</span></span></a>.</p>\n<p><strong>Description</strong>: A stream for those of us learning (human) languages!</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 148657164,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "welcome-bot@zulip.com",
            "sender_full_name": "Welcome Bot",
            "sender_id": 100007,
            "sender_realm_str": "zulipcore",
            "stream_id": 172975,
            "subject": "hello",
            "submessages": [],
            "timestamp": 1543342668,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Haha, amazing, apparently Danish is kinda hard even for Danes! <a href=\"https://twitter.com/PuzzleOfDanish\" target=\"_blank\" title=\"https://twitter.com/PuzzleOfDanish\">https://twitter.com/PuzzleOfDanish</a></p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 148657263,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Puzzle of Danish",
            "submessages": [],
            "timestamp": 1543342764,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "website",
            "content": "<p>I am very much into this channel</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 148719884,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f445",
                    "emoji_name": "tongue",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "juliatufts@gmail.com",
                        "full_name": "Julia Tufts (she/they) (F2'14)",
                        "id": 6677
                    },
                    "user_id": 6677
                },
                {
                    "emoji_code": "1f445",
                    "emoji_name": "tongue",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "marlenefdez@gmail.com",
                        "full_name": "Marlene Fernandez (she) (SP1'18)",
                        "id": 109654
                    },
                    "user_id": 109654
                },
                {
                    "emoji_code": "1f445",
                    "emoji_name": "tongue",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "ad@lamarque.fr",
                        "full_name": "Adrien Lamarque (they/he) (S1'16)",
                        "id": 9335
                    },
                    "user_id": 9335
                },
                {
                    "emoji_code": "1f445",
                    "emoji_name": "tongue",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "alan.m.odonnell@gmail.com",
                        "full_name": "Alan O'Donnell (he) (S1'19)",
                        "id": 813
                    },
                    "user_id": 813
                }
            ],
            "recipient_id": 219089,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Puzzle of Danish",
            "submessages": [],
            "timestamp": 1543419571,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Bit of a niche find, but this is a really nice French grammar (in French), written for Finns: <a href=\"http://research.jyu.fi/grfle/000.html\" target=\"_blank\" title=\"http://research.jyu.fi/grfle/000.html\">http://research.jyu.fi/grfle/000.html</a>. It's very good as a standalone French grammar, but it's also been fun to see how Finns explain French grammar vs. how English speakers do.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 148720852,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "une grammaire pour les finnophones",
            "submessages": [],
            "timestamp": 1543420092,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Super handy tool: <a href=\"https://dictionaries.io/\" target=\"_blank\" title=\"https://dictionaries.io/\">https://dictionaries.io/</a>. Lets you install a bunch of extra language dictionaries (which I think are scraped from wiktionary), click on words to see definitions, etc. It's helped a lot with Finnish.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 148857650,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "dictionaries.io",
            "submessages": [],
            "timestamp": 1543580034,
            "topic_links": [
                "https://dictionaries.io"
            ],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>If you want to get a fun sense for what Finnish sounds like, this playlist from a Finnish gammer playing the Finnish edition of a HP game is super cool: <a href=\"https://www.youtube.com/playlist?list=PL5tWckT00k-bNHhiELVLkeOPMse1fnlVJ\" target=\"_blank\" title=\"https://www.youtube.com/playlist?list=PL5tWckT00k-bNHhiELVLkeOPMse1fnlVJ\">https://www.youtube.com/playlist?list=PL5tWckT00k-bNHhiELVLkeOPMse1fnlVJ</a>. The text and the voice acting in the game are all in Finnish. Lots of cool voices, fast dialogue, theatrical dialogue, etc.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 152115100,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Harry Potter game in Finnish",
            "submessages": [],
            "timestamp": 1545146601,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c2c732b24ee5bd02a9d15fa2bcc59e647934b42?x=x&version=2",
            "client": "website",
            "content": "<p>I've been using this site a lot lately to get in context use and pronunciation of new words <a href=\"https://youglish.com/search/perro/spanish\" target=\"_blank\" title=\"https://youglish.com/search/perro/spanish\">https://youglish.com/search/perro/spanish</a></p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 166194628,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "joeleedel@gmail.com",
            "sender_full_name": "Joe Del (he) (S2'19)",
            "sender_id": 2146,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "youglish",
            "submessages": [],
            "timestamp": 1558460421,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c2c732b24ee5bd02a9d15fa2bcc59e647934b42?x=x&version=2",
            "client": "website",
            "content": "<p>Its basically a huge index of youtube subtitles</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 166194668,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "joeleedel@gmail.com",
            "sender_full_name": "Joe Del (he) (S2'19)",
            "sender_id": 2146,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "youglish",
            "submessages": [],
            "timestamp": 1558460458,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9c4af750426d3bf0c15347009913c0323596658f?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>t\u00fcrk\u00e7e bilen ki\u015fi var m\u0131?</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169441556,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "katelaurel@gmail.com",
            "sender_full_name": "Kate-Laurel Agnew (she) (SP2'19)",
            "sender_id": 215254,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "t\u00fcrk\u00e7e",
            "submessages": [],
            "timestamp": 1562024708,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6a2d4314e6a4b48264e7afdf3fd7e813?d=identicon&version=1",
            "client": "website",
            "content": "<p>y\u00f6k :( but i had a small  grasp of it ~3 years ago and would enjoy practicing again!</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169481995,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "pgchatha@gmail.com",
            "sender_full_name": "Prayag Chatha (he) (S2'19)",
            "sender_id": 228093,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "t\u00fcrk\u00e7e",
            "submessages": [],
            "timestamp": 1562075443,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9c4af750426d3bf0c15347009913c0323596658f?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>My Turkish used to be pretty proficient, around C1/low C2 on the (CEFR scale)[https://www.fluentin3months.com/cefr-levels/], but it's been several years since I spoke or read it regularly :( beginning to use it again with folks (native or not) would mean a lot to me!</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169487875,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "katelaurel@gmail.com",
            "sender_full_name": "Kate-Laurel Agnew (she) (SP2'19)",
            "sender_id": 215254,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "t\u00fcrk\u00e7e",
            "submessages": [],
            "timestamp": 1562079328,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/9c4af750426d3bf0c15347009913c0323596658f?x=x&version=2",
            "client": "ZulipElectron",
            "content": "<p>cc <span class=\"user-mention\" data-user-id=\"123796\">@Sydney Lefevre (she)</span> , who's also a (rusty?) turkish speaker :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169487895,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "katelaurel@gmail.com",
            "sender_full_name": "Kate-Laurel Agnew (she) (SP2'19)",
            "sender_id": 215254,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "t\u00fcrk\u00e7e",
            "submessages": [],
            "timestamp": 1562079345,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/a4e1f602882ac013a0e19b85c17366e4256f3fe3?x=x&version=2",
            "client": "website",
            "content": "<p>Here's my morning reading: <a href=\"https://www.languageatinternet.org/articles/2019/gawne\" target=\"_blank\" title=\"https://www.languageatinternet.org/articles/2019/gawne\">https://www.languageatinternet.org/articles/2019/gawne</a></p>\n<p>Thought that some of you might be interested!</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169879042,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f643",
                    "emoji_name": "upside_down",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "sebastian@morr.cc",
                        "full_name": "blinry (they) (SP2'19)",
                        "id": 215296
                    },
                    "user_id": 215296
                }
            ],
            "recipient_id": 219089,
            "sender_email": "bonnie.eisenman@gmail.com",
            "sender_full_name": "Bonnie Eisenman (she) (m5'20)",
            "sender_id": 105050,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "emoji as gestures",
            "submessages": [],
            "timestamp": 1562599635,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/da27a2081fcf44c802c1806cdb5bb881310dfe7c?x=x&version=5",
            "client": "website",
            "content": "<p>What are your favorite slang terms in a non-English language that are loaned from another non-English language?</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169901726,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "ad@lamarque.fr",
            "sender_full_name": "Adrien Lamarque (they/he) (S1'16)",
            "sender_id": 9335,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "slang",
            "submessages": [],
            "timestamp": 1562617450,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/da27a2081fcf44c802c1806cdb5bb881310dfe7c?x=x&version=5",
            "client": "website",
            "content": "<p>(we were having a discussion about this with a group of friends yesterday, which is why I'm asking)<br>\nAn example would be \"wesh\" which is originally from arabic and is used in France as the equivalent of \"'sup\"</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 169901906,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "ad@lamarque.fr",
            "sender_full_name": "Adrien Lamarque (they/he) (S1'16)",
            "sender_id": 9335,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "slang",
            "submessages": [],
            "timestamp": 1562617572,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>This is a fun question and I can't think of any good ones :( I guess French has a lot of them (words like cl\u00e9bard or toubib come to mind).</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170456620,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "slang",
            "submessages": [],
            "timestamp": 1562681680,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>wichajster - whatchamacallit in Polish, taken directly from a German sentence \"Wie heisst er?\" (\"What's his name?\")</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170462653,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f4af",
                    "emoji_name": "100",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "ad@lamarque.fr",
                        "full_name": "Adrien Lamarque (they/he) (S1'16)",
                        "id": 9335
                    },
                    "user_id": 9335
                }
            ],
            "recipient_id": 219089,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "slang",
            "submessages": [],
            "timestamp": 1562685368,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>bajzel - mess, borrowed from German through Yiddish</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170462860,
            "is_me_message": false,
            "last_edit_timestamp": 1562685515,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "slang",
            "submessages": [],
            "timestamp": 1562685506,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/d2d1f3e361a479849026fe298e091c50e1a4b20a?x=x&version=5",
            "client": "website",
            "content": "<p>pempik - something small, unimportant and possibly cute, borrowed from Polish (p\u0119pek - belly button) to Yiddish</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170463417,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "rc@alicja.dev",
            "sender_full_name": "Alicja Karolina Raszkowska (she/they) (W2'18)",
            "sender_id": 100049,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "slang",
            "submessages": [],
            "timestamp": 1562685865,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/da27a2081fcf44c802c1806cdb5bb881310dfe7c?x=x&version=5",
            "client": "website",
            "content": "<p>these are really cool and cute <span class=\"user-mention\" data-user-id=\"100049\">@Alicja Karolina Raszkowska (she/they) (W2'18)</span> thanks :)</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170511750,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "ad@lamarque.fr",
            "sender_full_name": "Adrien Lamarque (they/he) (S1'16)",
            "sender_id": 9335,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "slang",
            "submessages": [],
            "timestamp": 1562733767,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Funny, I had kind of the same experience: <a href=\"https://www.independent.co.uk/arts-entertainment/tv/features/kaamelott-french-tv-show-king-arthur-legend-spoof-monty-python-holy-grail-a8978456.html\" target=\"_blank\" title=\"https://www.independent.co.uk/arts-entertainment/tv/features/kaamelott-french-tv-show-king-arthur-legend-spoof-monty-python-holy-grail-a8978456.html\">https://www.independent.co.uk/arts-entertainment/tv/features/kaamelott-french-tv-show-king-arthur-legend-spoof-monty-python-holy-grail-a8978456.html</a>. (About the French show Kaamelot, funny spoof of King Arthur.) I'd watch the show and want to show it to my family, but yeah, tough to watch in translation.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 170853005,
            "is_me_message": false,
            "reactions": [
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "eliasdorneles@gmail.com",
                        "full_name": "Elias Dorneles (he) (SP1'17)",
                        "id": 100512
                    },
                    "user_id": 100512
                },
                {
                    "emoji_code": "1f44d",
                    "emoji_name": "+1",
                    "reaction_type": "unicode_emoji",
                    "user": {
                        "email": "victor@draft.li",
                        "full_name": "Victor Felder (he) (F1'14)",
                        "id": 6420
                    },
                    "user_id": 6420
                }
            ],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "\"sweet loneliness of TV in a foreign language\"",
            "submessages": [],
            "timestamp": 1563145548,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Fun experience this morning getting to combine two interests from the past year or so: reading a blog post in Finnish about ULMFit (a type of neural network language model): <a href=\"https://www.auria.fi/biopankki/blogit/index.php#ulmfit\" target=\"_blank\" title=\"https://www.auria.fi/biopankki/blogit/index.php#ulmfit\">https://www.auria.fi/biopankki/blogit/index.php#ulmfit</a>.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171372385,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Finnish & ML",
            "submessages": [],
            "timestamp": 1563715145,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>Also cool to get to the point where I can kinda sorta branch out from just reading Harry Potter\u2014this post would have been too hard a few months ago.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171372394,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Finnish & ML",
            "submessages": [],
            "timestamp": 1563715192,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c2c732b24ee5bd02a9d15fa2bcc59e647934b42?x=x&version=2",
            "client": "website",
            "content": "<p>that's awesome</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171387669,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "joeleedel@gmail.com",
            "sender_full_name": "Joe Del (he) (S2'19)",
            "sender_id": 2146,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Finnish & ML",
            "submessages": [],
            "timestamp": 1563742827,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c2c732b24ee5bd02a9d15fa2bcc59e647934b42?x=x&version=2",
            "client": "website",
            "content": "<p><span class=\"user-mention\" data-user-id=\"813\">@Alan O'Donnell (he) (S1'19)</span> I forget did you start Finnish from 0 with Harry Potter, or do other prep?</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171387758,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "joeleedel@gmail.com",
            "sender_full_name": "Joe Del (he) (S2'19)",
            "sender_id": 2146,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Finnish & ML",
            "submessages": [],
            "timestamp": 1563743012,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>I started with a Finnish course on Memrise for a few months, to learn some vocabulary and how to pronounce things, and then basically got a grammar book and started trying to read HP. It was tough lol.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171388665,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Finnish & ML",
            "submessages": [],
            "timestamp": 1563744761,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/282da691709f4715fc3e0ff6bebd278b?d=identicon&version=1",
            "client": "website",
            "content": "<p>I started looking at Mandarin a few weeks ago, and I'm probably going to do things a bit differently since the beginner resources are so much better than they are for Finnish.</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171388681,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "alan.m.odonnell@gmail.com",
            "sender_full_name": "Alan O'Donnell (he) (S1'19)",
            "sender_id": 813,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Finnish & ML",
            "submessages": [],
            "timestamp": 1563744812,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/8c2c732b24ee5bd02a9d15fa2bcc59e647934b42?x=x&version=2",
            "client": "website",
            "content": "<p>Ah cool. I really want to try an input only approach for my next language</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 171388738,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "joeleedel@gmail.com",
            "sender_full_name": "Joe Del (he) (S2'19)",
            "sender_id": 2146,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Finnish & ML",
            "submessages": [],
            "timestamp": 1563744896,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://secure.gravatar.com/avatar/6a2d4314e6a4b48264e7afdf3fd7e813?d=identicon&version=1",
            "client": "website",
            "content": "<p>I recently reconnected over the phone with a childhood babysitter who speaks Russian and little English. If you speak Russian and would be willing to correct a Google-translated letter, please let me know!</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 174503679,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "pgchatha@gmail.com",
            "sender_full_name": "Prayag Chatha (he) (S2'19)",
            "sender_id": 228093,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Seeking help of Russian speaker",
            "submessages": [],
            "timestamp": 1567123341,
            "topic_links": [],
            "type": "stream"
        },
        {
            "avatar_url": "https://zulip-avatars.s3.amazonaws.com/13/28427e9335cecebc2d8cadc90c1bd46516bd589f?x=x&version=3",
            "client": "website",
            "content": "<p>I want to revive the #zh zulip channel. Inviting everyone to join if interested in Mandarin or other Chinese languages. Let's help each other learn and chat in a safe environment\uff01</p>",
            "content_type": "text/html",
            "display_recipient": "\u2200\ud83d\udc45",
            "flags": [
                "read",
                "historical"
            ],
            "id": 185608851,
            "is_me_message": false,
            "reactions": [],
            "recipient_id": 219089,
            "sender_email": "darthmincho@gmail.com",
            "sender_full_name": "Carlos Rey (SP2'15)",
            "sender_id": 7875,
            "sender_realm_str": "recurse",
            "stream_id": 172975,
            "subject": "Come speak Chinese!",
            "submessages": [],
            "timestamp": 1579017263,
            "topic_links": [],
            "type": "stream"
        }
    ],
    "msg": "",
    "result": "success"
}
